### ISSUE TITLE
can I set different colours for one line in Line chart?

### ISSUE THREAD

**Issue by tuwshuu0227** [Abhinandan-Kushwaha/react-native-gifted-charts#100]
can I set different colours for one line in Line chart? or can I cut line in Line chart?
Like this...
![image](https://user-images.githubusercontent.com/58503747/157060805-61ad3982-ee56-4551-b3fb-bb474ac117ef.png)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @tuwshuu0227 👋

Multiple lines can handled using 2 separate data arrays. For this you can use the `data` and `data2` props. Since we have 2 separate lines, they are allowed to have 2 different colors.

However, the above chart may not be accomplished currently, even with 2 separate data arrays. I will work on this particular case soon.

The support for negative values in Line and Area charts is now added in version 1.0.1.🎉
Also, 2 more props have been added- `minValue` and `noOfSectionsBelowXAxis`.
To know more, visit [this comment](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/78#issuecomment-1028431175)

Hope it helps.🤗

**Comment by Abhinandan-Kushwaha** [comment]
Hi @tuwshuu0227 👋
The support for Line chart with different colors for 1 Line is now enabled in version `1.0.7`🎉

The props used to achieve this are - 
1. `data`
2. `data2`
3. `startIndex`
4. `endIndex`
5.  `startIndex2`
6. `endIndex2`

Let's say you want to render a chart like this -

<img width="319" alt="Screenshot 2022-03-09 at 2 58 18 AM" src="https://user-images.githubusercontent.com/20596944/157328215-394e8e9c-2872-43ea-82cd-ccfef15d291b.png">

The code for the above chart will be-

```js
const data = [
    {value:1.0, label:'1'},
    {value:0.75, label:'2'},
    {value:0.25, label:'3'},
    {value:0.00, label:'4'},
    {value:0.50, label:'5'},
    {value:0.72, label:'6'},
    {value:0.85, label:'7'},
  ];

return(
  <LineChart
        data={sdata}
        startIndex={0}
        endIndex={2}
        color1='red'
        data2={sdata}
        startIndex2={4}
        endIndex2={6}
        color2='blue'
        showFractionalValues
        maxValue={1.5}
        noOfSections={3}
        spacing={40}
        thickness={3}
        />
  )
``` 

Hope it helps🤗

**Comment by tuwshuu0227** [comment]
> Hi @tuwshuu0227 👋 The support for Line chart with different colors for 1 Line is now enabled in version `1.0.8`🎉
> 
> The props used to achieve this are -
> 
> 1. `data`
> 2. `data2`
> 3. `startIndex`
> 4. `endIndex`
> 5. `startIndex2`
> 6. `endIndex2`
> 
> Let's say you want to render a chart like this -
> 
> <img alt="Screenshot 2022-03-09 at 2 58 18 AM" width="319" src="https://user-images.githubusercontent.com/20596944/157328215-394e8e9c-2872-43ea-82cd-ccfef15d291b.png">
> 
> The code for the above chart will be-
> 
> ```js
> const data = [
>     {value:1.0, label:'1'},
>     {value:0.75, label:'2'},
>     {value:0.25, label:'3'},
>     {value:0.00, label:'4'},
>     {value:0.50, label:'5'},
>     {value:0.72, label:'6'},
>     {value:0.85, label:'7'},
>   ];
> 
> return(
>   <LineChart
>         data={data}
>         startIndex={0}
>         endIndex={2}
>         color1='red'
>         data2={data}
>         startIndex2={4}
>         endIndex2={6}
>         color2='blue'
>         showFractionalValues
>         maxValue={1.5}
>         noOfSections={3}
>         spacing={40}
>         thickness={3}
>         />
>   )
> ```
> 
> Hope it helps🤗

@Abhinandan-Kushwaha Hello there, thank you for your reply 
My goal is cut line 3 or more times in one line But right now limit prop is only data3.
Maybe if its possible If I do set data like this..
const data = [
    {value:1.0, label:'1'},
    {value:0.75, label:'2'},
    {value:0.25, label:'3'},
    {value: null, label:'4'},
    {value:0.50, label:'5'},
    {value:0.72, label:'6'},
    {value:0.85, label:'7'},
  ];
then it automatically cut line in null values

**Comment by Abhinandan-Kushwaha** [comment]
Hey @tuwshuu0227 

Actually it's quite hard to implement this feature with the help of `null` values.
Better stick with the approach using `startIndex` and `endIndex`.

And worry not! we can now have upto **5 data sets simultaneously**. 🎉
Just update to version `1.0.9`

**Comment by tuwshuu0227** [comment]
Hello @Abhinandan-Kushwaha 
Okay I understand its hard to do it. Thank you for update.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @tuwshuu0227 
Now we can cut the line into any number of segments using the `lineSegments` prop. This feature is available from version `1.3.18` onwards.🎉

See https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/432#issuecomment-1820013349

Here's an example- 

```js
const MultiSegmented = () => {
  const data = [
    {value: 5},
    {value: 8},
    {value: 7}, // break in line from previous to this point
    {value: 4},
    {value: 6},
    {value: 0, hideDataPoint: true}, // invisible, here's a break in the line
    {value: 0, hideDataPoint: true}, // break continued
    {value: 6},
    {value: 9},
  ];
  return (
    <LineChart
      spacing={35}
      data={data}
      lineSegments={[
        {startIndex: 0, endIndex: 1, color: 'green'},             // 1st segmant from 0th to 1st index
        {startIndex: 1, endIndex: 2, color: 'transparent'},       // break (transparent = invisible)
        {startIndex: 2, endIndex: 4, color: 'red'},               // 2nd segment from 2nd to 4th index
        {startIndex: 4, endIndex: 7, color: 'transparent'},       // 2nd break from 4th to 7th index
        // remaining of the data points, from 7th to 8th index make the last segment
      ]}
    />
  );
};
```
The output of the above code is-

<img width="350" alt="gments" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/10bc765b-2e50-4d8a-854d-f802ae110db7">

**Comment by giltheodor** [comment]
Hi @Abhinandan-Kushwaha,

Its seems if I use the `curved` props the lineSegments is not working. 

Thank you in advance

**Comment by Abhinandan-Kushwaha** [comment]
Hi @giltheodor 
It's working for me. Can you please share your code?

**Comment by mth-dwarf** [comment]
Why did you implement seperate parameter for each line rather than handling a list of datasets?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @mth-dwarf we have it both ways- 
1. separately for each line
2. using `dataSet` prop which takes an array

**Comment by adityaranjan006** [comment]
> const MultiSegmented = () => {
>   const data = [
>     {value: 5},
>     {value: 8},
>     {value: 7}, // break in line from previous to this point
>     {value: 4},
>     {value: 6},
>     {value: 0, hideDataPoint: true}, // invisible, here's a break in the line
>     {value: 0, hideDataPoint: true}, // break continued
>     {value: 6},
>     {value: 9},
>   ];
>   return (
>     <LineChart
>       spacing={35}
>       data={data}
>       lineSegments={[
>         {startIndex: 0, endIndex: 1, color: 'green'},             // 1st segmant from 0th to 1st index
>         {startIndex: 1, endIndex: 2, color: 'transparent'},       // break (transparent = invisible)
>         {startIndex: 2, endIndex: 4, color: 'red'},               // 2nd segment from 2nd to 4th index
>         {startIndex: 4, endIndex: 7, color: 'transparent'},       // 2nd break from 4th to 7th index
>         // remaining of the data points, from 7th to 8th index make the last segment
>       ]}
>     />
>   );
> };

Do I need to specifically, write indexed for hiding, the line segment?

**Comment by adityaranjan006** [comment]
> Hi [@mth-dwarf](https://github.com/mth-dwarf) we have it both ways-
> 
> 1. separately for each line
> 2. using `dataSet` prop which takes an array


using data prop right?

**Comment by Abhinandan-Kushwaha** [comment]
@adityaranjan006, you have a problem only in the Bar-Line combo chart (the one in the middle in the above screenshot)? Or do you have problem in all the 3 charts?

**Comment by adityaranjan006** [comment]
> [@adityaranjan006](https://github.com/adityaranjan006), you have a problem only in the Bar-Line combo chart (the one in the middle in the above screenshot)? Or do you have problem in all the 3 charts?

The Bottom one, LineChart with areaChart enabled.  

Data Array,
```
const data = [
  {value: 15, dataPointColor: '#4ECDC4'}, 
  {value: 30, dataPointColor: '#4ECDC4'}, 
  {value: 26, dataPointColor: '#4ECDC4'}, 
  {value: 40, dataPointColor: '#4ECDC4'}, 
  {value: 50, dataPointColor: '#4ECDC4'}, 
  {value: 0, hideDataPoint: true}, // This creates a line break
  {value: 70, dataPointColor: '#FF6B6B'}, 
  {value: 30, dataPointColor: '#FF6B6B'}, 
  {value: 50, dataPointColor: '#FF6B6B'}, 
  {value: 160, dataPointColor: '#FF6B6B'}
];
```

And LineChart

```
const AreaGraphWithLineBreak = () => {
  return (
    <View style={{justifyContent: 'center', alignItems: 'center',marginTop: 20}}>
      <LineChart
        data={data}
        hideRules={true}
        dataPointsColor="#FFFFFF"
        areaChart={true}
        dataPointsRadius={4}
        color="#4ECDC4"
        thickness={3}
        startFillColor="rgba(78, 205, 196, 0.3)"
        endFillColor="rgba(78, 205, 196, 0.1)"
        startOpacity={0.8}
        endOpacity={0.1}
        yAxisColor="transparent"
        xAxisColor="transparent"
      />
    </View>
  )
}
```

when value was zero, I wanted to have a line breaks but its not working.  I'm using "react-native-gifted-charts": "^1.4.47".

**Comment by Abhinandan-Kushwaha** [comment]
@adityaranjan006 if you want the line to break, you are supposed to put the value `undefined` and not `0`

**Comment by adityaranjan006** [comment]
> [@adityaranjan006](https://github.com/adityaranjan006) if you want the line to break, you are supposed to put the value `undefined` and not `0`

I tried, with value = undefined as,
```
const data = [
  {value: 15}, 
  {value: 30}, 
  {value: 50}, 
  {value: undefined}, // This creates a line break
  {value: 30}, 
  {value: 160}
];
```
But didn't got the result as your's. Demonstrated above.

```
const AreaGraphWithLineBreak = () => {
  return (
    <View style={{justifyContent: 'center', alignItems: 'center',marginTop: 20}}>
      <LineChart
        data={data}
        hideRules={true}
        dataPointsColor="#FFFFFF"
        dataPointsRadius={4}
        color="#4ECDC4"
        thickness={3}
        startOpacity={0.8}
        endOpacity={0.1}
        yAxisColor="transparent"
        xAxisColor="transparent"
      />
    </View>
  )
}
```

<img width="448" height="280" alt="Image" src="https://github.com/user-attachments/assets/235138f1-55d0-4188-b318-803b58507de6" />

<img width="433" height="301" alt="Image" src="https://github.com/user-attachments/assets/b92b84af-e3de-4e5e-a1af-4f36169b08d5" />

**Comment by Abhinandan-Kushwaha** [comment]
@adityaranjan006 you also need to set `interpolateMissingValues={false}`

See https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/LineChart/LineChartProps.md#interpolation

**Comment by tkoolhoven2** [comment]
> [@adityaranjan006](https://github.com/adityaranjan006) you also need to set `interpolateMissingValues={false}`
> 
> See https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/LineChart/LineChartProps.md#interpolation

Thanks so much Abhinandan-Kushwaha. Even Open AI couldn't find that prop. After killing an hour in figuring out how to terminate lines in a linechart using the dataset prop, i resorted back to the GitHub issues again. Just goes to show, old school forums can still be superior.
