### ISSUE TITLE
ShowVerticalLine isn't the height of the chart

### ISSUE THREAD

**Issue by kimdolion** [Abhinandan-Kushwaha/react-native-gifted-charts#106]
Was hoping to use `showVerticalLine` to render on specific data points while looking similar to the chart prop `showVerticalLines` where the lines are the height of the chart. 

Using `showVerticalLine` however only goes to the height of the data point.

![Screen Shot 2022-03-10 at 2 03 05 PM](https://user-images.githubusercontent.com/49125411/157736102-7b585438-7ae6-481e-b905-13d7f7700aad.png)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @kimdolion 
Can you please share the code you have written for the chart here?

**Comment by Abhinandan-Kushwaha** [comment]
@kimdolion 
I tried rendering Line chart with `showVerticalLines = true` and it works as expected for me.

Please share the code you're using.

**Comment by kimdolion** [comment]
The plural chart property `showVerticalLines` works as expected, but we are trying to use singular `showVerticalLine` to render on a specific set of data points rather than all of the data points.

**Comment by kimdolion** [comment]
@Abhinandan-Kushwaha This is the return for our data
```
      // Change X-Axis styling here
      return {
        ...point,
        label,
        value: aggDataValue,
        dataPointRadius: 5,
        labelComponent: function dateLabel() {
          return showDateLabel ? (
            <Text
              style={{
                color: Colors.neutral[700],
                fontSize: 12,
                fontFamily: 'GraphikRegular',
                fontWeight: '100',
                right: isWeekly ? 0 : 14,
                textAlign: 'center',
                width: 40,
              }}
            >
              {date}
            </Text>
          ) : null
        },
        showVerticalLine: !isWeekly && showDateLabel, // we want to have this individual vertical line be the height of our chart
```

**Comment by Abhinandan-Kushwaha** [comment]
Hi @kimdolion 👋

Your requirement has been fulfilled in version `1.0.10` 🎉

Now, all vertical lines' heights will default to the height of the chart.
However, if you want to set the height of vertical lines only upto the data point, you can use the prop `verticalLinesUptoDataPoint={true}` or set the data object property `verticalLineUptoDataPoint: true`

Hope it helps 🤗
