### ISSUE TITLE
Bar Chart label is not in the middle of the bar

### ISSUE THREAD

**Issue by htduongdl96** [Abhinandan-Kushwaha/react-native-gifted-charts#107]
![image](https://user-images.githubusercontent.com/37286834/158408734-b4245e2b-066a-44cc-a4fb-52007ccc8037.png)
Like the title, the X label is not in the middle of the bar.
 Here is my config for the bar chart
`          <BarChart
            barWidth={50}
            noOfSections={4}
            spacing={80}
            initialSpacing={50}
            maxValue={max.value}
            labelWidth={100}
            barBorderRadius={4}
            stepValue={(max.value - 0) / 4}
            frontColor="lightgray"
            data={showChart}
          />`

**Comment by Abhinandan-Kushwaha** [comment]
Hi @htduongdl96 👋
Your problem can be fixed using the `labelTextStyle` property inside the data objects.
Here's an example-

```js
const showChart = [
    {value: 50, label: 'archieved', labelTextStyle: {textAlign: 'left'}},
    {value: 450, label: 'discared', labelTextStyle: {textAlign: 'left'}},
    {value: 1387, label: 'active', labelTextStyle: {textAlign: 'left'}},
  ];
return(
  <BarChart
        barWidth={50}
        noOfSections={4}
        spacing={80}
        initialSpacing={50}
        labelWidth={100}
        barBorderRadius={4}
        frontColor="lightgray"
        data={showChart}
    />
);
```

And its output is-

<img width="390" alt="Screenshot 2022-03-18 at 5 27 41 PM" src="https://user-images.githubusercontent.com/20596944/158999101-76d56066-c86e-4e64-b442-bd20236fba5a.png">

Hope it helps🤗
