### ISSUE TITLE
Bar graph label not showing in android

### ISSUE THREAD

**Issue by navigarg91** [Abhinandan-Kushwaha/react-native-gifted-charts#108]
![processed-97836cc4-b692-4e23-8798-7cc229c1968e_5U528Z9k](https://user-images.githubusercontent.com/71089152/158600804-2a5d8293-9b08-4a21-8d0c-35a3a869909a.jpeg)

**Comment by navigarg91** [comment]
Label only shows up when we click on bar and hides again when screen rerenders.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @navigarg91 👋
I just tested it on Android and it works as expected. Can you please share your code here?
