### ISSUE TITLE
OnPress not working at all?

### ISSUE THREAD

**Issue by NemyaNation** [Abhinandan-Kushwaha/react-native-gifted-charts#109]
Can we get a complete example for onPress so that we can test locally and figure out why our graph functionality isn't working.

I have these following props set and nothing is triggered. Not using the graph inside tab-view / horizontal scrollview etc, so that is not the issue.

```
pressEnabled={true}
showDataPointOnPress={true}
showStripOnPress={true}
showTextOnPress={true}
focusedDataPointShape={"orange"}
focusedDataPointColor={"blue"}
focusedDataPointRadius={5}
onPress={() => console.log("hey!")}
```

**Comment by Abhinandan-Kushwaha** [comment]
Hi @NemyaNation 👋
I tested on both Android and iOS, and it works as expected on both.

Please try rendering only the Line chart on a new screen. This will help you find the exact issue.

I am sharing the code I used-

```js
const lineData = [
    {value: 0},
    {value: 10},
    {value: 8},
    {value: 58},
    {value: 56},
    {value: 78},
    {value: 74},
    {value: 98},
  ];
return(
  <LineChart
        data={lineData}
        pressEnabled={true}
        showDataPointOnPress={true}
        showStripOnPress={true}
        showTextOnPress={true}
        focusedDataPointShape={'orange'}
        focusedDataPointColor={'blue'}
        focusedDataPointRadius={5}
        onPress={() => console.log('hey!')}
      />
 )
 ```

**Comment by NemyaNation** [comment]
I have like a million options set and I had to go through one by one to find the problem.

I had accidentally set `hideDataPoints={true}`
