### ISSUE TITLE
Some props in the documentation are not actually implemented?

### ISSUE THREAD

**Issue by NemyaNation** [Abhinandan-Kushwaha/react-native-gifted-charts#110]
@Abhinandan-Kushwaha 

Documentation states you can set `yAxisLabelText` as data point for y-axis data point, however this does not work.

Checking the code, there is no mention of this field anywhere: 

https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/b3c05d961bd91dbbdb8f2c8470f92d1eed1ac46b/src/LineChart/index.tsx#L255

---

I need this because when using `yAxisLabelTexts` you have to pick your labels very carefully to make sure they match the graph boundaries and I don't want to handle this myself.

I would much rather prefer to set the y-label for each data point and let your library do the existing heavy lifting.

**Comment by NemyaNation** [comment]
As well as this, how do we bring the y-axis labels forward in the view.

I have my y-axis on the right hand side, displayed above the chart, and I've set

```
yAxisTextStyle={{
  right: -30,
  position: "absolute",
  zIndex: 9999,
  elevation: 9999,
}}
```

Can we set an option so we can bring the yAxis label view forward instead of behind the chart curve.

**Comment by NemyaNation** [comment]
We really need this prop as a function similar to `onPress` for the prop `unFocusOnPressOut`

I am using a state implementation for our graph and so am using onPress to create and style a custom data component. onFocus allows me to update, however I am not alerted on press out.

You should either add function input for `unFocusOnPressOut` or call onPress once again with undefined `item`/`index` prop-values.

----

Also can I get advice on how to get animated scroll on dataPoint. I want to be able to swipe on the graph and get access to each datapoint using the swipe.

Currently the only way to view each data point is by clikcing on it individually instead of swiping to it.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @NemyaNation 
Please let me know when you are free, we can schedule a Google meet to solve all your issues in one time.

**Comment by NemyaNation** [comment]
@Abhinandan-Kushwaha sorry just seen this!

I'm really swamped in the next couple of weeks, this was a feature-request task that I was working on in my spare time which I'm still having difficulty with.

The library has met 98% of all my needs, it definitely is the best custom component library on the market today for react native so good job.

I've tried and tested about 3 others previous to this one and none match the quality!!

----

If you could give me some pointers in the meantime, I'm sure it would help me as well as others who view this later.

Kind regards,

**Comment by Abhinandan-Kushwaha** [comment]
Overwhelmed with your kind words!!
I will be pleased to solve your issues. But it's hard to understand your exact requirements here on GitHub.

Feel free to connect with me on Google meet whenever you are available.

**Comment by christophby** [comment]
>  I want to be able to swipe on the graph and get access to each datapoint using the swipe.

@NemyaNation  have you found a solution for this?
