### ISSUE TITLE
show a horizontal dotted line for average of two line charts 

### ISSUE THREAD

**Issue by VijinR** [Abhinandan-Kushwaha/react-native-gifted-charts#113]
Are we having an option to add a dotted horizontal line to show the average of two line charts?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @VijinR👋
The feature to support dotted/dashed lines is now added in version `1.0.11`🎉

To render a dotted/dashed line, we can make use of the prop `strokeDashArray`. **strokeDashArray**  is an array of 2 numbers denoting the _dashWidth_ and _dashGap_ of the line.

To selectively use dotted/dashed line in case of multiple lines, we can use `strokeDashArray1`, `strokeDashArray2`, `strokeDashArray3` and so on.

Now coming to your use case, let's say we have 2 data sets as follows-
```js
const lineData1 = [
    {value: 20},
    {value: 40},
    {value: 48},
    {value: 50},
    {value: 56},
    {value: 70},
    {value: 90},
    {value: 95},
  ];

  const lineData2 = [
    {value: 0},
    {value: 5},
    {value: 8},
    {value: 18},
    {value: 22},
    {value: 30},
    {value: 44},
    {value: 52},
  ];
```
And we want to render a third dotted line representing the average of the two lines.
Here's the code for the same-
```js
<LineChart
  data={lineData1}
  data2={lineData2}
  data3={lineData1.map((item, index) => {
    return {value: (lineData1[index].value + lineData2[index].value) / 2};
  })}
  strokeDashArray3={[2, 3]}
  hideDataPoints3
  spacing={30}
/>
```

The output of the above code is

![Screenshot 2022-03-29 at 2 55 38 PM](https://user-images.githubusercontent.com/20596944/160579959-c635e39a-15fe-490b-a82c-048f12508264.png)
-

Hope it helps🤗

**Comment by VijinR** [comment]
@Abhinandan-Kushwaha great work🎉..thanks
