### ISSUE TITLE
Scroll through data points instead of justing clicking on them.

### ISSUE THREAD

**Issue by NemyaNation** [Abhinandan-Kushwaha/react-native-gifted-charts#116]
@Abhinandan-Kushwaha

I really want to implement functionality similar to the delta investment app, where we can holdPress on the graph, and then we can scroll through the datapoints, without removing our focus from the graph.

Look at the video below

### Delta Investment App

https://user-images.githubusercontent.com/17049683/160614368-40cdc65a-4a26-444f-8292-ac7956ff6613.mp4

---

I want to achieve something similar and I've gotten as far as onPress, however I am having trouble handling the onScroll functionality with the focus still maintained on the graph.

### My attempt thus far (you can see there is no scroll functionality, it's just onPress on each of the several data points)

https://user-images.githubusercontent.com/17049683/160614583-e1d7b383-1299-44b7-b5f3-fa87afcb9195.mp4

**Comment by Abhinandan-Kushwaha** [comment]
Hi @NemyaNation 
Thanks for requesting the feature. You have already used the `react-native-gifted-charts` library to its full potential for achieving the above chart. The second video actually shows what can be achieved with the library's current version.

I will definitely try to improve the library so that we can achieve the chart depicted in the first video. Please wait for the next update.

**Comment by NemyaNation** [comment]
@Abhinandan-Kushwaha  thanks! really looking forward to it, the scroll will be a real game changer!

I'm releasing in about a month, so would be really nice to implement this before then.

I will look into it as well, although my react native expertise is not that advanced unfortunately.

Thanks for your help thus far, and for creating this brillian library!

**Comment by Abhinandan-Kushwaha** [comment]
Hi @NemyaNation 👋
You would be glad to know that this feature is rolled out in version `1.0.16`🎉

To enable such kind of scroll effect, just pass the prop pointerConfig. The pointerConfig object has following fields-
```js
type Pointer = {
  height?: number;
  width?: number;
  radius?: number;
  color?: ColorValue;
  pointerComponent?: Function;
  showPointerStrip?: boolean;
  pointerStripWidth?: number;
  pointerStripHeight?: number;
  pointerStripColor?: ColorValue;
  pointerStripUptoDataPoint?: boolean;
  pointerLabelComponent?: Function;
  shiftPointerLabelX?: number;
  shiftPointerLabelY?: number;
  pointerLabelWidth?: number;
  pointerVanishDelay?: number;
};
```
The above properties can be understood with this labelled diagram-

<img width="450" alt="rainbow" src="https://user-images.githubusercontent.com/20596944/161866419-e635106b-5dd4-48e9-9329-1012c1256fb9.png">

I have tried an example chart with help of `pointerConfig` - 

https://user-images.githubusercontent.com/20596944/161866599-fd350d00-6ac1-4378-bad3-9c6902dc6f40.mov

The code for the above chart is-
```js
const lineData = [
    {value: 8},
    {value: 10},
    {value: 12},
    {value: 8},
    {value: 11},
    {value: 13},
    {value: 19},
    {value: 18},
    {value: 22},
    {value: 20},
    {value: 28},
    {value: 32},
    {value: 36},
    {value: 40},
    {value: 38},
    {value: 40},
    {value: 42},
    {value: 46},
    {value: 44},
    {value: 40},
    {value: 36},
    {value: 32},
    {value: 38},
    {value: 36},
    {value: 32},
    {value: 28},
    {value: 22},
    {value: 20},
  ];
  return (
    <View
      style={{
        flex:1,
        paddingVertical: 100,
        backgroundColor:'black'
      }}>
      <LineChart
        data={lineData}
        initialSpacing={0}
        spacing={12}
        areaChart
        curved
        hideDataPoints
        startFillColor1="lightgreen"
        endOpacity={0.6}
        hideRules
        xAxisColor="white"
        yAxisColor="white"
        yAxisTextStyle={{color:'white'}}
        height={250}
        pointerConfig={{
          color: 'white',
          pointerStripColor: 'white',
          pointerStripHeight: 235,
          pointerLabelComponent: item => {
            return (
              <View>
                <Text style={{color:'yellow',fontWeight:'bold'}}>{item.value}</Text>
              </View>
            );
          },
        }}
      />
    </View>
  )
```
I hope it helps🤗
Cheers🍺

**Comment by NemyaNation** [comment]
Absoloutely smashing! I've just configured it with my graphs and it's working a charm, extra cudos for the extra params you've added which allows me to style the label component so it's always visible on the screen regardless of where the data point is on the graph! 🎉🎉🎉

**Comment by NemyaNation** [comment]
@Abhinandan-Kushwaha hey! just realised that your new prop `pointerConfig` does not take into consideration `pressEnabled`, so even if we have `pressEnabled=false` set, the use is still able to press on the graph and show the pointerLabelComponent.

I think possibly you just forgot to make this check again, (just like you do for usual graphs).
