### ISSUE TITLE
double stacked bar graph?

### ISSUE THREAD

**Issue by VijinR** [Abhinandan-Kushwaha/react-native-gifted-charts#120]
tried with giving the spacing for alternate bars like bar chart, but spacing not working.
{
spacing:40, 
stacks: [
               {color: '#640B9F', value: 0},
               {color: '#E39BC3', 'value': 1}
              ]
}

**Comment by Abhinandan-Kushwaha** [comment]
Hi @VijinR 👋
Thanks for pointing out the issue.
It is fixed in version `1.0.14`🎉
