### ISSUE TITLE
Normalize legend on  y-axis  (round grid to either 50s or 100s or some number that makes sense based on the data (ie:  show 50, 100, 150, 200 instead of 36, 72, 123, 179, etc)

### ISSUE THREAD

**Issue by AbhishekMuknak** [Abhinandan-Kushwaha/react-native-gifted-charts#121]

**Comment by Abhinandan-Kushwaha** [comment]
Hi @AbhishekMuknak 👋
This can be achieved using the props-
`maxValue`
`stepValue`
`noOfSections` 

These props are correlated:
They must follow the relation:
```js
maxValue = noOfSections * stepValue;
```

For example, to show 50, 100, 150, 200, you can set
```js
maxValue = {200}
stepValue = {50}
noOfSections = {4}
```
Find details here- [Bar Chart props](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/BarChart/BarChartProps.md)

I hope it helps🤗
