### ISSUE TITLE
Rotate label with small bar width

### ISSUE THREAD

**Issue by ansh029** [Abhinandan-Kushwaha/react-native-gifted-charts#125]
![BarChart](https://user-images.githubusercontent.com/26456500/161480693-b8e6a6b4-2758-4e8c-9c9f-b73d0075b0e0.jpeg)
Hi, How to rotate label like this with small bar width. I tried many ways but couldn't get success.

**Comment by ansh029** [comment]
My code :-

 const styleObject = {
      marginRight: 88,
      paddingTop:-30,
      transform: [{rotate: '-90deg'}],
    };
    const barData = [
      {
        value: 10,
        label: 'Jan 2021',
        labelTextStyle: styleObject,
        labelWidth: 90,
        spacing:40,
        
      },
      {
        value: 20,
        label: 'Feb 2021',
        labelTextStyle: styleObject,
        labelWidth: 130,
        spacing:40,
      },
      {
        value: 30,
        label: 'Mar 2021',
        labelTextStyle: styleObject,
        labelWidth: 130,
        spacing:40,
      },
      {
        value: 20,
        label: 'Apr 2021',
        labelTextStyle: styleObject,
        labelWidth: 130,
        spacing:40,
      },
    ]; 

 <BarChart
        
            frontColor={colors.COLOR_NORMAL_RED}
            barWidth={wp('2%')}
            data={barData}
            hideRules
            labelsExtraHeight={60}
            height={hp('45%')}
            width={wp('70%')}
            yAxisTextStyle={{ color: colors.COLOR_SEMI_GREY }}
            initialSpacing={wp('5%')}
            xAxisColor={colors.COLOR_NORMAL_GREY}
            yAxisColor={colors.COLOR_NORMAL_GREY}
            spacing={40}

          />

**Comment by ansh029** [comment]
` const styleObject = {
      marginRight: 88,
      paddingTop:-30,
      transform: [{rotate: '-90deg'}],
    };
    const barData = [
      {
        value: 10,
        label: 'Jan 2021',
        labelTextStyle: styleObject,
        labelWidth: 90,
        spacing:40,
        
      },
      {
        value: 20,
        label: 'Feb 2021',
        labelTextStyle: styleObject,
        labelWidth: 130,
        spacing:40,
      },
      {
        value: 30,
        label: 'Mar 2021',
        labelTextStyle: styleObject,
        labelWidth: 130,
        spacing:40,
      },
      {
        value: 20,
        label: 'Apr 2021',
        labelTextStyle: styleObject,
        labelWidth: 130,
        spacing:40,
      },
    ]; `

`<BarChart
        
            frontColor={colors.COLOR_NORMAL_RED}
            barWidth={wp('2%')}
            data={barData}
            hideRules
            labelsExtraHeight={60}
            height={hp('45%')}
            width={wp('70%')}
            yAxisTextStyle={{ color: colors.COLOR_SEMI_GREY }}
            initialSpacing={wp('5%')}
            xAxisColor={colors.COLOR_NORMAL_GREY}
            yAxisColor={colors.COLOR_NORMAL_GREY}
            spacing={40}

          />`

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ansh029 👋
This has already been discussed [here](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/93#issuecomment-1049346062)

Can you share your code? I can make changes in your code to get the desired result.
