### ISSUE TITLE
Bottom margin between bar and x axis

### ISSUE THREAD

**Issue by verofy-simon-denny** [Abhinandan-Kushwaha/react-native-gifted-charts#126]
Hi,

I just wondered if there was a way of adding a margin between the bottom of a bar and the x axis in the bar chart? I know you can use marginbottom with the stacked chart between the sections of the bar, but I want to be able to add a margin in a normal bar chart at the bottom.

Many Thanks, Simon.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @verofy-simon-denny 👋

This is perhaps not available in the current version. I have added it to the [Todo list](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/src/todos.md). Will be adding this feature in the next release.

**Comment by verofy-simon-denny** [comment]
Amazing, thanks for letting me know.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @verofy-simon-denny 👋
The prop `barMarginBottom` is now added in version `1.0.17`🎉
`barMarginBottom` can also be added as a property inside data objects.

**Comment by manuelf45** [comment]
Hi @Abhinandan-Kushwaha 
Could you also add a bottom margin between stack bar and x axis?

**Comment by Abhinandan-Kushwaha** [comment]
Thanks @manuelf45 for requesting this feature. `barMarginBottom` is now available for stacked Bar charts also from versions `1.4.48` onwards. 🎉

Please use the latest version of the library.
