### ISSUE TITLE
how to round the values on yaxis

### ISSUE THREAD

**Issue by AbhishekMuknak** [Abhinandan-Kushwaha/react-native-gifted-charts#127]
Suppose my array contains values like -10, 25, 24, 45, 60, -34 then i want to show yaxis axis values like -60, -40, -20, 0, 20, 40, 60, 80

**Comment by Abhinandan-Kushwaha** [comment]
Hi @AbhishekMuknak 👋

You need to use the following props-

1. maxValue
2. minValue
3. stepValue
4. stepHeight
5. height
6. noOfSections
7. noOfSectionsBelowXAxis

As per your requirement, here is an example chart-

<img width="363" alt="Screenshot 2022-04-05 at 5 29 13 PM" src="https://user-images.githubusercontent.com/20596944/161749066-23287aea-49f8-4f80-a1fd-916092b2adb9.png">

The code for this chart is-
```js
const data = [
  {value: -10},
  {value: 25},
  {value: 24},
  {value: 45},
  {value: 60},
  {value: -34},
];

return(
  <BarChart
    data={data}
    maxValue={80}
    stepValue={20}
    noOfSections={4}
    minValue={-60}
    noOfSectionsBelowXAxis={3}
    />
 );
```

For more details, refer to [this](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/78#issuecomment-1028431175).

Hope it helps🤗

**Comment by AbhishekMuknak** [comment]
My value are not static . So my min and Max values are also changes in that case how to calculate step values

**Comment by Abhinandan-Kushwaha** [comment]
Hi @AbhishekMuknak 
You can provide dynamic min and max values based on the biggest and smallest values in your data set.

For example, if you want the values to be rounded to nearest tens, you can use the formula-
```js
let biggest = Math.max(...data)
let maxValue = Math.ceil(biggest / 10) * 10
```
