### ISSUE TITLE
Horizontal + Vertical Line (Dotted / Dashed / Solid)

### ISSUE THREAD

**Issue by NemyaNation** [Abhinandan-Kushwaha/react-native-gifted-charts#131]
Feature Request:

Not urgent but if we can set a type prop for the data line props i.e

```
showStrip,
dataPointText,
textShiftX,
```

Even better if we can also have the Y-axis counterpart. 

---

### Why is this a good idea?

- A lot of graphs sometimes decrease straight from the onset, so if you use vertical lines to display that "highest" data point it wont be visible since it may get overlapped by the y-axis (if the highest is at index = 0)

- Also if you use a horizontally scrolling graph, having a horizontalLine means you will be able to see where the highest data point no matter how much you scroll to the left/right.

---

- also, the dashed/dotted/solid type prop idea is also useful because it allows us to distinguish between which custom data points we're showing. for example my background lines for the graph are solid, however I would like to display the highest in dotted (horizontal) and the lowest value in dashed.

Just some ideas for expanding this in the future, not really urgent. (would be great if we could have the option to set our own graph container border, right now it's default only the bottom and right of the graph (unless I have messed things up) / border radius etc..

**Comment by Abhinandan-Kushwaha** [comment]
Hi @NemyaNation Your suggestion is really helpful! Can you please add some pictures to illustrate your feature request? It would be of great help.
I will work on the feature soon.

Thanks!

**Comment by Abhinandan-Kushwaha** [comment]
@NemyaNation👋
For the horizontal line, the `showReferenceLine` props might be helpful.
A detailed explanation about horizontal reference lines is available [here](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/38#issuecomment-976766313)

**Comment by NemyaNation** [comment]
@Abhinandan-Kushwaha 

This is exactly what I needed, thanks, I must have missed it.

I was doing some initial testing to see if this would meet my needs and it would be extremely useful to also have a label functionality (otherwise why have the reference line right?) - this would be similar to this ->
![Screenshot_2022-04-13-23-51-46-838_io getdelta android](https://user-images.githubusercontent.com/17049683/163282929-6e859914-6c35-462b-81b6-96c2ef0eeccb.jpg)


I also seem to have found a bug somewhere in the implementation:


https://user-images.githubusercontent.com/17049683/163283029-572805d1-f141-4c0c-9bf1-6a315e339a20.mp4

In this video, I am decrementing the position of the reference line from (highest) all the way down to (highest-500).

Possibly something to do with opacity of the graph or something, but between highest-400 and highest-500 the reference line is not displayed.

I solved this very quickly by removing the backgroundColor prop for my line chart, so this isn't an issue for me right now but should be looked into.

---

Also can you please take a look at my comment here https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/117#issuecomment-1092366954

The same thing for this issue which can be seen in the video ^, the reference lines // yAxis labels are behind the graph background and the curve itself.

**Comment by NemyaNation** [comment]
also for the type prop inside `referenceLine1Config` i.e

```
showReferenceLine1
referenceLine1Position={highest}
referenceLine1Config={{
  type: 'dotted',
  color: Colors.mainText,
  thickness: 1,
  dashWidth: 5,
  dashGap: 7.5,
}}
```

both solid/dashed work great, however it seems dotted is not supported :/

**Comment by Abhinandan-Kushwaha** [comment]
Hi @NemyaNation 👋
Dotted type can be easily achieved by using `dashGap = 1` and `dashWidth = 1`

Updates in version `1.0.19` :
1. The issue with the reference line disappearing is now fixed.
2. reference lines can now have labels. To add labels to reference lines, add the property `labelText` to the `referenceLine1Config` prop. The style of the label text can be controlled with the `labelTextStyle` prop. Here's an example-

```js
<LineChart
  data={data}
  showReferenceLine1
  referenceLine1Position={40}
  referenceLine1Config={{
    labelText: '$40',
    labelTextStyle: {left:100,top:-10}
  }}/>
 ```

**Comment by NemyaNation** [comment]
Thanks for the dotted type prop workaround, it's worked for me.

Regarding your latest label prop, unfortunately this has not, use this following example that we've been using frequently over the past few weeks.

```
const lineData = [
  {value: 8},
  {value: 10},
  {value: 12},
  {value: 8},
  {value: 11},
  {value: 13},
  {value: 19},
  {value: 18},
  {value: 22},
  {value: 20},
  {value: 28},
  {value: 32},
  {value: 36},
  {value: 40},
  {value: 38},
  {value: 40},
  {value: 42},
  {value: 46},
  {value: 44},
  {value: 40},
  {value: 36},
  {value: 32},
  {value: 38},
  {value: 36},
  {value: 32},
  {value: 28},
  {value: 22},
  {value: 20},
];

<LineChart
  data={lineData}
  initialSpacing={0}
  spacing={12}
  areaChart
  curved
  hideDataPoints
  startFillColor1="lightgreen"
  endOpacity={0.6}
  hideRules
  xAxisColor="white"
  yAxisColor="white"
  yAxisTextStyle={{color:'white'}}
  height={250}
  pointerConfig={{
    color: 'white',
    pointerStripColor: 'white',
    pointerStripHeight: 235,
    pointerLabelComponent: item => {
      return (
        <View>
          <Text style={{color:'yellow',fontWeight:'bold'}}>{item.value}</Text>
        </View>
      );
    },
  }}

  showReferenceLine1
  referenceLine1Position={30}
  referenceLine1Config={{
    type: 'dotted',
    color: Colors.subText,
    thickness: 1,
    dashWidth: 1,
    dashGap: 2.5,
  }}
  referenceLine1Config={{
    labelText: "30",
    labelTextStyle: {left:100,top:-10}
  }}
/>
```

once we add the new code:

```
referenceLine1Config={{
    labelText: "30",
    labelTextStyle: {left:100,top:-10}
  }}
```

our reference line dissapears altogether, if we remove it, everything works as usual.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @NemyaNation 👋
The issue with reference line labels flipping is fixed in version `1.0.20`🎉

**Comment by NemyaNation** [comment]
🎉🎉🎉

**Comment by sajorahasan** [comment]
Hi @Abhinandan-Kushwaha Is it possible to add reference line 4 to the line chart? Or can you please suggest a different way to achieve the below result?

<img width="578" alt="Image" src="https://github.com/user-attachments/assets/1da7c4d7-580e-484e-a232-df06057c9909" />

I was able to achieve something similar using reference line 1, 2 & 3 (please note the value can be dynamic & changes with api response)

![Image](https://github.com/user-attachments/assets/c51abaf6-d69f-4e15-9bf9-7f3bcb524a28)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @aymenbuu This can be achieved using the `rulesConfigArray` prop. You can pass different color values for each rule, and can also omit some of the rules by setting their color to `transparent` inside the `rulesConfigArray` array. See https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/746
