### ISSUE TITLE
Data Points at indexes (0, n-1) not visible on LineChart Graphs

### ISSUE THREAD

**Issue by NemyaNation** [Abhinandan-Kushwaha/react-native-gifted-charts#133]
Using your example from issue https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/116 for a quick example:

https://user-images.githubusercontent.com/17049683/162674082-84a32c21-022e-4d85-8939-7871cc663ae1.mp4

As you can see, the data points at index (0,n-1) are barely visible which is causing some issues for my implementation.

I think offering a data prop config `verticalLineShiftX` would be useful alongside the current props such as `verticalLineThickness`.

Or you can program yourself so it adds a automatic shift to the data points at index 0 and index n-1.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @NemyaNation 👋
This problem is now solved in version `1.0.17`🎉
Just add the property `pointerShiftX` (and also `pointerShiftY` if needed) to specific data points.

For above example, the data array would look like-
```js
const lineData = [
    {value: 8, pointerShiftX: 10},
    {value: 10},
    {value: 12},
    {value: 8},
    {value: 11},
    {value: 13},
    {value: 19},
    {value: 18},
    {value: 22},
    {value: 20},
    {value: 28},
    {value: 32},
    {value: 36},
    {value: 40},
    {value: 38},
    {value: 40},
    {value: 42},
    {value: 46},
    {value: 44},
    {value: 40},
    {value: 36},
    {value: 32},
    {value: 38},
    {value: 36},
    {value: 32},
    {value: 28},
    {value: 22},
    {value: 20, pointerShiftX: -10},
  ];
```

Hope it helps🤗
