### ISSUE TITLE
Large data set is not working

### ISSUE THREAD

**Issue by dipanshugarg90** [Abhinandan-Kushwaha/react-native-gifted-charts#134]
The large data set is not working in react-native and crash at android and ios same.

The code is below listed:-

const getData = ()=>  {
        let dataValue = [];
        for (let i = 0; i < 2000; i++) {
            dataValue.push(Math.random() * 100)
        }
        return dataValue;
    }

    return(
        <View style={{marginTop:100}}>
            <Text>Bezier Line Chart</Text>
            <ScrollView
                horizontal={true}
                contentOffset={{ x: 0, y: 0 }} // i needed the scrolling to start from the end not the start
                showsHorizontalScrollIndicator={false} // to hide scroll bar
            >
                <LineChart
                    data={{
                        labels: ["January", "February", "March", "April", "May", "June", "January", "February", "March", "April", "May", "June"],
                        datasets: [
                            {
                                data:
                                    getData()

                            },
                            {
                                data:
                                    getData()

                            }
                        ]
                    }}
                    chartConfig={{
                        backgroundColor: "#e26a00",
                        backgroundGradientFrom: "#ffffff",
                        backgroundGradientTo: colors.danger,
                        decimalPlaces: 1, // optional, defaults to 2dp
                        color: (opacity = 1) => colors.lightestGrey,
                        labelColor: (opacity = 1) => colors.noticeBlueInDark,
                        style: {
                            borderRadius: 50
                        },
                    }}
                    width={10000}
                    height={250}
                    xLabelsOffset={10}
                    withHorizontalLines={false}
                    getDotColor={(dataPoint, dataPointIndex) => {
                        console.log('dataPoint ---->', dataPoint);
                        console.log('dataPointIndex --->', dataPointIndex);
//based on condition we return the color as string
                        if (dataPointIndex === 500) return 'blue';
                    }}
                    withVerticalLines={false}
                    withHorizontalLabels={false}
                    withInnerLines={false}
                    withOuterLines={false}
                    style={{
                        paddingRight: 20, // to remove white spaces at the start of the chart
                    }}
                    bezier
                />
            </ScrollView>
        </View>
    )

please help in into this .

**Comment by Abhinandan-Kushwaha** [comment]
Hi @dipanshugarg90 🤗
For very large data sets, we must reduce the spacing between data points. This will prevent the chart from becoming very very wide.
Just pass the prop `spacing={10}` to the `<LineChart>` component.

Also, the code you have used will not work for this library. Please go through the [docs](https://gifted-charts.web.app/)
