### ISSUE TITLE
Line chart onPress function and scroll.

### ISSUE THREAD

**Issue by htduongdl96** [Abhinandan-Kushwaha/react-native-gifted-charts#135]
It's very hard to scroll when onPress is implemented.
Is there a way to implement onPress function only on the label and/or data point?
Also if the data is too large, onPress function on the latter value doesnt work.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @htduongdl96 👋
Thanks for pointing out the issue.
This issue is now fixed in version `1.0.17`🎉
Now we can add the `onPress` property inside specific data objects. Doing so makes only the data point pressable.
For example-
```js
const lineData = [
    {value: 20, onPress:(item)=>Alert.alert(item.value+'')},
    {value: 40},
    {value: 48, onPress:(item)=>Alert.alert(item.value+'')},
    {value: 50},
    {value: 56},
    {value: 70},
    {value: 90},
    {value: 95},
    {value: 70},
    {value: 90},
    {value: 95},
  ];
```
I hope it helps🤗
