### ISSUE TITLE
Long label issue

### ISSUE THREAD

**Issue by htduongdl96** [Abhinandan-Kushwaha/react-native-gifted-charts#139]
I want to display some long labels, I also use rotateLabel but the content is cut off (not enough height).
Can you add the degree, label height, endSpacing to the props?

**Comment by Abhinandan-Kushwaha** [comment]
@htduongdl96 👋
Long labels can be achieved with the help of `labelTextStyle` and `labelsExtraHeight` props.

Please look at this issue - https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/93#issuecomment-1049346062
