### ISSUE TITLE
LabelExtraheight for linechart

### ISSUE THREAD

**Issue by htduongdl96** [Abhinandan-Kushwaha/react-native-gifted-charts#140]
As yesterday issue, but i only found LabelExtraheight  props is only for barChart?
Can you also implement it for LineChart?

And i notice another issue, if LabelExtraheight is too large, it will cut of the chart on Top
![image](https://user-images.githubusercontent.com/37286834/163417560-42af98da-3c05-4de5-b6c1-62d60b2a1a2e.png)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @htduongdl96 👋
Thanks for pointing out the issue.
`labelExtraHeight` is now added in Line and Area charts too. Please update to version `1.0.19`

Also, the top of bars cutting off due to large labelExtraHeight is now fixed.🎉
