### ISSUE TITLE
Setting 'spacing' to automatically fill the width provided for number of data points

### ISSUE THREAD

**Issue by joshuarichards001** [Abhinandan-Kushwaha/react-native-gifted-charts#151]
Hey,

Within the LineChart is there any way for the 'spacing' field to automatically be set to the value that would have each data point spaced equally along the width you provide?

My use case is that the number of data points I use will be dynamic so without doing a secondary calculation I won't know what the spacing should be.

Cheers,
Josh

**Comment by Abhinandan-Kushwaha** [comment]
Hi @joshuarichards001 👋
Thanks for requesting this feature. It is now available in version `1.2.3`🎉

Just use the prop `adjustToWidth={true}`. It auto computes the spacing value to fit the Line chart in the available width. If `width` is not provided by the developer, it takes a default width of 200

**Comment by joshuarichards001** [comment]
Hey Mate,

Getting this error when I have the 'data' field tied to a state that changes from an empty array while waiting for the list data to be full when the API response fills the state.

<img width="439" alt="Screen Shot 2022-04-25 at 2 48 13 PM" src="https://user-images.githubusercontent.com/28378835/165012495-fa063e93-bf93-43a7-a122-3252ec449997.png">

Let me know if you need more explanation.

Cheers,
Josh

**Comment by Abhinandan-Kushwaha** [comment]
Hi @joshuarichards001 
Can you share the code here?

**Comment by joshuarichards001** [comment]
![Screen Shot 2022-04-25 at 7 00 07 PM](https://user-images.githubusercontent.com/28378835/165036772-f43520c5-86e6-41a6-a0a3-e59d165c264a.png)

**Comment by joshuarichards001** [comment]
It seems like the problem goes away when I remove the areaChart={true} part.

`interface Props {
  history: AssetHistory[];
}

const AssetChart11 = ({history}: Props) => {
  const [parsedHistory, setParsedHistory] = useState<any[]>([]);
  const [max, setMax] = useState(0);

  useEffect(() => {
    let maxValue = Math.max(...history.map(item => item.price));
    let data = history.map(item => {
      return {value: item.price.toFixed(2)};
    });
    setMax(maxValue);
    setParsedHistory(data);
  }, [history]);

  return (
    <View>
      <LineChart
        data={parsedHistory}
        initialSpacing={0}
        maxValue={max}
        adjustToWidth={true}
      />
    </View>
  );
};

export default AssetChart11;`

**Comment by Abhinandan-Kushwaha** [comment]
Hi @joshuarichards001

The issue with empty data array is now fixed in version `1.2.8`🎉
Need more clarification for the min-height part.

**Comment by joshuarichards001** [comment]
Awesome, so below is an example of the 'history' the useEffect function receives when my API call is resolved. Below that is the code I'm using and then finally is a screenshot of the graph being displayed. I'm setting the min-height to the minimum value in the array but it's still starting at 0 for some reason. Sorry for all the messages by the way mate haha, really see a lot of potential for this library! Cheers.
```
[
  {"date": "2022-04-06T00:00:00.000Z", "price": 10457.6001}, 
  {"date": "2022-04-07T00:00:00.000Z", "price": 10572.6001}, 
  {"date": "2022-04-08T00:00:00.000Z", "price": 10254.8999}, 
  {"date": "2022-04-09T00:00:00.000Z", "price": 9759.2999}, 
  {"date": "2022-04-10T00:00:00.000Z", "price": 9759.2999}, 
  {"date": "2022-04-11T00:00:00.000Z", "price": 9759.2999}, 
  {"date": "2022-04-12T00:00:00.000Z", "price": 9869.500100000001}, 
  {"date": "2022-04-13T00:00:00.000Z", "price": 10223.7},
  {"date": "2022-04-14T00:00:00.000Z", "price": 9850}, 
  {"date": "2022-04-15T00:00:00.000Z", "price": 10042.8998}, 
  {"date": "2022-04-16T00:00:00.000Z", "price": 10042.8998}, 
  {"date": "2022-04-17T00:00:00.000Z", "price": 10042.8998},
  {"date": "2022-04-18T00:00:00.000Z", "price": 10042.8998},
  {"date": "2022-04-19T00:00:00.000Z", "price": 10281.5002},
  {"date": "2022-04-20T00:00:00.000Z", "price": 9772.000100000001}, 
  {"date": "2022-04-21T00:00:00.000Z", "price": 10087.8003}, 
  {"date": "2022-04-22T00:00:00.000Z", "price": 10050.499899999999}, 
  {"date": "2022-04-23T00:00:00.000Z", "price": 9980.200200000001},
  {"date": "2022-04-24T00:00:00.000Z", "price": 9980.200200000001}, 
  {"date": "2022-04-25T00:00:00.000Z", "price": 9980.200200000001},
  {"date": "2022-04-26T00:00:00.000Z", "price": 8955.9003}
]
```

```
const AssetChart11 = ({history}: Props) => {
  const [parsedHistory, setParsedHistory] = useState<any[]>([]);
  const [max, setMax] = useState(0);
  const [min, setMin] = useState(0);

  useEffect(() => {
    let maxValue = Math.max(...history.map(item => item.price));
    let minValue = Math.min(...history.map(item => item.price));
    let data = history.map(item => {
      return {value: item.price.toFixed(2)};
    });
    setMax(maxValue);
    setMin(minValue);
    setParsedHistory(data);
  }, [history]);

  return (
    <View>
      <LineChart
        data={parsedHistory}
        areaChart={true}
        initialSpacing={0}
        maxValue={max}
        minValue={min}
        adjustToWidth={true}
      />
    </View>
  );
};

export default AssetChart11;
```
<img width="264" alt="Screen Shot 2022-04-27 at 7 07 07 AM" src="https://user-images.githubusercontent.com/28378835/165374069-f72daa6c-fd16-49b9-b543-42e738a17832.png">

**Comment by joshuarichards001** [comment]
Oh, I just had a peek at your docs and It looks like the minHeight prop isn't functional in the ways that I thought it was (only if the data set has negative values). The functionality to set a minimum value is pretty important to me (as you can probably tell since the graph in the message above is not very legible). Should I submit a different issue or is it all good staying here?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @joshuarichards001 👋
Please have a look at https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/92#issuecomment-1049302572

If it doesn't help, do comment here.

**Comment by joshuarichards001** [comment]
Hey mate, cheers. That resolved the issue.

Not ideal having to use a workaround so could be worth chucking it on the backlog but definitely works for now :)

Thanks for your work on this library by the way, have really struggled to find a good well maintained React Native charting library until I found yours!

Cheers,
Josh

**Comment by Abhinandan-Kushwaha** [comment]
Hi @joshuarichards001 👋
Thanks for requesting the feature. It's implemented in version `1.2.13`🎉

Now, we can use the prop `yAxisOffset` to achieve this.

BTW, if you liked the library, please star⭐️ the repo.😀

**Comment by joshuarichards001** [comment]
Hey mate,

Appreciate it. Just gave the repo a star.

With the new update my code is now broken. I'm getting this error here.


<img width="477" alt="Screen Shot 2022-04-28 at 8 05 04 AM" src="https://user-images.githubusercontent.com/28378835/165621970-cfb191d6-4100-464e-98d6-39625754c544.png">

```
TypeError: undefined is not an object (evaluating 'data.length')

This error is located at:
    in LineChart (at AssetChart1.tsx:44)
    in RCTView (at View.js:32)
    in View (at AssetChart1.tsx:43)
    in AssetChart1 (at SharePage.tsx:143)
    in RCTScrollContentView (at ScrollView.js:1674)
    in RCTScrollView (at ScrollView.js:1792)
    in ScrollView (at ScrollView.js:1818)
    in ScrollView (at createNativeWrapper.tsx:66)
    in NativeViewGestureHandler (at createNativeWrapper.tsx:62)
    in ScrollView (at SharePage.tsx:107)
    in SharePage (at SceneView.tsx:126)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:118)
    in SceneView (at useDescriptors.tsx:210)
    in RCTView (at View.js:32)
    in View (at DebugContainer.native.tsx:27)
    in DebugContainer (at NativeStackView.native.tsx:71)
    in MaybeNestedStack (at NativeStackView.native.tsx:230)
    in RNSScreen (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (at src/index.native.tsx:252)
    in MaybeFreeze (at src/index.native.tsx:251)
    in Screen (at NativeStackView.native.tsx:176)
    in SceneView (at NativeStackView.native.tsx:278)
    in RNSScreenStack (at src/index.native.tsx:191)
    in ScreenStack (at NativeStackView.native.tsx:269)
    in NativeStackViewInner (at NativeStackView.native.tsx:323)
    in RCTView (at View.js:32)
    in View (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at NativeStackView.native.tsx:322)
    in NativeStackView (at createNativeStackNavigator.tsx:67)
    in NativeStackNavigator (at Pages.tsx:19)
    in Pages (at SceneView.tsx:126)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:118)
    in SceneView (at useDescriptors.tsx:210)
    in RCTView (at View.js:32)
    in View (at DebugContainer.native.tsx:27)
    in DebugContainer (at NativeStackView.native.tsx:71)
    in MaybeNestedStack (at NativeStackView.native.tsx:230)
    in RNSScreen (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (at src/index.native.tsx:252)
    in MaybeFreeze (at src/index.native.tsx:251)
    in Screen (at NativeStackView.native.tsx:176)
    in SceneView (at NativeStackView.native.tsx:278)
    in RNSScreenStack (at src/index.native.tsx:191)
    in ScreenStack (at NativeStackView.native.tsx:269)
    in NativeStackViewInner (at NativeStackView.native.tsx:323)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:46)
    in SafeAreaProviderCompat (at NativeStackView.native.tsx:322)
    in NativeStackView (at createNativeStackNavigator.tsx:67)
    in NativeStackNavigator (at Navigation.tsx:15)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:430)
    in BaseNavigationContainer (at NavigationContainer.tsx:132)
    in ThemeProvider (at NavigationContainer.tsx:131)
    in NavigationContainerInner (at Navigation.tsx:14)
    in Navigation (at App.tsx:14)
    in Theme (at App.tsx:12)
    in Provider (at App.tsx:11)
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in hedges(RootComponent) (at renderApplication.js:60)
```

**Comment by Abhinandan-Kushwaha** [comment]
My bad!!! I had made a blunder. This reminds me to add snapshot tests and UT.

The issue is fixed in version `1.2.14`🎉
Thanks for quickly finding it and reminding!

**Comment by Abhinandan-Kushwaha** [comment]
Snapshot tests for some example charts written.🎉
Expecting lesser blunders henceforth.😀

**Comment by wcastand** [comment]
can this be available on the bar chart too?

like i provide a bar width and the spacing is done auto?
