### ISSUE TITLE
endOpacity={0} in LineChart areaChart reverts back to opacity 1

### ISSUE THREAD

**Issue by joshuarichards001** [Abhinandan-Kushwaha/react-native-gifted-charts#161]
Hey,

Playing around with areaCharts and when I set the endOpacity to 0 it seems to revert back to 1. To get the functionality I'm looking for I'm currently setting it to 0.001 but it's a bit janky.

Cheers,
Josh

**Comment by Abhinandan-Kushwaha** [comment]
Hi @joshuarichards001 👋

Thanks for pointing out the issue. It has been fixed in version `1.2.8`🎉
