### ISSUE TITLE
Dynamic zIndex for each line for area chart

### ISSUE THREAD

**Issue by cuongnv-dev** [Abhinandan-Kushwaha/react-native-gifted-charts#165]
![Simulator Screen Shot - iPhone 13 - 2022-04-26 at 01 50 55](https://user-images.githubusercontent.com/82807964/165154832-a716aa2e-0690-4193-b0c2-c8e5340363f4.png)
![Simulator Screen Shot - iPhone 13 - 2022-04-26 at 01 51 22](https://user-images.githubusercontent.com/82807964/165154849-c21074e4-a391-43ab-b7c6-80d756124f56.png)

I'm utilizing four lines of data and only displaying one area at a time; with the last line of data, everything is OK, but with another line, the line and area color have been obscured by another area. Could you assist with adding the zIndex properties to the line chart?
Your repo is fantastic; it is extremely useful for React Native projects that have chart functionality. Thank you very much.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @cuongnv-dev 👋
Glad to know that you liked the library. And thanks for requesting this feature.
It is now available in version `1.2.10`🎉

Now we can use the props- `zIndex1`, `zIndex2`, `zIndex3` etc for the corresponding lines.

I hope it helps. Please star⭐️ the library if you liked it 😀
