### ISSUE TITLE
pointerConfig is now very unresponsive 

### ISSUE THREAD

**Issue by PROda221** [Abhinandan-Kushwaha/react-native-gifted-charts#174]
Hello! 
![image](https://user-images.githubusercontent.com/31884259/165887457-096ac717-6d54-48ee-816f-d6ed0bd9c8b2.png)
the pointer often lags now and stucks at a position when it registers a wrong scroll gesture. 

![image](https://user-images.githubusercontent.com/31884259/165887535-5f30aa4f-6175-4107-b38e-64fff5080ad3.png)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @PROda221 
Can you share the code here? Are you running on Android or on iOS? For me, it works fine on iOS. Android still has some issues with the tooltip component.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @PROda221 👋
The issue with pointer getting stuck when the Area chart is present inside vertical ScrollView is fixed in version `1.2.15`🎉

Thanks for your consistent contributions to improve the library.🤗

**Comment by PROda221** [comment]
Awesome work as always @Abhinandan-Kushwaha!!! Now things are much smoother <3
Just the android one is still jaggy and needs fixing.

**Comment by Abhinandan-Kushwaha** [comment]
> 

This is now fixed in version `1.2.16`🎉
Thanks for reminding.

**Comment by Abhinandan-Kushwaha** [comment]
After the major release `1.3.4` it is not slow or jaggy anymore. 
`autoAdjustPointerLabelPosition` is now false by default. This should make the Area and Line charts with `pointerConfig` smooth on Android.
