### ISSUE TITLE
pointer gets disabled when the page scrolls vertically

### ISSUE THREAD

**Issue by joshuarichards001** [Abhinandan-Kushwaha/react-native-gifted-charts#175]
Hey Mate,

I'm noticing that when I'm using the pointer and sliding my finger horizontally across the graph it all works fine but if I do any vertical scroll it cancels the pointer from moving and disables future movement with it.

Is there any way to maybe disable vertical scrolling on a page while I'm interacting with the LineChart?

Here's a video of what I mean:
https://user-images.githubusercontent.com/28378835/166125849-14e64783-c0ea-4359-b31a-a55003735dc6.mov

Cheers,
Josh

**Comment by Abhinandan-Kushwaha** [comment]
Hi @joshuarichards001 👋
The issue with pointer getting stuck when the Area chart is present inside vertical ScrollView is fixed in version `1.2.15`🎉

Thanks for your consistent contributions to improve the library.🤗

**Comment by joshuarichards001** [comment]
No worries mate, appreciate you being so proactive with fixing the issues.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @joshuarichards001 👋
You might want to take a look at this- https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/287#issuecomment-1885884042
