### ISSUE TITLE
isAnimated / Labels

### ISSUE THREAD

**Issue by asadraza4522** [Abhinandan-Kushwaha/react-native-gifted-charts#18]
when the isAnimated is enabled the labels are not showing

**Comment by Abhinandan-Kushwaha** [comment]
Labels do appear, I checked for both iOS and Android.
Can you install the latest version "0.1.4" and try again?

**Comment by Abhinandan-Kushwaha** [comment]
Closing the issue, it’s already working.

**Comment by abhinav-official** [comment]
> Closing the issue, it’s already working.

    "react-native-gifted-charts": "^0.1.15",
    
   
<img width="467" alt="Screenshot 2021-11-17 at 8 28 12 PM" src="https://user-images.githubusercontent.com/36004714/142224574-49530e06-8a63-4a5a-a84f-fdd58bf7a20f.png">
![simulator_screenshot_0B22C15C-6A2D-4A8F-8E42-E4ACCA530E55](https://user-images.githubusercontent.com/36004714/142224617-a42e0590-1aa3-4c0e-965a-764ff3f1e8c8.png)


PLease have a look. Labels vanish after enabling animated prop

**Comment by Abhinandan-Kushwaha** [comment]
Thanks, @abhinav-official for pointing out the issue and providing a solution as well!
I will surely add it to the docs.
