### ISSUE TITLE
This experimental syntax requires enabling the parser plugin: 'jsx', 'flow', or 'typescript'

### ISSUE THREAD

**Issue by programminghat** [Abhinandan-Kushwaha/react-native-gifted-charts#180]
After installing react-native-gifted-charts and adding a basic LineChart to the file, I receive any of the following errors when starting or building my project:

>.../node_modules/react-native-gifted-charts/src/PieChart/index.tsx:135:12: This experimental syntax requires enabling one of the following parser plugin(s): "jsx", "flow", "typescript". (135:12)
  133 |     });
  134 |     pData = __spreadArray([0], pData, true);
> 135 |     return (<react_native_1.View style={[
      |            ^
  136 |             {
  137 |                 backgroundColor: backgroundColor,
  138 |                 height: semiCircle ? canvasHeight / 2 : canvasHeight,

>.../node_modules/react-native-gifted-charts/src/BarChart/index.tsx:450:16: This experimental syntax requires enabling one of the following parser plugin(s): "jsx", "flow", "typescript". (450:16)
  448 |     };
  449 |     var renderHorizSections = function () {
> 450 |         return (<>
      |                ^
  451 |         {horizSections.map(function (sectionItems, index) {
  452 |                 return (<react_native_1.View key={index} style={[
  453 |                         styles_1.styles.horizBar,

>.../node_modules/react-native-gifted-charts/src/LineChart/index.tsx:1146:16: This experimental syntax requires enabling one of the following parser plugin(s): "jsx", "flow", "typescript". (1146:16)
  1144 |     }
  1145 |     var renderLabel = function (index, label, labelTextStyle, labelComponent) {
> 1146 |         return (<react_native_1.View style={[
       |                ^
  1147 |                 {
  1148 |                     position: 'absolute',
  1149 |                     bottom: 30,

This is my package.json:

> {
>   "name": "project",
>   "version": "1.0.0",
>   "main": "index.js",
>   "license": "MIT",
>   "devDependencies": {
>     "@babel/preset-react": "^7.16.7",
>     "@typescript-eslint/eslint-plugin": "^5.22.0",
>     "@typescript-eslint/parser": "^5.22.0",
>     "eslint": "^8.14.0",
>     "eslint-plugin-react": "^7.29.4",
>     "parcel-bundler": "^1.12.5",
>     "typescript": "^4.6.4"
>   },
>   "dependencies": {
>     "@types/react-native": "^0.66.15",
>     "express": "^4.17.2",
>     "mysql": "^2.18.1",
>     "react": "^17.0.2",
>     "react-dom": "^17.0.2",
>     "react-native-gifted-charts": "^1.2.16",
>     "react-native-linear-gradient": "^2.5.6",
>     "react-native-svg": "^12.3.0",
>     "react-native-web": "^0.17.5"
>   },
>   "scripts": {
>     "start": "parcel serve ./index.html",
>     "build": "parcel build ./index.html"
>   },
>   "alias": {
>     "react-native": "react-native-web"
>   }
> }
> 

Sorry if I am missing something obvious. I have searched for any article on the error and none of the solutions seem to have worked for me.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @programminghat 👋
I guess you are trying to use the library with `react-native-web`. Not sure if the library supports web.
Please reply here if this is the case or if you find any other reason behind the error.

**Comment by programminghat** [comment]
This was beyond my knowledge to adapt for react-native-web. I am sure it's possible with more experience!
