### ISSUE TITLE
[BarChart] numOfLines for xAxisLabelTexts

### ISSUE THREAD

**Issue by qsdamar** [Abhinandan-Kushwaha/react-native-gifted-charts#181]
Hello and thank you for such an amazing and simple to use library.

I have a request where I need to display text in 2 lines in xAxisLabelTexts (eg "MAY\n6") because there is not enough space to show everything in one line. As I can see inside the RenderBars component, its predefined numOfLines={1}. Is there a possibility to make that property customizable? To be more precise, I'm talking about RenderBars.tsx file, line 207.

Thanks in advance!

**Comment by Abhinandan-Kushwaha** [comment]
Hi @qsdamar 👋
Thanks for requesting the feature. It is now available in version `1.2.17`🎉

Now we can use the prop `yAxisTextNumberOfLines` to set the number of lines for y axis label text.

Please note that there should be enough vertical space to display the **`n`** lines of text. For that, the props `stepHeight`, `height` and `noOfSections` can be used. Remember that these props must follow the relation - 
```js
height = stepHeight * noOfSections
```

Similarly, we can use the prop `xAxisTextNumberOfLines` to set the number of lines for x axis label text.
I hope it helps.🤗
