### ISSUE TITLE
PointerComponent is not autoadjusting width on the left side

### ISSUE THREAD

**Issue by PROda221** [Abhinandan-Kushwaha/react-native-gifted-charts#183]
![image](https://user-images.githubusercontent.com/31884259/167874217-854829dd-2a5b-477d-bc83-1efe8e17269f.png)
On the right side it is working properly

**Comment by Abhinandan-Kushwaha** [comment]
Hi @PROda221 👋
Auto adjusting is not possible. And it makes sense because it gives a hint to the user that the chart exists further to the left and they should scroll to the left.

**Comment by PROda221** [comment]
Hello @Abhinandan-Kushwaha,
But this is the start of the chart. There is no chart to the left.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @PROda221 
Can you send me the code for the same?

**Comment by PROda221** [comment]
import React, {useEffect} from 'react';
import {View, Text, StyleSheet} from 'react-native';
import {LineChart} from 'react-native-gifted-charts';
import {
  scales,
  spacing,
  fontSizes,
  colors,
  deviceDimensions,
  fonts,
} from '../constants/AppStyles';
import {getCommaString} from '../constants/CommonFunctions';
const AreaGraphCard = props => {
  return (
    <View
      style={{
        backgroundColor: props.backgroundColor,
      }}>
      <LineChart
        horizontalRulesStyle={{width: deviceDimensions.width * 0.775}}
        thickness={scales(0)}
        startFillColor1={props.color}
        hideDataPoints={true}
        startFillColor2={props.color2}
        dataPointsColor1={props.color}
        dataPointsColor2={props.color2}
        color1={colors.black1}
        color2={colors.black1}
        adjustToWidth={true}
        maxValue={props.maxValue}
        noOfSections={props.noOfSections}
        yAxisLabelTexts={props.yAxisData}
        areaChart
        stepValue={props.stepValue}
        rulesThickness={scales(1)}
        yAxisTextStyle={{color: colors.grey2, fontSize: fontSizes.smaller}}
        data={props.data}
        verticalLineColor={colors.white}
        data2={props.data2}
        curved
        endFillColor1={props.color}
        endFillColor2={props.color2}
        startOpacity1={0.6}
        endOpacity1={0.1}
        startOpacity2={0.6}
        scrollAnimation={false}
        endOpacity2={0.1}
        spacing={props.graphType === 'Monthly' ? spacing(43) : spacing(58)}
        xAxisThickness={1}
        backgroundColor={props.backgroundColor}
        rulesColor={props.yAxisStyle}
        rulesType="solid"
        initialSpacing={scales(15)}
        yAxisColor={colors.black1}
        xAxisColor={props.yAxisStyle}
        dataPointsHeight={scales(20)}
        showScrollIndicator={true}
        dataPointsWidth={scales(20)}
        hideRules={props.rulesVisible}
        width={deviceDimensions.width * 0.75}
        pointerConfig={{
          pointerStripUptoDataPoint: true,
          activatePointersOnLongPress: true,
          activatePointersDelay: 10,
          pointerStripColor: colors.searchPlaceholderColor,
          autoAdjustPointerLabelPosition: true,
          pointerStripWidth: 2,
          strokeDashArray: [2, 5],
          pointerColor: 'lightgray',
          radius: 2,
          pointerLabelHeight: scales(115),
          // pointerLabelWidth: scales(100),
          pointerLabelComponent: items => {
            console.log('items :', items);
            return (
              <View style={styles.spacing}>
                <View style={styles.pointerLabelComponentStyle}>
                  {props.graphType === 'Yearly' ? (
                    <View>
                      <Text style={styles.pointerYearText}>
                        {props.tooltipText[0].value}
                      </Text>
                      <Text style={styles.pointerValueText}>
                        {getCommaString(
                          (
                            (items[0]?.value / 100) *
                            props.areaMaxValue
                          ).toFixed(2),
                        )}
                      </Text>
                      <Text
                        style={[
                          styles.pointerYearText,
                          {paddingTop: spacing(12)},
                        ]}>
                        {props.tooltipText[1].value}
                      </Text>
                      <Text style={styles.pointerValueText}>
                        {getCommaString(
                          (
                            (items[1]?.value / 100) *
                            props.areaMaxValue
                          ).toFixed(2),
                        )}
                      </Text>
                    </View>
                  ) : (
                    <View>
                      <Text style={styles.pointerYearText}>
                        {props.tooltipText[2].value}
                      </Text>
                      <Text style={styles.pointerValueText}>
                        {getCommaString(
                          (
                            (items[0]?.value / 100) *
                            props.areaMaxValue
                          ).toFixed(2),
                        )}
                      </Text>
                    </View>
                  )}
                </View>
                <View style={styles.triangleCenter}>
                  <View style={styles.triangleStyle}></View>
                </View>
              </View>
            );
          },
        }}
      />
    </View>
  );
};

export default AreaGraphCard;

const styles = StyleSheet.create({
  pointerLabelComponentStyle: {
    height: scales(100),
    width: scales(100),
    backgroundColor: colors.areaGraphPointerLabel,
    // position: 'absolute',
    left: spacing(-40),
    // top: spacing(-50),
    borderRadius: scales(6),
    justifyContent: 'center',
    paddingLeft: spacing(16),
  },
  triangleCenter: {justifyContent: 'center', alignItems: 'center'},
  triangleStyle: {
    width: 0,
    height: 0,
    borderStyle: 'solid',
    borderTopWidth: scales(10),
    borderRightWidth: scales(8),
    borderBottomWidth: 0,
    borderLeftWidth: scales(8),
    borderTopColor: colors.areaGraphPointerLabel,
    borderRightColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: 'transparent',
  },
  spacing: {
    left: spacing(-3),
  },
  pointerYearText: {
    color: colors.tooltipYearColor,
    fontSize: fontSizes.caption,
    // fontFamily: fonts.arialRegular,
  },
  pointerValueText: {
    color: colors.tooltipValueColor,
    fontWeight: 'bold',
    // fontFamily: fonts.arialRegular,
    fontSize: fontSizes.caption1,
  },
});

**Comment by Abhinandan-Kushwaha** [comment]
Hi @PROda221 
This is because you have commented the `pointerLabelWidth` property. Please uncomment it, then it should start working.

**Comment by PROda221** [comment]
Even when uncommenting it the issue still persists.

**Comment by Abhinandan-Kushwaha** [comment]
Maybe, you need increase the `pointerLabelWidth` value.

Actually, I was not able to run your code, because I didn't have the props. If you send the props object, I can run your code and find out the exact issue.

**Comment by PROda221** [comment]
![image](https://user-images.githubusercontent.com/31884259/168770705-788d4278-abdc-48c9-afa2-6feb632d4c1d.png)

{
    "data": [
        {
            "value": 0
        },
        {
            "value": 0
        },
        {
            "value": 0
        },
        {
            "value": 0
        },
        {
            "value": 2.543008714282514
        },
        {
            "value": 24.470271636182705
        }
    ],
    "data2": [
        {
            "value": 24.53946688785736
        },
        {
            "value": 100
        },
        {
            "value": 7.160509848729807
        },
        {
            "value": 0
        },
        {
            "value": 0
        },
        {
            "value": 0
        }
    ],
    "maxValue": 100,
    "areaMaxValue": 42095.805412999995,
    "noOfSections": 5,
    "stepValue": 8419.1610826,
    "color": "#439DAE",
    "color2": "#5674AF",
    "graphType": "Yearly",
    "backgroundColor": "#1C1C1C",
    "yAxisStyle": "#292929",
    "yAxisData": [
        "0%",
        "20%",
        "40%",
        "60%",
        "80%",
        "100%"
    ],
    "tooltipText": [
        {
            "value": "2022"
        },
        {
            "value": "2021"
        },
        {
            "value": "undefined - undefined"
        }
    ]
}

**Comment by PROda221** [comment]
Any updates yet?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @PROda221 👋

You need to wrap the `pointerLabelComponent` in a View and provide it a width equal to the `pointerLabelWidth`. Then it starts working fine.

Here is the code I used-
```js
<LineChart
    horizontalRulesStyle={{width: Dimensions.get('window').width * 0.775}}
    thickness={0}
    startFillColor1={props.color}
    hideDataPoints={true}
    startFillColor2={props.color2}
    dataPointsColor1={props.color}
    dataPointsColor2={props.color2}
    color1={'black'}
    color2={'black'}
    adjustToWidth={true}
    maxValue={props.maxValue}
    noOfSections={props.noOfSections}
    yAxisLabelTexts={props.yAxisData}
    areaChart
    stepValue={props.stepValue}
    rulesThickness={1}
    yAxisTextStyle={{color: 'grey', fontSize: 10}}
    data={props.data}
    verticalLineColor={'white'}
    data2={props.data2}
    curved
    endFillColor1={props.color}
    endFillColor2={props.color2}
    startOpacity1={0.6}
    endOpacity1={0.1}
    startOpacity2={0.6}
    scrollAnimation={false}
    endOpacity2={0.1}
    spacing={props.graphType === 'Monthly' ? 43 : 58}
    xAxisThickness={1}
    backgroundColor={props.backgroundColor}
    rulesColor={props.yAxisStyle}
    rulesType="solid"
    initialSpacing={15}
    yAxisColor={'black'}
    xAxisColor={props.yAxisStyle}
    dataPointsHeight={20}
    showScrollIndicator={true}
    dataPointsWidth={20}
    hideRules={props.rulesVisible}
    width={Dimensions.get('window').width * 0.75}
    pointerConfig={{
      pointerStripUptoDataPoint: true,
      // activatePointersOnLongPress: true,
      activatePointersDelay: 10,
      pointerStripColor: 'lightgray',
      autoAdjustPointerLabelPosition: true,
      pointerStripWidth: 2,
      strokeDashArray: [2, 5],
      pointerColor: 'lightgray',
      radius: 2,
      pointerLabelHeight: 115,
      pointerLabelWidth: 120,
      pointerLabelComponent: items => {
        console.log('items :', items);
        return props.graphType === 'Yearly' ? (
          <View style={{backgroundColor:'white',justifyContent:'center',width:120,padding:10}}>
            <Text>{props.tooltipText[0].value}</Text>
            <Text>{'Sample tooltip title'}</Text>
            <Text>{props.tooltipText[1].value}</Text>
            <Text>{'Sample tooltip text'}</Text>
          </View>
        ) : (
          <>
            <Text>{props.tooltipText[2].value}</Text>
            <Text>{'Looks cool'}</Text>
          </>
        );
      },
    }}
  />
 ```
 Everything is same as your code, I have just changed the `pointerLabelComponent`. See the style of the View inside pointerLabelComponent. I have given a width of 120 (same as pointerLabelWidth)
 
 And here is the output-

https://user-images.githubusercontent.com/20596944/169402639-838a0c0e-0834-4273-9b1f-89a485662e6d.mov



You can see that the left side is perfectly fine, but on the right side the label is not adjusting. I have fixed this in the new release - version `1.2.19`
Here is the output of the same code after the update-


https://user-images.githubusercontent.com/20596944/169402221-4bd0a259-bc53-412f-8367-568149b1fc72.mov

**Comment by siddhi-unthinkable-co** [comment]
Hello @Abhinandan-Kushwaha 

In my case it's not showing the pointer properly for the left most end:

https://user-images.githubusercontent.com/106315351/170823997-2578ac0a-01a9-4b02-a8ef-2f749ff5a29f.mov

Code Snippet:

const AreaGraphCard = props => {
  return (
    <View
      style={{
        backgroundColor: props.backgroundColor,
      }}>
      <LineChart
        horizontalRulesStyle={{width: deviceDimensions.width * 0.775}}
        thickness={scales(0)}
        startFillColor1={props.color}
        hideDataPoints={true}
        startFillColor2={props.color2}
        dataPointsColor1={props.color}
        dataPointsColor2={props.color2}
        color1={colors.black1}
        color2={colors.black1}
        adjustToWidth={true}
        maxValue={props.maxValue}
        noOfSections={props.noOfSections}
        yAxisLabelTexts={props.yAxisData}
        areaChart
        stepValue={props.stepValue}
        rulesThickness={scales(1)}
        yAxisTextStyle={{color: colors.grey2, fontSize: fontSizes.smaller}}
        data={props.data}
        verticalLineColor={colors.white}
        data2={props.data2}
        curved
        endFillColor1={props.color}
        endFillColor2={props.color2}
        startOpacity1={0.6}
        endOpacity1={0.1}
        startOpacity2={0.6}
        scrollAnimation={false}
        endOpacity2={0.1}
        spacing={props.graphType === 'Monthly' ? spacing(43) : spacing(58)}
        xAxisThickness={1}
        backgroundColor={props.backgroundColor}
        rulesColor={props.yAxisStyle}
        rulesType="solid"
        initialSpacing={scales(15)}
        yAxisColor={colors.black1}
        xAxisColor={props.yAxisStyle}
        dataPointsHeight={scales(20)}
        showScrollIndicator={true}
        dataPointsWidth={scales(20)}
        hideRules={props.rulesVisible}
        width={deviceDimensions.width * 0.75}
        pointerConfig={{
          pointerStripUptoDataPoint: true,
          activatePointersOnLongPress: true,
          //activatePointersDelay: 100,
          activatePointersDelay: 10,
          pointerStripColor: colors.searchPlaceholderColor,
          autoAdjustPointerLabelPosition: true,
          pointerStripWidth: 2,
          strokeDashArray: [2, 5],
          pointerColor: 'lightgray',
          radius: 2,
          pointerLabelHeight: scales(115),
          pointerLabelWidth: scales(100),
          pointerLabelComponent: items => {
            return (
              <View style={styles.spacing}>
                <View style={styles.pointerLabelComponentStyle}>
                  {props.graphType === 'Yearly' ? (
                    <View>
                      <Text style={styles.pointerYearText}>
                        {props.tooltipText[0].value}
                      </Text>
                      <Text style={styles.pointerValueText}>
                        {getCommaString(
                          (
                            (items[0]?.value / 100) *
                            props.areaMaxValue
                          ).toFixed(2),
                        )}
                      </Text>
                      <Text
                        style={[
                          styles.pointerYearText,
                          {paddingTop: spacing(12)},
                        ]}>
                        {props.tooltipText[1].value}
                      </Text>
                      <Text style={styles.pointerValueText}>
                        {getCommaString(
                          (
                            (items[1]?.value / 100) *
                            props.areaMaxValue
                          ).toFixed(2),
                        )}
                      </Text>
                    </View>
                  ) : (
                    <View>
                      <Text style={styles.pointerYearText}>
                        {props.tooltipText[2].value}
                      </Text>
                      <Text style={styles.pointerValueText}>
                        {getCommaString(
                          (
                            (items[0]?.value / 100) *
                            props.areaMaxValue
                          ).toFixed(2),
                        )}
                      </Text>
                    </View>
                  )}
                </View>
                <View style={styles.triangleCenter}>
                  <View style={styles.triangleStyle}></View>
                </View>
              </View>
            );
          },
        }}
      />
    </View>
  );
};

export default AreaGraphCard;

const styles = StyleSheet.create({
  pointerLabelComponentStyle: {
    height: scales(100),
    width: scales(100),
    backgroundColor: colors.areaGraphPointerLabel,
    //left: spacing(-40),
    borderRadius: scales(6),
    justifyContent: 'center',
    //paddingLeft: spacing(16),
    padding:scales(10)
  },
  triangleCenter: {justifyContent: 'center', alignItems: 'center'},
  triangleStyle: {
    width: 0,
    height: 0,
    borderStyle: 'solid',
    borderTopWidth: scales(10),
    borderRightWidth: scales(8),
    borderBottomWidth: 0,
    borderLeftWidth: scales(8),
    borderTopColor: colors.areaGraphPointerLabel,
    borderRightColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: 'transparent',
  },
  spacing: {
    //left: spacing(-3),
  },
  pointerYearText: {
    color: colors.tooltipYearColor,
    fontSize: fontSizes.caption,
    // fontFamily: fonts.arialRegular,
  },
  pointerValueText: {
    color: colors.tooltipValueColor,
    fontWeight: 'bold',
    // fontFamily: fonts.arialRegular,
    fontSize: fontSizes.caption1,
  },
});

Also the version used in the project is : 1.2.29
but, the pointer label is not adjusting for the right-end side.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @siddhi-unthinkable-co 👋

The pointer for the left-most end is getting auto-shifted because the value for `autoAdjustPointerLabelPosition` is true.
Try setting the property `autoAdjustPointerLabelPosition` to `false` inside the pointerConfig object.

If you intentionally set the `autoAdjustPointerLabelPosition` to true, then the pointer for the left-most end is supposed to be like this, otherwise half of the tooltip would go out of the chart beyond the y-axis, and thus would be invisible.
To me, the current behaviour seems fine. Maybe, for the leftmost part of the chart you need to change the position of the triangle towards the left of the tooltip as in the pic below-

<img width="515" alt="Screenshot 2022-05-28 at 19 15 59" src="https://user-images.githubusercontent.com/20596944/170828518-8de41846-e9ae-439b-a9fa-b4d6f4ff595b.png">

**Comment by siddhi-unthinkable-co** [comment]
Hi @Abhinandan-Kushwaha👋

Yes, for the leftmost part of the chart I need to change the position of the triangle towards the left of the tooltip, is it achievable?

Also for the right end, half of the tooltip is going out of the chart beyond the y-axis, and thus it's invisible, I have version 1.2.29 and as you mentioned above, u've corrected this issue for right end in version 1.2.19, then why is it so? 🙄???

**Comment by Abhinandan-Kushwaha** [comment]
Hi @siddhi-unthinkable-co 
Can you send me the props?

**Comment by siddhi-unthinkable-co** [comment]
<img width="754" alt="Screenshot 2022-05-30 at 10 43 29 AM" src="https://user-images.githubusercontent.com/106315351/170921400-2a3db095-23d1-4c8a-9340-e6ed58869ab4.png">

**Comment by Abhinandan-Kushwaha** [comment]
Can you please copy it as text and paste here.
It's too difficult for me to write these values from screenshot.

**Comment by siddhi-unthinkable-co** [comment]
Hello @Abhinandan-Kushwaha 
Following are the datas as per APIs:

data: Array(12)
0: {value: 0, labelComponent: ƒ}
1: {value: 0, labelComponent: ƒ}
2: {value: 0, labelComponent: ƒ}
3: {value: 0, labelComponent: ƒ}
4: {value: 0, labelComponent: ƒ}
5: {value: 0, labelComponent: ƒ}
6: {value: 0, labelComponent: ƒ}
7: {value: 0, labelComponent: ƒ}
8: {value: 0, labelComponent: ƒ}
9: {value: 2.5871326324555546, labelComponent: ƒ}
10: {value: 4.678033743362773, labelComponent: ƒ}
11: {value: 20.216823250031982, labelComponent: ƒ}


data2: Array(11)
0: {value: 16.844381361558508, labelComponent: ƒ}
1: {value: 8.120871495056477, labelComponent: ƒ}
2: {value: 100, labelComponent: ƒ}
3: {value: 1.7351068411690478, labelComponent: ƒ}
4: {value: 7.804353947946355, labelComponent: ƒ}
5: {value: 0, labelComponent: ƒ}
6: {value: 0, labelComponent: ƒ}
7: {value: 0, labelComponent: ƒ}
8: {value: 0, labelComponent: ƒ}
9: {value: 0, labelComponent: ƒ}
10: {value: 0, labelComponent: ƒ}

**Comment by Abhinandan-Kushwaha** [comment]
Hi @siddhi-unthinkable-co 
Please update to version `1.2.31`
The issue is fixed.
