### ISSUE TITLE
Issue when piechart data having single data

### ISSUE THREAD

**Issue by VijinR** [Abhinandan-Kushwaha/react-native-gifted-charts#187]
piechart not showing when having single data

const data = [{value: 15}, {value: 30}, {value: 26}, {value: 40}];
![Screenshot 2022-05-13 at 6 36 13 PM](https://user-images.githubusercontent.com/97605704/168289679-be30687a-e450-4d4a-9caa-1fe60e757fde.png)
const data = [{value: 15}];
![Screenshot 2022-05-13 at 6 36 52 PM](https://user-images.githubusercontent.com/97605704/168289809-11b8fcd1-17e7-4d81-9b8f-4180affbc0a5.png)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @VijinR 👋
Thanks for pointing out the issue. It has been resolved in version `1.2.18`🎉
