### ISSUE TITLE
xAxisLabel top margin

### ISSUE THREAD

**Issue by Hijleh** [Abhinandan-Kushwaha/react-native-gifted-charts#190]
I am trying to give more margin from the top to the x-axis labels, but still can't, 
I tried to use **labelComponent** with marginTop, but it seems that the labels container have fixed height because the text start to look trimmed from the bottom, any idea how to handle this?

<img width="520" alt="image" src="https://user-images.githubusercontent.com/48893105/169313050-868fcf73-7c88-40b8-a2da-d240ed27411f.png">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Hijleh 👋
Try the `labelsExtraHeight` prop. I hope it helps.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Hijleh 👋
Can you share the complete code you are using? Also, please include the values of the variables like `theme.typography.h9Regular` and `Locales.Ar`

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Hijleh 👋
Instead of giving marginTop try giving a **_negative_** `marginBottom` to the xAxisLabelTextStyle.

**Comment by Hijleh** [comment]
Hi @Abhinandan-Kushwaha, 

a negative marginBottom works good, thanks so much.

**Comment by rupalpatel0008** [comment]
In my case negative marginRight fixed the issue. I had the labels rotated
