### ISSUE TITLE
Event thrown when the LineChart is let go?

### ISSUE THREAD

**Issue by joshuarichards001** [Abhinandan-Kushwaha/react-native-gifted-charts#191]
Heya!

Does the LineChart have some functionality that 

- throws an event when the chart is pressed
- while the graph is being pressed an event sends out the current index of the point being pressed 
- and finally, throws an event when the chart is let go?

Cheers,
Josh

**Comment by Abhinandan-Kushwaha** [comment]
Hi @joshuarichards001 👋
Thanks for requesting this feature. I have added the prop `getPointerProps` in version `1.2.20`🎉


`getPointerProps` prop can be used to get the current pointer's index, x and y coordinate values. It is a callback function that accepts a single parameter which is an object. This object has following properties-
1. pointerIndex
2. pointerX
3. pointerY

Here's an example-
```js
getPointerProps= {(pointerProps)=>{
  console.log(pointerProps);
}}
```

When the chart is pressed, it returns the index of the data point pressed.
When the chart is scrolled after pressing, it returns the index of the data point currently focused.
When the chart is released, it returns the index -1.
