### ISSUE TITLE
Horizontal Bar chart issue

### ISSUE THREAD

**Issue by htduongdl96** [Abhinandan-Kushwaha/react-native-gifted-charts#194]
-I used horizontal bar chart but I have several issues:
+ It overlaps with another view which is the upward View.
+ When I tried to use labelWidth to expand the label, it doesn't line up with the bar chart, and the title is push to the outer left
+ It doesn't have a dynamic height  (Below image I have 8 columns but it only shows 7)

![image](https://user-images.githubusercontent.com/37286834/169494591-9a64e335-5ade-400d-a94d-34a99b081dd7.png)

Here is my props:
              <BarChart
                horizontal
                barWidth={22}
                noOfSections={3}
                barBorderRadius={4}
                frontColor="lightgray"
                data={showChart}
                yAxisThickness={0}
                xAxisThickness={0}
                yAxisTextStyle={{ color: '#d8c8d5' }}
                yAxisAtTop={false}
              />

**Comment by Abhinandan-Kushwaha** [comment]
Hi @htduongdl96 👋
Horizontal Bar charts are still under experiment. However, your use case can be achieved with some work-arounds.
For example providing negative **marginTop** and **marginLeft** values to `labelTextStyle`. And using the `labelsExtraHeight` prop.

Here's one similar chart I made-

<img width="315" alt="Screenshot 2022-05-20 at 4 35 41 PM" src="https://user-images.githubusercontent.com/20596944/169515257-6e7900a5-7a27-47ce-b045-f1068c4b41fe.png">

The code for the same is-
```js
const styleObject = {
    marginLeft: -130,
    paddingLeft: 110,
    marginTop: -55,
  };
const showChart = [
  {
    value: 13,
    label: 'hello world here',
    labelWidth: 120,
    labelTextStyle: styleObject,
  },
  {
    value: 9,
    label: 'hello world here',
    labelWidth: 120,
    labelTextStyle: styleObject,
  },
  {
    value: 3,
    label: 'hello world here',
    labelWidth: 120,
    labelTextStyle: styleObject,
  },
  {
    value: 2,
    label: 'hello world here',
    labelWidth: 120,
    labelTextStyle: styleObject,
  },
  {
    value: 2,
    label: 'hello world here',
    labelWidth: 120,
    labelTextStyle: styleObject,
  },
  {
    value: 1,
    label: 'hello world here',
    labelWidth: 120,
    labelTextStyle: styleObject,
  },
  {
    value: 1,
    label: 'hello world here',
    labelWidth: 120,
    labelTextStyle: styleObject,
  },
];

return(
<BarChart
  horizontal
  barWidth={22}
  noOfSections={3}
  barBorderRadius={4}
  labelsExtraHeight={120}
  data={showChart}
  yAxisThickness={0}
  xAxisThickness={0}
  yAxisTextStyle={{color: 'black'}}
  yAxisAtTop={false}
  width={320}
/>
)
```
Notice that in horizontal mode, `width` represents the height of the chart and `labelsExtraHeight` represents the labels' width.
I hope it helps.🤗
