### ISSUE TITLE
How to show full text of yAxisLabelTexts

### ISSUE THREAD

**Issue by cuongnv-dev** [Abhinandan-Kushwaha/react-native-gifted-charts#197]
**Describe the bug**
I cannot show full text of yAxisLabelTexts

Here is my yAxisLabelTexts : ["0", "246.122.825 VND", "492.245.650 VND", "738.368.475 VND", "984.491.300 VND"]

**Current result:** 
![Simulator Screen Shot - iPhone 13 - 2022-05-21 at 15 05 24](https://user-images.githubusercontent.com/82807964/169642292-63379421-f3f7-4e39-bf74-35b6605f103b.png)

**Expected behavior**
I want to show the suffix break in a new line like this. I try to using the prop yAxisLabelSuffix but it cannot break in new line. And seem like the number after "." has been removed.
<img width="314" alt="Screenshot 2022-05-21 at 3 00 56 PM" src="https://user-images.githubusercontent.com/82807964/169642122-2d4d956a-8427-46c2-a187-5959f4777225.png">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @cuongnv-dev 👋
To avoid cutting off the digits after "." we can use the prop `showFractionalValues`
To render the label in 2 lines we can set the prop `yAxisTextNumberOfLines = {2}`
Also, we can set the width of the y axis labels using the prop `yAxisLabelWidth`.

Here's an example-
<img width="302" alt="Screenshot 2022-05-21 at 3 59 13 PM" src="https://user-images.githubusercontent.com/20596944/169647545-8d5b3e56-1713-4550-b1ea-c4a582016cf3.png">

The code for the above chart is-
```js
<LineChart
  noOfSections={4}
  yAxisLabelTexts={[
    '0',
    '246.122.825 VND',
    '492.245.650 VND',
    '738.368.475 VND',
    '984.491.300 VND',
  ]}
  yAxisTextNumberOfLines={2}
  showFractionalValues
  yAxisLabelWidth={100}
  data={llData}
/>
```
I hope it helps.🤗

**Comment by Abhinandan-Kushwaha** [comment]
Hi @cuongnv-dev 
Just wanted to inform you that version `1.2.22` onwards, we don't need to set the prop `showFractionalValues` to **true**, if we use the prop `yAxisLabelTexts`. This is because we provide custom values in `yAxisLabelTexts` and it makes no sense to remove "." from the custom label texts.

**Comment by Abhinandan-Kushwaha** [comment]
Also, I see that you want the label text to be right aligned. You can use `{textAlign:'right'}` in the `yAxisTextStyle`. Also, provide appropriate width inside the `yAxisTextStyle`

So the new code will be-
```js
<LineChart
  noOfSections={4}
  yAxisLabelTexts={[
    '0',
    '246.122.825 VND',
    '492.245.650 VND',
    '738.368.475 VND',
    '984.491.300 VND',
  ]}
  yAxisTextNumberOfLines={2}
  yAxisTextStyle={{textAlign:'right',width:88}}
  yAxisLabelWidth={100}
  data={llData}
  pointerConfig={{
    showPointerStrip: true,
  }}
/>
```
It will produce the below output-
<img width="301" alt="Screenshot 2022-05-21 at 4 54 52 PM" src="https://user-images.githubusercontent.com/20596944/169649537-de9b52aa-5153-4538-bde4-5987d8cba50e.png">

**Comment by cuongnv-dev** [comment]
Awesome, thank you so much
