### ISSUE TITLE
Pointer stripe is visible in spite of showPointerStrip = false

### ISSUE THREAD

**Issue by cuongnv-dev** [Abhinandan-Kushwaha/react-native-gifted-charts#198]
I cannot hide the pointer strip in spite of I have added the showPointerStrip = false in line chart

**Here is my code**
<img width="486" alt="Screenshot 2022-05-21 at 5 12 26 PM" src="https://user-images.githubusercontent.com/82807964/169646920-31e93aa4-fd2d-450d-aa2b-ce1ee4197432.png">

**And the result**
![Simulator Screen Shot - iPhone 13 - 2022-05-21 at 17 12 55](https://user-images.githubusercontent.com/82807964/169646943-d01c3be5-c830-4b67-b05c-cbb4348f4405.png)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @cuongnv-dev 👋
Thanks for pointing out the issue. It has been fixed in the version `1.2.22`🎉

**Comment by cuongnv-dev** [comment]
I have upgrade version and it work well. Thank you

**Comment by cuongnv-dev** [comment]
But I have another question: I can't seem to find a way to display the pointer label directly above the pointer component. I tried using autoAdjustPointerLabelPosition = true, but it didn't work.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @cuongnv-dev 👋
To display the pointer label directly above the pointer component, you need to set the property `pointerStripUptoDataPoint` to true in the `pointerConfig` prop.

For example-
```js
<LineChart
  data={data}
  pointerConfig={{
    showPointerStrip: true,
    pointerStripUptoDataPoint: true,
    pointerLabelComponent: items => {
      return(
        <View style={{height:30, width:50, borderRadius:10, backgroundColor:'#565656'}}>
          <Text>{items[0].value}</Text>
        </View>
      )
    }
  }}
/>
```

Then you can adjust the label position to somewhat left, right or up, down using the style of the parent View in the `pointerLabelComponent`

I hope it helps. 🤗
