### ISSUE TITLE
How to use custom gradient colors in pie charts?

### ISSUE THREAD

**Issue by usama23sep** [Abhinandan-Kushwaha/react-native-gifted-charts#200]
Hi, thank you for this awesome library!

I would like to know if you can use custom gradient colors for each section of Pie Chart?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @usama23sep 👋
Radial Gradient can be applied by just passing the showGradient prop. The simplest example is-

```js
import { PieChart } from "react-native-gifted-charts";
    
const App = () => {
  const pieData = [
      {value: 54, color: '#177AD5'},
      {value: 40, color: '#79D2DE'},
      {value: 20, color: '#ED6665'}
  ];
  return <PieChart data={pieData} showGradient/>;
}
```
The result of the above code is-

<img width="213" alt="Screenshot 2022-05-21 at 10 40 01 PM" src="https://gifted-charts.web.app/static/media/pieGrad.0dc54734.png">

To set custom gradient colors for each section, we can use the `gradientCenterColor` property inside the data objects.

For example-
```js
const pieData = [
  {value: 54, color: '#177AD5', gradientCenterColor: 'lightblue'},
  {value: 40, color: '#79D2DE', gradientCenterColor: '#7777cc'},
  {value: 20, color: '#ED6665', gradientCenterColor: 'pink'},
];
```
Now the output will be-

<img width="222" alt="Screenshot 2022-05-21 at 10 57 09 PM" src="https://user-images.githubusercontent.com/20596944/169662692-f701900b-8efe-4b5e-9cd1-47128651de5f.png">

I hope it helps.🤗
