### ISSUE TITLE
LabelComponent label width

### ISSUE THREAD

**Issue by asifbadeghar54** [Abhinandan-Kushwaha/react-native-gifted-charts#201]
![WhatsApp Image 2022-05-23 at 5 45 10 PM](https://user-images.githubusercontent.com/39403588/169817292-75a27d81-e242-4424-8a24-0bff91701ee1.jpeg)

What to do if axis label text width is more how to adjust it.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @asifbadeghar54 👋
There are 2 ways to handle this-
1. You can make the x axis labels multiline using the `xAxisTextNumberOfLines` prop.
2. You can rotate the labels using the `rotateLabel` prop.
