### ISSUE TITLE
Tooltip for bar chart - stacks

### ISSUE THREAD

**Issue by Hijleh** [Abhinandan-Kushwaha/react-native-gifted-charts#202]
I didn't find a tooltip for the bar chart for each stack like this

<img width="347" alt="image" src="https://user-images.githubusercontent.com/48893105/169827011-167b762b-533f-44ae-b0ff-540afaec5afd.png">

please confirm if this is not supported yet

* I can contribute on this, just confirm to me

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Hijleh 👋
Thanks for requesting this feature. Your willingness to contribute matters a lot.

The feature is now available in version `1.2.24`🎉

Now we can use the `renderTooltip` prop. It is a function that returns the custom tooltip component. It takes item and index as parameters. With the help of item parameter, we can get values from each section of the stack (using item.stacks).

Here is an example-

https://user-images.githubusercontent.com/20596944/169871047-d1fe2aa4-de1a-486a-b189-d9fc63bdcd9c.mov

The code for the above chart is-

```js
const stackData = [
  {
    stacks: [
      {
        value: 10,
        color: 'orange',
        innerBarComponent: () => (
          <Text style={{transform: [{rotate: '-90deg'}, {translateX: 10}]}}>
            10
          </Text>
        ),
      },
      {
        value: 20,
        color: '#4ABFF4',
        marginBottom: 2,
        innerBarComponent: () => <Text>20</Text>,
      },
    ],
    spacing: 15,
    label: 'Jan',
  },
  {
    stacks: [
      {value: 10, color: '#4ABFF4', innerBarComponent: () => <Text>10</Text>},
      {
        value: 11,
        color: 'orange',
        marginBottom: 2,
        innerBarComponent: () => <Text>11</Text>,
      },
      {
        value: 15,
        color: '#28B2B3',
        marginBottom: 2,
        innerBarComponent: () => <Text>15</Text>,
      },
    ],
    label: 'Mar',
  },
  {
    stacks: [
      {value: 14, color: 'orange'},
      {value: 18, color: '#4ABFF4', marginBottom: 2},
    ],
    spacing: 15,
    label: 'Feb',
  },
  {
    stacks: [
      {value: 7, color: '#4ABFF4'},
      {value: 11, color: 'orange', marginBottom: 2},
      // {value: 10, color: '#28B2B3', marginBottom: 2},
    ],
    label: 'Mar',
  },
];

return(
  <BarChart
    width={340}
    rotateLabel
    noOfSections={4}
    stackData={stackData}
    renderTooltip={(item, index) => {
      return (
        <View
          style={{
            paddingHorizontal: 10,
            borderRadius: 10,
            backgroundColor: 'pink',
          }}>
          {item.stacks.map(stackItem => {
            return <Text>{stackItem.value}</Text>;
          })}
        </View>
      );
    }}
  />
);
```

**Comment by babarbahadur** [comment]
Hi @Abhinandan-Kushwaha
Thanks for introducing this feature but I have some more data to display and in that case the tooltip goes behind the other bars, can you please look into this issue?
I used the same code except that I added paddingHorizontal: 50 to tooltip <View />

![screenshot](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/48913440/97795d13-4365-47d1-ac72-56e999cdc336)

**Comment by babarbahadur** [comment]
I fixed this issue by adding zIndex on line#29 in this file: node_modules/react-native-gifted-charts/src/BarChart/RenderStackBars.tsx

`style={[
          {
            // overflow: 'visible',
            marginBottom: 60,
            width: item.stacks[0].barWidth || props.barWidth || 30,
            height: totalHeight,
            marginRight: spacing,
            zIndex: renderTooltip && selectedIndex === index ? 3 : 0
          },
`

**Comment by aik117** [comment]
@Abhinandan-Kushwaha is it possible to make the stacked bar chart into 3d chart?

**Comment by NikulVnnovate57** [comment]
@Abhinandan-Kushwaha  I have used your code but still tooltip is not visible in stack bar graph.

**Comment by savtym** [comment]
these fix helped me

```js
--- a/node_modules/react-native-gifted-charts/dist/BarChart/index.js
+++ b/node_modules/react-native-gifted-charts/dist/BarChart/index.js
@@ -231,7 +231,7 @@ export var BarChart = function (props) {
                 var _a = getPropsCommonForBarAndStack(item, index), selectedIndex = _a.selectedIndex, stackRestProps = __rest(_a, ["selectedIndex"]);
                 return (_jsx(RenderStackBars, __assign({ stackData: props.stackData || [], isAnimated: isAnimated, animationDuration: animationDuration, stackBorderRadius: props.stackBorderRadius, stackBorderTopLeftRadius: props.stackBorderTopLeftRadius, stackBorderTopRightRadius: props.stackBorderTopRightRadius, stackBorderBottomLeftRadius: props.stackBorderBottomLeftRadius, stackBorderBottomRightRadius: props.stackBorderBottomRightRadius, autoShiftLabelsForNegativeStacks: autoShiftLabelsForNegativeStacks, selectedStackIndex: selectedStackIndex, setSelectedStackIndex: setSelectedStackIndex, 
                     // highlightedStackIndex={props.highlightedStackIndex??-1}
-                    selectedIndex: selectedIndex[0] }, stackRestProps), index));
+                    selectedIndex: Array.isArray(selectedIndex) ? selectedIndex[0] : selectedIndex }, stackRestProps), index));
             });
         }
         else {
