### ISSUE TITLE
Vertical line spreading the full width

### ISSUE THREAD

**Issue by filippobarcellos** [Abhinandan-Kushwaha/react-native-gifted-charts#205]
**Describe the bug**
Hello. Is possible to have the vertical line spreading the full chart event I don't have enough data do populate?

**Screenshots**
What I have:
![Screenshot 2022-05-25 at 18 17 46](https://user-images.githubusercontent.com/56128203/170323783-5ea19915-4f5b-4074-b2b3-41078d8d3942.png)

**Expected behavior**
![Screenshot 2022-05-25 at 18 20 04](https://user-images.githubusercontent.com/56128203/170324478-c261c114-3982-424a-ab31-a5622a226e73.png)

**Comment by filippobarcellos** [comment]
Hi @Abhinandan-Kushwaha!
Appreciate the effort!
I might doing something wrong. When I pass verticalLinesSpacing={20} it works but when I try to add a little more space the lines kind of disappear.

Here's my code right now

`<LineChart
      width={screen_width - 84}
      noOfSections={5}
      dashGap={0}
      data={data}
      color={color}
      thickness={3}
      dataPointsColor={color}
      noOfVerticalLines={7}
      verticalLinesSpacing={20}
      backgroundColor='white'
      initialSpacing={30}
      yAxisColor='#FFFFFF'
      xAxisColor='#FFFFFF'
      xAxisIndicesWidth={100}
      dataPointsRadius={9}
/>
`

![Screenshot 2022-05-26 at 18 29 21](https://user-images.githubusercontent.com/56128203/170542801-5c460e31-c1a1-
415e-bfc5-1aa5bda85571.png)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @filippobarcellos 
In your code, you are missing the prop `showVerticalLines`.
