### ISSUE TITLE
Scrollbar color and xAxisLine style

### ISSUE THREAD

**Issue by Hijleh** [Abhinandan-Kushwaha/react-native-gifted-charts#213]
I am looking to change the scrollbar color, 

also to change the **xAxisLine style to dashed** like this: 
<img width="286" alt="image" src="https://user-images.githubusercontent.com/48893105/170873070-7bcb0f7b-33db-4b8f-9174-724ee705acad.png">

are these not supported?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Hijleh 👋
Thanks for requesting the feature. It is now available in version `1.2.30`🎉

The X axis can be made dashed by setting the prop `xAxisType` to `dashed`.
the scrollbar color can be changed using the `indicatorColor` prop. It accepts 3 values- `default`, `black` and `white`. It is applicable only to iOS. See [React Native doc](https://reactnative.dev/docs/scrollview#indicatorstyle-ios) to understand this.
