### ISSUE TITLE
Set minimum AxisLabelTexts different of zero. 

### ISSUE THREAD

**Issue by jarrillaga** [Abhinandan-Kushwaha/react-native-gifted-charts#218]
@Abhinandan-Kushwaha I'm trying to set a minimum in the Y axis different than 0, in other words I want that the first value of the Y axis is 30, for example. 

I'm not sure if the library supports it. 

Can you help me on this?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @jarrillaga 
For Line chart you can use the prop `yAxisOffset` https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/92#issuecomment-1110279382

**Comment by Abhinandan-Kushwaha** [comment]
Hi @jarrillaga 👋
Version `1.2.32` onwards `yAxisOffset` is available for Bar, Stack, Line and Area charts🎉

**Comment by AshotN** [comment]
@Abhinandan-Kushwaha yAxisOffset seems to effect the value of the data point. Is this intentional behavior?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @AshotN 👋
For me the value of data points doesn't change due to yAxisOffset.
Can you please share screenshots of before and after using `yAxisOffset`? Also, please highlight the part that is getting changed due to `yAxisOffset`.
Thanks.
