### ISSUE TITLE
Horizontal lines width

### ISSUE THREAD

**Issue by filippobarcellos** [Abhinandan-Kushwaha/react-native-gifted-charts#219]
**Describe the bug**
Is there a way to limit the width of the horizontal line? I would like to the chart go full screen but limit the lines. Thanks

**Expected behavior**
![Screenshot 2022-06-04 at 13 21 59](https://user-images.githubusercontent.com/56128203/171998816-b41353ad-4987-4e71-8020-ab0789eaa4b6.png)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @filippobarcellos 👋
Thanks for requesting the feature. It is now available in version `1.2.32`🎉

The width of the horizontal line can be set using the `rulesLength` prop.
The width of the X axis can be set separately using the `xAxisLength` prop.
These are applicable to Bar, Stack, Line and Area charts.
