### ISSUE TITLE
startFillColor and endFillColor based on values

### ISSUE THREAD

**Issue by joomsch** [Abhinandan-Kushwaha/react-native-gifted-charts#221]
Hey,

is it possible to add a different startFillColor / endFillColor based on a given value? I'd like to have an AreaChart where everything below 0 is styled in a red area and everything above in green.

<img width="278" alt="Bildschirmfoto 2022-06-06 um 18 21 35" src="https://user-images.githubusercontent.com/13629606/172202911-920aefa7-1a78-4e5e-91d5-d3670e00fe45.png">

Thanks for this great library!

**Comment by Abhinandan-Kushwaha** [comment]
Hi @joomsch 👋
Thanks for requesting this feature. It is now available in version `1.2.34`🎉

To render such charts, we can use the `<LineChartBicolor>` component.

For example-
```js
<LineChartBicolor
  data={data}
  areaChart
  color="green"
  colorNegative="red"
  startFillColor="green"
  startFillColorNegative="red"
/>
```
For more details see [LineChartBicolor props](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/LineChart/LineChartBicolorProps.md).
