### ISSUE TITLE
Stripe Horizontal line

### ISSUE THREAD

**Issue by Ritesh175862** [Abhinandan-Kushwaha/react-native-gifted-charts#225]
**Describe the bug**
Not able to draw strip line
**To Reproduce**

**Expected behavior**
The target line should increase or decrease according to entered data
**Screenshots**
<img width="281" alt="Screenshot 2022-06-09 at 2 16 18 PM" src="https://user-images.githubusercontent.com/51701629/172806518-3f7704fe-9acf-471b-829e-9b675ab3289e.png">

 - Version of the library being used [e.g. 1.2.32]

**Comment by Ritesh175862** [comment]
Hi @Abhinandan-Kushwaha 
Yes i am talking about the horizontal dotted line of green color at the value 54
can we do that in this library

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Ritesh175862 
Please describe this a bit more-
> The target line should increase or decrease according to entered data
