### ISSUE TITLE
Android area chart data is being overflown outside the container but the data pointer actions are being handled

### ISSUE THREAD

**Issue by srinivas-dev-reddy** [Abhinandan-Kushwaha/react-native-gifted-charts#230]
In android area chart the data points is being overflown outside the container. In IOS it doesn't have this issue.

**Screenshots**
In Android
![WhatsApp Image 2022-06-18 at 2 10 54 PM](https://user-images.githubusercontent.com/100875822/174430019-19dc689b-50fc-4abb-aa98-1763830e1cd8.jpeg)

In IOS
<img width="320" alt="Screenshot 2022-06-18 at 2 10 04 PM" src="https://user-images.githubusercontent.com/100875822/174429990-80e8847f-06ce-48cd-92fb-ea3c9667d810.png">

 - Device: Asus Rog phone 5
 - OS: Android 12
 - Version of the library being used : 1.2.34

**Comment by lukasmalik17** [comment]
Hi, any fix on this issue?

**Comment by T-Lukashevich** [comment]
any solution for this issue? i am also getting same error

**Comment by AntonZelk** [comment]
also this problem

**Comment by Abhinandan-Kushwaha** [comment]
Hi @srinivas-dev-reddy @lukasmalik17 @T-Lukashevich @AntonZelk 👋

If the chart overflows, you can pass the `width` prop to give it a fixed width.

Also, there have been some updates in version `1.3.1` regarding the width of charts. You might want to upgrade to `1.3.0`
