### ISSUE TITLE
App crashed  in pixel 5

### ISSUE THREAD

**Issue by Rajkamal-agicent** [Abhinandan-Kushwaha/react-native-gifted-charts#234]
App is crashed whenever the screen where i integrated the gifted-chart library is navigated..

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Rajkamal-agicent 
I tested on Android Emulator - Pixel 5 API 32. Works fine, no crashes.
Can you please share your code here. Maybe the code is responsible for the crash.

**Comment by Rajkamal-agicent** [comment]
@Abhinandan-Kushwaha App is working fine in other systems only crashed in pixel 5.
