### ISSUE TITLE
topLabelComponent is not working in stacked bar chart

### ISSUE THREAD

**Issue by akshPairroxz** [Abhinandan-Kushwaha/react-native-gifted-charts#235]
when i try to add top label component in stacked bar chart it does'n work .

**Comment by Abhinandan-Kushwaha** [comment]
Hi @akshPairroxz 👋
The top label component is working fine. 
Here's an example-

<img width="228" alt="Screenshot 2022-06-24 at 15 13 17" src="https://user-images.githubusercontent.com/20596944/175509542-4c4adcd1-eba9-493b-8170-405ded1e66ad.png">

The code for the above chart is-

```js
const stackData = [
  {
    stacks: [
      {
        value: 10,
      },
      {
        value: 20,
        marginBottom: 2,
      },
    ],
    spacing: 15,
    label: 'Jan',
    topLabelComponent: ()=> <Text>1st</Text>
  },
  {
    gradientColor: 'blue',
    stacks: [
      {value: 10},
      {
        value: 11,
        marginBottom: 2,
      },
      {
        value: 15,
        marginBottom: 2,
      },
    ],
    label: 'Mar',
    topLabelComponent: ()=> <Text>2nd</Text>
  },
  {
    stacks: [{value: 14}, {value: 18, marginBottom: 2}],
    spacing: 15,
    label: 'Feb',
    topLabelComponent: ()=> <Text>3rd</Text>
  },
  {
    stacks: [{value: 7}, {value: 11, marginBottom: 2}],
    label: 'Mar',
    topLabelComponent: ()=> <Text>4th</Text>
  },
];

return <BarChart
  stackData={stackData}/>
  ```

**Comment by akshPairroxz** [comment]
okay ,turn out i was providing this key inside the object of stackdata , now it is working .thanks for responding.

**Comment by AlekPacul** [comment]
Hello @Abhinandan-Kushwaha, i got problem turn out if I actived isAnimated the topLabelComponent won't show, I try with your example above. Thank you
<img width="155" alt="image" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/43445919/c7166701-128f-4fa5-b7ba-a09bb15be563">
