### ISSUE TITLE
Can we show y axis number into shorthand abbreviation?

### ISSUE THREAD

**Issue by swati-ag** [Abhinandan-Kushwaha/react-native-gifted-charts#238]
Hi @Abhinandan-Kushwaha 
can we show y axis number into shorthand abbreviation by using any default props ? 
if my max value is 20000, then y axis should be
as [5K,10K,15K,20K]
if my max value is 2000000, then y axis should be
as [5L,10L,15L,20L]

thanks

**Comment by Abhinandan-Kushwaha** [comment]
Hi @swati-ag 👋
You can use the prop `yAxisLabelTexts` to provide custom y axis labels.
Here's an example-

```js
const bigData = [
  {value: 5000},
  {value: 6000},
  {value: 8000},
  {value: 3000},
  {value: 2000},
];
return <BarChart
        noOfSections={5}
        maxValue={10000}
        yAxisLabelTexts={['0','2k','4k','6k','8k','10k']}
        data={bigData} />
```
It produces the below output-

<img width="268" alt="Screenshot 2022-06-27 at 18 33 44" src="https://user-images.githubusercontent.com/20596944/175948205-a054467f-91f6-4635-8e52-abbdba710e5c.png">

A better approach would be to dynamically generate the `yAxisLabelTexts` like this-

```js
const getYaxisLabels = (maxValue, noOfSteps) => {
    const stepValue = maxValue/noOfSteps;
    const labelsArray=[];
    for(let i=0; i<=noOfSteps; i++){
      let value = stepValue*i;
      labelsArray.push(value === 0 ? '0' : value/1000 + 'k');
    }
    return labelsArray;
  }
```

And now, the new code would be-

```js
const bigData = [
  {value: 5000},
  {value: 6000},
  {value: 8000},
  {value: 3000},
  {value: 2000},
];

return <BarChart
        noOfSections={5}
        maxValue={10000}
        yAxisLabelTexts={getYaxisLabels(10000,5)}
        data={bigData} />
```
I hope it helps.🤗
