### ISSUE TITLE
Tooltip off Screen

### ISSUE THREAD

**Issue by mmatahen** [Abhinandan-Kushwaha/react-native-gifted-charts#240]
hello team,
at first i would like to thank you for this great package.
Tooltip component is viewed off screen when multiple columns for bar charts.
and how can i change the scrollbar color with custom color not only balck,white and default
thank you in advance

**Comment by Abhinandan-Kushwaha** [comment]
Hi @mmatahen 👋
Glad to know that you loved the package.
Can you please share a screenshot for the `Tooltip` issue? This will help me fix it faster.

**Comment by mmatahen** [comment]
> Hi @mmatahen 👋 Glad to know that you loved the package. Can you please share a screenshot for the `Tooltip` issue? This will help me fix it faster.

![image](https://user-images.githubusercontent.com/24762905/175959878-6882195e-e2ac-4e8d-a5f1-994ab0c677fd.png)

**Comment by mmatahen** [comment]
hi again,
as you can see the tooltip is hidden when it reaches the end, is there away to flip to the opposite direction when it reaches the end. and is there a way to change horizontalScrollBar color?
thank you in advance

**Comment by Abhinandan-Kushwaha** [comment]
Hi @mmatahen 👋
Thanks for requesting this useful update. It is now available in version `1.2.37`🎉

Now you can use the prop `leftShiftForLastIndexTooltip`. It accepts a number and shifts the tooltip of last bar by the given number.

I hope it helps.🤗

**Comment by Abhinandan-Kushwaha** [comment]
And unfortunately the scrollbar color cannot be changed to other colors except black/white/default. This would require a huge effort and is not in my priority list currently. WIll work on it once I get some time.

**Comment by mmatahen** [comment]
it didn't work for me as im using stackData not Data
i suggest to make it this way so i can decide when to flip 
style={{
            position: 'absolute',
            bottom: totalHeight + 60,
            left: leftSpacing - (leftShiftForLastIndexTooltip || 0 ),
              // index === data.length - 1
              //   ? leftSpacing - leftShiftForLastIndexTooltip
              //   : leftSpacing,
            zIndex: 1000,

**Comment by Abhinandan-Kushwaha** [comment]
Hi @mmatahen 👋

Thanks for requesting the feature. It is now available in version `1.2.38`🎉

Apart from the `leftShiftForLastIndexTooltip`, we now have the `leftShiftForTooltip` prop which we can add to selected Bars. So, suppose you have 12 bars and the 6th bar reaches to the end of screen, you can add `leftShiftForTooltip` to 6th, 7th, 8th, 9th, 10th, 11th and 12th bars.

Here's an example-

```js
const stackData = [
  {
    stacks: [
      {
        value: 10,
      },
      {
        value: 20,
        marginBottom: 2,
      },
    ],
    label: 'Jan',
  },
  {
    stacks: [
      {value: 10},
      {
        value: 11,
        marginBottom: 2,
      },
      {
        value: 15,
        marginBottom: 2,
      },
    ],
    label: 'Feb',
  },
  {
    stacks: [{value: 14}, {value: 18, marginBottom: 2}],
    label: 'Mar',
  },
  {
    stacks: [{value: 7}, {value: 11, marginBottom: 2}],
    label: 'Apr',
  },
  {
    stacks: [
      {
        value: 10,
      },
      {
        value: 20,
        marginBottom: 2,
      },
    ],
    label: 'May',
  },
  {
    stacks: [
      {value: 10},
      {
        value: 11,
        marginBottom: 2,
      },
      {
        value: 15,
        marginBottom: 2,
      },
    ],
    label: 'Jun',
    leftShiftForTooltip: 20,
  },
  {
    stacks: [{value: 14}, {value: 18, marginBottom: 2}],
    label: 'Jul',
    leftShiftForTooltip: 60,
  },
  {
    stacks: [{value: 7}, {value: 11, marginBottom: 2}],
    label: 'Aug',
  },
];

return <BarChart
      minHeight = {6}
      renderTooltip = {()=> {
        return(
          <Text style={{backgroundColor: 'white'}}>
            Hello World!!
          </Text>
        )
      }}
      leftShiftForLastIndexTooltip = {55}
      stackData = {stackData} />
```
Here you can see we have provided `leftShiftForTooltip: 20` to the 6th bar and `leftShiftForTooltip: 60` to the 7th bar. Also we have passed the prop `leftShiftForLastIndexTooltip = {55}`. So we are able to shift the 6th, 7th and the last bar separately.

Note that, if we pass `leftShiftForTooltip` prop directly to the `<BarChart>` component, it shifts all the bars by the given value.

I hope it helps.🤗

**Comment by mmatahen** [comment]
Thank you my friend
But I can't install version 1.2.38 or 1.2.39 as I got an error

"No matching version found for react-native-gifted-charts@^1.2.39"

**Comment by L2Develop96** [comment]
@Abhinandan-Kushwaha 
What about top shift? What if the tooltip gets overflown from the top ? When I click on the highest value the tooltip is truncated

**Comment by ritaVaja** [comment]
import {StyleSheet, Text, View, useWindowDimensions} from 'react-native';
import React from 'react';
import {Color} from '../../../utils';
import {BarChart} from 'react-native-gifted-charts';
import {Fonts} from '../../../assets/fonts';
import {Loader} from '../../../components';

export function Barchart({weeklyExpense}) {
  const windowWidth = useWindowDimensions().width;
  const barChartWidth = windowWidth * 0.8;
  const numDataPoints = weeklyExpense.length;
  const barWidth = barChartWidth / numDataPoints;
  const maxExpenseValue = Math.max(...weeklyExpense.map(item => item.value));
  return (
    <>
      {weeklyExpense?.length === 0 ? (
        <Loader />
      ) : (
        <View style={[styles.graphWrapper, {width: barWidth}]}>
          <BarChart
            data={weeklyExpense}
            barWidth={10}
            spacing={barWidth - 2}
            width={barChartWidth}
            height={140}
            roundedTop
            roundedBottom
            yAxisLabelWidth={50}
            xAxisColor={Color.semiLightGray}
            xAxisTextNumberOfLines={2}
            renderTooltip={(item, index) => {
              return (
                <View style={[styles.tooltipWrapper(index)]}>
                  <Text>₹ {item.value}</Text>
                </View>
              );
            }}
            rulesType="solid"
            showFractionalValue
            yAxisThickness={1}
            noOfSections={4}
            hideRules={false}
            dashWidth={380}
            rulesColor={Color.semiLightGray}
            leftShiftForTooltip={30}
            leftShiftForLastIndexTooltip={55}
            maxValue={maxExpenseValue | 10}
            yAxisTextStyle={styles.yAxisTextStyle}
          />
        </View>
      )}
    </>
  );
}

const styles = StyleSheet.create({
  graphWrapper: {
    backgroundColor: Color.darkBlack,
    borderRadius: 10,
    height: 180,
    flex: 1,
    marginBottom: 12,
  },

  tooltipWrapper: item => ({
    bottom: 6,
    backgroundColor: Color.white,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    zIndex: 1,
    marginLeft: item === 0 || item === 1 ? 10 : item === 10 ? 0 : 0,
    position: 'absolute',
  }),
  yAxisTextStyle: {
    fontFamily: Fonts.avenir,
    fontSize: 10,
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: 36.7,
    letterSpacing: 0.1,
    textAlign: 'left',
    color: Color.white,
  },
});
here issue is top height tooltip cut i am giving responsive style but tooltip cut also i am data chnage in brachart when user select filter like(weekly/monthly/yearly) so first time show barchart perfectly but i am chnage filter monthly so my tooltip & label and value show perfectly but my barchrat display height & width last filter then i am check and click tooltip show data 0 so here not barchart display perfectly but barchart label,tooltip& value so perfectly

**Comment by Harish2412k** [comment]
Hi, 
I have an issue, I can able to show the tooltip in the barChart by clicking on the bar but, how can I show the tooltip by default when the data appears in the barChart.

**Comment by Abhinandan-Kushwaha** [comment]
@Harish2412k you can use the `topLabelComponent` property inside the data array.

**Comment by Harish2412k** [comment]
@Abhinandan-Kushwaha can you give me some example that may help a lot.

**Comment by Abhinandan-Kushwaha** [comment]
Were you able to do it @Harish2412k ?

**Comment by ArnabXD** [comment]
> import {StyleSheet, Text, View, useWindowDimensions} from 'react-native'; import React from 'react'; import {Color} from '../../../utils'; import {BarChart} from 'react-native-gifted-charts'; import {Fonts} from '../../../assets/fonts'; import {Loader} from '../../../components';
> 
> export function Barchart({weeklyExpense}) { const windowWidth = useWindowDimensions().width; const barChartWidth = windowWidth * 0.8; const numDataPoints = weeklyExpense.length; const barWidth = barChartWidth / numDataPoints; const maxExpenseValue = Math.max(...weeklyExpense.map(item => item.value)); return ( <> {weeklyExpense?.length === 0 ? ( ) : ( <View style={[styles.graphWrapper, {width: barWidth}]}> <BarChart data={weeklyExpense} barWidth={10} spacing={barWidth - 2} width={barChartWidth} height={140} roundedTop roundedBottom yAxisLabelWidth={50} xAxisColor={Color.semiLightGray} xAxisTextNumberOfLines={2} renderTooltip={(item, index) => { return ( ₹ {item.value} ); }} rulesType="solid" showFractionalValue yAxisThickness={1} noOfSections={4} hideRules={false} dashWidth={380} rulesColor={Color.semiLightGray} leftShiftForTooltip={30} leftShiftForLastIndexTooltip={55} maxValue={maxExpenseValue | 10} yAxisTextStyle={styles.yAxisTextStyle} /> )} </> ); }
> 
> const styles = StyleSheet.create({ graphWrapper: { backgroundColor: Color.darkBlack, borderRadius: 10, height: 180, flex: 1, marginBottom: 12, },
> 
> tooltipWrapper: item => ({ bottom: 6, backgroundColor: Color.white, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 12, zIndex: 1, marginLeft: item === 0 || item === 1 ? 10 : item === 10 ? 0 : 0, position: 'absolute', }), yAxisTextStyle: { fontFamily: Fonts.avenir, fontSize: 10, fontWeight: '500', fontStyle: 'normal', lineHeight: 36.7, letterSpacing: 0.1, textAlign: 'left', color: Color.white, }, }); [@Abhinandan-Kushwaha](https://github.com/Abhinandan-Kushwaha) here issue is top height tooltip cut i am giving responsive style but tooltip cut also i am data chnage in brachart when user select filter like(weekly/monthly/yearly) so first time show barchart perfectly but i am chnage filter monthly so my tooltip & label and value show perfectly but my barchrat display height & width last filter then i am check and click tooltip show data 0 so here not barchart display perfectly but barchart label,tooltip& value so perfectly
> 
> ![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/149557820/dee219a3-707b-41b1-b016-b3d01ca7b79a) ![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/149557820/2b9a3f99-84c4-4062-b657-f47d938668f0)


@ritaVaja  you can use `yAxisExtraHeight` property to add some extra height for the chart and it would display the tooltip properly
