### ISSUE TITLE
Issue in double bar graph 

### ISSUE THREAD

**Issue by VijinR** [Abhinandan-Kushwaha/react-native-gifted-charts#249]
given data set:
[
{"frontColor": "#FFB1C2", "label": "01 Jul", "labelTextStyle": {"color": "#5F5F5F", "fontSize": 10, "textAlign": "center"}, "labelWidth": 70, "spacing": 2, "value": 5}, {"frontColor": "#9CD0F6", "value": 1},
 {"frontColor": "#FFB1C2", "label": "02 Jul", "labelTextStyle": {"color": "#5F5F5F", "fontSize": 10, "textAlign": "center"}, "labelWidth": 70, "spacing": 2, "value": 3}, {"frontColor": "#9CD0F6", "value": 0},
{"frontColor": "#FFB1C2", "label": "03 Jul", "labelTextStyle": {"color": "#5F5F5F", "fontSize": 10, "textAlign": "center"}, "labelWidth": 70, "spacing": 2, "value": 0}, {"frontColor": "#9CD0F6", "value": 0}, 
{"frontColor": "#FFB1C2", "label": "04 Jul", "la`belTextStyle": {"color": "#5F5F5F", "fontSize": 10, "textAlign": "center"}, "labelWidth": 70, "spacing": 2, "value": 0}, {"frontColor": "#9CD0F6", "value": 0},
 {"frontColor": "#FFB1C2", "label": "05 Jul", "labelTextStyle": {"color": "#5F5F5F", "fontSize": 10, "textAlign": "center"}, "labelWidth": 70, "spacing": 2, "value": 0}, {"frontColor": "#9CD0F6", "value": 0}, 
{"frontColor": "#FFB1C2", "label": "06 Jul", "labelTextStyle": {"color": "#5F5F5F", "fontSize": 10, "textAlign": "center"}, "labelWidth": 70, "spacing": 2, "value": 0}, {"frontColor": "#9CD0F6", "value": 1},
 {"frontColor": "#FFB1C2", "label": "07 Jul", "labelTextStyle": {"color": "#5F5F5F", "fontSize": 10, "textAlign": "center"}, "labelWidth": 70, "spacing": 2, "value": 1}, {"frontColor": "#9CD0F6", "value": 1}
]

<BarChart
                  data={barChartData}
                  width={DisplayUtils.setWidth(72)}
                  height={120}
                  barWidth={30}
                  spacing={10}
                  rulesType={''}
                  isAnimated={true}
                  initialSpacing={8}
                  xAxisThickness={1}
                  yAxisThickness={1}
                  yAxisTextStyle={{
                    fontSize: 10,
                    color: Colors.PRIMARY_TEXT_COLOR,
                  }}
                  noOfSections={3}
                  maxValue={barChartMaxValue}
                  scrollToEnd
 />

output:-

![Screenshot 2022-07-07 at 7 46 05 PM](https://user-images.githubusercontent.com/97605704/177795624-8d18eafd-b9f3-4abd-ad47-286e393fd0ca.png)
![Screenshot 2022-07-07 at 7 46 25 PM](https://user-images.githubusercontent.com/97605704/177795698-9a194995-9bd5-42a1-a005-a3c82cc8c030.png)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @VijinR 👋
If you set `maxValue` to `5` and `noOfSections` to `3`, it becomes impossible to divide 5 into 3 sections of whole numbers.
By default, the charts don't show fractional labels on Y axis. Hence, the `1` that we see on Y axis is actually the rounded value of `1.7` and the `3` that we see is the rounded value of `3.3`.

To avoid this problem, either set the prop `showFractionalValues` to `true` or set the `maxValue` to `6`.
