### ISSUE TITLE
How to increase label width for vertical axis

### ISSUE THREAD

**Issue by kenngo81** [Abhinandan-Kushwaha/react-native-gifted-charts#253]
Hello everyone,
Currently I'm having a problem with the width of the labels on the vertical axis. It's obscuring my data. So I want to increase its width, how do I do it?
Thanks very much,
Have a nice working week

![image](https://user-images.githubusercontent.com/46308678/179931778-22eac780-a28f-463b-b3bb-c558c5dc41c0.png)

**Comment by pmayur392** [comment]
Set yAxisLabelWidth according to your need. thank you.
