### ISSUE TITLE
Overview for chart

### ISSUE THREAD

**Issue by htduongdl96** [Abhinandan-Kushwaha/react-native-gifted-charts#255]
I want to have an overview of the line and bar chart (view full chart without scroll). It doesn't need to have any zoom for now.
Is there any function to do that?

**Comment by Abhinandan-Kushwaha** [comment]
You can use the `width` and `spacing` props.
Set `spacing` value very less so that the entire chart can be adjusted on screen.
Also set `disableScroll` to true.
