### ISSUE TITLE
BarChart Props types with this Features

### ISSUE THREAD

**Issue by abisalde** [Abhinandan-Kushwaha/react-native-gifted-charts#256]
Please how can this be achieved with the props types, you do have a similar picture on the *README.md*
![Screenshot from 2022-07-27 05-46-44](https://user-images.githubusercontent.com/38655623/181217926-6d4f688f-cfa5-447f-9cd2-6b5066d02821.png)

![Screenshot from 2022-07-27 05-49-55](https://user-images.githubusercontent.com/38655623/181218031-c676452d-fdc9-45db-8eb9-9faffab274d8.png)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @abisalde 👋
Were you able to find the solution? If you are still stuck, let me know.

**Comment by abisalde** [comment]
> Hi @abisalde 👋
> Were you able to find the solution? If you are still stuck, let me know.

No, I couldn't find any solution so I had to display it without the number. Thanks

**Comment by Abhinandan-Kushwaha** [comment]
Do you need the number to be displayed on pressing the bar, or you just need to display the number for some specific bar without pressing on it?

**Comment by Abhinandan-Kushwaha** [comment]
If you want the number to be displayed on pressing the bar, you can use the `renderTooltip` prop.
Example-
```js
const topLabelComponent = (item) => (
    <View
      style={{
        width: 60,
        height: 28,
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 10,
        backgroundColor: 'green',
        marginBottom: 4,
        marginLeft: -12
      }}>
      <Text style={{fontWeight: 'bold', color: 'white', textAlign:'center'}}>{item.value}</Text>
    </View>
  );
 
 const data = [
    {value: 2000},
    {value: 1800},
    {value: 1000},
    {value: 3600},
 ];
 
 return <BarChart data={data} renderTooltip={topLabelComponent}/>
 ```

---

If you want to display the number for some specific bar without pressing on it, you can add the `topLabelComponent` property to the object in the data array.
Here's an example-
```js
const topLabelComponent = (label) => (
    <View
      style={{
        width: 60,
        height: 28,
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 10,
        backgroundColor: 'green',
        marginBottom: 4,
      }}>
      <Text style={{fontWeight: 'bold', color: 'white'}}>{label}</Text>
    </View>
  );
 
 const data = [
    {value: 2000},
    {value: 1800},
    {value: 1000, topLabelComponent: ()=>topLabelComponent('$1000')},
    {value: 3600},
 ];
 
 return <BarChart data={data} />
 ```
Output-

<img width="220" alt="Screenshot 2023-07-31 at 5 06 17 AM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/503ee68c-6d8a-485e-9053-36a2a577e789">
