### ISSUE TITLE
yAxisLabelTexts cannot be strings along with yAxisOffset in an area/line chart

### ISSUE THREAD

**Issue by virgilcui** [Abhinandan-Kushwaha/react-native-gifted-charts#260]
Thanks for the amazing lib! It has a lot of options to customize.

I have a LineChart with both yAxisOffset and yAxisLabelTexts. However, when yAxisLabelTexts is an array of strings, then the yaxis labels will be displayed as NaN.

In lines of 2233, 2242 in the src/LineChart/index.tsx, it expects the elements in yAxisLabelTexts array are number.
label = props.yAxisOffset
          ? (Number(val) + props.yAxisOffset).toString()
          : val;

**To Reproduce**
<LineChart 
     areaChart 
     data={chartData}
     noOfSections={2}
     yAxisOffset={20000}
     yAxisLabelTexts={['20k', '50k', '75k']}
/>

**Expected behavior**
The y axis labels should be shown as '20k', '50k', '75k'. 

**Screenshots**
![Screen Shot 2022-08-11 at 11 57 31 PM](https://user-images.githubusercontent.com/27963830/184282671-23723073-c9c1-400a-b83a-6a5f31c7c530.png)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @virgilcui 👋
I can see that using both `yAxisLabelTexts` and `yAxisOffset`  together breaks. Sadly, I don't have time to fix it now.

I suggest using `yAxisSuffix='k'` instead of `yAxisLabelTexts`. 

The labels on y Axis can be controlled using maxValue, noOfSections, and stepValue props.

**Comment by robertoperez18** [comment]
Is there anything that can be done here to fix it? In my case, I need to only add the suffix 'k' when the value of the label is above 1000. For example, if the value is 1500 I have to display '1.5k' and if the value is 900 I have to display '900'. The only way I found is using together yAxisLabelTexts and yAxisOffset...

Thank you!
