### ISSUE TITLE
java.lang.Double cannot be cast to com.facebook.react.bridge.ReadableMap

### ISSUE THREAD

**Issue by Vynex** [Abhinandan-Kushwaha/react-native-gifted-charts#263]
**Describe the bug**
When I try to use any of the Charts available in the package I get the following issue. Tested on multiple devices, also with a newly init App. However, weirdly when I copied the code for the charts from source it works without any errors.

**To Reproduce**
1. Copy Example App
2. See error

**Screenshots**
![69bb3f27-a1b3-447f-8a9f-4c0a21be7d6c](https://user-images.githubusercontent.com/14802053/186639745-7a52ada5-eb3a-4e1f-bb01-2d4519a2690c.png)

 - Device tested on: [OnePlus Nord 2, ROG Phone 5, Samsung Galaxy M52]
 - OS: [Android 12]
 - Version of the library being used [1.2.41]

**Comment by zameerm99x** [comment]
@Vynex I got this issue. After fixing the following packages with the specific versions and reinstalling all the packages worked for me.
 "react-native-linear-gradient": "2.5.6",
 "react-native-svg": "12.1.0",

**Comment by FranDepascuali** [comment]
I can confirm that @zameerm99x fix works with `2.6.2`:
```json
"react-native-linear-gradient": "2.6.2",
"react-native-svg": "12.1.0",
```

**Comment by lheshiki** [comment]
@FranDepascuali 
@zameerm99x 
I had the same error and changed the versions as you guys said but it doesnt work...
In my case I tried in ios and android expo go application. In ios works perfectly but in android I still have the error "
java.lang.Double cannot be cast to com.facebook.react.bridge.ReadableMap".
also tried to change it to the newest version which is "react-native-svg": "^13.6.0" but did not work either...
Anybody with other solutions?

**Comment by lheshiki** [comment]
just to mentioned that the error content changed to "Invariant Violation: requireNativeComponent: "RNSVGSvgViewAndroid" was not found in the UIManager.". I can tell it is still related with the svg version of react-native-svg I guess... Hoping somebody run into the same error in the past...
below the versions of my files
-------------------------------------------------------------------------------------------------------------------------------------------
"react-native-linear-gradient": "2.6.2",
"react-native-svg": "^12.1.0",

**Comment by Leonit654** [comment]
> @FranDepascuali @zameerm99x I had the same error and changed the versions as you guys said but it doesnt work... In my case I tried in ios and android expo go application. In ios works perfectly but in android I still have the error " java.lang.Double cannot be cast to com.facebook.react.bridge.ReadableMap". also tried to change it to the newest version which is "react-native-svg": "^13.6.0" but did not work either... Anybody with other solutions?

Same for me

**Comment by Lieutenant-Vernyc** [comment]
I had the same issue due to an empty quote "" on the fill attribute like this:
 <RamadanDua width={70} height={40} fill=" " />. After I had removed it, it worked fine.

**Comment by pahirdinhamut** [comment]
so is this problem solved?

**Comment by MatheusHash** [comment]
I have the same problem

    "react-native-svg": "13.4.0",
    "styled-components": "^5.3.6",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-fontawesome-pro": "^2.1.0",

**Comment by FranDepascuali** [comment]
Update:I can confirm these versions work:

```json
"react-native-linear-gradient": "2.6.2",
"react-native-svg": "12.4.4",
```

**Comment by yewyewXD** [comment]
Downgrading to Expo v45 worked for me.

I used `expo-cli upgrade 45`, it helps u change the Expo version, change dependencies version to a compatible one, remove `package-lock.json` & `node_modules` and install everything back again, works like magic.

**Comment by eatanga-git** [comment]
> I had the exact same err on android. Downgrading to Expo v45 worked for me. I was on Expo v47.
> 
> I used `expo-cli upgrade 45`, it helps u change the Expo version, change dependencies version to a compatible one, remove `package-lock.json` & `node_modules` and install everything back again, works like magic.
> 
> `"react-native-svg": "13.4.0"` was also automatically downgraded to `"react-native-svg": "12.3.0"`

How do you install everything again?

**Comment by AdkoToIdeRozbit** [comment]
> I had the same issue due to an empty quote "" on the fill attribute like this: . After I had removed it, it worked fine.

Same for me, had an svg with the following logic <Pause fill={timerRunning && "#0B6DFF"}/>
Changed it to <Pause fill={timerRunning? "#0B6DFF" : "#000000"}/> and works perfectly

**Comment by eatanga-git** [comment]
> 

Can you go more in depth with this? What file is this?

Is gifted charts working fine for you now? Or anyone else?

I think it would be helpful if someone just posted the whole package json at this point...

**Comment by eatanga-git** [comment]
> > I had the same issue due to an empty quote "" on the fill attribute like this: . After I had removed it, it worked fine.
> 
> Same for me, had an svg with the following logic `<Pause fill={timerRunning && "#0B6DFF"}/>`
> 
> Changed it to `<Pause fill={timerRunning? "#0B6DFF" : "#000000"}/>` and works perfectly

What file? How did you know this was the issue?

**Comment by radiancegeorge** [comment]
in my case i am using react-native-iconly and the same issue occurs, no clue on what to do as i'm only a fresher

**Comment by Abhinandan-Kushwaha** [comment]
Hey guys👋
The dependencies have been upgraded in version `1.3.0`🎉

Please use the latest version and feel free to reopen if the issue still persists.

**Comment by Count-Monte** [comment]
Hi @Abhinandan-Kushwaha 

I have tried with these versions
"react-native-svg": "^13.6.0", (also 13.4.0)
"react-native-linear-gradient": "^2.6.2",
"react-native-gifted-charts": "^1.3.0",

Now fails with (requireNativeComponent: "RNSVGSvgViewAndroid" was not found in the UIManager)

**Comment by eatanga-git** [comment]
> Hi @Abhinandan-Kushwaha
> 
> I have tried with these versions "react-native-svg": "^13.6.0", (also 13.4.0) "react-native-linear-gradient": "^2.6.2", "react-native-gifted-charts": "^1.3.0",
> 
> Now fails with (requireNativeComponent: "RNSVGSvgViewAndroid" was not found in the UIManager)

I have this error too. Expo Dev Client version 47.
What is the correct setup?

Also, which versions of Expo even support svg 13.9?

**Comment by eatanga-git** [comment]
Has anyone found a solution to this with Expo Dev Client?

**Comment by Abhinandan-Kushwaha** [comment]
Are you guys still facing this issue? A new version of react-native-gifted-charts is recently released which has `react-native-svg` listed as a peer dependency instead of a direct dependency. Please try the latest version of the library where this issue is hopefully resolved.
