### ISSUE TITLE
Positive minValue does not work for line Charts

### ISSUE THREAD

**Issue by OnwardGroup-ABB** [Abhinandan-Kushwaha/react-native-gifted-charts#265]
Negative minValue works for line Charts, but positive value greater than 0 does not work. The Y axis starts from 0 only even if min value is given e.g. 30/100.

**Comment by Abhinandan-Kushwaha** [comment]
Use the prop `yAxisOffset`

**Comment by OnwardGroup-ABB** [comment]
Worked.. Thanks very much.

**Comment by ftaibi** [comment]
the yAxisOffset is also offsetting the value, I just want the y axis to a minimum value

**Comment by Abhinandan-Kushwaha** [comment]
@ftaibi Try the`formatYLabel` prop. See https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/22#issuecomment-1801091502

**Comment by Abhinandan-Kushwaha** [comment]
`yAxisLabelTexts` can also be used. See https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/54#issuecomment-1001873640
