### ISSUE TITLE
onPress area for dataPoint not big enough

### ISSUE THREAD

**Issue by aleroca96** [Abhinandan-Kushwaha/react-native-gifted-charts#266]
Hi

First of all, thank you for such a great library!

The only caveat I've found so far is when implementing onPress for datapoints in LineSeries.

It looks like even if you increase the radius of the datapoints, the pressable area remains the same.

I've found users find it challenging to pin point the pressable area and it would be an enhancement if it would increase with the radius of the datapoint.

Please, do let me know if I am missing any tricks.

Many thanks!

**Comment by Abhinandan-Kushwaha** [comment]
Hi @aleroca96 👋
The pressable area increases with an increase in the radius of datapoints. I am unable to reproduce your bug. Please provide the code you are using to render the chart.

Also, you might like to upgrade to the new version- `1.3.1`. There have been some updates regarding onPress.
