### ISSUE TITLE
How to ScrollToEnd Programmatically

### ISSUE THREAD

**Issue by darkholiday** [Abhinandan-Kushwaha/react-native-gifted-charts#273]
I tired using refs but no success

```
 const chartRef = useRef(null);
 
<LineChart
         ref={chartRef}
         ......
/>

chartRef.current.scrollToEnd()
```

**Comment by Abhinandan-Kushwaha** [comment]
Use the `scrollToEnd` prop inside the `<LineChart>` component.

**Comment by darkholiday** [comment]
i wanna scroll to end on a button click !
how to do that ?

**Comment by anniewey** [comment]
> i wanna scroll to end on a button click ! how to do that ?

@Abhinandan-Kushwaha is this possible?
