### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNSVGSvgView, js engine: hermes

### ISSUE THREAD

**Issue by bharvadiyavishal** [Abhinandan-Kushwaha/react-native-gifted-charts#274]
Invariant Violation: Tried to register two views with the same name RNSVGSvgView, js engine: hermes

**Comment by Zetakai** [comment]
got the same error

**Comment by bharvadiyavishal** [comment]
any solution about that ?

**Comment by AmitP1392** [comment]
any solution for this issue? i am also getting same error

**Comment by Zetakai** [comment]
Im trying with other library. Will come back to this library if the issue is fixed

**Comment by bharvadiyavishal** [comment]
> i fixed it by changing the version of my root react-native-svg to the same version as the one from react-native-gifted-charts (in node_modules/react-native-gifted-charts/react-native-svg package json)

bro can you give a your root photo or any code so will see and do. ?

**Comment by Zetakai** [comment]
What? I dont really understand what u mean but what i did was. I uninstalled my react native svg. And installed it again with same spesific version as react native svg version from the node modules i mentioned before

**Comment by bharvadiyavishal** [comment]
> What? I dont really understand what u mean but what i did was. I uninstalled my react native svg. And installed it again with same spesific version as react native svg version from the node modules i mentioned before

oh i was try what say but cant solve error

**Comment by KulBoiz** [comment]
You need to downgrade react-native-svg's version to 12.4.4 then it will solve the problem

**Comment by MarciusSme** [comment]
Same here using react-native-svg's@^13

**Comment by MaximPVladimirovich** [comment]
In my case I ran 'npm uninstall' then 'npm install react-native-svg', It upgrade the package version from 12.4.4 to 13.6.0 and The error went away.

**Comment by kendrickw** [comment]
In my case, I enforced a specific version by adding this to `package.json`, since I already have 12.3.0 installed in the existing project:
```
  "resolutions" : {
    "react-native-svg": "12.3.0"
  },
```

**Comment by anniewey** [comment]
> i fixed it by changing the version of my root react-native-svg to the same version as the one from react-native-gifted-charts (in node_modules/react-native-gifted-charts/react-native-svg package json)

able to fix the error following the suggested solution above. downgraded `react-native-svg:13.7.0` to `react-native-svg:13.6.0`

**Comment by Abhinandan-Kushwaha** [comment]
Hey guys👋
The dependencies have been upgraded in version `1.3.0` 🎉

Please use the latest version and feel free to reopen if the issue still persists.
