### ISSUE TITLE
Line chart has white space when using adjustToWidth

### ISSUE THREAD

**Issue by KulBoiz** [Abhinandan-Kushwaha/react-native-gifted-charts#276]
- When I use adjustToWidth line chart shows white space like this
![596580790c86cad89397](https://user-images.githubusercontent.com/105470699/201569329-64d52a44-6738-4c28-85c4-8021758c770f.jpg)
- How can I make a chart look like this: https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/demos/scrollLine.gif
- I'm using chart version ^1.2.41
- this is my line chart code:
<LineChart
        areaChart
        data={chartData}
        width={width * 0.85}
        curved
        adjustToWidth
        disableScroll
        initialSpacing={0}
        hideDataPoints
        scrollToEnd
        scrollAnimation={false}
        color={hexToRgbA(color.primary, 0.7)}
        thickness={1.5}
        startFillColor={hexToRgbA(color.primary, 0.1)}
        endFillColor={hexToRgbA(color.background, 0.1)}
        startOpacity={0.2}
        endOpacity={0.1}
        noOfSections={4}
        stepValue={highestNav / 4}
        maxValue={highestNav}
        minValue={minNav}
        showXAxisIndices
        xAxisIndicesColor={color.palette.deepGray}
        xAxisIndicesHeight={1}
        xAxisIndicesWidth={7}
        yAxisThickness={1}
        xAxisColor={color.palette.deepGray}
        hideRules
        hideOrigin
        yAxisColor={color.palette.deepGray}
        yAxisTextStyle={{
          color: color.palette.lightBlack,
          right: s(-70),
          position: "absolute",
        }}
        yAxisSide="right"
        yAxisLabelWidth={s(50)}
        yAxisLabelContainerStyle={{ zIndex: -1 }}
        verticalLinesUptoDataPoint
        getPointerProps= {(pointerProps)=>{
          if (pointerProps.pointerIndex > 0){
            setScrollAble(false)
            return
          }
          setScrollAble(true)
        }}
        pointerConfig={{
          pointerStripColor: color.palette.deepGray,
          pointerStripWidth: 2,
          pointerColor: color.primary,
          radius: 4,
          pointerLabelWidth: s(100),
          pointerLabelHeight: 90,
          // set to false => can not scroll when enable scrollEnable
          activatePointersOnLongPress: false,
          autoAdjustPointerLabelPosition: true,
          pointerLabelComponent: items => {
            return (
              <View style={styles.toolkit}>
                <AppText style={{ fontSize: ms(14), textAlign: "center" }}>
                  {items[0].date}
                </AppText>
                <View style={ALIGN_CENTER}>
                  <AppText style={FONT_BOLD_12}>
                    {numberWithCommas(items[0].value)} VNĐ
                  </AppText>
                </View>
              </View>
            )
          },
        }}
      />

**Comment by skhizerabass** [comment]
Any success on this?

**Comment by farooqalam20996** [comment]
still waiting for this solution...

**Comment by farooqalam20996** [comment]
![bgter](https://user-images.githubusercontent.com/33805731/209159978-56620fc5-5ec6-42c9-b411-5aeb01447c67.png)
how I remove extra white space, so my graph will show complete on the container

**Comment by farooqalam20996** [comment]
![fsdfds](https://user-images.githubusercontent.com/33805731/209160544-450a6228-60c4-4535-b2d1-8b2ee9cf8ffe.png)
kindly guide me on how to remove this extra white space... and show the graph full on the container...
Thanks

**Comment by Dr0pG** [comment]
Any solution for this? I'm also facing it...
<img width="319" alt="Screenshot 2023-01-30 at 09 34 29" src="https://user-images.githubusercontent.com/43783195/215440210-e98125dd-9609-4afb-aeb5-4a2d5f584399.png">

**Comment by Dr0pG** [comment]
still waiting for this solution, please...

**Comment by T-Lukashevich** [comment]
Same problem

**Comment by RoccoDocco** [comment]
same here

**Comment by Abhinandan-Kushwaha** [comment]
Hey fellas👋 Sorry for the late response.
This issue is now fixed in version `1.3.1`🎉

We have introduced a new prop named `endSpacing` whose default value is `20`. Set `endSpacing` to `0` if you want to remove the space at the right side of the chart.

Also when we set the prop `adjustToWidth` to true, `endSpacing` automatically sets to `0`.

**Comment by Dance225** [comment]
add in your LineChart 
export enum CurveType {
  CUBIC,
  QUADRATIC,
}
<LineChart
...
curveType={CurveType.QUADRATIC}
...
