### ISSUE TITLE
Error: AnimatedValue: Attempting to set value to undefined

### ISSUE THREAD

**Issue by Yubiny16** [Abhinandan-Kushwaha/react-native-gifted-charts#277]
I'm getting this error when I install and run this library for the first time.

 - Device: [e.g. iPhone13]
 - OS: [e.g. iOS16.1]
<img width="393" alt="스크린샷 2022-11-15 오후 5 49 08" src="https://user-images.githubusercontent.com/26242745/201873225-aee65fa9-89a5-4c6f-9c3d-fd1ed6f77a1e.png">

I'm assuming the error is caused by libraries clashing but I'm not sure. These are my packages that I have installed on my project.

"react-native-svg": "^12.1.0",
"react-native-reanimated": "^2.12.0",
"react-native-linear-gradient": "^2.5.6",
"react-native-gifted-charts": "^1.2.41",

Would appreciate if I could get some guidance.

**Comment by Ritesh175862** [comment]
Hi @Abhinandan-Kushwaha I am getting this in the project can you suggest me any solution ?
