### ISSUE TITLE
react-native-svg version bump necessary for expo

### ISSUE THREAD

**Issue by ythomop** [Abhinandan-Kushwaha/react-native-gifted-charts#280]
**Describe the bug**
I checked with `expo@~47.0.8` which requires `react-native-svg@13.4.0` and the collision between expo's version and gifted-charts' version is preventing the app from running by emitting the following error:

![image](https://user-images.githubusercontent.com/35526357/203819587-a20fcb17-e5e3-4afd-ab5a-6421c3162a10.png)

When using only the version required by gifted charts, I get this error in the emulator/device:

![image](https://user-images.githubusercontent.com/35526357/203820052-23f3a70a-421c-4ebe-bb3f-0a2682f5d099.png)

which is obviously a problem in the native code of `react-native-svg@^12.1.0`.

**To Reproduce**
1. Create a simple expo app (should install `expo@~47.0.8`)
2. Install react-native-gifted-charts
3. Run the app
4. See the error in the emulator

 - Version of the library being used [e.g. 1.2.41]

**Additional context**
I upgraded locally the react-native-svg version used by gifted charts to the one that expo requires and everything seems to be working fine both with expo and gifted charts, but I cannot maintain my own react-native-gifted-charts.

**Comment by apapalillo** [comment]
I'm having the same issue, please bump the version up

**Comment by Abhinandan-Kushwaha** [comment]
`react-native-svg` is now upgraded to `13.6.0` closing the issue.
