### ISSUE TITLE
[ Help ] LineChart, Point focus not hiding.

### ISSUE THREAD

**Issue by KieQuang** [Abhinandan-Kushwaha/react-native-gifted-charts#285]
[ Help ]
Any chance to auto focus point in Linechart.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @KieQuang 👋

If you want some point to appear differently on the Line chart, you can use these properties inside the data object for that point-

1.  `dataPointHeight`
2. `dataPointWidth`
3. `dataPointRadius`
4.  `dataPointColor`
5.  `dataPointShape`
6. `hideDataPoint`

You can even use a custom data point component of your own using the property `customDataPoint`

Complete list available under item description table on this link- [Line Chart props](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/LineChart/LineChartProps.md)

Or maybe you want something like this-

![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/15aa3a30-e687-4394-a06d-1010e85c6ea9)

This is explained well in the docs here- [Area chart docs](https://gifted-charts.web.app/areachart)
Scroll down and you will see something like this on the above link-

<img width="1124" alt="dataPointLabel" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/933d3e86-a5ad-4c20-8ec3-7ad84c4ca415">

The code is also provided in the doc. I hope it helps.🤗
