### ISSUE TITLE
Line Chart: PressIn on chart doesn't lock the pointer when scrolling vertically

### ISSUE THREAD

**Issue by dchhetri** [Abhinandan-Kushwaha/react-native-gifted-charts#287]
**Describe the bug**
- Have a line chart inside a scroll view
- pressIn on a line chart with pointerConfig defined
- While pressed in, move the finger down and notice the scrollview scrolls down.

The issue sounds similar to #175 

**Expected behavior**
I'm hoping once the user presses in on the line chart, moving the finger while pressed will not cause the scroll view to scroll down. Atm, the pointerConfig doesn't operate as expected in this situation due to the scrolling conflict. 

I'm trying to find a workaround but nothing in the exposed API allows it as far as I can tell.

**Comment by FrSenpai** [comment]
Same here, any ETA ?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @dchhetri @FrSenpai 
Thanks for requesting this feature.

Here's a workaround-

In the parent **ScrollView**, set the prop `scrollEnabled` to true only when the _pointer_ is not displayed over the chart. To know when the pointer is displayed, we can use the `getPointerProps` provided with the `<LineChart>` component.

Here's an example-

```ts
const data = [
    {value: 80},
    {value: 130},
    {value: 80},
    {value: 106},
    {value: 86},
    {value: 91},
    {value: 82},
    {value: 90},
    {value: 130},
    {value: 90},
    {value: 106},
    {value: 96},
    {value: 106},
    {value: 86},
    {value: 91},
    {value: 92},
    {value: 80},
    {value: 130},
    {value: 106},
    {value: 96},
    {value: 91},
  ];

  const [isPointerShown, setIsPointerShown] = useState(false);

  return (
    <ScrollView scrollEnabled={!isPointerShown}>

      {[0, 0, 0].map((item, index) => {
        return (
          <Text key={index} style={{padding: 15}}>
            Hello
          </Text>
        );
      })}

      <LineChart
        data={data}
        spacing={15}
        hideDataPoints
        hideRules
        pointerConfig={{
          pointerLabelComponent: items => {
            return (
              <View
                style={{
                  height: 30,
                  width: 100,
                  justifyContent: 'center',
                  backgroundColor: '#ede',
                }}>
                <Text style={{fontWeight: 'bold', textAlign: 'center'}}>
                  {items[0].value}
                </Text>
              </View>
            );
          },
        }}
        getPointerProps={({pointerIndex})=>setIsPointerShown(pointerIndex!==-1)}
      />

      {[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0].map((item, index) => {
        return (
          <Text key={index} style={{padding: 15}}>
            Hello
          </Text>
        );
      })}

    </ScrollView>
  );
```
The output is-

https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/92641d0a-df38-4e18-a835-6a443ad9bd30

---
**Note** - Please use the latest version of the library, previous versions might have minor issues.

**Comment by MrGainn** [comment]
@Abhinandan-Kushwaha the getPointerProps={({pointerIndex})=>setIsPointerShown(pointerIndex!==-1)} doesn't return -1 for me when I release the pointer. Do you have an idea why? It does return the correct index, I just don't get a callback when I release the pointer. I'm using an android device with expo.

**Comment by MrGainn** [comment]
I found the solution for anyone struggling with the same issue as me. 

```	getPointerProps={(item, index) => {
	  const {pointerIndex, pointerX, pointerY} = item;
	  if (pointerIndex === -1 && pointerX === 0 && pointerY === 0) {
	    return;
	  } else if (item.pointerX === 0) {
	    setIsScroll(true);
	  } else {
	    setIsScroll(false);
	  }
	}}```. Thanks to this chinese website: https://velog.io/@tmdghks_dev/React-Native-react-native-gifted-chart%EC%9D%98-LineChart%EC%97%90%EC%84%9C-pointer-%ED%99%9C%EC%84%B1%ED%99%94-%EC%8B%9C-scrollView-disable-%EB%B0%A9%EB%B2%95

**Comment by Abhinandan-Kushwaha** [comment]
@MrGainn `getPointerProps` was modified recently to not return -1 on releasing the press. This was done to persist the last touched index, which might be useful in showing legends and some other use cases.

You can use `pointerX === 0` instead of `pointerIndex === -1`. The website you mentioned has a detailed explanation which can be really useful.
