### ISSUE TITLE
Question:  Is it possible to have pointerConfig active and show soon as touch event happens vs current behavior of onMove

### ISSUE THREAD

**Issue by dchhetri** [Abhinandan-Kushwaha/react-native-gifted-charts#288]
**Describe the bug**
For a line chart, I noticed that I have to touch then move my fingers for the pointerConfig to take affect. I am wondering if it's possible to provide immediate feedback with the pointerConfig on touch start instead of on move?

**To Reproduce**
1. Take any of the demo chart and verify the pointer config data only shows after touch move and not on touch start.

 - Device: Iphone 11 pro max
 - OS: latest
 - Version of the library being used [e.g. 1.2.17]

**Comment by kayGweb** [comment]
I have the same issue. 

Device iPhone X pro 
"react-native": "0.69.1"

**Comment by Abhinandan-Kushwaha** [comment]
Hi @dchhetri @kayGweb 👋
Sorry for replying so late.

If you want to activate the pointers immediately on touch, perhaps you should remove the `pointerConfig` prop and use the following props instead-
1. `focusEnabled`
2. `showStripOnFocus` 
3. `showDataPointLabelOnFocus`
 
Using these props you can achieve pointer-like behaviour without having to move your fingers.

See https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/664#issuecomment-2179476496

Please use the latest version of the library.
