### ISSUE TITLE
haven't  data line format make dotted or dashed ?

### ISSUE THREAD

**Issue by RDDSampath** [Abhinandan-Kushwaha/react-native-gifted-charts#289]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

 - Version of the library being used [e.g. 1.2.17]

**Additional context**

**Comment by Abhinandan-Kushwaha** [comment]
Hi @RDDSampath 
You can use the `strokeDashArray` prop

For dotted-
```
strokeDashArray={[1,2]}
```
For dashed-
```
strokeDashArray={[4,6]}
```

**Comment by RDDSampath** [comment]
ok **thank you**
