### ISSUE TITLE
Donut Pie Chart focusOnPress crashes if tapping edge of circle.

### ISSUE THREAD

**Issue by StevenGonzalez** [Abhinandan-Kushwaha/react-native-gifted-charts#296]
**Describe the bug**
On the Donut PieChart when focusOnPress is true and the circle has been expanded by pressing on it, if you then tap on the edge of the expanded circle it crashes with the error: "undefined is not a function"

**To Reproduce**
Create a PieChart with at least 2 items.
Set donut true, focusOnPress true, and toggleFocusOnPress true
Tap the circle once to select an item.
Once the item has been selected and that portion of the circle has expanded to show the selection, tap the very edge of the expanded circle. 

**Expected behavior**
When pressing on the circle anywhere after the circle has expanded, the focusOnPress handles unexpanding correctly and does not throw an exception.

**Screenshots**
![image](https://user-images.githubusercontent.com/23227963/214893364-26668096-5aa9-45e5-bd82-035fbdcd7850.png)

Tested on both Android and iOS
Package version 1.2.42

**Comment by PBallal0702** [comment]
Facing same issue

**Comment by Abhinandan-Kushwaha** [comment]
Hey @StevenGonzalez @PBallal0702 Thanks for pointing out the issue, it has been resolved in version `1.3.1`🎉
