### ISSUE TITLE
Handle data as low as   0.0044

### ISSUE THREAD

**Issue by stijnvddonk** [Abhinandan-Kushwaha/react-native-gifted-charts#300]
**Describe the bug**
The show fractions only works with doubles with 1 decimal.
I am working with values which can go up to 0.0044, but all values will be low in this case.

How can I get it so that my chart will work with both numbers and very low numbers?
**To Reproduce**

**Expected behavior**
Allow the yAxis to handle low floats.

 - Version of the library being used [e.g. 1.2.17]

**Additional context**

**Comment by Abhinandan-Kushwaha** [comment]
Use the props `maxValue`, `roundToDigits` and `yAxisLabelWidth`. Here's an example-

```js
const const barData = [{value:.0066}, {value:.0044}, {value:.0088}];

return(
 <BarChart
   data={barData}
   showFractionalValues
   maxValue={.01}
   roundToDigits={3}
   yAxisLabelWidth={50}/>
);
```
The result is-

<img width="256" alt="Screenshot 2023-02-10 at 8 40 56 PM" src="https://user-images.githubusercontent.com/20596944/218126193-a628cc69-1dec-4a2e-966e-ea2b86b0d607.png">

**Comment by stijnvddonk** [comment]
Amazing! Thanks you! Is is also possible to add trailing zero's to the numbers which are whole?

**Comment by Abhinandan-Kushwaha** [comment]
Can you please elaborate your use case with an example?

**Comment by stijnvddonk** [comment]
For instance: 
![Screenshot 2023-02-13 at 15 22 16](https://user-images.githubusercontent.com/45181614/218483710-b6a15566-ec9b-4057-98da-c16e963a7201.png)

I added the roundToDigits={2}
But some values now show no digits or 1. How would I be able the add trailing 0's to these values. 
so 2.50, 5.00 etc

**Comment by Abhinandan-Kushwaha** [comment]
Hi @stijnvddonk 👋
Thanks for pointing this out. This issue has been fixed.🎉 Please update to version 1.3.6 of react-native-gifted-charts.
