### ISSUE TITLE
Current month(time) indicator

### ISSUE THREAD

**Issue by dogancancelik12** [Abhinandan-Kushwaha/react-native-gifted-charts#301]
Hey, 

Is there possibility of creating a prop for tracing/seeing current month on chart. For example, in screenshot below, I show data for 3 months, user can see previous months by swiping, any possible development for showing which month is currently on screen. 

![Screen Shot 2023-02-24 at 10 18 20](https://user-images.githubusercontent.com/61014989/221116449-c0373ff1-caa2-49d2-a5eb-9c1172ae1442.png)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @dogancancelik12 👋
This can be achieved using the `scrollRef` prop.

Here is an example-

https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/cff60f6d-12c2-4722-8d53-221e6aab03a2

The code for the above chart is-

```js
const App = () => {
const ref = useRef(null)
  
  const lineData = [
    {value: 4, label: '1 Jan'},
    {value: 14, label: '10 Jan'},
    {value: 8, label: '20 Jan'},
    {value: 38, label: '30 Jan'},
    {value: 36, label: '1 Feb'},
    {value: 28, label: '10 Feb'},
    {value: 14, label: '20 Feb'},
    {value: 28, label: '28 Feb'},
    {value: 4, label: '1 Mar'},
    {value: 14, label: '10 Mar'},
    {value: 8, label: '20 Mar'},
    {value: 14, label: '30 Mar'},
    {value: 8, label: '1 Apr'},
    {value: 38, label: '10 Apr'},
    {value: 14, label: '20 Apr'},
    {value: 28, label: '30 Apr'},
    {value: 4, label: '1 May'},
    {value: 10, label: '10 May'},
    {value: 8, label: '20 May'},
    {value: 14, label: '30 May'},
    {value: 8, label: '1 Jun'},
    {value: 38, label: '10 Jun'},
    {value: 14, label: '20 Jun'},
    {value: 28, label: '30 Jun'},
    {value: 4, label: '1 Jul'},
    {value: 28, label: '10 Jul'},
    {value: 4, label: '20 Jul'},
    {value: 14, label: '30 Jul'},
  ];

  const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul']

  const showOrHidePointer = (ind) => {
    ref.current?.scrollTo({
    x: ind*200 - 25}); // adjust as per your UI
  };

  return (
    <View>
      <View style={{flexDirection: 'row', marginLeft: 8}}>
        {months.map((item, index) => {
          return (
            <TouchableOpacity
              key={index}
              style={{
                padding: 6,
                margin: 4,
                backgroundColor: '#ebb',
                borderRadius: 8,
              }}
              onPress={() => showOrHidePointer(index)}>
              <Text>{months[index]}</Text>
            </TouchableOpacity>
          );
        })}
      </View>
        <LineChart
          scrollRef={ref}
          data={lineData}
          curved
          initialSpacing={0}
          rotateLabel
        />
    </View>
  );
}
```

**Comment by jeanniton-mnr** [comment]
> d
>           initialSpacing={0}
>           rotateLabel

I have copied this exact source code, and the line chart never scrolls - documentation inconsistency.

You can find a copy of the documented sample at [the following expo snack](https://snack.expo.dev/@jeanniton.mnr/scrollview-chart):   


https://snack.expo.dev/@jeanniton.mnr/scrollview-chart

PS:
I don't know if that would help in finding the problem, but the onScroll callback function would be triggered if it is provided.

**Comment by jeanniton-mnr** [comment]
I was able to find that:
1. You need to set the `width` prop for the chart.
2. It will still not work with `react-gifted-charts` but will work with `react-native-gifted-charts`.
