### ISSUE TITLE
xAxisLabel is ellipsis and not showing full

### ISSUE THREAD

**Issue by huan415201** [Abhinandan-Kushwaha/react-native-gifted-charts#303]
When my xAxisLabel is long, it becomes this:
![image](https://user-images.githubusercontent.com/43948939/222718363-c127f294-8bef-4a67-aac4-b18545d407ef.png)

Is there any option to show full the label without ellipsis? I tried to set width for ```xAxisLabelTextStyle``` and this is what I got:
![image](https://user-images.githubusercontent.com/43948939/222718523-68a56e0a-9cd2-4ae2-837c-e9ce699701e6.png)

A new problem appears, is that the bar is not align center of the label, pls help...

**Comment by Abhinandan-Kushwaha** [comment]
Hi @huan415201 👋
You can give a negative left margin inside `xAxisLabelTextStyle` like this-
```js
xAxisLabelTextStyle = {{width:60, marginLeft: -12}}
```

**Comment by bhavesh-trentium** [comment]
@Abhinandan-Kushwaha  Hello,  If i have a long Text that can we wrap a text or not?

**Comment by Abhinandan-Kushwaha** [comment]
@bhavesh-trentium You can use custom X-axis labels using the `labelComponent` property in the data array.

**Comment by bhavesh-trentium** [comment]
@Abhinandan-Kushwaha I pass this data array but we don't see any text there.
```
  data={[
                      {
                        value: 15,
                        // label: 'Number of smatches',
                        frontColor: '#4BC0C0',
                        barBorderColor: '#4BC0C0',
                        barWidth: 50,
                        barBorderRadius: 4,
                        barBorderWidth: 1,
                        spacing: 50,
                        labelWidth: 50,
                        LabelComponent: () => (
                          <Text
                            style={{
                              color: 'blue',
                              fontSize: 13,
                            }}>
                            {'Number of smatches'}
                          </Text>
                        ),
                      }]
```

**Comment by Abhinandan-Kushwaha** [comment]
@bhavesh-trentium change `LabelComponent` to `labelComponent`, it should start with a lower case "l"
