### ISSUE TITLE
Zoom area on load

### ISSUE THREAD

**Issue by AkbarBakhshi** [Abhinandan-Kushwaha/react-native-gifted-charts#304]
Is there a prop that I can use to determine what range of data to be shown when the chart is loaded? 

For example, I have this chart that shows my weight over time. I have entered many data in it and now I have to scroll horizontally to the right to see the most recent data. 

Is there a way to show the most recent data on load (in this case the most right data point instead of the most left one, once the chart is loaded)?

<img width="303" alt="Screenshot 2023-03-03 at 10 54 57 AM" src="https://user-images.githubusercontent.com/46682991/222766440-7738f10f-97c6-4cbe-b2f1-d24254e22d20.png">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @AkbarBakhshi 👋
You can set the `scrollToEnd` prop to true. It will show the rightmost data on load.
