### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNSVGRect, js engine: hermes

### ISSUE THREAD

**Issue by MinChanSike** [Abhinandan-Kushwaha/react-native-gifted-charts#306]
`Invariant Violation: Tried to register two views with the same name RNSVGRect, js engine: hermes`

I got that issue when I'm trying to use  `react-native-gifted-charts` with `react-native-ui-kitten.`
Below are project dependencies from package.json.

```json
 "dependencies": {
    "@eva-design/eva": "^2.1.1",
    "@gorhom/bottom-sheet": "^4.4.5",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@ui-kitten/components": "^5.1.2",
    "@ui-kitten/eva-icons": "^5.1.2",
    "axios": "^1.3.4",
    "expo": "~48.0.6",
    "expo-status-bar": "~1.4.4",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-native": "0.71.3",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-gifted-charts": "^1.2.42",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-reanimated": "~2.14.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-svg": "13.4.0",
    "react-native-vector-icons": "^9.2.0",
    "react-query": "^3.39.3"
  },
```

**Comment by SpertsyanKM** [comment]
The problem might be with the `react-native-svg` library version. Try to upgrade your version of `react-native-svg` to 13.6.0, used in this library. It helped me.

**Comment by AkbarBakhshi** [comment]
Hi. I also got this error and changed the `react-native-svg` version to `13.6.0` and it works. However, when I do eas build, `expo doctor` fails and I am worried that it will become a problem in production. I am using `"expo": "~47.0.9"`. Anyone has any insights?


<img width="865" alt="Screenshot 2023-03-29 at 11 53 17 AM" src="https://user-images.githubusercontent.com/46682991/228596310-b2c44b4a-9805-446a-9862-d923ca614843.png">

**Comment by 100pearl** [comment]
Hi, @AkbarBakhshi 
Have you encountered any issue with prod level when running on v13.6.0?

**Comment by AkbarBakhshi** [comment]
> Hi, @AkbarBakhshi Have you encountered any issue with prod level when running on v13.6.0?

Not so far..

**Comment by teofilp** [comment]
I am experiencing the same issue with v13.6.0 on bare react native setup

**Comment by 100pearl** [comment]
FYI I'm following managed workflow and on RN v.0.71.6
I ended up remove the dependency and chose another.
2023년 4월 25일 (화) 오후 11:06, Teodor Filp ***@***.***>님이 작성:

**Comment by osmanthustonx** [comment]
facing this issue in expo 48.
is any progress?

**Comment by simp7** [comment]
Well, I also encountered this problem, and In my situation, I can't downgrade old version of react-native-svg, so I had to find another solution.
Finally, I solved this problem by adding 
```
"resolutions": {
    "react-native-gifted-charts/react-native-svg": "13.9.0" // The version of react-native-svg you use
  },
```
to package.json. You may notice that react-native-svg can't detect another version(I think it's weird, btw), and [this way forcing this library's dependency version](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) of react-native-svg solves the problem.

**Comment by hbcondo** [comment]
> Any update on this issue? I'm on expo 48.

Is this library truly compatible and supports the Expo Go platform per the React Native Directory? I'm on expo 48 as well experiencing this same error even after trying the workarounds discussed[^1].

https://reactnative.directory/?order=popularity&search=react-native-gifted-charts&expo+go=true
![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/306958/7c6420b5-30a9-4685-876b-b73f8a8f91df)

[^1]: https://forums.expo.dev/t/issue-with-react-native-svg-13-6-0-android/68454/17

**Comment by Abhinandan-Kushwaha** [comment]
Hey guys👋
The dependencies have been upgraded in version `1.3.0` 🎉

Please use the latest version and feel free to reopen if the issue still persists.
