### ISSUE TITLE
Feature Request: Animation for stacked BarCharts

### ISSUE THREAD

**Issue by docluis** [Abhinandan-Kushwaha/react-native-gifted-charts#307]
Currently the isAnimated prop only works on BarCharts with the data prop. It would be great if the animation is also available for BarCharts that use the stackData prop.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @docluis 👋
Thanks for requesting the feature.
Animation is now supported for stacked bar charts.🎉
Just pass the `isAnimated` prop. Use the latest version of the library.
