### ISSUE TITLE
typescript should be a devDependency and not a regular dependency

### ISSUE THREAD

**Issue by toter3** [Abhinandan-Kushwaha/react-native-gifted-charts#308]
**Describe the bug**
typescript should be a devDependency and not a regular dependency, being a dependency causes it to force the library version in projects which uses a devDependency for typescript (as it should be)

please move the typescript dependency to devDependency

**Comment by Abhinandan-Kushwaha** [comment]
Hi @toter3 👋
Thanks for pointing it out. typescript is now a devDependency version `1.3.0` onwards. 🎉
