### ISSUE TITLE
"z index" on reference line vs topLabelComponent

### ISSUE THREAD

**Issue by jameskennethrobinson** [Abhinandan-Kushwaha/react-native-gifted-charts#310]
Hello,

Wondering if it's possible to change the `zIndex` on the reference line, specifically relative the `topLabelComponent`. It can be seen here that the reference line renders in front of the medal icon.

Both the medals and reference lines are SVGs, so I tried the advice in the following issue. However, couldn't get the z index to work.

Thank you!

https://github.com/software-mansion/react-native-svg/issues/682

<img width="400" alt="image" src="https://user-images.githubusercontent.com/8107077/228682280-2903c512-f63f-4f65-9865-fa0105f4d316.png">

**Comment by audn** [comment]
Did you find a workaround?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @jameskennethrobinson @audn 👋
Thanks for requesting this feature. This can now be achieved using the `zIndex` property to `referenceLine1Config`, `referenceLine2Config` and `referenceLine3Config`. The default value of zIndex is `1`. To render the reference lines behind the bars and the top label components, set zIndex to `0` 

This feature is available from version `1.3.25` onwards. Please use the latest version of the library.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @jameskennethrobinson @audn 
Try using the prop `referenceLinesOverChartContent={false}`
It is available from version `1.3.29` onwards.
