### ISSUE TITLE
LineChart Curve graph is not properly showing when the value is 0

### ISSUE THREAD

**Issue by androidmasterid** [Abhinandan-Kushwaha/react-native-gifted-charts#315]
![LineChart_Curve Graph](https://user-images.githubusercontent.com/52368506/236136107-69c1b713-28f3-4c01-903a-5d4d3d38d5a3.png)

let DATA_IS = [
{"label": "Jun", "value": 0},
{"label": "Jul", "value": 0}, 
{"label": "Aug", "value": 0}, 
{"label": "Sep", "value": 0}, 
{"label": "Oct", "value": 0}, 
{"label": "Nov", "value": 0}, 
{"label": "Dec", "value": 0},
{"label": "Jan", "value": 0}, 
{"label": "Feb", "value": 0}, 
{"label": "Mar", "value": 0}, 
{"label": "Apr", "value": 0}, 
{"label": "May", "value": 10677}
]

 <LineChart
      minValue={0}
      curved={true}
      height={dpHeight(150)}
      spacing={dpWidth(30)}
      width={window.width / 1.3}
      showScrollIndicator={false}
      animateOnDataChange={true}
      areaChart
      data={DATA_IS}
      color={AppColors.graphLine}
      startFillColor={AppColors.graphShad}
      endFillColor={AppColors.white}
      horizSections
      initialSpacing={dpWidth(20)}
      startOpacity={0.9}
      endOpacity={0.4}
      thickness={3}
      noOfSections={5}
      yAxisColor="white"
      xAxisColor="white"
      yAxisThickness={0}
      hideRules={true}
      yAxisTextStyle={styles.yxisTextColor}
      xAxisLabelTextStyle={styles.axisTextColor}
    />

**Comment by prakashawal** [comment]
Did you find the solution? I am also stuck in this issue.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @prakashawal 👋
This is happening because the line is going below 0, and hence it becomes invisible.
You can use the prop `curveType={CurveType.QUADRATIC}` to fix this issue.
