### ISSUE TITLE
how to fire an event onMove / onDrag?

### ISSUE THREAD

**Issue by nickcom111** [Abhinandan-Kushwaha/react-native-gifted-charts#317]
I've got the same line chart with point working from the [examples folder](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/examples/LineChart/ChartWithPointer.js).

I need to update an external state based on the value displayed in the pointer (ie the selected chart value). I'd also like to fire a vibration as the user moves over data points in the chart. This requires some sort of event to be fired as the pointer is moved/updated. 

I couldn't see reference to this in the documentation.

**Comment by farajFreebnk** [comment]
Same here
