### ISSUE TITLE
After Installation not able to use chart -urgent

### ISSUE THREAD

**Issue by Ekta29yadav** [Abhinandan-Kushwaha/react-native-gifted-charts#319]
**Describe the bug**
after install show error
**To Reproduce**
yarn start face error

**Expected behavior**
chart to be use
![Screenshot from 2023-05-21 13-29-41](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/35370466/8660518a-c94e-49a8-a8dd-d9c7710798d7)

**Comment by Abhinandan-Kushwaha** [comment]
@Ekta29yadav Looks like you had not been able to install the package properly. Closing it.
Feel free to reopen if you are still facing the issue.
