### ISSUE TITLE
donut chart stroke width not working

### ISSUE THREAD

**Issue by ShivaSunny9** [Abhinandan-Kushwaha/react-native-gifted-charts#32]
Strokewidth is not working properly for donut chart

**Resolve this issue ASAP!! largely dependent on this stroke width for data viewing**

Versions : 
"react": "17.0.2",
"react-native": "0.65.1",
"react-native-gifted-charts": "^0.1.14"

![Screenshot_1635758587](https://user-images.githubusercontent.com/32735889/139650531-e423bf72-2561-4add-9354-9dddaf0ffab8.png)

Code :

const pieData = [
    {
      value: 25,
      color: '#FFC107',
      textBackgroundColor: '#FFC107',
      textColor: '#343A40',
      textSize: 12,
    },
    {
      value: 25, 
      color: '#FAD76F', 
      textBackgroundColor: '#FAD76F',
    textColor: '#343A40',
    textSize: 12,
  },
    {
      value: 25, 
       color: '#F7E3A7',  
      textBackgroundColor: '#F7E3A7',
    textColor: '#343A40',
    textSize: 12,
  },
    {
      value: 25,
      color: '#F5EBCD',
      textBackgroundColor: '#F5EBCD',
      textColor: '#343A40',
      textSize: 12,
    },
  ]; 
 <PieChart
        data={pieData}
        donut
        innerRadius={55}
        radius={110}
        showText={true}
        showValuesAsLabels={true}
        showTextBackground={true}
        strokeWidth={20}
        strokeColor={'green'}
      />

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ShivaSunny9 
Thanks for pointing out the issue. This has been now fixed in version `0.1.15`
Closing the issue.
Cheers! 🎉

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ShivaSunny9
I guess you were trying to achieve something like this-

<img width="263" alt="pie" src="https://user-images.githubusercontent.com/20596944/139721848-5261be31-dc7e-4fdb-a736-c559136b495c.png">

For this, you need to upgrade the **react-native-gifted-charts** package to `0.1.15`. 
In addition to this, you need to add the `innerCircleBorderWidth` and `innerCircleBorderColor` props.

So your code should look like this-

```
const pieData = [
    {
      value: 25,
      color: '#FFC107',
      textBackgroundColor: '#FFC107',
      textColor: '#343A40',
      textSize: 12,
    },
    {
      value: 25,
      color: '#FAD76F',
      textBackgroundColor: '#FAD76F',
      textColor: '#343A40',
      textSize: 12,
    },
    {
      value: 25,
      color: '#F7E3A7',
      textBackgroundColor: '#F7E3A7',
      textColor: '#343A40',
      textSize: 12,
    },
    {
      value: 25,
      color: '#F5EBCD',
      textBackgroundColor: '#F5EBCD',
      textColor: '#343A40',
      textSize: 12,
    },
  ];
  <PieChart
        data={pieData}
        donut
        innerRadius={55}
        radius={110}
        showText={true}
        showValuesAsLabels={true}
        strokeWidth={20}
        innerCircleBorderWidth={20}
        innerCircleBorderColor={'green'}
        strokeColor={'green'}
      />
```

**Comment by ShivaSunny9** [comment]
Thanks for the resolving the issue
