### ISSUE TITLE
[Q] How to scroll to specific point on x-axis?

### ISSUE THREAD

**Issue by anniewey** [Abhinandan-Kushwaha/react-native-gifted-charts#322]
For instance, my x-axis is displaying hour for the day (24h) from 12 am to 11pm. There I need a function scroll the chart to current hour such as 2pm. Is there any available fn to trigger the scrolling? I only found scrollToEnd` props on BarChart and LineChart but i want to scroll to specific hour instead.

Tried using ref but getting `null`. Noticed that there's `scrollRef` defined in the `LineChart` itself. Is there a way to override it?

```
import { LineChart } from 'react-native-gifted-charts';
const LineChartApp = forwardRef((props, ref) => LineChart(props, ref)); //due to Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

const chartRef = useRef(null);

const scrollToXAxis = () => {    
    if (chartRef.current) { //return null
      chartRef.current.scrollToEnd();
    }
  };

<LineChartApp
            ref={chartRef}
            data={lineChartData}
..
/>
```

**Comment by Abhinandan-Kushwaha** [comment]
Hi @anniewey 
Thanks for requestin the feature. You can now use the scrollToIndex prop to scroll to any particular index.
Also, you can use the scrollRef prop to scroll to any position.

Please use the latest version of the library.
