### ISSUE TITLE
BUG: endIndex usage with lineChart

### ISSUE THREAD

**Issue by dogancancelik12** [Abhinandan-Kushwaha/react-native-gifted-charts#323]
I am using line chart with data and data1, when there is no endIndex1, endIndex2 there is no error on my chart when I added new value but when I activated endIndex1 and endIndex2 then add a new value I had a crash. 

1. create line chart with data and data2 props with no endline1 endline2 prop or endline1=null endline2=null add new value to chart (there is no problem) 
2.create line chart with data and data2 props with endline1 endline2 = some value then add a new value will have crash

![Screen Shot 2023-05-30 at 14 23 19](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/61014989/c0cc6ba1-8527-452e-8681-de5358f0ec09)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @dogancancelik12 
Can you please share the code, so I can debug the issue?
