### ISSUE TITLE
[HELP] Donut focus inside instead of outside

### ISSUE THREAD

**Issue by Abe101** [Abhinandan-Kushwaha/react-native-gifted-charts#325]
Hi, I am glad I found this library, almost everything that I need. I am trying to figure out two things:

1. I am trying to replicate this

![Design](https://i.ibb.co/5cbfj9S/Screenshot-2023-06-08-at-6-05-13-PM.png)

and I have achieved it like this

![Replicated](https://i.ibb.co/j5mmDDy/Whats-App-Image-2023-06-08-at-6-01-16-PM.jpg)

Heres the code

```
const Fake_Data = [
  {
    value: 45,
    color: "#3A83FF",
    focused: true,
  },
  {
    value: 55,
    color: "#BDD5FF",
  },
];

<PieChart
    donut
    data={Fake_Data}
    innerRadius={110}
    sectionAutoFocus
    centerLabelComponent={() => {
      return (
        <View style={styles.center}>
          <Text style={styles.value}>$1.740.00</Text>
          <Text style={styles.text}>invested</Text>
        </View>
      );
    }}
    strokeWidth={0}
    strokeColor={theme.colors.white}
  />
```

How do I get the focused section to grow inside instead of outside?

2. In line and bar charts there is y axis labels suffix and prefix. I can't seem to find a prop that could help me set the suffix/prefix conditionally, for instance I don't want suffix/prefix on the 0 (starting) index of the y axis

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Abe101 
Thanks for requesting this feature. It is available from version `1.3.27` onwards.

To achieve this, you need to pass the following props-

```ts
inwardExtraLengthForFocused={20}
extraRadiusForFocused={0}
```
