### ISSUE TITLE
[HELP] App crashes on TestFlight after building with Expo EAS

### ISSUE THREAD

**Issue by jimmyz2** [Abhinandan-Kushwaha/react-native-gifted-charts#326]
The library works fine on Expo Go development (after downgrading react-native-svg), and installing react-native-gesture-handler into my project. However, when I build the app with EAS Build and submit to TestFlight, any time a component renders from the library (BarChart, LineChart), the app immediately crashes.

Other times, the app simply becomes a white screen and unresponsive. I've tried installing react-native-gesture-handler in the library code itself, adding it as a peer dependency, etc., with no luck.

Strangely, when running the Expo app in production mode with `expo start --no-dev --minify -c`, it runs on Expo Go. But any time I try to run as a binary IPA file on my iPhone (through TestFlight), it crashes.

Note that I forked the repo at version 1.2.42 to add a few custom components, but I also installed the library at version 1.2.42 and the same bug still occurs.

 - Device: iPhone 13
 - OS: iOS 15.7.1
 - Version of the library being used [e.g. 1.2.17]

**Comment by Rohit-Parte** [comment]
@jimmyz2  Is it still working on Expo react-native or you just get out of it :)
