### ISSUE TITLE
x axis date formate label need to adjust 

### ISSUE THREAD

**Issue by NikhilMasurkar** [Abhinandan-Kushwaha/react-native-gifted-charts#327]
![Screenshot_2023-06-22-10-52-11-51](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/101415426/8c7b55e7-5965-4a6e-92a4-3a3b1c9a9adc)

i want to adjust the below date how can i adjust it

**Comment by NikhilMasurkar** [comment]
in your library there is one 

renderAnimatedLabel please pass one prop to adjust label rotation or height or bottom that help us to handle label 


  const renderAnimatedLabel = (
    index: number,
    label: String,
    labelTextStyle: any,
    labelComponent: Function,
  ) => {
    // console.log('label', label);
    return (
      <Animated.View
        style={[
          {
            height: rotateLabel ? 40 : 20,
            // backgroundColor: 'yellow',
            position: 'absolute',
            bottom: rotateLabel ? 10 : 30,
            zIndex: 10,
            width: spacing,
            left:
              index === 0 && initialSpacing < 10
                ? initialSpacing + spacing * index - spacing / 2 + 8
                : initialSpacing + spacing * index - spacing / 2,
            opacity: appearingOpacity,
          },
          rotateLabel && {transform: [{rotate: '60deg'}]},
        ]}>
        {labelComponent ? (
          labelComponent()
        ) : (
          <Text
            style={labelTextStyle || {textAlign: 'center'}}
            numberOfLines={xAxisTextNumberOfLines}>
            {label || ''}
          </Text>
        )}
      </Animated.View>
    );
  };

**Comment by Abhinandan-Kushwaha** [comment]
Hi, @NikhilMasurkar Can you please share the code you have written to render the above graph? I think I can help you adjust the label position.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @NikhilMasurkar 👋
You can use the `xAxisLabelTextStyle` prop to give it desired width and margin. Pass a suitable value of marginLeft (possibly -ve) in the style object.

Here's an example-
<img width="346" alt="Screenshot 2023-09-17 at 11 30 22 AM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/87e9d556-30f9-4986-acdd-246df2218c83">

The code for the above chart is-
```js
const dd1= [1,2,3,4,5,6,7,8,9]
const dd2= [0.4,0.5,0.7,1.8,1.9,2,2,2,2]
const labels = ['Feb-23','Mar-23','Apr-23','May-23','Jun-23','Jul-23','Aug-23','Sep-23','Oct-23']

return <LineChart
  areaChart
  curved
  spacing={36}
  data={dd1.map((i,ind)=>{
    return {
      value:i,
      label:labels[ind]
    }
  })}
  data2={dd2.map(i=>{return{value:i}})}
  color1='orange'
  startFillColor1='#FBEDE1'
  dataPointsColor1='orange'
  dataPointsRadius={4}
  color2='blue'
  startFillColor2='#C7CFEA'
  hideRules
  thickness={3}
  showVerticalLines
  rotateLabel
  xAxisLabelTextStyle={{width:50}}
/>
```
