### ISSUE TITLE
Barchart X-Axis not spacing

### ISSUE THREAD

**Issue by josh-thompson13** [Abhinandan-Kushwaha/react-native-gifted-charts#338]
**Describe the bug**
My barchart is not spacing correctly.

**To Reproduce**

**Expected behavior**
I need the bars to space evenly with the x-axis labels

**Screenshots**
This is what is being rendered
![Screenshot 2023-07-11 at 3 42 34 pm](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/69380003/9e761319-79ad-4cdc-b90d-71074cc939d5)

 - Device: [e.g. iPad 10]

 - Version of the library being used [e.g. 1.2.42]

Here is my code:

<BarChart
                                            data={dataSets}
                                            yAxisLabelPrefix={def.atrPrefix}
                                            yAxisLabelSuffix={def.atrSuffix}
                                            xAxisColor={"#d3d3d3"}
                                            yAxisColor={"#d3d3d3"}
                                            minValue={minValue ?? findLowestValue(dataSets)}
                                            maxValue={maxValue ?? findHighestValue(dataSets)}
                                            width={chartWidth * 0.9}
                                        
                                            onPress={(event: {
                                                index: number;
                                                value: number | undefined;
                                            }) => tapMarker(event.index, event.value)}
                                        />

**Comment by ak-spotter** [comment]
Hi @josh-thompson13 
I assume the issue you are facing is- x axis labels are overlapping on each other due to less space.

Following are the possible solutions- 

1. One way to avoid overlapping of x axis lables is to rotate them using the `rotateLabel` prop.
2. Alternatively, you can use the `spacing` prop to give spacing between consecutive bars. e.g. `spacing={40}`
3. If neither of the above suits your use case, you can pass your own custom label component in the objects of data array using the `labelComponent` property

I hope it helps.

**Comment by josh-thompson13** [comment]
> I assume the issue you are facing is- x axis labels are overlapping on each other due to less space.

Hi @ak-spotter, thank you for taking the time to respond! I did consider adding spacing but nothing actually happened. I added spacing={1000} to really test but they all remained in the same spot. There must be a way to evenly space the bars depending on width right?

**Comment by Abhinandan-Kushwaha** [comment]
Strange @josh-thompson13 
Spacing works fine for me. Below is a snapshot from version `1.2.42`

<img width="553" alt="Screenshot 2023-07-12 at 4 17 23 PM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/66475c6a-5a09-4616-8bca-c310a3d5786e">

Here is the code I used-

```js
const chartWidth = 600;

return <BarChart
      data={[
        { value: 50, label: 'January' },
        { value: 63, label: 'February' },
        { value: 61, label: 'March' },
        { value: 67, label: 'April' },
        { value: 70, label: 'May' },
        { value: 100, label: 'June' },
        { value: 74, label: 'July' }
      ]}
      xAxisColor={"#d3d3d3"}
      yAxisColor={"#d3d3d3"}
      minValue={0 }
      maxValue={120 }
      width={chartWidth * 0.9}
      spacing={50}
      
        onPress={(event: {
            index: number;
            value: number | undefined;
        }) => console.log(event.index, event.value)}
    />;
```
Try upgrading to the latest version of react-native-gifted-charts
