### ISSUE TITLE
labelComponent should be optional

### ISSUE THREAD

**Issue by ThucTrieu** [Abhinandan-Kushwaha/react-native-gifted-charts#340]
**Describe the bug**
This bug occur when data object don't have labelComponent
<img width="786" alt="image" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/100109060/6e094fa8-0cd6-4007-96c8-f9b4a86b82ef">
<img width="1792" alt="image" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/100109060/c35f0533-1e3e-4565-9244-a3c55550af7b">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ThucTrieu 👋
Thanks for pointing out this issue.
I will fix this and other typescript errors this weekend.

Till then, as a workaround you can pass empty callback function as the `labelComponent` inside the data objects.

**Comment by Abhinandan-Kushwaha** [comment]
This has been fixed in the latest version of the library.
