### ISSUE TITLE
PointerLabelComponent not available for the last data points (x-axis)

### ISSUE THREAD

**Issue by sheryarkhan55** [Abhinandan-Kushwaha/react-native-gifted-charts#343]
**Describe the bug**
The tooltip works like a charm for all the data points in the Line Chart except the last ones. When you hold and scroll the tooltip to the right (to the end), the tooltip appears at max for the 3rd last data point. 

**To Reproduce**
1. Touch anywhere on the LineChart to initiate Tooltip.
2. Scroll to the right while holding the tooltip.
3. Notice how the tooltip appears at max for the 3rd last data point.
4. The last two data points are not accessible for tooltip.
5. The last two data points are plotted by the graph, but the tooltip cannot access them.

**Expected behavior**
Tooltip should be visible for all Data points.

**Screenshots**
![Simulator Screenshot - iPhone 14 Pro - 2023-07-18 at 12 20 46](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/113686383/3dc06d6a-6276-44fa-869d-faceba8c5837)

See how the Tooltip is only available for 10:00 pm. However, the data points plotted on the graph are until 12:00 am. If I further scroll my tooltip to see 11:00 and 12:00 am, it does not allow me to. 

 - Device: [all iPhone and Android phones]
 - OS: [No Specific requirement]
 - Version of the library being used [ ^1.2.42]

**Additional context**
I tried using the example provided by the library for PointerLabelComponent. However, I am facing the same issue with it. I think it is a generic bug in the library.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sheryarkhan55 👋
Thanks for pointing out the issue. Can you please share your code? It will help me in debugging.

**Comment by sheryarkhan55** [comment]
Hello @Abhinandan-Kushwaha, Thank you very much for your response. Below is the sample code for the LineChart with Tooltip. Notice how the tooltip only appears until the second last hour. 

import React from "react";
import { StyleSheet, Text, View, Dimensions } from "react-native";
import { LineChart } from "react-native-gifted-charts";

const Graph = () => {

	var data1: any = [
		{ time: '12:00', value: 10, label: '00:00', labelTextStyle: { width: 40, fontSize: 10, } },
		{ time: '01:00', value: 12, },
		{ time: '02:00', value: 40, },
		{ time: '03:00', value: 50, },
		{ time: '04:00', value: 50, },
		{ time: '05:00', value: 70, label: '05:00', labelTextStyle: { width: 40, fontSize: 10, } },
		{ time: '06:00', value: 90, },
		{ time: '07:00', value: 100 },
		{ time: '08:00', value: 100 },
		{ time: '09:00', value: 110 },
		{ time: '10:00', value: 120, label: '10:00', labelTextStyle: { width: 40, fontSize: 10, } },
		{ time: '11:00', value: 130 },
		{ time: '12:00', value: 140 },
		{ time: '13:00', value: 140 },
		{ time: '14:00', value: 145, label: '02:00', labelTextStyle: { width: 40, fontSize: 10, } },
		{ time: '15:00', value: 150 },
		{ time: '16:00', value: 150 },
		{ time: '17:00', value: 150 },
		{ time: '18:00', value: 165, label: '06:00', labelTextStyle: { width: 40, fontSize: 10, } },
		{ time: '19:00', value: 168 },
		{ time: '20:00', value: 175 },
		{ time: '21:00', value: 180 },
		{ time: '22:00', value: 185 },
		{ time: '23:00', value: 190, label: '11:00', labelTextStyle: { width: 40, fontSize: 10, } }
	]

	return (
		<View style={{ flex: 1, justifyContent: 'center' }}>
			<LineChart
				areaChart
				data={data1}
				height={220}
				key={Math.random()}
				width={Dimensions.get('window').width * 0.74}
				hideDataPoints
				spacing={13}
				adjustToWidth={true}
				color={'#001441'}
				thickness={2}
				startFillColor={'#001441'}
				endFillColor={'#001441'}
				startOpacity={1}
				endOpacity={1}
				initialSpacing={0}
				yAxisColor={'#e9ebee'}
				yAxisThickness={0}
				rulesType="solid"
				rulesColor={'#e9ebee'}
				yAxisTextStyle={styles.yAxisTextStyle}
				yAxisTextNumberOfLines={2}
				isAnimated={true}
				animateTogether={true}
				animationDuration={700}
				xAxisColor="lightgray"
				pointerConfig={{
					pointerStripHeight: 120,
					pointerStripColor: "white",
					pointerStripWidth: 2,
					pointerColor: "white",
					radius: 3,
					pointerLabelWidth: 100,
					pointerLabelHeight: 90,
					autoAdjustPointerLabelPosition: false,
					pointerLabelComponent: (items) => {
						return (
							<View style={styles.toolTipContainer}>
								<View style={styles.toolTipSubContainer}>
									<Text style={[styles.graphPointerLabel, { color: '#677387' }]}>
										{"time"}: {items[0].time}
									</Text>
									<Text style={[styles.graphPointerLabel, { color: '#677387' }]}>
										{"value"}: {items[0].value}
									</Text>
								</View>
							</View>
						);
					},
				}}
			/>
		</View>
	)
}

const styles = StyleSheet.create({
	yAxisTextStyle: {
		fontSize: 10,
		color: "gray",
	},
	toolTipContainer: {
		height: 70,
		width: 180,
		paddingHorizontal: 5,
		marginTop: -80,
		marginLeft: -50
	},
	toolTipSubContainer: {
		borderWidth: 1,
		borderRadius: 3,
		borderColor: '#e9ebee',
		backgroundColor: 'white',
		marginRight: 25,
		padding: 5
	},
	graphPointerLabel: {
		color: 'black',
		fontSize: 12,
	},
})

export default Graph;

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sheryarkhan55 👋
Sorry for the late reply. And thanks for pointing out the bug.

I will fix it in the next update which will be released within 2-3 days.

**Comment by sheryarkhan55** [comment]
Hello @Abhinandan-Kushwaha, Thank you for the solution. This actually helps accessing the last index of the graph. However, the very first index, which is 0, can still not be accessed. Even if you add some value to the first element, it is not accessible for the tooltip.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sheryarkhan55 
I will fix it in the next release.

Till then, you can try giving `initialSpacing` some value other than 0, like `initialSpacing={5}`

**Comment by sheryarkhan55** [comment]
Hello @Abhinandan-Kushwaha, thank you very much.
The initial spacing does not help accessing the first element. Waiting for the next release. :)

**Comment by Abhinandan-Kushwaha** [comment]
Can you try with `initialSpacing={10}`?

**Comment by sheryarkhan55** [comment]
@Abhinandan-Kushwaha setting initialSpacing to 10 has actually solved the issue for me. Thank you so much for your help. :)
