### ISSUE TITLE
 ERROR  Invariant Violation: Tried to register two views with the same name RNSVGCircle, js engine: hermes

### ISSUE THREAD

**Issue by anilsmaitic01** [Abhinandan-Kushwaha/react-native-gifted-charts#345]
I am using React Native v0.72.3 with "react-native-svg" and this package. The latest in "react-native-svg" is 13.10.0 however this package relies on 13.9.0. I tried downgrading my "react-native-svg" package to match the version however no any help. Can you explain how can I solve this issue? My app keep on crashing with the same error message: " ERROR  Invariant Violation: Tried to register two views with the same name RNSVGCircle, js engine: hermes"

**Expected behavior**
To work seemlesly

 - Device: iPhone Simulator 14 pro max
 - OS: MacOS M1, Ventura 13.4.1
 - Version of the library being used [e.g. 1.3.2]

**Comment by charlieStrikeBright** [comment]
I am having the same issue with android builds, but working OK on iOS builds.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @anilsmaitic01 @charlieStrikeBright 
This was perhaps due to version conflicts in react-native-svg. We have now moved both react-native-svg and react-native-linear-gradient to peer dependencies. Please try the latest version of the library.
