### ISSUE TITLE
Bar Chart scroll to specific position

### ISSUE THREAD

**Issue by anhnq0212** [Abhinandan-Kushwaha/react-native-gifted-charts#347]
Hi, I'm working with Horizontal StackedBarChart. Is there any way to scroll horizontal to a specific position base on data index

For example, I have data base on each day in a moth, how can I scroll to current date ?

Looking forward to your reply. Thank you so much

**Comment by Abhinandan-Kushwaha** [comment]
Hi @anhnq0212 
Thanks for requesting the feature. We have added 2 new props- `scrollRef` and `scrollToIndex`

**scrollRef**
In Bar, Line and Area charts, we can access the ScrollView using the scrollRef prop. You just need to create a ref using React.useRef() and pass it into the scrollRef prop. The most common use of scrollRef is to scroll to a given position, and to fire the scroll on an event like a button press.

**scrollToIndex**
In Bar, Line and Area charts, we can scroll to any given index using the scrollToIndex prop.

Please use the latest version of the library.
