### ISSUE TITLE
Barchart with LineData incorrect.

### ISSUE THREAD

**Issue by DannyBloky** [Abhinandan-Kushwaha/react-native-gifted-charts#348]
The lineData is incorrect in the Barchart. It doesn't confirm my data set that I"m using.
As you can see in the screenshot the same data set is used but the line data is above the bars.

**To Reproduce**
Here the example code that I used:

`  const barData = [
    { value: 250, label: 'M' },
    { value: 500, label: 'T' },
    { value: 745, label: 'W' },
    { value: 320, label: 'T' },
    { value: 600, label: 'F', frontColor: '#177AD5' },
    { value: 256, label: 'S' },
    { value: 0, label: 'S' }
  ]
  
  <BarChart
              barWidth={14}
              barBorderRadius={4}
              noOfSections={3}
              maxValue={750}
              stepValue={750}
              height={238}
              yAxisLabelTexts={['0', '5km', '10km', '15km']}
              frontColor={themeColors['tint']}
              data={barData}
              yAxisThickness={0}
              xAxisThickness={1}
              isAnimated={true} 
              hideRules={true} 
              hideYAxisText={false} 
              lineData={barData} 
              roundedTop={true}
              showLine={true}
              spacing={28}
              lineConfig={{
                color: 'black',
                thickness: 1,
                curved: true,
                isAnimated: true,
                delay: 10,
                hideDataPoints: true,
              }}
              xAxisLabelTextStyle={{
                color: themeColors['text-primary'],
                fontSize: graphTextX,
                textAlign: 'center'
              }} // text X style
            />
  `
  
  Just to clarify. The themeColors['text-primary'] is just a color

The result should be that the lines are at the same point as the Bar. And not above it.
![Screenshot 2023-07-28 at 14 03 39](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/42135253/19c657ed-931e-4f13-a406-e00bc874a2c8)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @DannyBloky 
This has been fixed in the latest version of the library. Please update to the latest version.
