### ISSUE TITLE
[Help] BarChart renderTooltip not working when using lineData true

### ISSUE THREAD

**Issue by DannyBloky** [Abhinandan-Kushwaha/react-native-gifted-charts#349]
The using the BarChart with lineData the click event is not triggered.

Is there a way to use the renderTooltip with lineData.
Or can it only be used when not using lineData

**Comment by Abhinandan-Kushwaha** [comment]
Hi @DannyBloky 👋
While using `lineData` in the Bar chart, we need to pass the prop `lineBehindBars` if we want the bars to be clickable.

Here is an example Bar chart with line chart and renderTooltip-
 
![tooltip](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/4c769f88-c10e-44b6-8f2f-933a5ed24496)

The code for above chart is-
```js
const App = () => {
  const data = [
    {value: 120},
    {value: 80},
    {value: 60},
    {value: 70},
    {value: 80},
    {value: 90},
  ];

  return (
    <BarChart
      data={data}
      showLine
      lineBehindBars
      renderTooltip={item => (
        <View
          style={{
            backgroundColor: 'green',
            borderRadius: 6,
            paddingHorizontal: 8,
            paddingVertical: 4,
            marginBottom: 4,
          }}>
          <Text style={{color: 'white'}}>{item.value}</Text>
        </View>
      )}
    />
  );
}
```
