### ISSUE TITLE
[Help] BarChart xAsisLabel not center

### ISSUE THREAD

**Issue by DannyBloky** [Abhinandan-Kushwaha/react-native-gifted-charts#350]
It now looks like the text is not center on the Bar.
Als je can see it a slightly to the right of the center of the bar.

In the code I set my textAlign to center:

` xAxisLabelTextStyle={{
                color: '#162130',
                fontSize: 16,
                textAlign: 'center'
              }}`
              
 Do I need to center the Bar on some way. Or is there a other way to do this.

![Screenshot 2023-07-28 at 14 03 39](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/42135253/9c7ddd7f-8127-46cd-879e-fcf2be83212c)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @DannyBloky 👋
This issue is addressed in the version `1.3.3` which will be released soon. 🎉

**_Till then you can try a workaround_**- add the property `labelTextStyle` to the objects in the data array.

For example-
```js
const data = [
    {value: 250, label: 'M', labelTextStyle: {marginRight: 4}},
    {value: 500, label: 'T'. labelTextStyle: {marginRight: 4}},
    {value: 745, label: 'W', labelTextStyle: {marginRight: 4}},
    {value: 320, label: 'T', labelTextStyle: {marginRight: 4}},
    {value: 600, label: 'F', frontColor: '#177AD5', labelTextStyle: {marginRight: 4}},
    {value: 256, label: 'S', labelTextStyle: {marginRight: 4}},
  ];
```
