### ISSUE TITLE
how can I add the legends notation for the y axis and x axis after labels? 

### ISSUE THREAD

**Issue by NikhilMasurkar** [Abhinandan-Kushwaha/react-native-gifted-charts#351]

**Comment by Abhinandan-Kushwaha** [comment]
We don't have in-built legend components for any chart in the library. However, it's pretty easy to make your own custom legend component.

I have shared an example of a custom legend [here](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/64)

Reasons why we don't provide legends-
1. Legends are highly customisable. Every designer may suggest a different style of legend.
2. Legends are simple components easy to make.
3. Legends can be positioned anywhere in or around the chart.


Hence it is better if the developers write the code for legends by themselves and position it wherever needed.
