### ISSUE TITLE
Horizontal Bar chart data is distorted on positive values

### ISSUE THREAD

**Issue by raazatul7** [Abhinandan-Kushwaha/react-native-gifted-charts#352]
**Describe the bug**
Horizontal Bar chart data is distorted on positive values, for mixed and negative values it's working fine.

**Expected behavior**
My Props -
`<BarChart
          autoShiftLabels={true}
          barWidth={10}
          horizontal={true}
          roundedTop={true}
          width={360}
          initialSpacing={20}
          disableScroll={true}
          spacing={50}
          hideRules={true}
          xAxisLength={Dimensions.get("window").width}
          xAxisColor={Colors.infoBase.gray}
          data={formatBarchartData()}
          // data={barData}
          yAxisLabelContainerStyle={{ width: 0 }}
          yAxisThickness={0}
          xAxisThickness={2}
        />`
Data -
`const barData = [
    {
      value: 5.6 / 2,
      frontColor: Colors.base.primaryText,
      labelComponent: () => <Label labelValue={5} labelText={"My Portfolio"} />,
    },
    {
      value: 12.6 / 2,
      frontColor: Colors.errorBase.primary,
      labelComponent: () => <Label labelValue={1} labelText={"Sensex"} />,
    },
    {
      value: 6 / 2,
      frontColor: Colors.brandBase[300],
      labelComponent: () => <Label labelValue={6} labelText={"Nifty"} />,
    },
    {
      value: 5.6 / 2,
      frontColor: Colors.brandBase[300],
      labelComponent: () => <Label labelValue={5.6} labelText={"SAP 500"} />,
    },
    {
      value: 12.6 / 2,
      frontColor: Colors.errorBase.primary,
      labelComponent: () => <Label labelValue={12.6} labelText={"NASDAQ"} />,
    },
    {
      value: 5.6 / 2,
      frontColor: Colors.brandBase[300],
      labelComponent: () => <Label labelValue={5.6} labelText={"SAP 500"} />,
    },
  ];`
  ` const formatBarchartData = () => {
    let data = barChartData?.map((item: IBarDataProps, index: number) => {
      let updatedObject = {
        value: item?.Value * 100 || 0,
        frontColor: item?.Value < 0 ? Colors.errorBase.primary : Colors.brandBase[300],
        labelComponent: () => <Label labelValue={item?.Value || 0} labelText={item?.Name} />,
      }
      return updatedObject;
    })

    let myPortfolioObj = {
      value: myStocksTGainPct && myStocksTGainPct * 100 || 0,
      frontColor: Colors.base.primaryText,
      labelComponent: () => <Label labelValue={myStocksTGainPct && myStocksTGainPct || 0} labelText={'My Portfolio'} labelTextstyle={{ fontFamily: Fonts.Medium }} />,
    }
    data?.unshift(myPortfolioObj)
    return data || []
  }`
  
  
**Screenshots**
Expected for positive values -
![Simulator Screenshot - iPhone 14 - 2023-08-02 at 11 58 47](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/29301407/e7fc2ae0-253d-4bb9-999d-da48ff0cccaa)
Issue - 
![Simulator Screenshot - iPhone 14 - 2023-08-02 at 11 58 59](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/29301407/5f46c7ac-205c-42f7-ae63-5e942dffcd0c)

 - Device: [iPhone14]
 - OS: [iOS16.3]
 - Version of the library being used [1.2.42]

**Comment by Abhinandan-Kushwaha** [comment]
Hi @raazatul7 
 It has been fixed now. Please use the latest version of the library.
If the issue persists, you can use the shiftX and shiftY props to adjust the position of the horizontal chart.
