### ISSUE TITLE
Line Chart not showing all X-axis label.

### ISSUE THREAD

**Issue by prakashawal** [Abhinandan-Kushwaha/react-native-gifted-charts#353]
Here my data is
const newData = [
    {value: 80, label: 'MON'},
    {value: 90, label: 'WED'},
    {value: 55, label: 'THU'},
    {value: 50, label: 'SAT'}
  ];

and the Line chart is as below
    <LineChart
                data={newData}
                xAxisLabelTexts={['SUN',  'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT']}
                showXAxisIndices={true}
              />

### With the code above it looks like this now.
<img width="300" alt="Screenshot 2023-08-03 at 9 55 50 AM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/132885516/ff3b284d-437f-432f-b541-507494b3c93f">

### Problem
In my data, there is no label for 'TUE', as there is no value for it. and the graph is missing the TUE axis label.  Can you guide me how to implement like the below graph.

### What I needed 
<img width="532" alt="Screenshot 2023-08-03 at 9 47 47 AM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/132885516/ee2e1fac-6f7f-44e2-887b-c298e4ab48a6">

**Comment by parasfusemachine** [comment]
Same here!

**Comment by Abhinandan-Kushwaha** [comment]
Hi @prakashawal 👋
To render the above chart we can add the `hideDataPoint` property to those data objects for which we don't want to show the dataPoint.
Also, if your data array has values only for SUN, MON and FRI, you must interpolate the values for TUE, WED and THU. Since we know the values for MON and FRI, we can calculate the values for the remaining days in between using this function-

```js
const getValue = (initialValue, finalValue, index, count) => {
    const step = (finalValue - initialValue) / count;
    return initialValue + step * index;
};
```
Below is the complete code-
```js
const App = () => {
  const getValue = (initialValue, finalValue, index, count) => {
    const step = (finalValue - initialValue) / count;
    return initialValue + step * index;
  };

  const newData = [
    {value: 120, label: 'SUN'},
    {value: 80, label: 'MON'},
    {value: getValue(80, 90, 1, 4), label: 'TUE', hideDataPoint: true},
    {value: getValue(80, 90, 2, 4), label: 'WED', hideDataPoint: true},
    {value: getValue(80, 90, 3, 4), label: 'THU', hideDataPoint: true},
    {value: 90, label: 'FRI'},
  ];

  return (
    <LineChart
      data={newData}
      dataPointsRadius={10}
      color="#B4FFCE"
      dataPointsColor="#35B074"
      thickness={4}
      hideRules
      showVerticalLines
      showReferenceLine1
      referenceLine1Position={100}
      referenceLine1Config={{color: 'gray'}}
      maxValue={160}
      stepValue={20}
      noOfSections={8}
      yAxisColor={'gray'}
    />
  );
}
```

The output of this code is-

<img width="315" alt="Screenshot 2023-08-05 at 4 38 12 AM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/dc30c398-e531-4bc3-81b7-6e6822bfc701">

**Comment by Abhinandan-Kushwaha** [comment]
Hi Audun Hilden,  This is how you can interpolate the line for null values.

**Comment by audn** [comment]
> Hi Audun Hilden,  This is how you can interpolate the line for null values.

Awesome, thanks!

**Comment by Abhinandan-Kushwaha** [comment]
Hi @audn @prakashawal @parasfusemachine 

The library now supports interpolation by default from version `1.4.3` onwards. You can pass null or undefined values to data items for which you don't have values.

Here is an example-
```js
const ddataa = [
  {value: 10, label: 'S'},
  {value: 15, label: 'M'},
  {value: null, label: 'T'},
  {value: null, label: 'W'},
  {value: 20, label: 'T'},
  {value: 15, label: 'F'},
  {value: 10, label: 'S'},
];

return <LineChart data={ddataa} />;
```
The output is-

<img width="353" alt="Screenshot 2024-01-27 at 10 27 30 PM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/fde60534-8282-4089-a16a-a554b96607de">

Notice that we don't see data points for Tuesday and Wednesday, because we passed null values for them. The library auto-computes nullish values, but hides data points for them. To show data points for such values, use the `showDataPointsForMissingValues` prop.

If you don't want the library to auto-compute nullish values, instead break the line for nullish values, set the prop `interpolateMissingValues` to false.

Here's the same chart with `showDataPointsForMissingValues={false}`-

<img width="357" alt="Screenshot 2024-01-27 at 10 32 10 PM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/1c4cbaa6-d289-4707-b042-a077d674b012">

See [Interpolation in Line chart docs](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/LineChart/LineChartProps.md#interpolation)

**Comment by mahisaajy** [comment]
> Hi @audn @prakashawal @parasfusemachine
> 
> The library now supports interpolation by default from version `1.4.3` onwards. You can pass null or undefined values to data items for which you don't have values.
> 
> Here is an example-
> 
> ```js
> const ddataa = [
>   {value: 10, label: 'S'},
>   {value: 15, label: 'M'},
>   {value: null, label: 'T'},
>   {value: null, label: 'W'},
>   {value: 20, label: 'T'},
>   {value: 15, label: 'F'},
>   {value: 10, label: 'S'},
> ];
> 
> return <LineChart data={ddataa} />;
> ```
> 
> The output is-
> 
> <img alt="Screenshot 2024-01-27 at 10 27 30 PM" width="353" src="https://private-user-images.githubusercontent.com/20596944/300192559-fde60534-8282-4089-a16a-a554b96607de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjQ0MjMsIm5iZiI6MTcxMzE2NDEyMywicGF0aCI6Ii8yMDU5Njk0NC8zMDAxOTI1NTktZmRlNjA1MzQtODI4Mi00MDg5LWExNmEtYTU1NGI5NjYwN2RlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA2NTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MTg4MWVmMzNkMTg3N2JhZjcwODRmNzc1YzU2NDM2ZDM2ZGJmMDEwZjdmNGE3MmVmMjNjMDMzY2M5NzlmNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bnEwejVe0S5dO-ABPE44RYqwv2Mw_Tkqe4TObWVvzRw">
> Notice that we don't see data points for Tuesday and Wednesday, because we passed null values for them. The library auto-computes nullish values, but hides data points for them. To show data points for such values, use the `showDataPointsForMissingValues` prop.
> 
> If you don't want the library to auto-compute nullish values, instead break the line for nullish values, set the prop `interpolateMissingValues` to false.
> 
> Here's the same chart with `showDataPointsForMissingValues={false}`-
> 
> <img alt="Screenshot 2024-01-27 at 10 32 10 PM" width="357" src="https://private-user-images.githubusercontent.com/20596944/300192964-1c4cbaa6-d289-4707-b042-a077d674b012.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjQ0MjMsIm5iZiI6MTcxMzE2NDEyMywicGF0aCI6Ii8yMDU5Njk0NC8zMDAxOTI5NjQtMWM0Y2JhYTYtZDI4OS00NzA3LWIwNDItYTA3N2Q2NzRiMDEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA2NTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMTQ1YTAxMDJiNzNmYmY4MGU5ZjI3MjRlYmM5OGVmNTk5ZTYwMDVmZGJmYmMyYjM4ZDA4MjA4MzdiMWNlMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7HnwqhIysvq1dn46VQdwy_YcDnHfJq9bjQOKCfRElto">
> See [Interpolation in Line chart docs](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/LineChart/LineChartProps.md#interpolation)

awesome

**Comment by mahisaajy** [comment]
AWESOME

**Comment by noahkurz** [comment]
> Hi @audn @prakashawal @parasfusemachine
> 
> The library now supports interpolation by default from version `1.4.3` onwards. You can pass null or undefined values to data items for which you don't have values.
> 
> Here is an example-
> 
> ```js
> const ddataa = [
>   {value: 10, label: 'S'},
>   {value: 15, label: 'M'},
>   {value: null, label: 'T'},
>   {value: null, label: 'W'},
>   {value: 20, label: 'T'},
>   {value: 15, label: 'F'},
>   {value: 10, label: 'S'},
> ];
> 
> return <LineChart data={ddataa} />;
> ```
> 
> The output is-
> 
> <img alt="Screenshot 2024-01-27 at 10 27 30 PM" width="353" src="https://private-user-images.githubusercontent.com/20596944/300192559-fde60534-8282-4089-a16a-a554b96607de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0OTA4NDgsIm5iZiI6MTcyNjQ5MDU0OCwicGF0aCI6Ii8yMDU5Njk0NC8zMDAxOTI1NTktZmRlNjA1MzQtODI4Mi00MDg5LWExNmEtYTU1NGI5NjYwN2RlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDEyNDIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMTBhZTBhMDdmOWE4OTA3MTAzY2YzMGYyYmUzZTk4MDhkY2M3NDEyNzgyNjIwODNlMGQ4ZTg4ZGFkNzczMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3iV2ofUxX3GCqsPrxe9wFmz3OcQKCRjaTY5NkYUCx7g">
> Notice that we don't see data points for Tuesday and Wednesday, because we passed null values for them. The library auto-computes nullish values, but hides data points for them. To show data points for such values, use the `showDataPointsForMissingValues` prop.
> 
> If you don't want the library to auto-compute nullish values, instead break the line for nullish values, set the prop `interpolateMissingValues` to false.
> 
> Here's the same chart with `showDataPointsForMissingValues={false}`-
> 
> <img alt="Screenshot 2024-01-27 at 10 32 10 PM" width="357" src="https://private-user-images.githubusercontent.com/20596944/300192964-1c4cbaa6-d289-4707-b042-a077d674b012.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0OTA4NDgsIm5iZiI6MTcyNjQ5MDU0OCwicGF0aCI6Ii8yMDU5Njk0NC8zMDAxOTI5NjQtMWM0Y2JhYTYtZDI4OS00NzA3LWIwNDItYTA3N2Q2NzRiMDEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDEyNDIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNDdhMzgyZjMzN2YxMWQ0ZWU5OTRlNzY1N2IyNDljYmUzMzU4ODZmZTIxMDAwOWUxMDQ0Yzg5NGI3OWNmNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w8QPrdpOSd1j_WUpaCwznVonmL7dftJDehoAPsoe8Kc">
> See [Interpolation in Line chart docs](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/LineChart/LineChartProps.md#interpolation)

Im getting a type error when value is null or undefined. Is that expected?

**Comment by Abhinandan-Kushwaha** [comment]
Yes, the type error exists but the result will be as expected
