### ISSUE TITLE
Error: AnimatedValue: Attempting to set value to undefined

### ISSUE THREAD

**Issue by nubwang** [Abhinandan-Kushwaha/react-native-gifted-charts#355]
Error: AnimatedValue: Attempting to set value to undefined

<LineChart 
                                                    data={item.values} 
                                                    noOfSections={5}
                                                    stepValue={2}
                                                    maxValue={10}
                                                    shadowWidth={5} 
                                                    tiltAngle={20}
                                                    xAxisColor={'rgba(0,0,0,.5)'}
                                                    yAxisColor={'rgba(0,0,0,.5)'}
                                                    yAxisTextStyle={{fontSize: 6,color: '#666',marginLeft: 15}}
                                                    xAxisLabelTextStyle={{fontSize: 1,color: '#fff',lineHeight: 16}}
                                                    xAxisLength={windowWidth-80}
                                                    horizontalRulesStyle={{marginTop: 0}}
                                                    curved={true}
                                                    showScrollIndicator={true}
                                                    color={'#3498db'}
                                                    hideDataPoints={true}
                                                    endSpacing={10}
                                                    initialSpacing={20}
                                                    spacing={(windowWidth-80)/item.values.length}
                                                    hideRules={true}
                                                    // onFocus={onFocusLine}
                                                    
                                                    // onPress={onPressLine}
                                                    pointerConfig={{
                                                        pressEnabled: true,
                                                        pointerStripHeight: 150,
                                                        pointerStripColor: '#3498db',
                                                        pointerStripWidth: 0.5,
                                                        pointerColor: '#3498db',
                                                        // radius: 6,
                                                        // pointerLabelWidth: 100,
                                                        // pointerLabelHeight: 90,
                                                        // activatePointersOnLongPress: true,
                                                        // pointerStripUptoDataPoint: true,
                                                        showTextOnFocus: true,
                                                        showStripOnFocus: true,
                                                        showDataPointOnFocus: true,
                                                        autoAdjustPointerLabelPosition: false,
                                                        unFocusOnPressOut: false,
                                                        pointerLabelComponent: items => {
                                                            console.log(items,'items')
                                                          return (
                                                            <View style={{width: 100,padding: 10,backgroundColor: 'rgba(0,0,0,0.4)',borderRadius: 5,marginLeft: -50 }}>
                                                                <View style={{flexDirection: 'row'}}>
                                                                    <Text style={{fontSize: 10,lineHeight: 15,color: '#fff',fontFamily: 'Montserrat-Medium'}}>label: </Text>
                                                                    <Text style={{fontSize: 10,lineHeight: 15,color: '#fff',fontFamily: 'Montserrat-Medium'}}>{items[0].label}</Text>
                                                                </View>
                                                                <View style={{ flexDirection: 'row'}}>
                                                                    <Text style={{fontSize: 10,lineHeight: 15,color: '#fff',fontFamily: 'Montserrat-Medium'}}>value: </Text>
                                                                    <Text style={{fontSize: 10,lineHeight: 15,color: '#fff',fontFamily: 'Montserrat-Medium'}}>{items[0].value}</Text>
                                                                </View>
                                                            </View>
                                                          );
                                                        },
                                                      }}
                                                    ></LineChart>

**Comment by Abhinandan-Kushwaha** [comment]
Hi @BanidAzin 
Can you please share the code here?

**Comment by carter-0** [comment]
I was facing the same issue, it turned out to be a problem with the data I was passing to the data prop of the LineChart component. Using the example data `[{value: 15}, {value: 30}, {value: 26}, {value: 40}]` from the docs worked fine.

Turns out the problem was that I was passing strings as the value (like `[{"value": "5"}]`) rather than numbers (like `[{"value": 5}]`).
