### ISSUE TITLE
Line chart pointer strip - 1. add background to entire pointer strip  2. Dont want to remove the pointer view if release touch for last touched

### ISSUE THREAD

**Issue by poonamdhomane** [Abhinandan-Kushwaha/react-native-gifted-charts#356]
<img width="333" alt="Screenshot 2023-08-07 at 2 02 44 PM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/2657399/e55453bc-2ba3-4ba1-b292-560cc8ffbdee">

1. as shown in screenshot can we make the blue bar with the same height of dotted line .
2. Can we make the blue line with dotted line visible (last shown) even if we remove touch from the screen

This two points required in my project. 

currentlt I have used below code to show the blue bar 

` pointerComponent:items => (
            <View style={ {
              backgroundColor: 'blue',opacity:'0.4', width:30, height:300, marginLeft:-10 ,
            } } />
          ),`

 - Version of the library being used - latest

**Comment by Abhinandan-Kushwaha** [comment]
Hi @poonamdhomane 👋
I think your requirement can be fulfilled using the `focusEnabled` and `showStripOnFocus` props, and disabling `unFocusOnPressOut`

```js
focusEnabled
showStripOnFocus
stripWidth={30}
stripColor={'blue'}
stripHeight={300}
unFocusOnPressOut={false}
```
The output now is-

<img width="365" alt="Screenshot 2023-08-26 at 5 14 44 PM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/f9778d6c-8107-4178-b77e-9d9fb932dc8a">

 And also, the strip is visible even if we remove touch from the screen.
 
 If this doesn't fulfil your requirement, feel free to post here.
