### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNSVGSvgViewAndroid" was not found in the UIManager.

### ISSUE THREAD

**Issue by eatanga-git** [Abhinandan-Kushwaha/react-native-gifted-charts#359]
This error pops up when using the latest version of this library. (I am using expo dev-client)

I tried using a simple chart as outlined in the tutorial
 
    `import { LineChart } from "react-native-gifted-charts";

    const App = () => {
    const data = [{value: 15}, {value: 30}, {value: 26}, {value: 40}];
    return <LineChart areaChart data={data}/>;
    };`
 

**Expected behavior**
I expect the chart to simply show up normally.

**Screenshots** 
![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/55466881/ba7628df-f739-4cf9-9bcb-e3cb281d3335)

Running on an android, with expo dev-client:
"expo-dev-client": "~2.0.1",
"expo": "^49.0.7",
"react-native-gifted-charts": "^1.3.2",
"react-native-svg": "13.9.0",

I have been stuck with this issue for MONTHS. I still cannot figure it out. I've tried everything - downgrading react-native-svg, downgrading the react-native-gifted-charts library, downgrading and upgrading expo, removing node modules, removing package-lock.json, using expo start -c , etc. Nothing seems to work and it's demoralizing.

**Comment by Rayne182** [comment]
I am facing the exact same issue (also react native expo)

**Comment by eatanga-git** [comment]
> I am facing the exact same issue (also react native expo)
> 
> `"expo": "^48.0.7", ` `"react-native-linear-gradient": "^2.7.3", ` `"react-native-svg": "^13.9.0"`
> 
> Edit: I have tried the downgrades recommended [here](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/263). No luck, so just going to try other libraries. Such a shame, because aesthetically this library is exactly what I was hoping to use.

For some reason I have similar issues with other libraries.

**Comment by Abhinandan-Kushwaha** [comment]
@Rayne182 @eatanga-git I am working on making this library compatible with expo. The next release will have this fix.

**Comment by eatanga-git** [comment]
> @Rayne182 @eatanga-git I am working on making this library compatible with expo. The next release will have this fix.

Alright, thank you

**Comment by alexkhazzam** [comment]
works fine with expo iOS, but I encounter the same issue when running on android emulator. Please fix this! Your library is awesome. When can the release be expected?

**Comment by Abhinandan-Kushwaha** [comment]
The next release is expected within 1-2 weeks

**Comment by alexkhazzam** [comment]
Ok, great thanks.

**Comment by Abhinandan-Kushwaha** [comment]
Hi guys, I tried using the library in my expo go project and it's working fine. Let's connect over google meet or zoom to discuss the issue you are facing. Drop a comment here when you are available @eatanga-git  @Rayne182 @alexkhazzam

**Comment by eatanga-git** [comment]
> Hi guys, I tried using the library in my expo go project and it's working fine. Let's connect over google meet or zoom to discuss the issue you are facing. Drop a comment here when you are available @eatanga-git @Rayne182 @alexkhazzam

I have issues using it with _Expo Dev-Client_, on Expo versions 47, 48, etc.

**Comment by Abhinandan-Kushwaha** [comment]
The library used to break when used in an expo project. This was perhaps due to version conflicts in `react-native-svg`. We have now moved both `react-native-svg` and r`eact-native-linear-gradient` to peer dependencies. This should hopefully fix the issues with expo.🎉

Please try the latest version of the library.
