### ISSUE TITLE
When I add the Horizontal prop to a bar chart the chart goes out of the container

### ISSUE THREAD

**Issue by Intelebee1234** [Abhinandan-Kushwaha/react-native-gifted-charts#361]
**Describe the bug**
When I add the Horizontal prop to a bar chart the chart goes out of the container

**To Reproduce**
import React, {useContext, useEffect, useState} from 'react';
import {
  Dimensions,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import {BarChart} from 'react-native-gifted-charts';
import {ThemeContext} from '../../App';
import {theme} from '../constants/constants';
import {Dropdown} from '../components/DropDownStore';

const SalesAnalysisByProductCatScreen = () => {
  const {isDarkMode} = useContext(ThemeContext);
  const styles = isDarkMode ? darkTheme : lightTheme;
  const [selectedStore, setSelectedStore] = useState();
  const [reRender, setReRender] = useState(false);

  const screenWidth = Dimensions.get('window').width;

  const [orientation, setOrientation] = useState('portrait');

  const handleOrientationChange = () => {
    const newWidth = Dimensions.get('window').width;
    const newHeight = Dimensions.get('window').height;

    if (newWidth < newHeight) {
      setOrientation('portrait');
    } else {
      setOrientation('landscape');
    }
  };

  useEffect(() => {
    handleOrientationChange();
  }, []);

  useEffect(() => {
    Dimensions.addEventListener('change', handleOrientationChange);

    return () => {
      // Dimensions.removeEventListener('change', handleOrientationChange);
    };
  }, []);

  useEffect(() => {
    setReRender(!reRender);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [orientation]);

  const dataInfo = [
    {
      label: "Portillo's and Lou Malmati's Party Package",
      value: 821,
    },
    {label: "4 Lou Malnati's Deep Dish Pizzas", value: 544},
    {label: "2 Lou Malnati's Deep Dish Pizzas", value: 449},
    {label: "Portillo's Italian Beef Kit & 2 Lou's Pizzas", value: 406},
    {label: "1 Lou's Pizza", value: 340},
    {label: 'Wildfire Prime Rib Dinner Kit', value: 302},
    {label: "1 Lou's Pizza", value: 340},
    {label: 'Wildfire Prime Rib Dinner Kit', value: 302},
    {label: "4 Gibsons 14oz. GGA New York Strips & 2 Lou's Pizzas", value: 277},
    {
      label: "6 Lou Malnati's Deep Dish Pizzas",
      value: 264,
    },
  ];

  const TopLabelComponent = ({item}) => {
    return (
      <Text
        style={{
          left: getLabelPosition(item.value),
          width: 600,
          fontSize: 24,
          fontWeight: '400',
          color: isDarkMode ? 'white' : 'black',
        }}>
        {item.label}
      </Text>
    );
  };

  const LabelComponent = ({item}) => {
    return (
      <Text
        style={{
          fontSize: 16,
          fontWeight: '400',
          color: isDarkMode ? 'white' : 'black',
        }}>
        $ {item.value}
      </Text>
    );
  };

  const getLabelPosition = value => {
    if (value > 800) {
      return -100;
    }
    if (value > 500) {
      return 0;
    }
    return 150;
  };

  const data = dataInfo.map(item => ({
    ...item,
    frontColor: '#12b2f4',
    topLabelComponent: () => <TopLabelComponent item={item} />,
    labelComponent: () => <LabelComponent item={item} />,
  }));

  const renderTitle = () => (
    <View style={styles.titleContainer}>
      <Text style={styles.title}>Top 10 Pizzas by Sales</Text>
    </View>
  );

  const renderChartSection = () => (
    <View style={styles.horizontalChartContainer}>
      {renderTitle()}
      <View style={styles.chartContainer}>
        <BarChart
          data={data}
          isAnimated
          // horizontal
          // barWidth={
          //   orientation === 'portrait' ? screenWidth - 790 : screenWidth - 1155
          // }
          // width={
          //   orientation === 'portrait' ? screenWidth - 150 : screenWidth - 550
          // }
          // height={
          //   orientation === 'portrait' ? screenWidth - 350 : screenWidth - 450
          // }
          // xAxisColor={isDarkMode ? 'white' : 'black'}
          // yAxisColor={isDarkMode ? 'white' : 'black'}
          // xAxisLabelTextStyle={styles.barChartLabelText}
          // yAxisLabelTextStyle={styles.barChartLabelText}
          // yAxisTextStyle={styles.yAxisColor}
          // hideRules={true}
          // noOfSections={4}
        />
      </View>
      {/* <View style={styles.bottomDiv} /> */}
    </View>
  );

  return (
    <ScrollView style={styles.container}>
      <View style={styles.filterCard}>
        <Text style={styles.filterTitle}>Filter based on Store</Text>
        <Dropdown
          options={['Store 1', 'Store 2', 'Store 3']}
          selectedOption={selectedStore}
          setSelectedOption={setSelectedStore}
        />
      </View>
      {renderChartSection()}
    </ScrollView>
  );
};

const lightTheme = StyleSheet.create({
  container: {
    // flex: 1,
    backgroundColor: theme.light.backgroundColor,
  },
  filterCard: {
    backgroundColor: theme.light.cardColor,
    margin: 10,
    gap: 10,
    paddingBottom: 10,
  },
  filterTitle: {
    fontSize: 22,
    padding: 10,
    color: theme.light.textColor,
  },
  horizontalChartContainer: {
    borderRadius: 10,
    margin: 10,
    padding: 20,
    zIndex: -1,
    ...theme.boxShadow,
    backgroundColor: theme.light.cardColor,
  },
  title: {
    fontSize: 30,
    textAlign: 'center',
    color: theme.light.textColor,
  },
  titleContainer: {
    marginBottom: 30,
  },
  chartContainer: {},
});

const darkTheme = StyleSheet.create({});

**Expected behavior**
The bar should stay within the container

**Screenshots**
without horizontal
![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/88726438/07405d76-6276-4dc4-b44f-5c5cabf714f7)

with horizontal
![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/88726438/963aafb2-680d-4e51-a019-ee46a7b9e7f8)

 - Device: Ipad pro 11 inch

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Intelebee1234 👋
Thanks for pointing out the issue. It has been fixed now. Please use the latest version of the library. 
If the issue persists, you can use the `shiftX` and `shiftY` props to adjust the position of the horizontal chart.
