### ISSUE TITLE
Question: Is it possible to combine bar and line chart

### ISSUE THREAD

**Issue by hgjura** [Abhinandan-Kushwaha/react-native-gifted-charts#365]
I have two sets of data. One (main) needs to show as bars, but the second (or others) will need to show in the chart lines. Is this possible with gifted charts? 
I can see that in the barchart you can also show a line with 'showline' but this seems a line for the same data. I need this reflect a different set of data.

Thanks

**Comment by Abhinandan-Kushwaha** [comment]
Hi @hgjura 👋
To show a Line in a Bar chart with a different set of data, you can use the `lineData` prop, along with `showLine`.
Also, you can control the properties of the line like color, thickness, curved, isAnimated etc using the `lineConfig` prop.

Here is an example-
```js
<BarChart
  data={[{value: 10}, {value: 15}, {value: 6}, {value: 8}, {value: 10}]}
  showLine
  lineData={[{value: 18}, {value: 15}, {value: 17}, {value: 8}]}
  lineConfig={{color: 'red', dataPointsColor: 'green', dataPointsRadius: 6}}
/>
```

The output of the above code is-

<img width="302" alt="Screenshot 2023-08-23 at 12 53 27 PM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/14e20bbe-e608-42fa-84ac-8363ddbf11de">

Complete detail about `lineConfig` can be found in the [props list of Bar chart](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/BarChart/BarChartProps.md). Search for lineConfig on this page.

Currently, the library supports only 1 line in a Bar chart. If you want multiple lines, raise a request. I will try to add this feature in the next release.
