### ISSUE TITLE
Render issues: yAxis space, initialSpacing missalignment; number of bars, topLabelComponent  for line

### ISSUE THREAD

**Issue by hgjura** [Abhinandan-Kushwaha/react-native-gifted-charts#366]
I am testing this in React Native and on a iPhone 13 mini. But I believe this may happen in other devices as well. In the image attached, the 'red' part is the surrounding view, and 'pink' is the barchart.

Issue 1: I have a requirement where the chart should not show the YAxis or the XAxis text. The 'hideYAxisText' seems to work in hiding the text. However, it leaves the space that the text was occupying as a gap. And there seem to no properties such as marginLeft or paddingLeft to eliminate that gap. For the XAxis, it seems that if I don't provide the labels with the data the text would not show. But the same issue with space remains. I was expecting a property such as 'showYAxis' and 'showXAxis' where once they are set to false, the chart area expands and takes all available space.
Issue 2: the initialSpacing property between the BarChart and lineConfig seems entirely out-of-sync. In the image attached you can see how bar and line do not align, with initialSpacing set at 10 for both. In order to align them you must set very specific values for bar, lineConfig and barWidth. But this would work only if you have a fixed width for the BarChart. The moment you use something like  const width = Dimensions.get('window').width - 20; than this is broken again. I was expecting that the alignment of the line and bars is done automatically in a way and more harmoniously. 
Issue 3: The bar chart visible space does not include all the data. So if the data provided is of a certain length, the BarChart would only display the data that it can fit and make scrollable all the data form the right side of the chart. So, in order to get this right, you need to know precisely how many bars would eventually need to be available, and set the barWidth to a certain size in order to accommodate future data. This is not practical! I was expecting that, if you don't set the barWidth, the chart will accommodate all data within the visible space, by dynamically setting barWidth dynamically, and taking all that visible available space. It seems that if there is more data it become scrollable, which may not be intuitive to the end-user
Issue 4: I love the feature, where you can pass the style of the bar as well as  topLabelComponent for the bar. This works best n my case where I have a requirement to show the top label (with a certain color) for lowest point, highest point and latest point of the bars. I wish I could have been able to do the same for the line as well. I don't seem to be able to show any labels for the line. 

Maybe I am misreading the props or there is a way around some of the issues above. I would love to know. 

Thanks

````typescript
<View
        style={{
          alignItems: 'center',
          flexDirection: 'row',
          backgroundColor: 'red',
        }}>
        <BarChart
          initialSpacing={10}
          backgroundColor={'pink'}
          width={width}
          height={height}
          hideYAxisText={true}
          hideRules={true}
          barWidth={20}
          spacing={1}
          noOfSections={3}
          barBorderRadius={4}
          frontColor="lightgray"
          data={barData}
          yAxisThickness={0}
          xAxisThickness={0}
          showLine={true}
          lineData={lineData}
          lineConfig={{
            initialSpacing: 10,
            color: 'red',
            hideDataPoints: false,
            curved: false,
          }}
        />
      </View>

```


![gifted-charts-reported-issues](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/9681487/b519febc-a22c-4ba5-a5a7-a01c203d56dc)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @hgjura 👋
Thanks for pointing out these issues. The first 2 issues have already been fixed and the fix will be available in the next release.

For the third issue, we can auto-calculate the bar width based on available space, but there's another factor to it- the spacing between bars. Should spacing also be auto-calculated? Or should we provide a dynamic spacing too based on available width? Would love to know your opinion on this. Then I will try adding some new props to auto adjust bar widths and spacing.

Fourth issue-
We have a prop named `dataPointLabelComponent` using which we can render custom labels on data points in Line charts. But this does not work for Line displayed inside Bar charts. I will add this feature for Line inside Bar charts in the next release.

The next release should be available within a week. This release will include a number of bug fixes, new features and code refactor.

**Comment by hgjura** [comment]
For the third issue reported, this is my suggestion:
- If 'spacing' is set then, if it set to 0, than no space should be between bars, if it is set to anything higher than 0, than do not calculate dynamically the spacing. Always provide the set spacing.
- If 'spacing' property is not set to any value, then dynamically calculate the spacing between bars according to the visible space.

For the bars, sort of apply the same logic,
- If a barWidth it is set, than do not calculate anything dynamically. Practically, the same behavior that it is there now.
- But if barWidth it is not set, than dynamically calculate width to fit the visible space. And if both 'barWdth' and 'spacing' are not set, than calculate both dynamically, to fit the visible space.
Hope this helps.

**Comment by hgjura** [comment]
And for forth point, 'dataPointLabelComponent ' it would be great if this works the same way as with the bars, where you want to show the label only for a certain data point and not all of them.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @hgjura 
`dataPointLabelComponent` can now be passed to specific data objects. Please try the latest version of the library. The first 2 issues are aldo fixed in this version.
