### ISSUE TITLE
FEATURE REQUEST: barBorderRadius settings for individual corners

### ISSUE THREAD

**Issue by hgjura** [Abhinandan-Kushwaha/react-native-gifted-charts#367]
In the BarChart, the prop 'barBorderRadius' works as expected. However, it would be great to also have the following: barBorderRadiusTopLeft, barBorderRadiusTopRight, barBorderRadiusBottomLeft, barBorderRadiusBottomRight, to set the corners individually. I have a requirement where only the top Left/Right should be set individually.  
So the option could be, barBorderRadius is set oevrride inidividual settings, but if not set than look for individual settings, and if noone is set, than defaults.

**Comment by Abhinandan-Kushwaha** [comment]
@hgjura Thanks for requesting this feature. It has already been developed and will be available in the next release. Please have a look at [this issue](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/354). Here I have provided a workaround for the same.

**Comment by hgjura** [comment]
This is not working for me. I set
          cappedBars={true}
          capRadius={8}
          capThickness={8}
          //barBorderRadius={8}
And I see no change. The bars are all square.
I reverse it at 
This is not working for me. I set
         // cappedBars={true}
         // capRadius={8}
        //  capThickness={8}
          barBorderRadius={8}
And now all corners have radius. 
Am I missing a prop somewhere?

**Comment by Abhinandan-Kushwaha** [comment]
Can you share the code? I will check.

**Comment by Abhinandan-Kushwaha** [comment]
@hgjura The problem here is that the default capColor is black, so it's invisible in black background. Adding the prop `capColor={"lightgray"}` solves the issue.
