### ISSUE TITLE
Horizontal scroll not working in LineChart/AreaChart

### ISSUE THREAD

**Issue by SwikarBhattarai** [Abhinandan-Kushwaha/react-native-gifted-charts#368]
**Describe the bug**
For larger sets of data with fixed width, i am not able to scroll horizontally.

 - Device: Android Emulator

**Comment by michaelpomogajko** [comment]
Same here, iOS horizontal scroll works, Android doesn't

**Comment by Abhinandan-Kushwaha** [comment]
Hi @SwikarBhattarai @michaelpomogajko 
Please use the latest version of the library.
Feel free to reopen the issue, if it's still not soved in the latest version.

**Comment by connorpmullins** [comment]
Hi @Abhinandan-Kushwaha - thanks for your work maintaining the library. I am on version 1.3.5 (latest public version) and am encountering the same issue!

**Comment by Abhinandan-Kushwaha** [comment]
Please share the code and the data for the chart. I will debug. @SwikarBhattarai @michaelpomogajko @connorpmullins

**Comment by connorpmullins** [comment]
Thank you for the response!

Here's the return statement of the component that renders the data:
`
  return (
    <Box>
      <Box
        flex="1"
        bg="white"
        rounded="lg"
        mx="3"
        mt="3"
        mb="2"
        pb="9"
        overflow="hidden"
        p="1.5"
        display="flex">
        <Text
          fontWeight="semibold"
          fontSize="xs"
          borderRightColor={color.JeremiahGray}
          borderRightWidth={1}>
          BARO
        </Text>
        <LineChart
          areaChart
          roundToDigits={1}
          maxValue={3}
          noOfSections={3}
          thickness1={4}
          yAxisOffset={28}
          yAxisTextStyle={{
            fontSize: 12,
            fontWeight: "700",
            color: color.SuperGray,
          }}
          xAxisLabelTextStyle={{
            fontSize: 12,
            fontWeight: "700",
            color: color.SuperGray,
          }}
          curved
          showXAxisIndices
          showFractionalValues
          color={color.Blue}
          color2={color.Red}
          textColor1={color.Black}
          textColor2={color.Black}
          dataPointsColor1={color.Blue}
          dataPointsColor2={color.Red}
          xAxisLabelTexts={X_AXIS_LABEL_TEXTS}
          data={currentDateWithData?.baroData}
          data2={currentDateWithData?.solunarData}
          showVerticalLines
          hideRules
          startOpacity2={0}
          thickness2={6}
          textShiftY={-2}
          textShiftX={-3}
          startFillColor={color.Blue}
          endFillColor={color.Blue}
          startOpacity={0.8}
          endOpacity={0.1}
          yAxisColor={color.JeremiahGray}
          xAxisColor={color.JeremiahGray}
          // yAxisTextStyle={{ textAlign: "right", flex: 1, paddingRight: 4 }}
          // hideYAxisText
          // secondaryData={currentDateWithData?.solunarData}
          // secondaryYAxis={{
          //   maxValue: 3,
          //   noOfSections: 3,
          //   yAxisOffset: 28,
          //   roundToDigits: 1,
          // }}
          // secondaryLineConfig={{
          //   curved: true,
          //   curveType: 1,
          //   areaChart: false,
          //   color: color.Red,
          // }}
        />
      </Box>
      <Row justifyContent="center">
        <Row alignItems="center" mr="4">
          <Box bg={color.Blue} mr="2" rounded="full" h={3} w={3} />
          <Text fontSize="xs" fontWeight="semibold">
            BAROMETRIC PRESSURE
          </Text>
        </Row>
        <Row alignItems="center">
          <Box bg={color.Red} mr="2" rounded="full" height={3} width={3} />
          <Text fontSize="xs" fontWeight="semibold">
            MOON POSITION
          </Text>
        </Row>
      </Row>
    </Box>
  );
`

I'm also having issues where the secondaryData / secondaryYAxis isn't rendering, which is why that's commented out, but that's a distinct bug from the one being reported here.

The `Box` / `Row` tags are from a library called NativeBase, but just function as a flex box with a flex direction or 'row' or 'column' and allow for terse inline styling. I don't have a reason to believe they're part of the scrolling issue.

**Comment by connorpmullins** [comment]
I know it's a boring graph - sorry.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @connorpmullins 👋
For me, the horizontal scroll is working fine on Android simulator. See the recording below-

https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/21ffa8ce-1abc-4357-aea3-1dc93bc4ae5b

Please update to the latest version- `1.3.7` If the issue still persists, comment here, I can connect with you to solve it.

I am using the below code-

```js
const baroData = [
    {
      "dataPointText": 29.94,
      "value": 29.94
    },
    {
      "dataPointText": 29.94,
      "value": 29.94
    },
    {
      "dataPointText": 29.94,
      "value": 29.94
    },
    {
      "dataPointText": 29.94,
      "value": 29.94
    },
    {
      "dataPointText": 29.94,
      "value": 29.94
    },
    {
      "dataPointText": 29.94,
      "value": 29.94
    },
    {
      "dataPointText": 29.94,
      "value": 29.94
    },
    {
      "dataPointText": 29.94,
      "value": 29.94
    },
    {
      "dataPointText": 29.94,
      "value": 29.94
    },
    {
      "dataPointText": 29.94,
      "value": 29.94
    },
    {
      "dataPointText": 29.94,
      "value": 29.94
    },
    {
      "dataPointText": 29.94,
      "value": 29.94
    },
    {
      "dataPointText": 29.94,
      "value": 29.94
    },
    {
      "dataPointText": 29.91,
      "value": 29.91
    },
    {
      "dataPointText": 29.91,
      "value": 29.91
    },
    {
      "dataPointText": 29.88,
      "value": 29.88
    },
    {
      "dataPointText": 29.88,
      "value": 29.88
    },
    {
      "dataPointText": 29.88,
      "value": 29.88
    },
    {
      "dataPointText": 29.88,
      "value": 29.88
    },
    {
      "dataPointText": 29.91,
      "value": 29.91
    },
    {
      "dataPointText": 29.91,
      "value": 29.91
    },
    {
      "dataPointText": 29.91,
      "value": 29.91
    },
    {
      "dataPointText": 29.91,
      "value": 29.91
    },
    {
      "dataPointText": 29.91,
      "value": 29.91
    }
  ]

  return <LineChart
          areaChart
          roundToDigits={1}
          maxValue={3}
          noOfSections={3}
          thickness1={4}
          yAxisOffset={28}
          yAxisTextStyle={{
            fontSize: 12,
            fontWeight: "700",
            color: 'SuperGray',
          }}
          xAxisLabelTextStyle={{
            fontSize: 12,
            fontWeight: "700",
            color: 'SuperGray',
          }}
          curved
          showXAxisIndices
          showFractionalValues
          color={'blue'}
          color2={'red'}
          textColor1={'black'}
          textColor2={'black'}
          dataPointsColor1={'blue'}
          dataPointsColor2={'red'}
          // xAxisLabelTexts={X_AXIS_LABEL_TEXTS}
          data={baroData}
          data2={baroData.map(item=>{
            const newVal = item.value + Math.random();
            return {
              value: newVal,
              dataPointText: (newVal+'').substring(0,5)
            }
          })}
          showVerticalLines
          hideRules
          startOpacity2={0}
          thickness2={6}
          textShiftY={-2}
          textShiftX={-3}
          startFillColor={'blue'}
          endFillColor={'blue'}
          startOpacity={0.8}
          endOpacity={0.1}
          yAxisColor={'JeremiahGray'}
          xAxisColor={'JeremiahGray'}
        />
```

**Comment by connorpmullins** [comment]
@Abhinandan-Kushwaha - thanks for working on this! I believe the issue I'm experiencing is actually with the library,[React Native Bottom Sheet](https://github.com/gorhom/react-native-bottom-sheet).

The issue is NOT with this library (at least directly).

For anyone else who finds their way to this thread, please check the parent component you're rendering the chart in. I was rendering this chart inside a vertical scrollview. I didn't think that my issue was related to nested scrollviews because I was also rendering a horizontal scrollview right above my LineChart that was scrolling correctly on Android. 

However, for one reason or another I needed a different solution for this chart than I did for my other horizontally-scrolling component. For me, the below fix took care of things for me. People using other gesture-handling-enabled libraries may encounter similar issues/fixes.
https://github.com/gorhom/react-native-bottom-sheet/issues/770
