### ISSUE TITLE
Automatic Scroll to a Specific Index

### ISSUE THREAD

**Issue by ZanaNabaz** [Abhinandan-Kushwaha/react-native-gifted-charts#369]
I've been working on a feature for my app, and I'm curious if there's a way to make the BarChart automatically scroll to a specific index. For example, let's say I have an array with 50 items, and I want the app to scroll to index 25 as soon as it's rendered.

If you have any insights on how I can achieve this, I'd really appreciate your input.

If there's currently no feature for this, I'd like to suggest adding it. It could greatly enhance the user experience by focusing their attention on a specific point within the list.

 Thanks a bunch for this repo, amazing work!

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ZanaNabaz 👋
Thanks for requestin the feature. You can now use the `scrollToIndex` prop to scroll to any particular index.
Also, you can use the `scrollRef` prop to scroll to any position.

Please use the latest version of the library.
