### ISSUE TITLE
The graph bars and labels not aligning

### ISSUE THREAD

**Issue by YubinKim16** [Abhinandan-Kushwaha/react-native-gifted-charts#374]
**Describe the bug**
When using the bar graph, the bar and the label are not aligned.

**To Reproduce**
Here are my props.
<BarChart
        stackData={data}
        height={deviceHeight * 0.175}
        // xAxisLength={deviceWidth}
        width={deviceWidth - 90}
        xAxisThickness={0}
        yAxisThickness={0}
        noOfSections={4}
        barWidth={barWidth}
        spacing={spacing}
        disableScroll={true}
        isAnimated={true}
        hideRules={false}
        yAxisTextStyle={{
          width: 0,
        }}
        yAxisLabelContainerStyle={{
          width: 0,
        }}
        yAxisLabelWidth={1}
        xAxisLabelTextStyle={{
          textAlign: 'center',
          color: COLORS.GREY500,
          width: '100%',
        }}
        initialSpacing={0}
      />

**Expected behavior**
The graph bars and labels should be centered.

**Screenshots**
<img width="355" alt="스크린샷 2023-08-31 오후 4 57 38" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/117627980/7bb09eae-2027-47a0-b0f4-e68892a32cc3">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @YubinKim16 
Please try the latest version of the library. 

And please dont give 0 width to labels. Remove this-
```js
yAxisTextStyle={{
width: 0,
}}
yAxisLabelContainerStyle={{
width: 0,
}}
yAxisLabelWidth={1}
```
