### ISSUE TITLE
correction in the typing of dos das das code and import of dos types

### ISSUE THREAD

**Issue by MatheusFellipi** [Abhinandan-Kushwaha/react-native-gifted-charts#378]
**Describe the bug**
I wanted a correction of the typegem in the code and to be able to import them in my code

**Reproduce**
4. See the error

**Expected behavior**
the data 1 2.. are having error in typing.

**Screenshots**
![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/47674343/1c9e247b-c1bf-44b0-85dc-bdbf218f5e71)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @MatheusFellipi 👋
Thanks for pointing out the issue.
Which version of the library are you using? Also, can you share the code instead of screenshot.
