### ISSUE TITLE
Reference line option isn't provided in the props

### ISSUE THREAD

**Issue by mohzameer** [Abhinandan-Kushwaha/react-native-gifted-charts#38]
Great library with ease of use. In the library examples as well in the documentation, the following graph is provided,
![image](https://user-images.githubusercontent.com/31923811/142878579-5120f825-3d31-41cb-be4c-770d624f5159.png)

but, neither does the dotted reference line appear if we implement the example nor does the library has properties for any such lines. Is there any possibility to have that reference line in a bar chart/any chart?

**Comment by Abhinandan-Kushwaha** [comment]
Hi, @mohzameer👋  
Thanks for pointing out this issue. It has been fixed now. 🎉

Now we can use the `showReferenceLine1` prop to show the reference line. The position of the reference line can be set using the `referenceLine1Position` prop.

This feature is available from version `0.1.18` onwards.

Multiple reference lines can be added using `showReferenceLine2` and `showReferenceLine3` props.

Additional properties like thickness, color, type (solid or dashed) etc can be configured using the `referenceLine1Config` prop.

Here's an example with 1 reference line-

```js
<BarChart
    data={data}
    showReferenceLine1
    referenceLine1Position={50}
    referenceLine1Config={{
      type: 'solid',
      color: 'red',
      thickness: 1,
      dashWidth: 5,
      dashGap: 13,
    }}
```

Hope it helps.🤗
