### ISSUE TITLE
Combining LineChart and StackedBarChart not working

### ISSUE THREAD

**Issue by markkobbert** [Abhinandan-Kushwaha/react-native-gifted-charts#380]
Can be reproduced with a simple configuration like this:

`<BarChart stackData={data} showLine />`

Results in Render Error: Cannot read property 'barWidth' of undefined.

![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/39066484/ac69f825-b300-4156-98e5-62c1b3fb3f47)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @markkobbert 👋
Thanks for pointing this out. This issue has been fixed.🎉 Please update to version `1.3.6` of react-native-gifted-charts.
