### ISSUE TITLE
Chart with data left Line and data right Barchart

### ISSUE THREAD

**Issue by ducsilva** [Abhinandan-Kushwaha/react-native-gifted-charts#392]
**Describe the isssue**

I want to show my chart with LineChart data left and Bar chart with data right as below image. Have you any idea for this?

**To Reproduce**<img width="381" alt="Screenshot 2023-09-19 at 10 26 12" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/46064085/e269b625-17ee-4995-a493-b27c28f1571a">Steps to reproduce the

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ducsilva 👋
Thanks for requesting this feature. It is now implemented in the latest version of the library. Please use version `1.3.8` of `react-native-gifted-charts`

I have added support for a new property named `isSecondary` in the `lineConfig` object. Setting `isSecondary` to true results in making the line correspond to the secondary Y axis.

Here's an example-

<img width="361" alt="Screenshot 2023-09-20 at 3 54 57 AM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/498e28e6-742c-4b3e-9f1f-f9e58a84590e">

The code for the above chart is-
```js
const data = [10, 20, 30, 20, 15, 12];
const lineData = [12, 5, 8, 15, 8, 10];

return (
  <View style={{backgroundColor: 'black'}}>
    <BarChart
      data={data.map(i => {
        return {value: i};
      })}
      showGradient
      frontColor={'#8BC9CB'}
      gradientColor={'#07A0A3'}
      barBorderTopLeftRadius={4}
      barBorderTopRightRadius={4}
      hideRules
      yAxisColor={'gray'}
      xAxisColor={'gray'}
      yAxisTextStyle={{color: 'gray'}}
      secondaryYAxis={{
        yAxisLabelPrefix:'$'
      }}
      showLine
      lineData={lineData.map(i => {
        return {value: i};
      })}
      lineConfig={{
        thickness: 4,
        color: 'yellow',
        hideDataPoints: true,
        isSecondary: true, // this is the newly added property
      }}
    />
  </View>
);
