### ISSUE TITLE
Question: Can I create a vertical line-divider using this lib?

### ISSUE THREAD

**Issue by grigorii-horos** [Abhinandan-Kushwaha/react-native-gifted-charts#393]
Design:

![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/4980269/1eea9fb2-0447-4faa-97f7-2881678b0dc8)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @grigorii-horos 👋
This can be achieved by setting the property `showVerticalLine: true` inside the data object.

Here's an example-

<img width="302" alt="Screenshot 2023-09-20 at 4 00 26 AM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/df512c90-9944-4a74-a934-8892008fffe1">


The code for the above chart is-

```js
const data = [
  {value: 10, label:'12:00'},
  {value: 20,label:'13:00', showVerticalLine:true},
  {value: 30,label:'14:00'},
  {value: 20,label:'15:00'},
  {value: 15,label:'16:00'},
  {value: 12,label:'17:00'},
];
const data2 = [12, 5, 8, 15, 8, 10];

return (
  <LineChart
    data={data}
    secondaryData={ldata2.map(i => {
      return {value: i};
    })}
    verticalLinesThickness={3}
    verticalLinesStrokeDashArray={[6,8]}
    verticalLinesColor={'gray'}
    yAxisSide={yAxisSides.RIGHT}
    width={270}
  />
);
```
Please use the latest version, i.e- `1.3.8` of react-native-gifted-charts.
