### ISSUE TITLE
Data Point Label and Custom Data Point not shown when yAxisOffset is applied

### ISSUE THREAD

**Issue by samobrien13** [Abhinandan-Kushwaha/react-native-gifted-charts#397]
**Describe the bug**

When using yAxisOffset I'm not able to see focused data points and labels 

**To Reproduce**

```
import { Dimensions, Text, View } from 'react-native';
import { LineChart as GiftedLineChart } from 'react-native-gifted-charts';
import { itemType } from 'react-native-gifted-charts/src/LineChart/types';

const { width } = Dimensions.get('window');

const Graph = () => {
    const data: itemType[] = [
        {
            value: Math.random() * 50 + 50,
            focusedDataPointLabelComponent: () => <Text>Custom label</Text>,
            focusedCustomDataPoint: () => (
                <View
                    style={{
                        backgroundColor: 'blue',
                    }}
                />
            ),
        },
        {
            value: Math.random() * 50 + 50,
            focusedDataPointLabelComponent: () => <Text>Custom Label</Text>,
            focusedCustomDataPoint: () => (
                <View
                    style={{
                        backgroundColor: 'red',
                        height: 20,
                        width: 20,
                    }}
                />
            ),
        },
    ];

    return (
        <GiftedLineChart
            width={width}
            data={data}
            focusEnabled
            yAxisOffset={30}
        />
    );
};

export default Graph;
```

**Expected behavior**

Able to see the data points and label when focused

**Screenshots**

 - Device: [iPhone14Pro Simulator]
 - OS: [iOS16.4]
 - Version of the library being used [1.3.8]

|Without offset|With offset|
|-|-|
|![Simulator Screenshot - iPhone 14 Pro - 2023-09-21 at 12 59 47](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/11660441/14519062-56a3-45ee-b242-f4442fa0cd2e)|![Simulator Screenshot - iPhone 14 Pro - 2023-09-21 at 13 00 08](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/11660441/5f901f99-ca31-4384-9137-ae1811791d9a)|

**Comment by Abhinandan-Kushwaha** [comment]
Hi @samobrien13 👋
Thanks for bringing this up. This has been fixed in version 1.3.9🎉
Please update.
