### ISSUE TITLE
X-Axis Linechart (AreaChart) Label

### ISSUE THREAD

**Issue by noelzappy** [Abhinandan-Kushwaha/react-native-gifted-charts#40]
Going through the documentation,  I have not seen the equivalent of ```yAxisLabelTexts={ [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ]}``` for X-Axis.

I want this to be  ```xAxisLabelTexts={ [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ]}``` so it shows  on x axis instead but it does not  work.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @noelzappy 👋
We already have the `label` and 'labelComponent` properties in the `item` object that can be used for the same purpose.

For a simple text like your example, we can use `label` in the `item` object. The style of the label can be controlled with the `labelTextStyle` property.

Here's a simple example - 

```js
<BarChart
  data={
    [
      {value: 250, label: 'Jan'},
      {value: 500, label: 'Feb'},
      {value: 745, label: 'Mar'},
      {value: 320, label: 'Apr'},
      {value: 600, label: 'May'}
    ]}
/>
```

Hope it helps. 🤗

Also, you can see the complete list of all different props for BarCharts [here](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/HEAD/docs/BarChart/BarChartProps.md)

Closing the issue.

**Comment by noelzappy** [comment]
Does this apply to LineChart also?

**Comment by Abhinandan-Kushwaha** [comment]
Yes @noelzappy it does apply to LineChart too.

Here's the prop list for Line charts - [Line and Area Chart props](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/LineChart/LineChartProps.md)

**Comment by noelzappy** [comment]
Ok. I will check it out. Thanks 😊
