### ISSUE TITLE
handle null values in gifted charts

### ISSUE THREAD

**Issue by PrabhjotAndroid** [Abhinandan-Kushwaha/react-native-gifted-charts#400]
**Describe the bug**
In our App user is entering a value for each day for a week and we are creating a line chart for all the values. For a date if a user do not enter value, I wanted to skip a point in chart but i do not want to skip xAxis label. We have an option to use hideDataPoint but it hides label as well. 

If we add 0 as a value, it will show the same in graph. However, we just want to hide a value, by showing a line between previous and next value. I also tried to pass null value  but it does not works. 

**To Reproduce**
const data = [{ value: 10,  label:"22Nov"}, { value: 20,  label:"23Nov"}, { value: 30,  label:"24Nov" }, { value: 40,  label:"25Nov"}, { value: null,  label:"26Nov" }, { value: 60,  label:"27Nov" }];

**Expected behavior**
For above data, the value for 26 Nov is not available, we just want to skip the point without hiding its 26Nov label. If there is any functionality to hide a value without hiding a label that would be very helpful for us.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @PrabhjotAndroid 
Please take a look at https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/353 
Let me know if it doesn't solve your problem.

**Comment by PrabhjotAndroid** [comment]
Thanks @Abhinandan-Kushwaha  - This worked fine if i have empty values in the middle of array. But there is a case if empty value in the start or end of array. how we can resolve it. Thanks so much for your help

const data = [{ value: null, label:"22Nov"}, { value: 20, label:"23Nov"}, { value: 30, label:"24Nov" }, { value: 40, label:"25Nov"}, { value: 10, label:"26Nov" }, { value: null, label:"27Nov" }];

**Comment by Abhinandan-Kushwaha** [comment]
@PrabhjotAndroid Please try using `startIndex` and `endIndex` props. 
See props table- https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/LineChart/LineChartProps.md#line-related-props 
Let me know if it doesn't help.

**Comment by dumihi313** [comment]
if empty value in the start or end of array, it can crash app. I put all item lines in dataSet

Crash cause: 
 Error: AnimatedValue: Attempting to set value to undefined
