### ISSUE TITLE
Pie Chart: OnPress returns wrong index

### ISSUE THREAD

**Issue by markkobbert** [Abhinandan-Kushwaha/react-native-gifted-charts#401]
Values which are 0 are ignored when returning the index of the pressed value.

This code:

```
  const data = [{value: 15}, {value: 30}, {value: 0}, {value: 40}];
  return <PieChart data={data} onPress={(_: any, index: number) => console.log(index)} />;
```

returns index 2, if the value 40 is clicked, which should be index 3.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @markkobbert 👋
Thanks for pointing out this issue. It will be fixed in the next release which is scheduled for tomorrow.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @markkobbert 🎉
The issue has been fixed now. Please update to version `1.3.10` of `react-native-gifted-charts`
