### ISSUE TITLE
Question: gaps in data values

### ISSUE THREAD

**Issue by grigorii-horos** [Abhinandan-Kushwaha/react-native-gifted-charts#405]
I want to create a weekly graph with 1-5 values per day. But I want to keep equal distance between days. How I can create gaps in the data?
Like:

```js
[
{ value: 40, },   // Monday
{ value: 60, },   // Monday
{ value: 10, },   // Monday
{ value: null, }, // Thursday
{ value: null, }, // Thursday
{ value: 50, },   // Thursday
{ value: null, }, // Wednesday
{ value: 50, },   // Wednesday
{ value: 80, },   // Wednesday
...
]
```

**Comment by Abhinandan-Kushwaha** [comment]
Hi @grigorii-horos 👋
Please have a look at https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/353 and https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/400
Let me know if it doesn't help.
