### ISSUE TITLE
Cannot reading barWidth

### ISSUE THREAD

**Issue by ducsilva** [Abhinandan-Kushwaha/react-native-gifted-charts#406]
First of all, I want to thank you for your library. It is very useful. However, I encountered an issue that caused my app to crash. I see the problem is in the Barchat/index.tsx file. I tried to fix the problem by adding synctax (props.stackData ?? data )?.[0]?.barWidth and it worked. Are there any solutions?
![bugs](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/46064085/389ad007-8b85-4943-b2d7-2c0247926037)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ducsilva 👋
Thanks for pointing out this issue, it has been fixed in version `1.3.11` 🎉
