### ISSUE TITLE
How to make X axis not too crowded ?

### ISSUE THREAD

**Issue by sunzhaoyang** [Abhinandan-Kushwaha/react-native-gifted-charts#408]
<img width="386" alt="image" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/2182116/87768356-fd7c-41a6-b4ac-ad2836a8e8d1">

Too  much date label of x axis leading to barely identify . I wish only the date label  end with 0 display .

how to hide some of them without modify datasets?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sunzhaoyang 👋
Can you please share the dataset?

**Comment by sunzhaoyang** [comment]
> Hi @sunzhaoyang 👋
> Can you please share the dataset?

Thanks for your reply , here is the dataset

```
[{"label": "0914", "value": "50.0"}, {"label": "0915", "value": "50.0"}, {"label": "0916", "value": "50.0"}, {"label": "0917", "value": "50.0"}, {"label": "0918", "value": "50.0"}, {"label": "0919", "value": "50.0"}, {"label": "0920", "value": "50.0"}, {"label": "0921", "value": "50.0"}, {"label": "0922", "value": "50.0"}, {"label": "0923", "value": "50.0"}, {"label": "0924", "value": "50.0"}, {"label": "0925", "value": "50.0"}, {"label": "0926", "value": "50.0"}, {"label": "0927", "value": "50.0"}, {"label": "0928", "value": "50.0"}, {"label": "0929", "value": "57.0"}, {"label": "0930", "value": "57.0"}, {"label": "1001", "value": "57.0"}, {"label": "1002", "value": "57.0"}, {"label": "1003", "value": "57.0"}, {"label": "1004", "value": "57.0"}, {"label": "1005", "value": "57.0"}, {"label": "1006", "value": "57.0"}, {"label": "1007", "value": "50.0"}, {"label": "1008", "value": "50.0"}, {"label": "1009", "value": "50.0"}, {"label": "1010", "value": "50.0"}, {"label": "1011", "value": "50.0"}, {"label": "1012", "value": "50.0"}, {"label": "1013", "value": "50.0"}]
```

I found a solution that replace "label" to "lablecomponent", but I just want to know is there any other solution .

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sunzhaoyang 👋
If you want x-axis labels to display, only if they end with "0", you can use this logic-

```js
<LineChart
  data={data.map(item => {
    return {...item, label: item.label.endsWith('0') ? item.label : ''};
  })}
  xAxisLabelTextStyle={{width: 40}}
  rotateLabel
  spacing={12}
/>
```
The output will be-
<img width="380" alt="labels0" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/411b5291-7582-4100-a25e-1e8bcf75a888">

Notice that we need to specify the width of the labels using the `xAxisLabelTextStyle` prop. This is because the default width of the labels is determined by the `spacing` and here the spacing is too less- `12`
