### ISSUE TITLE
pointerConfig behaviour for BarCharts

### ISSUE THREAD

**Issue by marcinczenko** [Abhinandan-Kushwaha/react-native-gifted-charts#410]
How can I achieve the pointerConfig-like behaviour for BarCharts? I would like to scroll over the chart and receive the `onPress` event when the user's finger reaches the each bar.  Or anything that would let me sense that the user is dragging over the bar. Without this it seems I need to render some sort of a touchable view over the graph - not very elegant.

~Ability to do that is an absolute must-have for my project. Could you maybe advise about other libraries that provide this functionality if this cannot be done with gifted-charts?~

I did some research. `BarChart` from  [react-native-charts-wrapper](https://github.com/wuxudong/react-native-charts-wrapper/blob/master/Example/app/BarChartScreen.js) seem to support this behaviour. In the linked example above, just make sure you remove [the following line](https://github.com/wuxudong/react-native-charts-wrapper/blob/11ca62ac8400d43bc77d21794b3b3eb3b2d42581/Example/app/BarChartScreen.js#L84).

I find _gifted-charts_ somehow easier to use and better documented, so I would really like if this could be achieved with gifted-charts as well.

Thanks in advance for any hint.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @marcinczenko 👋
Thanks for suggesting this feature. I will do an effort estimate and post here if it's feasible.

**Comment by marcinczenko** [comment]
Thanks @Abhinandan-Kushwaha ! Looking forward. I would love to offer my help in working on it, but currently I am a bit overloaded. I am happy to discuss if any feedback is needed.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @marcinczenko 👋
`pointerConfig` is now available for bar charts as well (version `1.3.12`)🎉

**Comment by marcinczenko** [comment]
Wow - nice! I was busy with some other stuff and missed that - I will give it a spin asap!

**Comment by giltheodor** [comment]
Hi, is pointerConfig feature available for stackBars?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @giltheodor 👋
Thanks for requesting this feature. `pointerConfig` is now supported for Stacked bar charts from version `1.3.24` onwards.

**Comment by giltheodor** [comment]
Is there a way to set the pointerConfig Strip behind the stackBars????

![Simulator Screenshot - iPhone 15 - 2023-11-30 at 12 42 44](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/111180498/f3f52cf7-d94c-477b-99b9-4333ebb268dc)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @giltheodor 
Thanks for requesting this feature. It is now available in version `1.3.25`

We can now add the property `stripBehindBars` inside the `pointerConfig` object to show the Strip behind the bars.

**Comment by giltheodor** [comment]
Thank you for your response but is seems that the `stripΒehindBars` prop when set to true also hides the entire `pointerLabelComponent`

**Comment by giltheodor** [comment]
In version 1.3.25 in BarChart Component the app is crashing when we use the `initialPointerIndex` prop. This was not happening in previous version. 

The error is: undefined is not an object (evaluating 'pointerItemLocal[0].pointerShiftX')

**Comment by Abhinandan-Kushwaha** [comment]
> Thank you for your response but is seems that the `stripΒehindBars` prop when set to true also hides the entire `pointerLabelComponent`

Can you please share the screenshot

**Comment by Abhinandan-Kushwaha** [comment]
> In version 1.3.25 in BarChart Component the app is crashing when we use the `initialPointerIndex` prop. This was not happening in previous version.
> 
> The error is: undefined is not an object (evaluating 'pointerItemLocal[0].pointerShiftX')

Noted. I will fix it and release a new version today.

**Comment by giltheodor** [comment]
> > Thank you for your response but is seems that the `stripΒehindBars` prop when set to true also hides the entire `pointerLabelComponent`
> 
> Can you please share the screenshot

![Simulator Screenshot - iPhone 15 - 2023-12-11 at 12 15 58](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/111180498/258c2542-1d47-4d2f-9a74-1594650728c0)

![Simulator Screenshot - iPhone 15 - 2023-12-11 at 12 16 11](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/111180498/20d9d1ea-1d2d-41b6-a7d8-ca319837d8fb)

**Comment by Abhinandan-Kushwaha** [comment]
@giltheodor Both the issues have been fixed in version `1.3.26` 🎉
