### ISSUE TITLE
BarChart with showLine, don't have tooltip

### ISSUE THREAD

**Issue by tiborelsan** [Abhinandan-Kushwaha/react-native-gifted-charts#411]
When I have a BarChart type graph and I add showLine, then the tooltip no longer works.

I found where the problem comes from, in the renderLineInBarChart.tsx file.
We should add "none" pointerEvents in the different renders.

![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/17316591/eb3652f5-d6e2-493e-8f02-f3c354d3b6fe)

Have a nice day

**Comment by tiborelsan** [comment]
The tooltip is also under the points and line and I don't know why 🥺

**Comment by Abhinandan-Kushwaha** [comment]
Hi @tiborelsan 👋
You just need to use the `lineBehindBars` prop. Let me know if it doesn't help.

**Comment by Abhinandan-Kushwaha** [comment]
Hey @tiborelsan 
Sorry, I didn't consider your suggestion of using `pointerEvents='none'`. In fact, it works like a charm.

I will add this in the next version. If you need it urgently I can release a new version today.

**Comment by tiborelsan** [comment]
Not a problem.
This is not urgent for the moment :)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @tiborelsan 
I have added `pointerEvents='none'` as per your suggestion. Please update to the latest version- `1.3.13`
