### ISSUE TITLE
Unable to activate background Scroll, only able to scroll when pressed on graph components (Bar and Line Graph)

### ISSUE THREAD

**Issue by sahad00** [Abhinandan-Kushwaha/react-native-gifted-charts#412]
This is a video representing it ,any fixes ? 

https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/133844717/b3af747d-566c-4d85-89f4-bf76fe72deeb

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sahad00 👋
I'm unable to reproduce this issue. Can you please share the code (complete code including the surrounding View or ScrollView)
