### ISSUE TITLE
Center/origo not centered within the PieChart.

### ISSUE THREAD

**Issue by m4d0x** [Abhinandan-Kushwaha/react-native-gifted-charts#415]
**Describe the bug**
The center of the PieChart doesnt align correctly within its parent. This shouldnt really be a problem if: flex: 1, alignItems: 'center', justifyContent: 'center', were the default and additional adding a prop for this that does make sense.
Tried using these and none of them helps:
  innerCircleBorderWidth?: number;
  innerCircleBorderColor?: ColorValue;
  shiftInnerCenterX?: number;
  shiftInnerCenterY?: number;
  
Having to use "paddings" within the stylecreations wont be optimal when it will differ majorly between mobile and tablets.

**To Reproduce**
1. Use the default PieChart and try it.

**Expected behavior**
It should always be centered within its parent, possibly with the option to offset it if thats even necessary at use.

**Screenshots**
Attached further down .

 - Device: [e.g. iPhone8+ and really any other]
 - OS: [e.g. iOS15+]
 - Version of the library being used [latest]
 
![IMG_4990](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/82669829/d55f7bff-88ec-49db-8a8a-222903e6347e)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @m4d0x 👋
Thanks for pointing out this issue. It has been fixed in version `1.3.12`. You can now center the Pie chart by using `alignItems: 'center', justifyContent: 'center'` to the surrounding View
