### ISSUE TITLE
X axis lable not showing 

### ISSUE THREAD

**Issue by happybhalodiyaBrain** [Abhinandan-Kushwaha/react-native-gifted-charts#417]
X axis lable not showing 

<img width="422" alt="Screenshot 2023-10-26 at 12 17 13 PM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/86781322/351cde67-d595-44ce-983b-77fd411d208f">

here is my code 
```
 <BarChart
                data={barData}
                barWidth={8}
                spacing={30}
                roundedTop
                roundedBottom
                hideRules
                xAxisThickness={0}
                yAxisThickness={0}
                yAxisTextStyle={{color: 'gray'}}
                xAxisTextStyle={{color: 'red'}}
                xAxisLabelTextStyle = {{width:60}}
                noOfSections={3}
                maxValue={75}
              />
```
              
              

version
 "react-native-gifted-charts": "^1.3.11",
"react-native-linear-gradient": "2.6.2",
 "react-native": "0.61.3",

**Comment by Abhinandan-Kushwaha** [comment]
Hi @happybhalodiyaBrain 
Can you please share the barData?

**Comment by happybhalodiyaBrain** [comment]
const barData = [
  {
    value: 40,
    label: "Jan",
    spacing: 5,
    labelWidth: 30,
    labelTextStyle: { color: "gray" },
    frontColor: "#177AD5",
  },
  {
    value: 70,
    spacing: 5,
    frontColor: "#177AD5",
  },

  {
    value: 35,
    spacing: 20,
    frontColor: "#177AD5",
  },

  {
    value: 50,
    label: "Feb",
    spacing: 4,
    labelWidth: 30,
    labelTextStyle: { color: "gray" },
    frontColor: "#177AD5",
  },
  { value: 40, frontColor: "#ED6665" },
  {
    value: 75,
    label: "Mar",
    spacing: 2,
    labelWidth: 30,
    labelTextStyle: { color: "gray" },
    frontColor: "#177AD5",
  },
  { value: 25, frontColor: "#ED6665" },
  {
    value: 30,
    label: "Apr",
    spacing: 2,
    labelWidth: 30,
    labelTextStyle: { color: "gray" },
    frontColor: "#177AD5",
  },
  { value: 20, frontColor: "#ED6665" },
  {
    value: 60,
    label: "May",
    spacing: 2,
    labelWidth: 30,
    labelTextStyle: { color: "gray" },
    frontColor: "#177AD5",
  },
  { value: 40, frontColor: "#ED6665" },
  {
    value: 65,
    label: "Jun",
    spacing: 2,
    labelWidth: 30,
    labelTextStyle: { color: "gray" },
    frontColor: "#177AD5",
  },
  { value: 30, frontColor: "#ED6665" },
];

**Comment by Abhinandan-Kushwaha** [comment]
Hi @happybhalodiyaBrain 👋
The X-axis labels are displayed but they are getting **hidden** behind your button component - the **_"View Detailed Report"_** button. You need to somehow push the button a little downwards and the labels will become visible.

**Comment by happybhalodiyaBrain** [comment]
Hello @Abhinandan-Kushwaha  
I removed the button but still i am not able to see x axis

**Comment by ak-spotter** [comment]
Can you share the complete code of the screen you have shared in the screenshot @happybhalodiyaBrain

**Comment by happybhalodiyaBrain** [comment]
Analyticpage.tsx

`import React from "react";
// Customizable Area Start
import {
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
  StatusBar,
  SafeAreaView,
  FlatList,
  ScrollView,
} from "react-native";
// Customizable Area End
import AnalyticsPageController from "./AnalyticsPageController";
import { scaledSize } from "../../../framework/src/Utilities";
import colors from "./colors";
import Icon from "react-native-vector-icons/MaterialIcons";
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from "react-native-responsive-screen";
import { BarChart } from "react-native-gifted-charts";
import * as Progress from "react-native-progress";

const InvoicebarData = [
  {
    value: 40,
    label: "Jan",
    spacing: 5,
    labelWidth: 30,
    labelTextStyle: { color: "red" },
    frontColor: colors.raised,
  },
  {
    value: 70,
    spacing: 5,
    frontColor: colors.rejected,
  },

  {
    value: 35,
    spacing: 5,
    frontColor: colors.approved,
  },
  {
    value: 25,
    spacing: 5,
    frontColor: colors.pending,
  },
  {
    value: 66,
    spacing: 20,
    frontColor: colors.completed,
  },

  {
    value: 50,
    label: "Feb",
    spacing: 5,
    labelWidth: 30,
    labelTextStyle: { color: "gray" },
    frontColor: colors.raised,
  },
  {
    value: 70,
    spacing: 5,
    frontColor: colors.rejected,
  },

  {
    value: 35,
    spacing: 5,
    frontColor: colors.approved,
  },
  {
    value: 25,
    spacing: 5,
    frontColor: colors.pending,
  },
  {
    value: 66,
    spacing: 20,
    frontColor: colors.completed,
  },

  {
    value: 75,
    label: "Mar",
    spacing: 5,
    labelWidth: 30,
    labelTextStyle: { color: "gray" },
    frontColor: colors.raised,
  },
  {
    value: 70,
    spacing: 5,
    frontColor: colors.rejected,
  },

  {
    value: 35,
    spacing: 5,
    frontColor: colors.approved,
  },
  {
    value: 25,
    spacing: 5,
    frontColor: colors.pending,
  },
  {
    value: 66,
    spacing: 20,
    frontColor: colors.completed,
  },

  {
    value: 30,
    label: "Apr",
    spacing: 5,
    labelWidth: 30,
    labelTextStyle: { color: "gray" },
    frontColor: colors.raised,
  },
  {
    value: 70,
    spacing: 5,
    frontColor: colors.rejected,
  },

  {
    value: 35,
    spacing: 5,
    frontColor: colors.approved,
  },
  {
    value: 25,
    spacing: 5,
    frontColor: colors.pending,
  },
  {
    value: 66,
    spacing: 20,
    frontColor: colors.completed,
  },

  {
    value: 60,
    label: "May",
    spacing: 5,
    labelWidth: 30,
    labelTextStyle: { color: "gray" },
    frontColor: colors.raised,
  },
  {
    value: 70,
    spacing: 5,
    frontColor: colors.rejected,
  },

  {
    value: 35,
    spacing: 5,
    frontColor: colors.approved,
  },
  {
    value: 25,
    spacing: 5,
    frontColor: colors.pending,
  },
  {
    value: 66,
    spacing: 20,
    frontColor: colors.completed,
  },

  {
    value: 65,
    label: "Jun",
    spacing: 5,
    labelWidth: 30,
    labelTextStyle: { color: "gray" },
    frontColor: colors.raised,
  },
  {
    value: 70,
    spacing: 5,
    frontColor: colors.rejected,
  },

  {
    value: 35,
    spacing: 5,
    frontColor: colors.approved,
  },
  {
    value: 25,
    spacing: 5,
    frontColor: colors.pending,
  },
  {
    value: 66,
    spacing: 20,
    frontColor: colors.completed,
  },
];
const barData = [
  {
    value: 40,
    label: "Jan",
    spacing: 5,
    labelWidth: 30,
    labelTextStyle: { color: "red" },
    frontColor: colors.raised,
  },
  {
    value: 70,
    spacing: 5,
    frontColor: colors.approved,
  },

  {
    value: 35,
    spacing: 20,
    frontColor: colors.raised,
  },

  {
    value: 50,
    label: "Feb",
    spacing: 5,
    labelWidth: 30,
    labelTextStyle: { color: "gray" },
    frontColor: colors.raised,
  },
  {
    value: 70,
    spacing: 5,
    frontColor: colors.approved,
  },

  {
    value: 35,
    spacing: 20,
    frontColor: colors.raised,
  },
  {
    value: 75,
    label: "Mar",
    spacing: 5,
    labelWidth: 30,
    labelTextStyle: { color: "gray" },
    frontColor: colors.raised,
  },
  {
    value: 70,
    spacing: 5,
    frontColor: colors.approved,
  },

  {
    value: 35,
    spacing: 20,
    frontColor: colors.raised,
  },
  {
    value: 30,
    label: "Apr",
    spacing: 5,
    labelWidth: 30,
    labelTextStyle: { color: "gray" },
    frontColor: colors.raised,
  },
  {
    value: 70,
    spacing: 5,
    frontColor: colors.approved,
  },

  {
    value: 35,
    spacing: 20,
    frontColor: colors.raised,
  },
  {
    value: 60,
    label: "May",
    spacing: 5,
    labelWidth: 30,
    labelTextStyle: { color: "gray" },
    frontColor: colors.raised,
  },
  {
    value: 70,
    spacing: 5,
    frontColor: colors.approved,
  },

  {
    value: 35,
    spacing: 20,
    frontColor: colors.raised,
  },
  {
    value: 65,
    label: "Jun",
    spacing: 5,
    labelWidth: 30,
    labelTextStyle: { color: "gray" },
    frontColor: colors.raised,
  },
  {
    value: 70,
    spacing: 5,
    frontColor: colors.approved,
  },

  {
    value: 35,
    spacing: 20,
    frontColor: colors.raised,
  },
];
const innvoinceData = [
  {
    id: 0,
    value: "Raised",
    color: colors.raised,
  },
  {
    id: 1,
    value: "Rejected",
    color: colors.rejected,
  },
  {
    id: 2,
    value: "Pending",
    color: colors.pending,
  },
  {
    id: 3,
    value: "Appoved",
    color: colors.approved,
  },
  {
    id: 4,
    value: "Completed",
    color: colors.completed,
  },
];
const projectData = [
  {
    id: 0,
    value: "Ongoing",
    color: colors.pending,
  },
  {
    id: 1,
    value: "Upcoming",
    color: colors.approved,
  },
  {
    id: 2,
    value: "Complted",
    color: colors.raised,
  },
];
const balanceData = [
  {
    id: 0,
    name: "Samsung Advertisment",
    value: "₹45.60K",
    subTitle: "Overall Budget: ₹100.75K",
    progress: 0.4,
  },
  {
    id: 1,
    name: "Pushpa 2",
    value: "₹80.50K",
    subTitle: "Overall Budget: ₹150.50K",
    progress: 0.7,
  },
  {
    id: 2,
    name: "Boat Headphones Advertisment",
    value: "₹65.60K",
    subTitle: "Overall Budget: ₹80K",
    progress: 0.9,
  },
  {
    id: 3,
    name: "Vision - A Short Film",
    value: "₹10.60K",
    subTitle: "Overall Budget: ₹100.75K",
    progress: 0.3,
  },
];

export default class AnalyticsPage extends AnalyticsPageController {
  displayInvoice = ({ item }: { item: any }) => {
    return (
      <View style={styles.typeView}>
        <View style={[styles.dot, { backgroundColor: item.color }]} />
        <Text style={styles.typeText}>{item.value}</Text>
      </View>
    );
  };
  displayProject = ({ item }: { item: any }) => {
    return (
      <View style={styles.typeView}>
        <View style={[styles.dot, { backgroundColor: item.color }]} />
        <Text style={styles.typeText}>{item.value}</Text>
      </View>
    );
  };
  dislayBalanceData = ({ item }: { item: any }) => {
    return (
      <View>
        <View style={styles.balanceConntainer}>
          <Text style={styles.balanceTitle}>{item.name}</Text>
          <View style={styles.progressRow}>
            <View style={{ flex: 8 }}>
              <Progress.Bar
                progress={item.progress}
                width={null}
                color={colors.yellow}
                unfilledColor={colors.lightBlue1}
                borderWidth={0}
              />
            </View>
            <View style={styles.progressValueView}>
              <Text style={styles.progressValue}>{item.value}</Text>
            </View>
          </View>
          <Text style={styles.subTitleText}>{item.subTitle}</Text>
        </View>
        <View style={[styles.borderLine, { borderStyle: "dotted" }]} />
      </View>
    );
  };
  render() {
    // Customizable Area Start
    return (
      <SafeAreaView style={styles.ub_container}>
        <StatusBar backgroundColor={colors.darkYellow} />

        <View style={styles.ub_container}>
          <View style={styles.ub_headerContainer}>
            <TouchableOpacity
              testID="goBack"
              onPress={() => this.goBack()}
              style={styles.ub_backView}
            >
              <Icon name={"arrow-back"} size={20} color={colors.white} />
            </TouchableOpacity>
            <Text style={styles.ub_headerText}>Analytics</Text>
          </View>

          <ScrollView
            style={styles.ub_mainContainer}
            bounces={false}
            keyboardShouldPersistTaps={"handled"}
          >
            <View style={styles.cartContainer}>
              <View style={styles.titleHeader}>
                <Text style={styles.chartTitle}>{"Invoices"}</Text>
                <View style={styles.row}>
                  
                  <TouchableOpacity
                  testID="prevBtn"
                    onPress={() => this._TogglePrev()}
                    style={styles.smallCircle}
                  >
                    <Icon name="chevron-left" size={20} color={colors.black} />
                  </TouchableOpacity>
                  <View style={styles.filterView}>
                    <Text style={styles.filterText}>{this.state.dataFilter[this.state.selectedIndex]}</Text>
                  </View>
                  <TouchableOpacity
                    testID="nextBtn"
                    onPress={() => this._ToggleNext()}
                    style={styles.smallCircle}
                  >
                    <Icon name="chevron-right" size={20} color={colors.black} />
                  </TouchableOpacity>
                </View>
              </View>
              <View style={styles.borderLine} />

              <FlatList
                testID="invoiceFlatList"
                data={innvoinceData}
                horizontal={true}
                renderItem={this.displayInvoice}
              />

              <BarChart
                data={InvoicebarData}
                barWidth={5}
                spacing={30}
                roundedTop
                roundedBottom
                xAxisLabelTextStyle={{ color: "black" }}
                xAxisThickness={0}
                yAxisThickness={0}
                yAxisTextStyle={{ color: "gray" }}
                noOfSections={3}
                maxValue={75}
              />

              <TouchableOpacity
                testID="navigateToInvoiceBtn"
                onPress={() => this.navigateToInvoice()}
                style={styles.buttonContainer}
              >
                <Text style={styles.buttonText}>{"View Detailed Report"}{" "}</Text>
                <Icon name="arrow-forward" size={20} color={colors.white} />
              </TouchableOpacity>
            </View>

            <View style={styles.cartContainer}>
              <View style={styles.titleHeader}>
                <Text style={styles.chartTitle}>{"Projects"}</Text>
                <View style={styles.row}>
                  <TouchableOpacity 
                  onPress={() => this._TogglePrev()}
                  style={styles.smallCircle}>
                    <Icon name="chevron-left" size={20} color={colors.black} />
                  </TouchableOpacity>
                  <View style={styles.filterView}>
                  <Text style={styles.filterText}>{this.state.dataFilter[this.state.selectedIndex]}</Text>
                  </View>
                  <TouchableOpacity 
                  onPress={() => this._ToggleNext()}
                  style={styles.smallCircle}>
                    <Icon name="chevron-right" size={20} color={colors.black} />
                  </TouchableOpacity>
                </View>
              </View>
              <View style={styles.borderLine} />

              <FlatList
                testID="projectFlatlist"
                data={projectData}
                horizontal={true}
                renderItem={this.displayProject}
              />
              <BarChart
                data={barData}
                barWidth={5}
                spacing={30}
                roundedTop
                roundedBottom
                hideRules
                xAxisThickness={0}
                yAxisThickness={0}
                yAxisTextStyle={{ color: "gray" }}
                noOfSections={3}
                maxValue={75}
              />
              <TouchableOpacity
                testID="nnavigateProject"
                onPress={() => this.navigateToProject()}
                style={styles.buttonContainer}
              >
                <Text style={styles.buttonText}>{"View Detailed Report"}{" "}</Text>
                <Icon name="arrow-forward" size={20} color={colors.white} />
              </TouchableOpacity>
            </View>

            <View style={styles.cartContainer}>
              <View style={styles.titleHeader}>
                <Text style={styles.chartTitle}>{"Balance Sheet"}</Text>
                <View style={styles.row}>
                  <View style={styles.smallCircle}>
                    <Icon name="chevron-left" size={20} color={colors.black} />
                  </View>
                  <View style={styles.filterView}>
                    <Text style={styles.filterText}>2021-22</Text>
                  </View>
                  <View style={styles.smallCircle}>
                    <Icon name="chevron-right" size={20} color={colors.black} />
                  </View>
                </View>
              </View>
              <View style={styles.borderLine} />
              <FlatList
                testID="balanceFlatlist"
                data={balanceData}
                renderItem={this.dislayBalanceData}
              />
              <TouchableOpacity
                testID="balanceBtn"
                style={styles.buttonContainer}
              >
                <Text style={styles.buttonText}>{"View Detailed Report"}{" "}</Text>
                <Icon name="arrow-forward" size={20} color={colors.white} />
              </TouchableOpacity>
            </View>
          </ScrollView>
        </View>
      </SafeAreaView>
    );
    // Customizable Area End
  }

  // Customizable Area Start
  // Customizable Area End
}

// Customizable Area Start
const styles = StyleSheet.create({
  ub_container: {
    flex: 1,
    backgroundColor: colors.yellow,
  },
  ub_headerContainer: {
    flexDirection: "row",
    marginTop: 15,
    marginLeft: 16,
    alignItems: "center",
  },
  ub_backView: {
    backgroundColor: "#F7D24A",
    justifyContent: "center",
    alignItems: "center",
    width: 42,
    height: 42,
    borderRadius: 40,
  },
  ub_headerText: {
    color: colors.white,
    fontSize: 18,
    marginLeft: 13,
    fontWeight: "600",
  },
  ub_mainContainer: {
    flex: 1,
    marginTop: 15,
    backgroundColor: colors.white,
    borderTopLeftRadius: 20,
    borderTopEndRadius: 20,
  },
  cartContainer: {
    borderRadius: scaledSize(12),
    borderWidth: 1,
    borderColor: colors.lightBlue1,
    backgroundColor: colors.lightBlue,
    padding: scaledSize(10),
    margin: scaledSize(10),
  },
  titleHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: scaledSize(10),
  },
  chartTitle: {
    fontFamily: "Urbanist",
    fontSize: scaledSize(15),
    fontWeight: "200",
  },
  row: {
    flexDirection: "row",
  },
  smallCircle: {
    width: wp(8),
    height: wp(8),
    borderRadius: scaledSize(16),
    backgroundColor: colors.white,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.lightBlue1,
  },
  filterView: {
    borderRadius: scaledSize(16),
    width: wp(20),
    height: hp(4),
    borderColor: colors.white,
    marginLeft: scaledSize(10),
    marginRight: scaledSize(10),
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
  },
  filterText: {
    fontFamily: "Urbanist",
    fontSize: scaledSize(11),
    fontWeight: "200",
  },
  borderLine: {
    marginTop: scaledSize(5),
    marginBottom: scaledSize(5),
    borderColor: colors.lightBlue1,
    borderWidth: 1,
    height: 1,
    width: "100%",
    borderRadius: 1,
    alignSelf: "center",
  },
  typeView: {
    flexDirection: "row",
    backgroundColor: colors.white,
    padding: scaledSize(10),
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: scaledSize(5),
    paddingVertical: scaledSize(5),
    borderRadius: scaledSize(12),
    marginRight: scaledSize(10),
  },
  dot: {
    width: wp(2),
    height: wp(2),
    borderRadius: scaledSize(20),
    marginRight: scaledSize(5),
  },
  typeText: {
    fontSize: scaledSize(10),
    fontWeight: "100",
    marginRight: scaledSize(5),
  },
  buttonContainer: {
    width: "100%",
    padding: scaledSize(12),
    backgroundColor: colors.black,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: scaledSize(9),
    marginTop: scaledSize(10),
    flexDirection:'row'
  },
  buttonText: {
    fontSize: scaledSize(10),
    color: colors.white,
    fontWeight: "600",
  },
  balanceConntainer: {
    marginTop: scaledSize(5),
  },
  balanceTitle: {
    fontSize: scaledSize(12),
    fontWeight: "100",
  },
  progressRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  progressValue: {
    fontSize: scaledSize(17),
    fontWeight: "400",
  },
  progressValueView: {
    flex: 2.5,
    justifyContent: "center",
    alignItems: "center",
  },
  subTitleText: {
    color: colors.blue1,
    fontSize: scaledSize(10),
  },
});
// Customizable Area End
`


controllerfile 

`import { BlockComponent } from "../../../framework/src/BlockComponent";
import { runEngine } from "../../../framework/src/RunEngine";
import MessageEnum, {
  getName,
} from "../../../framework/src/Messages/MessageEnum";

// Customizable Area Start
// Customizable Area End

export const configJSON = require("./config");
export interface Props {
  navigation: any;
  id: string;
  // Customizable Area Start
  // Customizable Area End
}

interface S {
  // Customizable Area Start
  selectedIndex: number;
  dataFilter: any;
  // Customizable Area End
}

interface SS {
  // Customizable Area Start
  id: any;
  // Customizable Area End
}

export default class AnalyticsPageController extends BlockComponent<
  Props,
  S,
  SS
> {
  // Customizable Area Start

  // Customizable Area End
  apiCreateUserBioCallId: string = "";
  constructor(props: Props) {
    super(props);
    this.receive = this.receive.bind(this);
    // Customizable Area Start
    this.subScribedMessages = [
      getName(MessageEnum.RestAPIResponceMessage),
      getName(MessageEnum.SessionResponseMessage),
    ];

    this.state = {
      selectedIndex: 0,
      dataFilter: ["Yearly", "Monthly", "Weekly"],
    };

    // Customizable Area End
    runEngine.attachBuildingBlock(this, this.subScribedMessages);
  }

  // Customizable Area Start

  navigateToInvoice() {
    this.props.navigation.navigate("InvoicesAnalytics");
  }
  navigateToProject() {
    this.props.navigation.navigate("ProjectAnalytics");
  }
  goBack() {
    this.props.navigation.goBack();
  }
  _ToggleNext() {
    if (this.state.selectedIndex == this.state.dataFilter.length - 1) {
      this.setState({ selectedIndex: 0 });
    } else {
      this.setState((prevState) => ({
        selectedIndex: prevState.selectedIndex + 1,
      }));
    }
  }

  _TogglePrev() {
    if (this.state.selectedIndex == 0){
      this.setState({
        selectedIndex: this.state.dataFilter.length - 1
      });
    }else{
      this.setState((prevState) => ({
        selectedIndex: prevState.selectedIndex - 1,
      }));
    }

  }
  // Customizable Area End
}
`

**Comment by happybhalodiyaBrain** [comment]
okay let me check

**Comment by happybhalodiyaBrain** [comment]
i have check in ios and it is working fine but in android it is not working 
<img width="435" alt="Screenshot 2023-10-31 at 10 03 15 PM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/86781322/990e0fc1-3996-4685-b637-be91c58fd22a">
