### ISSUE TITLE
When noOfSections are given a value other than 10 (default) or 5, there is a misalignment between Y-Axis Labels & Y-Axis Values

### ISSUE THREAD

**Issue by nawafthedistance** [Abhinandan-Kushwaha/react-native-gifted-charts#421]
In Bar Chart with stackData, when the noOfSections are given as any other number other than a multiple of 5, there is a misalignment between Y-Axis Labels & values. Attached are screenshots of the same data with 5,6 and 10 sections. Observe that the values 1, 7 and 8 are misaligned in the chart with 6 Y sections.
Stacks: 
[{"color": "rgba(255,135,26,1)", "value": 5}, {"color": "rgba(107,78,69,1)", "value": 0}]
[{"color": "rgba(255,135,26,1)", "value": 5}, {"color": "rgba(107,78,69,1)", "value": 0}]
[{"color": "rgba(255,135,26,1)", "value": 8}, {"color": "rgba(107,78,69,1)", "value": 0}]
[{"color": "rgba(255,135,26,1)", "value": 7}, {"color": "rgba(107,78,69,1)", "value": 0}]
 [{"color": "rgba(255,135,26,1)", "value": 4}, {"color": "rgba(107,78,69,1)", "value": 0}]
[{"color": "rgba(255,135,26,1)", "value": 0}, {"color": "rgba(107,78,69,1)", "value": 0}]
[{"color": "rgba(255,135,26,1)", "value": 1}, {"color": "rgba(107,78,69,1)", "value": 0}]

![Simulator Screenshot - iPhone 14 Pro - 2023-10-30 at 15 34 34](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/106528931/dfe1c829-724f-4df3-b75b-d0ff316bf240)
![Simulator Screenshot - iPhone 14 Pro - 2023-10-30 at 15 30 23](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/106528931/13bf1758-e386-4d4f-bbe2-fb4488c3519d)
![Simulator Screenshot - iPhone 14 Pro - 2023-10-30 at 15 30 29](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/106528931/0fd499ee-0788-4ede-b634-6340ee961a2e)

Code:
`<BarChart
            stackData={transformedData}
            width={280}
            height={120}
            initialSpacing={0}
            barWidth={20}
            spacing={15}
            xAxisLength={280}
            yAxisThickness={0}
            rulesLength={280}
            rulesType={'solid'}
            rulesColor={palette.barChartRuleLines}
            xAxisColor={colourTheme.barChartRuleLines}
            yAxisLabelContainerStyle={{width: getWidth(15)}}
            yAxisTextStyle={{
              ...textStyles.regular9,
              color: colourTheme.xyAxisLabelContainerColor,
            }}
            noOfSections={5}
          />`

Platform: android & iOS
Version: 1.3.4
RN Version: 0.71.8

**Comment by Abhinandan-Kushwaha** [comment]
Hi @nawafthedistance 👋
I can see a misalignment in the second chart. This is because the labels we see on the Y-axis are not actual labels, they are rounded off. If we divide 10 into 6 sections, we get 1.667, 3.333, 5.000, 6.667... 

To fix this, you can use the `showFractionalValues` prop. This will show Y-axis labels correct to 1 decimal place.
To show labels correct to more decimal places, you can use the `roundToDigits` prop.

This issue is related to https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/35
