### ISSUE TITLE
`scrollX` not defined

### ISSUE THREAD

**Issue by grigorii-horos** [Abhinandan-Kushwaha/react-native-gifted-charts#424]
**Describe the bug**
`scrollX` not defined when I try to use `autoAdjustPointerLabelPosition = true`

**To Reproduce**
I try to set `autoAdjustPointerLabelPosition = true` to `pointerConfig` obj, but I obtain error

**Expected behavior**
Working graph

**Screenshots**
![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/4980269/c29061fb-868d-4567-a9e1-1b555bdb64a7)

 - Device: Android & iOS emulator
 - OS: android 12 
 - Version of the library being used: 1.3.14

**Comment by grigorii-horos** [comment]
This graph works properly when I use `1.3.11`, this bug was added in `1.3.12`

**Comment by Abhinandan-Kushwaha** [comment]
Hi @grigorii-horos 👋
Thanks for pointing this out. It is now fixed in version `1.3.15`🎉
