### ISSUE TITLE
How can I show pointer dynamically on specific point by writing code? 

### ISSUE THREAD

**Issue by kr396** [Abhinandan-Kushwaha/react-native-gifted-charts#427]
As per requirement, I want to show the pointer at a specific position without tapping the graph on the load of the screen. How can I achieve this?

**Comment by ak-spotter** [comment]
Hi @kr396 👋🏼
You can use `dataPointLabelComponent` and related props.

[See documentation](https://gifted-charts.web.app/areachart)

[See props table](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/LineChart/LineChartProps.md#item-description)

<img width="583" alt="label" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/139222298/c98b594d-be74-432c-bc96-0a93274fcd1b">

**Comment by kr396** [comment]
> Hi @kr396 👋🏼 You can use `dataPointLabelComponent` and related props.
> 
> [See documentation](https://gifted-charts.web.app/areachart)
> 
> [See props table](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/LineChart/LineChartProps.md#item-description)
> 
> <img alt="label" width="583" src="https://user-images.githubusercontent.com/139222298/280222401-c98b594d-be74-432c-bc96-0a93274fcd1b.png">

Hi, @ak-spotter , 

Thanks for the quick reply.  But, I need a pointer always on. Currently, it shows once the user taps on the graph and vanishes based on pointerVanishDelay. Also, need to show that pointer on specific point on the graph load. Like, show a pointer on the current month once the graph loads. After that user can move that to view different months' data.

**Comment by Abhinandan-Kushwaha** [comment]
@kr396 The example above shows the **pointer always on**. The code is also in the [documentation link](https://gifted-charts.web.app/areachart) shared above.

Add the properties `dataPointLabelComponent ` and `showStrip` to the data item you want the pointer to be always on.

**Comment by kr396** [comment]
@Abhinandan-Kushwaha @ak-spotter 
How can I set point visibility to always? It shows once the user clicks or scrolls on the graph. I'm not able to find any property in pointer config

**Comment by Abhinandan-Kushwaha** [comment]
@kr396 Don't use pointerConfig, use `dataPointLabelComponent` instead.

Add the properties `dataPointLabelComponent`  and `showStrip` to the data items you want the pointer to be always on.

**Comment by kr396** [comment]
> @kr396 Don't use pointerConfig, use `dataPointLabelComponent` instead.
> 
> Add the properties `dataPointLabelComponent` and `showStrip` to the data items you want the pointer to be always on.

Thanks for the quick response. Can you please help me with this - My requirement is, that I have to show the current month's pointer on the graph load. After that user can see data of any month by scrolling. That's why I'm using a pointer. 

Thanks in advance.

**Comment by Abhinandan-Kushwaha** [comment]
@kr396 Please see the example code on [this link](https://gifted-charts.web.app/areachart)

Open the link and scroll down to this-

![Screenshot_2023-11-04-17-21-07-04_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/cc3642e5-7276-4c37-aa1c-5077bf58982e)

Just copy the code and run it. It solves your use case.

**Comment by Abhinandan-Kushwaha** [comment]
@kr396 
I know you want to show pointer but still no need to use `pointerConfig`
Adding `dataPointLabelComponent` and `showStrip` inside the objects of data array will add a pointer to the specific data points. And the pointer will not disappear automatically.
Comment here if it doesn't help.

**Comment by kr396** [comment]
> @kr396 I know you want to show pointer but still no need to use `pointerConfig` Adding `dataPointLabelComponent` and `showStrip` inside the objects of data array will add a pointer to the specific data points. And the pointer will not disappear automatically. Comment here if it doesn't help.

@Abhinandan-Kushwaha 
Using this I can show pointer to specific point. But it is not scrollable. I cannot move/scroll strip/pointer.

**Comment by Abhinandan-Kushwaha** [comment]
Hey @kr396 👋
Sorry for my late response and the inconvenience due to a misunderstanding on my side.

If I understood correctly, your exact requirement is to show the pointer at a specific position, and then the user should be able to reposition the pointer by touching or scrolling the chart.

Thanks for requesting this feature. I have now added this feature in version `1.3.17`
You just need to add the property `initialPointerIndex` inside the `pointerConfig` object. 

Version `1.3.17` onwards, the following properties are also configurable inside the `pointerConfig` object-
1. initialPointerAppearDelay (number)
2. persistPointer (boolean)

**Comment by kr396** [comment]
> Hey @kr396 👋 Sorry for my late response and the inconvenience due to a misunderstanding on my side.
> 
> If I understood correctly, your exact requirement is to show the pointer at a specific position, and then the user should be able to reposition the pointer by touching or scrolling the chart.
> 
> Thanks for requesting this feature. I have now added this feature in version `1.3.17` You just need to add the property `initialPointerIndex` inside the `pointerConfig` object.
> 
> Version `1.3.17` onwards, the following properties are also configurable inside the `pointerConfig` object-
> 
> 1. initialPointerAppearDelay (number)
> 2. persistPointer (boolean)

Thanks, This is exactly what I wanted. Thank You @Abhinandan-Kushwaha
