### ISSUE TITLE
App Crash for LineChart if maxvalue 0 

### ISSUE THREAD

**Issue by asifbadeghar54** [Abhinandan-Kushwaha/react-native-gifted-charts#430]
ERROR  Invariant Violation: [26949,"RCTView",1,{"onStartShouldSetResponder":true,"onMoveShouldSetResponder":true,"onResponderGrant":true,"onResponderMove":true,"onResponderEnd":true,"onResponderTerminationRequest":true,"position":"absolute","height":"<<NaN>>","bottom":57,"width":15,"zIndex":0,"transform":[{"scaleX":1}]}] is not usable as a native method argument 
 
 below is my component 

 
 const { t, data: actualData = {} } = props;
    const [weekGraphData, setWeekGraphData] = useState([])
    const totalHourMinRef = useRef(0)
    const maxValueRef = useRef(0)
    const totalHoursRef = useRef(0)
    const totalMinutesRef = useRef(0)

    useEffect(() => {
        if (actualData) {
            //plot curve values data on graph
            const dateRange = getlast7Days(t)
            const weekGraphData = dateRange.map((item, index) => {
                let weekDate =getCurrentDate(item.date,'-');
                const backendMappedData = getWeeksData(weekDate,actualData, t)
                return {
                    date: item.date,
                    label: item.day,
                    duration: backendMappedData.duration,
                    value: backendMappedData.value,
                    time: backendMappedData.time,
                    labelComponent: () => customLabel(item.day),

                }
            })
            console.log("weekGraphData.current:::",weekGraphData)
            totalHourMinRef.current = weekGraphData.reduce((total, obj) => obj.duration + total, 0);
            console.log("totalHourMinRef.current:::",totalHourMinRef.current)
            maxValueRef.current = Math.max.apply(Math, weekGraphData.map(function (o) { return o.value; })) + 5;
            console.log("maxValueRef.current:::", maxValueRef.current )
            //small box container data
            totalHoursRef.current = converTimeStampToHoursMinutes(totalHourMinRef.current);
            totalMinutesRef.current = converTimeStampToHoursMinutes(totalHourMinRef.current, 'm');
            setWeekGraphData(weekGraphData)
        }

    }, [actualData])
    
    return  <LineChart
                        horizontalRulesStyle={{ width: Dimensions.get('window').width * 0.745 }}
                        height={200}
                        thickness={4}
                        data={weekGraphData}
                        curved
                        // showVerticalLine
                        color={COLORS.textInputBgColor}
                        spacing={LINE_CHART_WIDTH / 7}
                        hideRules
                        initialSpacing={15}
                        maxValue={maxValueRef.current>0 ?maxValueRef.current:5}
                        hideYAxisText
                        yAxisColor={COLORS.white}
                        yAxisThickness={0}
                        xAxisThickness={1}
                        xAxisColor={COLORS.textLightGrey}
                        hideDataPoints
                        pressEnabled
                        // adjustToWidth={true}
                        // unFocusOnPressOut={false}
                        // pointerConfig pointer scroll Effect 
                        pointerConfig={pointerConfig}
                    />

**Comment by asifbadeghar54** [comment]
Earlier its working  fine there is no data change also  not sure why its giving an error now for maxValue 0 and even for same error for BarChart iam using  "react-native-gifted-charts": "^1.2.22",

**Comment by Abhinandan-Kushwaha** [comment]
Hi @asifbadeghar54 👋
Please use the latest version of the library. Feel free to reopen the issue if it doesn't help.

**Comment by hz-sanaullah** [comment]
Still happening with rn-v0.68.0 and latest versions of each of react-native-svg, react-native-linear-gradient and react-native-gifted-charts. Happening when maxValue=0.
