### ISSUE TITLE
Text Overflowig into charts when xAxisTextNumberOfLines is set more than 1

### ISSUE THREAD

**Issue by sahad00** [Abhinandan-Kushwaha/react-native-gifted-charts#433]
```
   <BarChart
                {...list}
                xAxisTextNumberOfLines={2}
                noOfSections={4}
                barWidth={18}
                barBorderRadius={2}
                hideRules
                formatYLabel={(label) =>
                  label?.length > 4 ? label.slice(0, 3) + '...' : label
                }
                scrollEventThrottle={16}
                xAxisThickness={1}
                xAxisColor={COLOR.GRAY200}
                yAxisColor={COLOR.GRAY200}
                yAxisTextStyle={{
                  color: COLOR.TEXT_TITLE,
                }}
                yAxisLabelWidth={40}
                yAxisThickness={1}
                spacing={35}
              />
```
![Simulator Screenshot - iPhone 15 Pro Max - 2023-11-09 at 01 16 23](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/133844717/d44aa32b-9535-47cb-8fb8-961556b23dac)

I have tried text style with some margin or padding its still not working

**Comment by Abhinandan-Kushwaha** [comment]
@sahad00 
Try using the `labelsExtraHeight` prop

**Comment by sahad00** [comment]
@Abhinandan-Kushwaha not working I have used 

`     <BarChart
                labelsExtraHeight={20}
                {...list}
                xAxisTextNumberOfLines={2}
                noOfSections={4}
                barWidth={18}
                barBorderRadius={2}
                hideRules
                formatYLabel={(label) =>
                  label?.length > 4 ? label.slice(0, 3) + '...' : label
                }
                scrollEventThrottle={16}
                xAxisColor={COLOR.GRAY200}
                yAxisColor={COLOR.GRAY200}
                yAxisTextStyle={{
                  color: COLOR.TEXT_TITLE,
                }}
                yAxisLabelWidth={40}
                yAxisThickness={1}
                spacing={35}
              />`
              
              ![Simulator Screenshot - iPhone 15 Pro Max - 2023-11-09 at 12 19 21](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/133844717/8a3d6cc0-9b1f-46cf-9159-945099be153c)
              
              I have highlighted the background

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sahad00 👋
Thanks for pointing out this issue. I will fix it in the next version.

Till then I have a workaround for you. Try giving a negative marginBottom in `labelTextStyle`. For example-

```js
labelTextStyle: {marginBottom: -20}
```

Add this inside the objects of data array.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sahad00 👋
This has been fixed in version `1.3.17` 🎉

I have also added 2 new props which might help here-
1. xAxisLabelsHeight
2. xAxisLabelsVerticalShift

**Comment by sahad00** [comment]
Thanks @Abhinandan-Kushwaha

**Comment by yathu** [comment]
I also had this problem, I just fixed it, so I'm sharing it because it might be useful to someone.

```
      <StackChart
        chartData={chartData}
        yAxisLabel={yAxisLabel}
        initialSpacing={20}
        endSpacing={0}
        spacing={25}
        barWidth={20}
        xAxisTextNumberOfLines={1}
        xAxisLabelTextStyle={{
          textAlign: "right",
          fontSize: 11,
          color: "#696974",
          fontFamily: "Inter_500Medium",
          transform: [{ rotate: "-60deg" }],
          width: 110,
          marginLeft: -60,
        }}
        labelsExtraHeight={40}
        xAxisLabelsHeight={60}
        labelsDistanceFromXaxis={35}
      />
```

<img width="1206" height="2622" alt="Image" src="https://github.com/user-attachments/assets/01ecfcb8-e407-41b7-9ea5-6c43114824a7" />
