### ISSUE TITLE
After upgrading to react native 0.72.5 the BarChart causes a crash (typescript)

### ISSUE THREAD

**Issue by Eliajn** [Abhinandan-Kushwaha/react-native-gifted-charts#435]
**BarChart is crashing the application after upgrading react native to 0.72.5**

I had the BarChart working before upgrading react native where it uses the new 

**To Reproduce**

```
const initialBarData = [
    {
      value: 0,
      frontColor: "rgba(137,220,101, 0.5)",
    },
    {
      value: 0,
      spacing: 2,
      labelWidth: 30,
      labelTextStyle: {
        color: "gray",
        width: responsiveScreenWidth(15),
        paddingLeft: responsiveScreenWidth(3),
      },
      frontColor: "#89DC65",
    },
    {
      value: 0,
      frontColor: "rgba(137,220,101, 0.5)",
    },
    {
      value: 0,
      spacing: 2,
      labelWidth: 30,
      labelTextStyle: {
        color: "gray",
        width: responsiveScreenWidth(15),
        paddingLeft: responsiveScreenWidth(3),
      },
      frontColor: "#89DC65",
    }
]

           <BarChart
                data={graphData}
                barBorderRadius={3}
                barWidth={responsiveScreenWidth(4)}
                spacing={responsiveScreenWidth(4)}
                roundedTop={false}
                roundedBottom={false}
                xAxisThickness={0}
                yAxisThickness={0}
                yAxisTextStyle={{
                  color: "gray",
                  fontSize: responsiveFontSize(1.2),
                }}
                yAxisLabelWidth={35}
                noOfSections={4}
                dashWidth={1}
                initialSpacing={5}
              />
```

**Screenshots**

 - Device: iphone 15 pro max 
 - OS: ios 17
 - Version of the library being used 1.3.16

![Simulator Screenshot - iPhone 15 Pro Max - 2023-11-10 at 22 22 26](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/34067448/13e92615-668f-4e86-980b-d3db16046e32)
![Simulator Screenshot - iPhone 15 Pro Max - 2023-11-10 at 22 22 14](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/34067448/2ff2ad78-3e23-4e23-be2a-b75904b9999a)

**Comment by Eliajn** [comment]
I solved this issue by adding values to `maxValue` greater than `0 `

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Eliajn Thanks for providing the solution.

If you are on latest react-native version, you should use the latest versions of `react-native-svg` and `react-native-linear-gradient` as well. I am using the latest versions of all 3 and I don't face this isuue.

**Comment by hz-sanaullah** [comment]
> Hi @Eliajn Thanks for providing the solution.
> 
> If you are on latest react-native version, you should use the latest versions of `react-native-svg` and `react-native-linear-gradient` as well. I am using the latest versions of all 3 and I don't face this isuue.

Hi @Abhinandan-Kushwaha this issue is still happening with rn-v0.68.0 and latest versions of each of react-native-svg, react-native-linear-gradient and react-native-gifted-charts. Happening when maxValue=0.
