### ISSUE TITLE
Donut chart is distorted if the value is greater than 237

### ISSUE THREAD

**Issue by theambidextrous** [Abhinandan-Kushwaha/react-native-gifted-charts#436]
**Describe the bug**
Whenever a single data set is 100% and the rest are at 0%, Donut chart is distorted if the `value`  is greater than 237

Example input:

```
[{"color": "#FB853C", "count": 2, "id": 1, "name": "merchandise", "percentage": 100, "spent": "860.00", "value": 860}, {"color": "#00704A", "count": 0, "id": 2, "name": "restaurant", "percentage": 0, "spent": "0.00", "value": 0}, {"color": "#05174d", "count": 0, "id": 3, "name": "travel", "percentage": 0, "spent": "0.00", "value": 0}]
```

**To Reproduce**
1. initialise a donut with 3 data sets.
2. Amend the data to ensure a single set is 100% and the rest are 0%
3. Amend the `value` attribute to be more than 237
4. See error - the chart will look something like an acute angle

**Expected behavior**
The chart should show with 100%

**Screenshots**
![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/13588614/c1a936e6-72ad-43b0-bd3e-6268270cf383)

 - Device: iPhones and Android
 - OS: 16, 13 respectively
 - Version of the library being used: 1.3.9

**Comment by Abhinandan-Kushwaha** [comment]
Hi @theambidextrous 👋
Thanks for pointing out this issue. It has been fixed in version `1.3.17`
Please update to the latest version.
