### ISSUE TITLE
Stepped Line Chart

### ISSUE THREAD

**Issue by gromspys** [Abhinandan-Kushwaha/react-native-gifted-charts#438]
Is there a way to create stepped line chart like [this one](https://www.highcharts.com/demo/stock/step-line)?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @gromspys 👋
Thanks for requesting this feature. It is now available in version `1.3.17`🎉

To render a step chart, just pass the prop `stepChart` to the `<LineChart>` component.

**Comment by gromspys** [comment]
> Hi @gromspys 👋 Thanks for requesting this feature. It is now available in version `1.3.17`🎉
> 
> To render a step chart, just pass the prop `stepChart` to the `<LineChart>` component.

Thanks for the fast delivery of the new feature! That's what I mean, but I see a slight problem. For example, on December 1 our price is 10, and on December 10 the price is 20. This means that the chart should go up not on December 5, but on December 10. I would appreciate it if you would fix this in the next release.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @gromspys 👋
Thanks for pointing this out. It has been fixed in version `1.3.18` 🎉

However, I have also kept the previous way of rendering the steps. To render it as before, we can pass the prop
```js
edgePosition = {EdgePosition.AROUND_DATA_POINT}
```

**Comment by gromspys** [comment]
Thanks @Abhinandan-Kushwaha. It's what I need!
