### ISSUE TITLE
Able to add one line in bar chart, but can we add more than one line in a Bar chart.

### ISSUE THREAD

**Issue by DeepakAnthati** [Abhinandan-Kushwaha/react-native-gifted-charts#440]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

 - Version of the library being used [e.g. 1.2.17]

**Additional context**

**Comment by Abhinandan-Kushwaha** [comment]
Hi @DeepakAnthati 👋
Thanks for requesting this feature. From version `1.3.18` onwards, we support 2 lines in Bar charts. 🎉

To render the second line, we need to use the `lineData2` prop.
The second line can be customised using the `lineConfig2` prop.

**Comment by DeepakAnthati** [comment]
Thank you @Abhinandan-Kushwaha !!
