### ISSUE TITLE
Will  stacked bar chart supports Top Label Component with the sum of the stacks at top ?

### ISSUE THREAD

**Issue by sahad00** [Abhinandan-Kushwaha/react-native-gifted-charts#446]
I tried rendering one manually with tooltip , but is their a way to do it so that labels will always be shown above the stacked bar

![Simulator Screenshot - iPhone 12 - 2023-11-23 at 02 49 49](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/133844717/84d48b9b-d92d-47d4-bc3e-7ac8e62f8808)

**Comment by Abhinandan-Kushwaha** [comment]
Yes @sahad00 
This can be achieved by adding the `topLabelComponent` property to each object in the `stackData` array.

You can programmatically add `topLabelComponent` to each object in the `stackData` array using the below code-

```js
stackData.forEach(stackItem => {
  stackItem.topLabelComponent = () => (
    <Text>
      {stackItem.stacks.map(stack => stack.value).reduce((v, a) => v + a)}
    </Text>
  );
});
```

Here's an example-

<img width="325" alt="Screenshot 2023-11-24 at 6 13 02 AM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/e843b794-113f-4284-8720-b9c5a2deeb4f">

The code for the above chart is-

```js
import React from 'react';
import {Text, View} from 'react-native';
import {BarChart} from 'react-native-gifted-charts';

const RoundStackBar = () => {
  const stackData = [
    {
      stacks: [
        {value: 10, color: 'orange'},
        {value: 20, color: '#4ABFF4', marginBottom: 2},
      ],
      label: 'Jan',
    },
    {
      stacks: [
        {value: 10, color: '#4ABFF4'},
        {value: 11, color: 'orange', marginBottom: 2},
        {value: 15, color: '#28B2B3', marginBottom: 2},
      ],
      label: 'Mar',
    },
    {
      stacks: [
        {value: 14, color: 'orange'},
        {value: 18, color: '#4ABFF4', marginBottom: 2},
      ],
      label: 'Feb',
    },
    {
      stacks: [
        {value: 7, color: '#4ABFF4'},
        {value: 11, color: 'orange', marginBottom: 2},
        {value: 10, color: '#28B2B3', marginBottom: 2},
      ],
      label: 'Mar',
    },
  ];

  stackData.forEach(stackItem => {
    stackItem.topLabelComponent = () => (
      <Text>
        {stackItem.stacks.map(stack => stack.value).reduce((v, a) => v + a)}
      </Text>
    );
  });

  return (
    <View>
      <BarChart
        width={340}
        rotateLabel
        spacing={40}
        noOfSections={4}
        barBorderRadius={20}
        stackData={stackData}
      />
    </View>
  );
};
```

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sahad00 👋
For stacked bar charts, `showValuesAsTopLabel` now shows the sum of stack item values at the top of each stack. This feature is available from version `1.3.25` onwards.

**Comment by waheed25** [comment]
@Abhinandan-Kushwaha  i am trying to change the color of the top label on the stacked charts, it's getting changed for Bar charts but for stacked it's not working, trying to use `labelTextStyle` to override the color of `showValuesAsTopLabel ` labels, how can i do this?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @waheed25 👋
Thanks for reporting this issue.

For now you can use the property `topLabelTextStyle` inside the objects of `stackData` array.

**Comment by Abhinandan-Kushwaha** [comment]
@waheed25 
The prop `topLabelTextStyle` now works for stacked Bar charts just like it used to work for simple Bar charts.
Please use the latest version of the library.
