### ISSUE TITLE
Spacing below my chart

### ISSUE THREAD

**Issue by nmasi322** [Abhinandan-Kushwaha/react-native-gifted-charts#448]
**Describe the bug**
I have an extra spacing/padding below my chart and can't find a prop to remove it.

**My code**
<LineChart
        data={currentData}
        areaChart
        stepHeight={25}
        isAnimated
        adjustToWidth
        noOfSections={4}
        pointerConfig={{
          pointerLabelHeight: 30,
          pointerLabelWidth: 50,
          pointerColor: "#6E40C0",
          pointerStripColor: "#FF0000",
          strokeDashArray: [4],
        }}
        thickness={2}
        color="#533090"
        yAxisTextStyle={{ color: "#B4B4B4" }}
        xAxisLabelTextStyle={{ color: "#B4B4B4" }}
        startOpacity={0.2}
        endOpacity={0.01}
        spacing={22}
        startFillColor={"rgba(61, 55, 241, 0.2)"}
        endFillColor={"rgba(61, 55, 241, 0)"}
        backgroundColor="#fff"
        rulesColor="#E0E0E0"
        hideDataPoints
        yAxisColor="#E0E0E0"
        xAxisColor="#E0E0E0"
      />

**Screenshots**
<img width="334" alt="Screenshot 2023-11-23 at 4 41 06 AM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/74861009/90614822-214c-43ea-acde-548e3bdb5929">

 - Device: [e.g. iPhone14 Plus]
 - OS: => IOS 16
 - Version of the library being used => 1.3.18

**Comment by sahad00** [comment]
Yes, it happening for every charts @Abhinandan-Kushwaha

**Comment by nmasi322** [comment]
Is there a way I can remove the space please? It looks really odd in my app 🥲

**Comment by Abhinandan-Kushwaha** [comment]
Hi @nmasi322 @sahad00 I will release a new version with the fix in a few hours

**Comment by Abhinandan-Kushwaha** [comment]
Hi @nmasi322 @sahad00 This has been fixed in version `1.3.23`🎉
