### ISSUE TITLE
app carsh for data undefined

### ISSUE THREAD

**Issue by Rinku222** [Abhinandan-Kushwaha/react-native-gifted-charts#449]
hey, Thnx for such a great package.
I am having a scenario where i am using line chart with 2 lines in it using "data" and "data2" props. Initially if "data" is provided and "data2" is kept undefined it works pretty fine but if i change the value from "data2" to an array with valid values and keep "data" undefined the app crashes giving error :-Thread 1: EXC_BAD_ACCESS (code=1, address=0xbeadddab3080). I have a functionality where user can decide whether he wants to see 1st line on chart or 2nd line or both the lines at the same time. This error is visible in Xcode. I hope i am able to explain the scenario. i am using  "react-native-gifted-charts": "^1.3.18" version of the package. Let me know if you need any more information on crash. 
Thanks in advance.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Rinku222 👋
I understand your use case, but the library doesn't support `data2` if `data` is undefined.

Your use case has 3 states-

1. Only data1 is displayed
2. Only data2 is displayed
3. Both data1 and data2 are displayed together

This can be achieved as follows-
1. To display only data1, pass the prop `data={data1}`
2. To display only data2, pass the prop `data={data2}`
3. To display both together, pass both the props `data={data1}` and `data2={data2}`
