### ISSUE TITLE
Can we customize y axis line based on data?

### ISSUE THREAD

**Issue by ngocht143** [Abhinandan-Kushwaha/react-native-gifted-charts#455]
Hi @Abhinandan-Kushwaha,
I'm using the BarChart and it almost met all my requirements.
But is there available to customize a range from a specific min value to max value with different colors (red dashed and green dashed)? 
My code:
`<BarChart
                    data={data}
                    stepHeight={30}
                    frontColor={'#075BB5'}
                    initialSpacing={screenWidth / 4.5}
                    width={screenWidth / 1.5}
                    noOfSections={3}
                    barWidth={72}
                    rulesColor={'#E5E6EB'}
                    xAxisColor={'#C9CDD4'}
                    yAxisColor={'transparent'}
                    yAxisLabelWidth={60}
                    showValuesAsTopLabel
                />`

Please check the attached screenshot:
![Screenshot at Nov 30 14-31-15](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/7259317/6adba264-c01a-47d0-bfe5-dcdab03cd0f2)
Looking forward to hear your reply.

**Comment by ngocht143** [comment]
Hi @Abhinandan-Kushwaha 
The solution `showReferenceLine1` is worked for me. 
But is there possible to show label above the reference line, and set background between 2 lines?
Thank you so much.

**Comment by ngocht143** [comment]
Hi @Abhinandan-Kushwaha 
**Updated**: I resolved my issue "show label above the reference line" by set style of `labelText` prop. And i still have issue with  how to set background between two reference lines?
Thanks for your support. :)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ngocht143 👋
Here's a work-around to set the background color between 2 reference lines-

The `backgroundColor` between 2 reference lines can be set using a 3rd reference line of appropriate width and color.

<img width="307" alt="Screenshot 2023-12-11 at 1 06 38 AM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/2410921f-f867-4709-9c0f-150e02f7c36e">

The code for the above chart is-

```ts
const dataBack = [
  {value: 180},
  {value: 80},
  {value: 270},
  {value: 300},
  {value: 500},
  {value: 300},
];

return (
  <LineChart
    data={dataBack}
    hideRules
    showReferenceLine1
    referenceLine1Position={250}
    showReferenceLine2
    referenceLine2Position={400}
    showReferenceLine3
    referenceLine3Position={252}
    referenceLine3Config={{
      color: 'lightgreen', // use 'rgba(r,g,b,a)' to set opacity along with color
      type: ruleTypes.SOLID,
      thickness: 58,
    }}
  />
);
```
