### ISSUE TITLE
Render referenceline over linechart (zindex)

### ISSUE THREAD

**Issue by audn** [Abhinandan-Kushwaha/react-native-gifted-charts#459]
Is it possible to get the text inside `referenceLine1` to be shown over the line chart?
<img width="406" alt="image" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/21041399/c7a9b9e4-e562-4226-af4e-70fcf42dde94">

I tried setting `z-index` on the `labelTextStyle`, but no luck.
```tsx
 referenceLine1Position={80}
  referenceLine1lConfig={{
    color: tw.color('white/50'),
    labelText: `${user?.healthProfile?.targetCalories}`,
    type: 'dashed',
    labelTextStyle: twStyle(
      'text-on-200 z-50 '
    ),
  }}
  showReferenceLine1={true}
```

**Comment by Abhinandan-Kushwaha** [comment]
Hi @audn For me the reference line is getting displayed over the line chart. I'm not sure how it is appearing under the line for you. Can you share your code along with the data?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @audn 
Please use the latest version of the library.
