### ISSUE TITLE
How can I remove padding top of chart?

### ISSUE THREAD

**Issue by quoc-dev** [Abhinandan-Kushwaha/react-native-gifted-charts#461]
**Describe the bug**
<img width="252" alt="Screen Shot 2023-12-08 at 16 00 30" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/13532376/6269c9f8-931c-4e1f-8461-b411c165cb99">

I need set height like image below, could you provide any solution for that

![Screen Shot 2023-12-08 at 16 03 20](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/13532376/bcc5f98a-5d70-461e-ab7e-702e1aa8ebd7)

Thanks so much

**Comment by Abhinandan-Kushwaha** [comment]
Hi @quoc-dev 👋
Thanks for requesting this feature. You can use the prop `trimYAxisAtTop`  to remove the top padding of the chart.
It is available from version `1.3.25` onwards.
