### ISSUE TITLE
Chart has dynamic height

### ISSUE THREAD

**Issue by giltheodor** [Abhinandan-Kushwaha/react-native-gifted-charts#467]
The height of the chart is changing when the maxValue of yAxis change.

When there are no data available, the maxValue of yAxis is equal to 0, as a result I set `stepValue={10}` and `numOfSection={5}`

In the example below the container (backgroundColor: 'yellow') has property `height:260` and `paddingTop: 20`

The `LineChart` component has `height={190}` and `overflowTop={20}`

https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/111180498/ea90dc0d-6598-4e20-9dea-5c1f2bfd4c7f

if  I set `stepValue={10}` and `numOfSection={1}` then the result is:

![Simulator Screenshot - iPhone 15 - 2023-12-12 at 19 56 55](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/111180498/d44a55d1-ee5e-4130-967e-7cd548b8d0bc)

**Comment by giltheodor** [comment]
LineChart Component
`<LineChart
          // line-chart style and animation
          isAnimated
          // animateOnDataChange={true}
          animateTogether={true}
          animationDuration={1000}
          width={screenWidth}
          height={200}
          overflowTop={20}
          thickness={1}
          maxValue={getYAxisMaxValue().numOfSections * getYAxisMaxValue().step}
          noOfSections={getYAxisMaxValue().numOfSections}
          stepValue={getYAxisMaxValue().step}
          spacing={activeTab === 0 ? 33 : 7}
          initialSpacing={56}
          endSpacing={100}
          hideRules
          hideDataPoints={activeTab !== 0}
          data={targetValues}
          data2={values}
          color={
            showChartWithoutTarget ? 'transparent' : theme.colorTokens.S[30]
          }
          color2={
            unit === '%' && getYAxisMaxValue().maxValue === 0
              ? 'transparent'
              : getYAxisMaxValue().maxViewValue === 0
              ? 'transparent'
              : theme.colors_ds.PRIMARY_ICON_MAIN
          }
          dataPointsColor={
            showChartWithoutTarget ? 'transparent' : theme.colorTokens.S[30]
          }
          dataPointsColor2={
            unit === '%' && getYAxisMaxValue().maxValue === 0
              ? 'transparent'
              : getYAxisMaxValue().maxViewValue === 0
              ? 'transparent'
              : theme.colors_ds.PRIMARY_ICON_MAIN
          }
          dataPointsRadius={activeTab === 0 ? 2.5 : 1.5}
          //2nd set of data - archived values

          strokeDashArray2={[0, 0]}
          strokeDashArray={[3, 3]}
          // yAxis Configuration
          showYAxisIndices={false}
          yAxisTextStyle={[
            style.yAxisTextStyle,
            getYAxisMaxValue().maxViewValue === 0 && {color: 'transparent'},
          ]}
          yAxisIndicesHeight={1}
          yAxisIndicesWidth={7}
          yAxisIndicesColor={theme.colorTokens.N[60]}
          yAxisColor={theme.colorTokens.N[60]}
          hideOrigin={true}
          // xAxis Configuration
          showXAxisIndices={false}
          xAxisLength={screenWidth - 100}
          xAxisIndicesHeight={7}
          xAxisIndicesWidth={1}
          xAxisIndicesColor={theme.colorTokens.N[60]}
          xAxisColor={theme.colorTokens.N[60]}
          pointerConfig={{
            resetPointerOnDataChange: false,
            showPointerStrip: maxYAxisValue !== 0,
            persistPointer: true,
            stripOverPointer: true,
            shiftPointerLabelX: -35,
            pointerStripHeight: 210,
            pointerStripColor: theme.colors_ds.NEUTRAL_BORDER_WEAK,
            pointerStripWidth: showPointerConfig ? 3 : 0,
            radius: showPointerConfig ? (activeTab === 0 ? 3.5 : 2.5) : 0,
            initialPointerIndex: 0,
            pointerColor: showChartWithoutTarget
              ? 'transparent'
              : theme.colorTokens.S[30],
            pointer2Color: theme.colors_ds.PRIMARY_ICON_MAIN,
            pointerLabelComponent: labelComponent,
          }}
          endIndex={getEndIndexOfValues()}
          endIndex2={getEndIndexOfValues()}
        />`

Function to calculate yAxis Max Value, Step and numOfSections:

`const getYAxisMaxValue = () => {
    const maxValue = Math.round(
      data.reduce(
        (max, curr) => (max > curr.avg_value ? max : curr.avg_value),
        0,
      ),
    );
    let maxTargetValue = 0;
    if (data[0].target !== undefined) {
      maxTargetValue = Math.round(
        data.reduce(
          (max, curr) => (max > curr.avg_value ? max : curr.avg_value),
          0,
        ),
      );
    }

    maxYAxisValue =
      maxValue > maxTargetValue || showChartWithoutTarget
        ? maxValue
        : maxTargetValue;

    const numOfSection =
      maxYAxisValue === 0
        ? 5
        : maxYAxisValue > 2000
        ? Math.round(maxYAxisValue / (stepValue * 3))
        : maxYAxisValue > 1000
        ? Math.round(maxYAxisValue / (stepValue * 2))
        : Math.round(maxYAxisValue / stepValue);

    const stepVal =
      maxYAxisValue > 2000
        ? stepValue * 3
        : maxYAxisValue > 1000
        ? stepValue * 2
        : stepValue;

    if (unit === '%') {
      return {
        maxValue: maxYAxisValue > 0 ? 100 : 0,
        maxViewValue: 100,
        step: 25,
        numOfSections: 4,
      };
    } else {
      return {
        maxValue: maxYAxisValue,
        maxViewValue: maxYAxisValue,
        step: stepVal,
        numOfSections: numOfSection + 1,
      };
    }
  };`

**Comment by Abhinandan-Kushwaha** [comment]
@giltheodor I would recommend you to pass `maxValue` explicitly instead of letting it be `0` in case of no data.

**Comment by giltheodor** [comment]
Hi @Abhinandan-Kushwaha 

The maxValue is calculated from numOfSections (never equals to zero because `numOfSections: numOfSection + 1`) multiplied by the stepVal which is a prop form the parent component and in the example is equal to 10.

The problem is that the maxValue is calculated based on the data provided and it is different each week or month

**Comment by Abhinandan-Kushwaha** [comment]
Got it @giltheodor 
We are getting charts of different heights for different values because the extra height at the top is `stepHeight/2` by default. 
I will fix this by changimg it to a constant value in the next release.

Till then I can suggest you a workaround. Try using the prop `trimYAxisAtTop` . This sets the extra height at the top to `0`

**Comment by giltheodor** [comment]
Hi @Abhinandan-Kushwaha 

The bug still remain after I add the prop `trimYAxisAtTop`. 

Please find below some examples with all the cases and fixed stepHeight. The yellow container has `height` 240 and the LineChart has `height` 210 and `overflowTop` 20.
![Simulator Screenshot - iPhone 15 - 2023-12-16 at 11 27 17](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/111180498/21edac2b-2fe6-4324-83b4-675bb2a4f056)
![Simulator Screenshot - iPhone 15 - 2023-12-16 at 11 27 25](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/111180498/0c1ea53a-9615-453f-b396-9d9ed308e7c9)
![Simulator Screenshot - iPhone 15 - 2023-12-16 at 11 26 53](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/111180498/ed3e6798-ba8b-4354-9a13-149b4e8e978f)
![Simulator Screenshot - iPhone 15 - 2023-12-16 at 11 27 03](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/111180498/7d5988ad-9f4a-4cd1-925e-459815d8c446)
![Simulator Screenshot - iPhone 15 - 2023-12-16 at 11 27 10](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/111180498/17ee9380-72a7-4762-8e6f-4e267de07ded)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @giltheodor 
This has been fixed in version `1.3.27`🎉

Earlier, charts used to have an extra length of Y axis equal to `sectionHeight/2` at the top. Due to this, charts' height used to change along with `sectionHeight`. Fixed this by making the default value of `yAxisExtraHeight` to a constant value which equals 1/20th of the chart height.

Also, you can provide a custom value of `yAxisExtraHeight` by passing it as a prop.

**Comment by giltheodor** [comment]
Hi @Abhinandan-Kushwaha,

 I use as you suggested the prop `yAxisExtraHeight`. Thank you very much for this because it was what I was looking for initially. 

Can you check these examples and find out why there is this empty space on top of the chart and as a result the pointerLabelComponent can not render correctly. 
![Simulator Screenshot - iPhone 15 - 2023-12-18 at 17 54 48](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/111180498/ac3a8858-d4d1-4625-a56a-db4d2c80b7de)

![Simulator Screenshot - iPhone 15 - 2023-12-18 at 17 55 19](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/111180498/48e25123-4e39-47fb-9fd7-5c1e254fc2a8)

It seems that when a have bigger max value the problem is more visible.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @giltheodor, thanks for pointing out the issue.
It has been fixed in version `1.3.28`🎉
