### ISSUE TITLE
Showing value outside the chart

### ISSUE THREAD

**Issue by lukaswvd** [Abhinandan-Kushwaha/react-native-gifted-charts#469]
Hi, I am having issues showing the value of a "hovered" datapoint i the chart. I want to display the value above/outside the chart. I have tried doing this by using setState on the getPointerProps. This sets the value as expected but i get the following error:

![Screenshot 2023-12-15 at 10 28 29](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/79897805/24926cea-e507-45a7-8812-8c4c6dfc3e72)

Use a setState inside the getPointerProps attribute

Parent component containing chart:
![Screenshot 2023-12-15 at 10 29 58](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/79897805/12417827-398e-4666-a509-687bcab72603)

Chart:
![Screenshot 2023-12-15 at 10 30 15](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/79897805/28030d3b-ca0b-4477-b58a-dffb355788f0)

Any help is appreciated!

**Comment by Abhinandan-Kushwaha** [comment]
Hi @lukaswvd 
Thanks for pointing out this bug. It has been fixed in version `1.3.27` 🎉
