### ISSUE TITLE
Error: Error setting property 'pointerEvents' of RNSVGSvgView box-none 

### ISSUE THREAD

**Issue by christophby** [Abhinandan-Kushwaha/react-native-gifted-charts#472]
**Describe the bug**
In the PieChart I'm getting the error
> Error setting property 'pointerEvents' of RNSVGSvgView with tag #2673: UIView base class does not support pointerEvent value: box-none

**To Reproduce**
In my case it throws the error as soon as I render the PieChart

**Expected behavior**
No error thrown

**Screenshots**
<img width="260" alt="image" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/12933672/70c6cd4a-f69e-4295-b840-b470f304ff11">

 - Device: iPhone 15 Simulator
 - OS: iOS 17.2
 - Version of the library being used: 1.3.27
 - React Native 0.68.2

**Comment by Abhinandan-Kushwaha** [comment]
Hi @christophby 👋
Can you please share the code and data?

**Comment by Abhinandan-Kushwaha** [comment]
Hi Christoph,
 I am unable to repro the issue. Can you please share the code and data?

Thanks & Regards.

**Comment by christophby** [comment]
@Abhinandan-Kushwaha it seems to be a problem with React Native 0.68.2. So far I didn't have any issues with that RN and this library.

* `npx react-native@0.68.2 init AwesomeProject --version 0.68.2`

```typescript
<PieChart
  strokeWidth={2}
  strokeColor={'#f9fafb'}
  donut
  showGradient
  radius={140}
  innerRadius={90}
  data={[
    {
      value: 50.49,
      color: '#08d419',
      gradientCenterColor: '#2057be',
    },
    {
      value: 49.51,
      color: '#2f4b7c',
      gradientCenterColor: '#2f4b7c',
    },
  ]}
/>
```

**Comment by Abhinandan-Kushwaha** [comment]
Hi @christophby 
Can you check in version `1.3.28`?

**Comment by saurabhafk** [comment]
Hi @Abhinandan-Kushwaha, I was having the same issue, and no it is not yet resolved. 
In your code in PieChart -> main.tsx, line 204, you're using 'box-none' for RN version > 7, but box-none is not supported in versions greater than 7 either, as my version is 0.71

**Comment by saurabhafk** [comment]
@Abhinandan-Kushwaha I guess replacing "box-none" with "auto" will solve the issue in both index and main files, it worked for me

**Comment by christophby** [comment]
@Abhinandan-Kushwaha for me with RN version 0.68.2 it's working now, thank you 🙌🏼

**Comment by Abhinandan-Kushwaha** [comment]
@saurabhafk Can you please check which version of react-native started supporting `'box-none'` for <Svg> elements?

**Comment by saurabhafk** [comment]
@Abhinandan-Kushwaha it was 0.64 I think, but idk why it was not working even in my 0.71 version :(

**Comment by Abhinandan-Kushwaha** [comment]
Hi @saurabh Sorry, I meant which version of react-native started supporting 'box-none' for `<Svg>` elements?

We might need to check with the `react-native-svg` package.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @saurabhafk @christophby 👋
I am now using `box-none` for react native versions `0.72` onwards. This fix is available in _react-native-gifted-charts_ versions `1.3.30` and above.
