### ISSUE TITLE
Question: Stepped Line Chart

### ISSUE THREAD

**Issue by lukaswvd** [Abhinandan-Kushwaha/react-native-gifted-charts#477]
Hi!

I was wondering if it is possible to configure the LineChart in such a way that it displays like stepped lines (see image below)?

<img width="749" alt="Screenshot 2023-12-22 at 14 43 09" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/79897805/d8e083a6-dc22-4d6e-a56a-60c49e74edfc">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @lukaswvd this feature is supported.
Just add the prop `stepChart` to the `<LineChart>` component.
