### ISSUE TITLE
Text Strings

### ISSUE THREAD

**Issue by leonardodecastro-programmer** [Abhinandan-Kushwaha/react-native-gifted-charts#479]
When I try to use the library, I receive the following error: `Text strings must be rendered within a <Text> Component.`
Code Example:
`
<View style={styles.container}>
  <LineChart
      areaChart
      curved
      data={data}
  />;
  <StatusBar style="auto" />
</View>
`

**Comment by leonardodecastro-programmer** [comment]
It is possible to encapsulate the content within the <Text> component, however, it is not appropriate and causes several problems.

**Comment by rzfzr** [comment]
@leonardodecastro-programmer how did you solve this?

**Comment by Abhinandan-Kushwaha** [comment]
@rzfzr 
I guess the problem was the semi-colon after the closing of the `<LineChart />` tag-
```js
<View style={styles.container}>
  <LineChart areaChart curved data={data} />; <-- remove this semicolon
  <StatusBar style="auto" />
</View>
```
