### ISSUE TITLE
Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.

### ISSUE THREAD

**Issue by vuongbkdn** [Abhinandan-Kushwaha/react-native-gifted-charts#48]
I use barchart it warns:
Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
    in RCTView (at View.js:32)
    in View (at ThreeDBar/index.tsx:159)
    in RCTView (at View.js:32)
    in View (at ThreeDBar/index.tsx:75)
    in ThreeDBar (at RenderBars.tsx:333)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (at TouchableOpacity.js:228)
    in TouchableOpacity (at TouchableOpacity.js:278)
    in TouchableOpacity (at RenderBars.tsx:264)
    in RenderBars (at BarChart/index.tsx:1025)
    in AndroidHorizontalScrollContentView (at ScrollView.js:1674)
    in AndroidHorizontalScrollView (at ScrollView.js:1792)
    in ScrollView (at ScrollView.js:1818)
    in ScrollView (at BarChart/index.tsx:966)
    in RCTView (at View.js:32)
    in View (at BarChart/index.tsx:956)
    in BarChart (at HomeScreen.js:48)
    in RCTView (at View.js:32)
    in View (at HomeScreen.js:47)
    in HomeScreen (at SceneView.tsx:126)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:118)
    in SceneView (at useDescriptors.tsx:210)
    in RCTView (at View.js:32)
    in View (at Screen.tsx:63)
    in RCTView (at View.js:32)
    in View (at Background.tsx:13)
    in Background (at Screen.tsx:58)
    in Screen (at BottomTabView.tsx:129)
    in MaybeFreeze (at src/index.native.tsx:229)
    in RNSScreen (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (at src/index.native.tsx:208)
    in Screen (at ScreenFallback.tsx:37)
    in MaybeScreen (at BottomTabView.tsx:122)
    in RNSScreenContainer (at src/index.native.tsx:277)
    in ScreenContainer (at ScreenFallback.tsx:28)
    in MaybeScreenContainer (at BottomTabView.tsx:93)
    in RCTView (at View.js:32)
    in View (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at BottomTabView.tsx:92)
    in BottomTabView (at createBottomTabNavigator.tsx:116)
    in Unknown (at createBottomTabNavigator.tsx:115)
    in BottomTabNavigator (at Main.js:16)
    in Main (at SceneView.tsx:126)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:118)
    in SceneView (at useDescriptors.tsx:210)
    in RCTView (at View.js:32)
    in View (at DebugContainer.native.tsx:27)
    in DebugContainer (at NativeStackView.native.tsx:71)
    in MaybeNestedStack (at NativeStackView.native.tsx:230)
    in MaybeFreeze (at src/index.native.tsx:229)
    in RNSScreen (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (at src/index.native.tsx:208)
    in Screen (at NativeStackView.native.tsx:176)
    in SceneView (at NativeStackView.native.tsx:278)
    in RNSScreenStack (at src/index.native.tsx:160)
    in ScreenStack (at NativeStackView.native.tsx:269)
    in NativeStackViewInner (at NativeStackView.native.tsx:323)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:46)
    in SafeAreaProviderCompat (at NativeStackView.native.tsx:322)
    in NativeStackView (at createNativeStackNavigator.tsx:67)
    in NativeStackNavigator (at App.js:17)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:430)
    in BaseNavigationContainer (at NavigationContainer.tsx:132)
    in ThemeProvider (at NavigationContainer.tsx:131)
    in NavigationContainerInner (at App.js:16)
    in App (at SVONLINE_/index.js:14)
    in ThemeProvider (at Provider.tsx:104)
    in RCTView (at View.js:32)
    in View (at PortalHost.tsx:125)
    in Portal.Host (at Provider.tsx:102)
    in Provider (at SVONLINE_/index.js:13)
    in Main (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
please help me fix this error
thanks you!
code:
import {BarChart} from 'react-native-gifted-charts';
import React, {useEffect} from 'react';
import {View} from 'react-native';

const HomeScreen = () => {
  const barData = [
    {
      value: 230,
      label: 'Jan',
      frontColor: '#4ABFF4',
      sideColor: '#23A7F3',
      topColor: '#92e6f6',
    },
    {
      value: 180,
      label: 'Feb',
      frontColor: '#79C3DB',
      sideColor: '#68BCD7',
      topColor: '#9FD4E5',
    },
    {
      value: 195,
      label: 'Mar',
      frontColor: '#28B2B3',
      sideColor: '#0FAAAB',
      topColor: '#66C9C9',
    },
    {
      value: 250,
      label: 'Apr',
      frontColor: '#4ADDBA',
      sideColor: '#36D9B2',
      topColor: '#7DE7CE',
    },
    {
      value: 320,
      label: 'May',
      frontColor: '#91E3E3',
      sideColor: '#85E0E0',
      topColor: '#B0EAEB',
    },
  ];
  useEffect(() => {
    
  }, []);
  return (
    <View>
      <BarChart
        showFractionalValue
        showYAxisIndices
        hideRules
        noOfSections={4}
        maxValue={400}
        data={barData}
        barWidth={40}
        sideWidth={15}
        isThreeD
        side="right"
      />
    </View>
  );
};
export default HomeScreen;

**Comment by Abhinandan-Kushwaha** [comment]
Hi, @vuongbkdn I see an empty return block at the end of your code.
