### ISSUE TITLE
population pyramid

### ISSUE THREAD

**Issue by nehalasim** [Abhinandan-Kushwaha/react-native-gifted-charts#481]
I am trying to develop a population pyramid using the stackdata. But when I convert them into horizontal format is messed up...
please check bellow image as reference
![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/47064533/5cb38b0b-d70b-42d3-9124-3d38080df7d3)

I want to develop a population pyramid like below image....please anyone able to help me to format  the chart like below image,
![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/47064533/8e867406-41b2-4011-a399-2a71e97bbd81)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @nehalasim 
Thanks for requesting this feature. It's not supported yet. I will add this feature and release a new version in 1 or 2 days.

**Comment by nehalasim** [comment]
Thank you, i will wait for your update... thank you for your quick response...

**Comment by nehalasim** [comment]
hi,
is there any update?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @nehalasim 
Sorry for the delay. The code is ready, will deploy it today.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @nehalasim 👋
Population Pyramid charts are now supported from version `1.3.29` onwards.🎉
 See [Population Pyramid props](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/PopulationPyramid/PopulationPyramid.md)
 
 Here's an example-
 ```ts
 import React from 'react';
import {View} from 'react-native';
import {PopulationPyramid} from 'react-native-gifted-charts';

const PopulationChart = () => {
  const popData = [
    {left: 30, right: 40, midAxisLabel: '~115'},
    {left: 40, right: 44, midAxisLabel: '~105'},
    {left: 55, right: 57, midAxisLabel: '~95'},
    {left: 94, right: 87, midAxisLabel: '~85'},
    {left: 90, right: 88, midAxisLabel: '~75'},
    {left: 88, right: 86, midAxisLabel: '~65'},
  ];

  return (
    <View style={{backgroundColor: 'white', flex: 1}}>
      <PopulationPyramid
        data={popData}
        yAxisLabelTexts={[
          '0-10',
          '10-20',
          '20-30',
          '30-40',
          '40-50',
          '50-60',
          '60-70',
          '70-80',
          '80-90',
          '90-100',
          '100-110',
          '110-120',
        ].reverse()}
        yAxisLabelFontSize={9}
        showYAxisIndices
        showMidAxis
        midAxisLabelFontSize={10}
        midAxisLabelColor={'gray'}
        leftBarLabelColor={'blue'}
        rightBarLabelColor={'red'}
        midAxisLeftColor={'blue'}
        midAxisRightColor={'red'}
      />
    </View>
  );
};

export default PopulationChart;
```

The output is-

<img width="362" alt="pyr" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/61acb95d-06ef-48bb-9b02-f856b67c0d03">

Try the `showValuesAsBarLabels` and `showSurplus` props for your requirement.
