### ISSUE TITLE
How to use charts in automatic mode?

### ISSUE THREAD

**Issue by IoTManagerProject** [Abhinandan-Kushwaha/react-native-gifted-charts#483]
Thank You for this library!
Most popular charting libraries support automatic mode.
When a chart is set to automatic mode, it means that the chart will automatically adjust its minimum and maximum values based on the data that is being displayed. This can be useful when dealing with large sets of data, as it allows the chart to adapt to changes in the data without requiring manual adjustments to the axis scales. 

I apologize for the confusion. I could not find such a mode in your library. I conducted many experiments with your library.

 ```
        let noOfSections = 10;
        maxValue = Math.max(...data.map((p) => p.value));
        minValue = Math.min(...data.map((p) => p.value));

        setChartValues({
          ...chartValues,
          maxValue: maxValue * (1 - minValue / maxValue),
          minValue: minValue,
          stepValue: maxValue / noOfSections,
          noOfSections: noOfSections,
        });
        
        <LineChart
        spacing={70} //Distance between 2 consecutive bars in the Bar chart
        initialSpacing={0} //distance of the first data point from the Y axis
        endSpacing={15} //отступ справа
        color="#3B82F6"
        scrollToEnd
        maxValue={chartValues.maxValue}
        noOfSections={chartValues.noOfSections} //количество горизонтальных линий
        stepValue={chartValues.stepValue}
        //mostNegativeValue={130}
        yAxisOffset={chartValues.minValue}
        yAxisTextNumberOfLines={1}
        //hideYAxisText
        //stepHeight={200}
        dataPointsColor="#3B82F6"
        //pointerConfig={{}} //режим курсора
        showScrollIndicator={true}
        xAxisType="solid"
        height={300}
        width={Dimensions.get('window').width - 85}
        overflowBottom={20}
        dataPointsRadius={3}
        showValuesAsDataPointsText //показать значения
        textShiftY={-10}
        showVerticalLines
        onDataChangeAnimationDuration={500}
        isAnimated={true}
        animateOnDataChange={true}
        data={chData}
        curved
        rotateLabel
        rulesColor={colorScheme === 'dark' ? '#38383b' : 'lightgray'} //цвет горизонтальных линий
        verticalLinesColor={colorScheme === 'dark' ? '#38383b' : 'lightgray'} //цвет вертикальных линий
        rulesThickness={1}
        thickness={2} //толщина линии
        animationDuration={400}
        areaChart //включает заполнение
        yAxisTextStyle={{ color: 'gray', fontSize: 12, margin: 0 }} //стиль обозначений y
        yAxisLabelWidth={25}
        //secondaryYAxis //включить вторую ось
        xAxisLabelTextStyle={{ color: 'gray', fontSize: 12, margin: 0 }} //слиль обозначений x
        startFillColor={'#3B82F6'}
        endFillColor={'#3B82F6'}
        startOpacity={0.4}
        endOpacity={0.1}
        backgroundColor={colorScheme === 'dark' ? '#27272a' : 'white'} //rgb(63 63 70)
        rulesType="solid"
        yAxisColor={colorScheme === 'dark' ? '#38383b' : 'gray'} //цвет вертикальной линейки
        xAxisColor={colorScheme === 'dark' ? '#38383b' : 'gray'} //цвет горизонтальной линейки
      />
```

I used this calculations to get chats in auto mode. But Y scale in this case is wrong. 

Could you please give me way how to run your charts in auto scaling mode?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @IoTManagerProject 👋

Are you talking about automatically adjusting the values on the Y-axis on data change? It's already working.
Here's an example-

```ts
const App = () => {
  const iData = [
    {value: 180},
    {value: 80},
    {value: 270},
    {value: 300},
    {value: 500},
    {value: 80},
  ];

  const [data, setData] = useState(iData);

  const onButtonPress = () => {
    setData(data.map(item => ({value: item.value * 2})));
  };

  return (
    <>
      <BarChart data={data} />
      <TouchableOpacity onPress={onButtonPress}>
        <Text>{'Button'}</Text>
      </TouchableOpacity>
    </>
  );
};
```
The output is-

https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/4e6ee1ea-7ab2-4b9b-b445-0ca620e1a37b

Notice that the Y-axis labels (and maxValue) are auto-updating on data change (on button press).

If you want the Y-axis labels to auto-update on scroll, based on the current values getting rendered on screen, do let me know. It's not supported yet, but I can work on it.

**Comment by airowe** [comment]
> Hi @IoTManagerProject 👋
> 
> Are you talking about automatically adjusting the values on the Y-axis on data change? It's already working. Here's an example-
> 
> ```ts
> const App = () => {
>   const iData = [
>     {value: 180},
>     {value: 80},
>     {value: 270},
>     {value: 300},
>     {value: 500},
>     {value: 80},
>   ];
> 
>   const [data, setData] = useState(iData);
> 
>   const onButtonPress = () => {
>     setData(data.map(item => ({value: item.value * 2})));
>   };
> 
>   return (
>     <>
>       <BarChart data={data} />
>       <TouchableOpacity onPress={onButtonPress}>
>         <Text>{'Button'}</Text>
>       </TouchableOpacity>
>     </>
>   );
> };
> ```
> 
> The output is-
> 
>  autoMax.mov 
> Notice that the Y-axis labels (and maxValue) are auto-updating on data change (on button press).
> 
> If you want the Y-axis labels to auto-update on scroll, based on the current values getting rendered on screen, do let me know. It's not supported yet, but I can work on it.

@Abhinandan-Kushwaha Did you ever get this working to auto-update on scroll by chance?

**Comment by IoTManagerProject** [comment]
Thank you for this update!

**Comment by harishgupta01** [comment]
@IoTManagerProject  @Abhinandan-Kushwaha Is there a way to make this work for x axis as well ? Lets say I have a filter outside to select 2 Week, 3 week, 2 Month etc , though I will filter out the data and pass it but can we somehow make sure the x axis labels gets adjusted as per filter selection ? e.g. I will require more labelInterval if select 2 month to accommodate the complete chart in the provided chart width but 1 day interval if select 1 week data since I can accommodate 7 labels. Please note that I need to show all the data point, its just the label which need to be adjusted to show all data at once
