### ISSUE TITLE
LineChart Crash when data.length is 1, everything fine when data is not available or more than 1

### ISSUE THREAD

**Issue by oottoohh** [Abhinandan-Kushwaha/react-native-gifted-charts#484]
**Describe the bug**
LineChart Crash when data.length is 1, everything fine when data is not available or more than 1.

**To Reproduce**
my data : 
const listdata = {
      id:M0003K3W
      mileage:8000
      inputDate:31/08/2023
      category:MILEAGE
      fuelType:null
      fuelAmount:null
      cost:null
      frontTirePressure:null
      rearTirePressure:null
}
const generateLineChartData = () => {
      const data = listdata
        ?.slice()
        .reverse()
        .map((item, index) => ({
          value: item?.mileage ?? 0,
          label: item.inputDate?.slice(0, -5) ?? "",
        }))

      const result = data
      console.log("🚀  ~ generateLineChartData ~ data:", result)
      //OUTPUT :  
      //[
      //   "🚀 ~ generateLineChartData ~ data:",
      //   [
      //     {
      //       "value": 8000,
      //       "label": "31/08"
      //     }
      //   ]
      // ]
      return result
    }
**My Component**
<LineChart
              data={generateLineChartData()}
              pointerConfig={{
                pointerColor: color.astraBlue,
                pointerStripWidth: 2,
                pointerStripColor: color.astraBlue,
                pointerStripUptoDataPoint: true,
                autoAdjustPointerLabelPosition: false,
                pointerVanishDelay: 5000,
                pointerLabelComponent: () => {
                  return (
                    <View
                      style={
                        listdata.length > 3
                          ? getLabelStyle()
                          : styles.containerPointerLabelRight
                      }
                    >
                      <Text
                        text={`${
                          numberPrettier(generateLineChartData()[pointerIndex]?.value, "") ?? ""
                        } KM`}
                        style={styles.textTooltip}
                      />
                    </View>
                  )
                },

                strokeDashArray: [6, 4],
              }}
              disableScroll
              getPointerProps={onDataPressed}
              yAxisSide={"right"}
              width={SCREEN_WIDTH - 110}
              color={color.astraBlue}
              noOfSections={7}
              thickness={3}
              initialSpacing={40}
              endSpacing={20}
              yAxisTextStyle={styles.textAxisLabel}
              yAxisColor={color.white}
              xAxisColor={color.white}
              yAxisLabelWidth={50}
              yAxisLabelSuffix={"km"}
              yAxisOffset={
                listdata.length === 1 ||
                listdata.every((data) => data.mileage === listdata[0].mileage)
                  ? 0
                  : Math.min(...listdata.map((item) => item.mileage))
              }
              maxValue={
                listdata.length === 1 ||
                listdata.every((data) => data.mileage === listdata[0].mileage)
                  ? Math.max(...listdata.map((item) => item.mileage))
                  : Math.max(...listdata.map((item) => item.mileage)) -
                    Math.min(...listdata.map((item) => item.mileage))
              } // stepValue * noOfSections
              stepValue={
                listdata.length === 1 ||
                listdata.every((data) => data.mileage === listdata[0].mileage)
                  ? Math.max(...listdata.map((item) => item.mileage)) / 7
                  : (Math.max(...listdata.map((item) => item.mileage)) -
                      Math.min(...listdata.map((item) => item.mileage))) /
                    7
              } // maxValue / noOfSections
              endIndex={
                generateLineChartData().length === 1
                  ? generateLineChartData().length
                  : generateLineChartData().length - 1
              }
              showFractionalValues={Math.max(...listdata.map((item) => item.mileage)) < 7}
              roundToDigits={1}
              startFillColor={color.astraBlue}
              startOpacity={0.7}
              endFillColor={color.white}
              endOpacity={0.5}
              areaChart
              adjustToWidth
              pressEnabled
              showStripOnPress
              showTextOnPress
              hideRules
              customDataPoint={() => {
                return (
                  <View style={styles.pointerOuterCircle}>
                    <View style={styles.pointerInnerCircle} />
                  </View>
                )
              }}
            /><LineChart
              data={generateLineChartData()}
              pointerConfig={{
                pointerColor: color.astraBlue,
                pointerStripWidth: 2,
                pointerStripColor: color.astraBlue,
                pointerStripUptoDataPoint: true,
                autoAdjustPointerLabelPosition: false,
                pointerVanishDelay: 5000,
                pointerLabelComponent: () => {
                  return (
                    <View
                      style={
                        listdata.length > 3
                          ? getLabelStyle()
                          : styles.containerPointerLabelRight
                      }
                    >
                      <Text
                        text={`${
                          numberPrettier(generateLineChartData()[pointerIndex]?.value, "") ?? ""
                        } KM`}
                        style={styles.textTooltip}
                      />
                    </View>
                  )
                },

                strokeDashArray: [6, 4],
              }}
              disableScroll
              getPointerProps={onDataPressed}
              yAxisSide={"right"}
              width={SCREEN_WIDTH - 110}
              color={color.astraBlue}
              noOfSections={7}
              thickness={3}
              initialSpacing={40}
              endSpacing={20}
              yAxisTextStyle={styles.textAxisLabel}
              yAxisColor={color.white}
              xAxisColor={color.white}
              yAxisLabelWidth={50}
              yAxisLabelSuffix={"km"}
              yAxisOffset={
                listdata.length === 1 ||
                listdata.every((data) => data.mileage === listdata[0].mileage)
                  ? 0
                  : Math.min(...listdata.map((item) => item.mileage))
              }
              maxValue={
                listdata.length === 1 ||
                listdata.every((data) => data.mileage === listdata[0].mileage)
                  ? Math.max(...listdata.map((item) => item.mileage))
                  : Math.max(...listdata.map((item) => item.mileage)) -
                    Math.min(...listdata.map((item) => item.mileage))
              } // stepValue * noOfSections
              stepValue={
                listdata.length === 1 ||
                listdata.every((data) => data.mileage === listdata[0].mileage)
                  ? Math.max(...listdata.map((item) => item.mileage)) / 7
                  : (Math.max(...listdata.map((item) => item.mileage)) -
                      Math.min(...listdata.map((item) => item.mileage))) /
                    7
              } // maxValue / noOfSections
              endIndex={
                generateLineChartData().length === 1
                  ? generateLineChartData().length
                  : generateLineChartData().length - 1
              }
              showFractionalValues={Math.max(...listdata.map((item) => item.mileage)) < 7}
              roundToDigits={1}
              startFillColor={color.astraBlue}
              startOpacity={0.7}
              endFillColor={color.white}
              endOpacity={0.5}
              areaChart
              adjustToWidth
              pressEnabled
              showStripOnPress
              showTextOnPress
              hideRules
              customDataPoint={() => {
                return (
                  <View style={styles.pointerOuterCircle}>
                    <View style={styles.pointerInnerCircle} />
                  </View>
                )
              }}
            />
**Expected behavior**
Line chart renderered with 1 data

**Screenshots**
![Simulator Screenshot - iPhone 14 Pro - 2024-01-02 at 14 31 31](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/15274901/f1e513d1-acc9-427a-a6c5-df784828fc44)

 - Device: iPhone14 Pro Emulator
 - OS:  iOS 16.4
 - Version of the library being used : v1.3.27

**ERROR**
[
  "[5199,\"RCTView\",{\"width\":\"<<Infinity>>\"}] is not usable as a native method argument",
  "Fatal"
]

**Comment by Abhinandan-Kushwaha** [comment]
Hi @oottoohh 
Thanks for reporting this issue. It has been fixed in version `1.3.29`🎉
