### ISSUE TITLE
not smooth line in linechart

### ISSUE THREAD

**Issue by Rinku222** [Abhinandan-Kushwaha/react-native-gifted-charts#485]
**Describe the bug**
i am using line chart. 
my data set is :- 
[
  {
    "date": "2023-12-27",
    "isZero": true,
    "labelName": "Mood",
    "shift": false,
    "value": 0
  },
  {
    "date": "2023-12-28",
    "isZero": true,
    "labelName": "Mood",
    "shift": false,
    "value": 6
  },
  {
    "date": "2023-12-29",
    "isZero": true,
    "labelName": "Mood",
    "shift": false,
    "value": 9
  },
  {
    "date": "2023-12-30",
    "hideDataPoint": true,
    "isZero": true,
    "labelName": "Mood",
    "shift": false,
    "value": 8
  },
  {
    "date": "2023-12-31",
    "hideDataPoint": true,
    "isZero": true,
    "labelName": "Mood",
    "shift": true,
    "value": 7
  },
  {
    "date": "2024-01-01",
    "isZero": true,
    "labelName": "Mood",
    "shift": true,
    "value": 6
  },
  {
    "date": "2024-01-02",
    "isZero": true,
    "labelName": "Mood",
    "shift": true,
    "value": 9
  }
]

as you can see the values are whole numbers.I have attached the screenshot of chart produced using these data points. As you can see the curver from friday to monday is not smooth even though the points are whole numbers. Can you help me with this issue what wrog is done from my end using this package. the dotted lines are the values where the user has not entered the values so i have averaged out the score and changed those values from null to some value toto show dotted lines in this scenario.
![Simulator Screenshot - iPhone 12 mini - 2024-01-02 at 15 23 30](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/62506478/632d45ae-677e-48f9-b65d-2f2f01dbf0f6)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Rinku222 👋
Try using the prop `curveType={CurveType.QUADRATIC}`

See https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/474#issuecomment-1861036464
