### ISSUE TITLE
tried to register two views with the same name RNCWebView

### ISSUE THREAD

**Issue by minh-dai** [Abhinandan-Kushwaha/react-native-gifted-charts#49]

**Comment by Abhinandan-Kushwaha** [comment]
No proper description, and not reported for past 3 months.
Closing the issue.

**Comment by jorgegvallejo** [comment]
I ran into a similar issue due to having a dependency already installed (react-native-svg in my case), and it was fixed by just removing it from the package.json and re-installing.
