### ISSUE TITLE
How do I show label on referenceLine of BarChart

### ISSUE THREAD

**Issue by aprizaprasetio** [Abhinandan-Kushwaha/react-native-gifted-charts#493]
Hi, I love your library, because there have many feature that support for kind of graph development. But I have some issue, it refer the BarChart Component. The BarChart did I use is show the horizontal target line. Ofcourse I had read this [closed issue](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/38). I need to render the label in the right of line. My problem is, I don't found the solution.
This is my current chart :
![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/100743280/5ec06219-cffd-4ff1-8134-a93e14ec5a6b)
I have to remove all yAxisLabel except 90%/ or the label target.
Hopefully you can help me, sorry for my bad english.
Thank you.

**Comment by ak-spotter** [comment]
Hi @aprizaprasetio Can you share an image of the expected chart that you want to achieve?

**Comment by Abhinandan-Kushwaha** [comment]
Try using the `yAxisLabelTexts` prop-

```ts
yAxisLabelTexts={[,,,,,,,,,'90%',]}
```

**Comment by aprizaprasetio** [comment]
> Try using the `yAxisLabelTexts` prop-
> 
> ```ts
> yAxisLabelTexts={[,,,,,,,,,'90%',]}
> ```

Thank you for your solution response, but what chart I expected is only render the 90% label, and not the others. I'm trying to fill other yAxisLabelTexts with undefined/null/empty string, it render 0 automatically not hide the label.

But, Alhamdulillah I found the _tricky way._ So, I configured hideYAxisText to true and style the referenceLine1Config label:
`
hideYAxisText
showReferenceLine1
referenceLine1Config={{
            ...
            labelTextStyle: {
              position: 'absolute',
              right: -30,
              bottom: -8,
            },
          }}
`

This is the actually chart on the app :
![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/100743280/4375ec42-0610-4122-9c37-b7926b098558)

Anyway, thank you for the support guys, I hope you guys can maintain and grow this community.❤️❤️❤️
