### ISSUE TITLE
Dynamic Y axis labels

### ISSUE THREAD

**Issue by rahulmedicharla** [Abhinandan-Kushwaha/react-native-gifted-charts#502]
**Describe the bug**
I have looked for a while and haven't found a way to change the scale of the y axis so that instead of starting at 0, it starts and ends at a specified number and adjusts the positioning of the line chart accordingly.

Please help!

**To Reproduce**
Create any line chart.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @rahulmedicharla 
To change the starting value on the Y-axis, use the prop `yAxisOffset`, and for end-value, use the `maxValue` prop.
See [the props table for Line and area charts](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/LineChart/LineChartProps.md).

Other useful props for modifying the y-axis are- `noOfSections`, `stepHeight` etc
