### ISSUE TITLE
App Crashed after build Apk

### ISSUE THREAD

**Issue by alamgir8** [Abhinandan-Kushwaha/react-native-gifted-charts#503]
I'm using this package for showing charts, I'm using the latest version react native and Expo. It worked okay locally without any issues, but once I built the APK by Expo EAS build then it crashed on a real device after installing the app.

**Comment by hkellou-vitalcare** [comment]
Are you rendering large data ? Can you provide more context / code for this ?
Also please specify your device/os version and more details in order to help you

**Comment by alamgir8** [comment]
Hi @hkellou-vitalcare 
I'm sorry for the late reply. The data wasn't large.  My Android version is 13. If I say a more specific reason, it's for BarChart.

**Comment by 0x10Ayoub** [comment]
@alamgir8 can you make sure that you only render when you have data, if you pass an empty array it will crash

**Comment by alamgir8** [comment]
> @alamgir8 can you make sure that you only render when you have data, if you pass an empty array it will crash

The Array wasn’t empty when i was tested.

**Comment by BlackBear69420** [comment]
Hello 

> @alamgir8 can you provide the logs or a demo

Hi, I'm getting same issue. Did you guys find any solution to this?

**Comment by alamgir8** [comment]
Hi,
@BlackBear69420 and @0x10Ayoub  I didn't fix that issue so I removed this package from my project and used custom charts. 

Thanks

**Comment by rajat-0007** [comment]
Hey , I am getting the same issue, I guess it is related to some version mismatch in gradle or so (might be wrong). The app works fine locally and when I create debug apk, It crashes when I create prod apk.

**Comment by rajat-0007** [comment]
Hey, I figured it out.... The problem is due to the `react-native-svg` package. The property fill is causing errors with some other packages. You just have to navigate to `android/app/proguard-rules.pro` and add the following lines
`-keep public class com.horcrux.svg.** {*;}`

**Comment by Abhinandan-Kushwaha** [comment]
Please use the latest versions of `react-native-svg` and `react-native-linear-gradient`

**Comment by hz-sanaullah** [comment]
> Please use the latest versions of `react-native-svg` and `react-native-linear-gradient`

Still happening with rn-v0.68.0 and latest versions of each of react-native-svg, react-native-linear-gradient and react-native-gifted-charts. Happening when maxValue=0.
