### ISSUE TITLE
onLongPress prop [Feature Request]

### ISSUE THREAD

**Issue by izniburak** [Abhinandan-Kushwaha/react-native-gifted-charts#506]
Hi, 

I couldn't find the `onLongPress` prop for the BarChart component. I think it would be useful for all chart types in order to provide extra functionalities on our apps. 

Do you have any plan for that? Or could you please add it to the ToDo list as a first priority?

Thanks.

**Comment by Abhinandan-Kushwaha** [comment]
Thanks @izniburak for requesting this feature. I am about to release a new version today. I will add this feature in this release.

**Comment by izniburak** [comment]
Good news! Thanks @Abhinandan-Kushwaha . I'm looking forward to see the new version!

**Comment by Abhinandan-Kushwaha** [comment]
Hi @izniburak 
`onLongPress` is now available from version `1.4.1` onwards. It can be passed as a prop, or as a property to individual data items (similar to `onPress`)
