### ISSUE TITLE
Error: Unable to resolve module gifted-charts-core

### ISSUE THREAD

**Issue by priyanshop** [Abhinandan-Kushwaha/react-native-gifted-charts#509]
![Screenshot 2024-01-23 at 11 52 20 AM](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/73154019/c034c9e6-7e2c-46f0-838a-220b8adfb4f4)

Any solution of this

**Comment by priyanshop** [comment]
@Abhinandan-Kushwaha @christophby

**Comment by Abhinandan-Kushwaha** [comment]
Hi @priyanshop 
Please install [gifted-charts-core](https://www.npmjs.com/package/gifted-charts-core) -

```
npm i gifted-charts-core
```

**Comment by priyanshop** [comment]
> Hi @priyanshop Please install [gifted-charts-core](https://www.npmjs.com/package/gifted-charts-core) -
> 
> ```
> npm i gifted-charts-core
> ```

Thank you @Abhinandan-Kushwaha

**Comment by Abhinandan-Kushwaha** [comment]
Hi @priyanshop 
It has been in this PR- https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/pull/514
which got merged and released in version `1.4.1`

Please use the latest version of the library.
