### ISSUE TITLE
When yAxisLabelWidth changes, the width changes, but the block not

### ISSUE THREAD

**Issue by Critically** [Abhinandan-Kushwaha/react-native-gifted-charts#51]
When yAxisLabelWidth changes, the width changes, but the block where the chart enters when moving does not change
![skin](https://user-images.githubusercontent.com/4048161/147277858-d84df831-e818-4525-8b89-2bbb5efb76ab.jpg)

As you can see, i can swipe it after yAxisThickness

**Comment by Critically** [comment]
I'm found solution, to fix this you need to find file node_modules->react-native-gifted-charts->src->BarChart->index.tsx and on 969 line, change ScrollView style marginLeft from static 35 to yAxisLabelWidth variable

**Comment by Abhinandan-Kushwaha** [comment]
Hi, @Critically Thanks for pointing out the issue and providing the solution! 🤗

I have made the change and updated the repo. It's available in version `0.2.3` 🎉
