### ISSUE TITLE
Unable to resolve module 'gifted-charts-core'

### ISSUE THREAD

**Issue by christophby** [Abhinandan-Kushwaha/react-native-gifted-charts#510]
Imo `gifted-charts-core` should be included in the dependencies of [react-native-gifted-charts](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts) and not needed to be installed manually, wdyt?

Currently you have to `yarn add gifted-charts-core` manually which can lead to unmatching libs in the future.

Using **v1.4.1**

**Comment by Abhinandan-Kushwaha** [comment]
Hi @christophby 
You are right. I will put it as a dependency in the next release.

But JFYI,
I tested it today, created a brand new react native project and installed `react-native-gifted-charts` (along with svg and gradient libraries)

And it worked without having to install `gifted-charts-core`.

**Comment by christophby** [comment]
That's weird. For me, it didn't after upgrade.

**Comment by araphiel** [comment]
@Abhinandan-Kushwaha https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/pull/514

**Comment by Abhinandan-Kushwaha** [comment]
Thanks for the PR @araphiel !
I have added a comment. Please resolve it, so that I can merge your PR.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @araphiel 
I have merged your PR and released a new version `1.4.2`. It should fix the issue.
