### ISSUE TITLE
BarChart: stepValue behaves unexpected

### ISSUE THREAD

**Issue by christophby** [Abhinandan-Kushwaha/react-native-gifted-charts#511]
Hey Abhinandan!
I want to define the y-axis values interval. stepValue is the property for this, right?

```jsx
const data: () => stackDataItem[] = () => [
  {stacks: [{value: 123}], label: 'Jan'},
  {stacks: [{value: 18}], label: 'Feb'},
  {stacks: [{value: 100}], label: 'Mar'},
  {stacks: [{value: 256}], label: 'Jun'},
];

<BarChart
  barWidth={40}
  stepValue={100}
  spacing={24}
  noOfSections={5}
  stackData={data()}
  rulesType="solid"
  yAxisThickness={0}
  xAxisThickness={1}
  xAxisTextNumberOfLines={2}
  showScrollIndicator={true}
  scrollToEnd={true}
/>
```

**Current behaviour:**

`stepValue={undefined}`
  
<img width="338" alt="SCR-20240123-lliv" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/12933672/32b3fefd-90ea-4e90-bbaa-6b3884804954">

`stepValue={100}`
<img width="362" alt="SCR-20240123-lllj" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/12933672/8d846dce-23f3-47e4-ba46-b9a08a1f4a81">

**Expected behavior:**
Y-Axis shows **0, 100, 200, 300**... and chart scales correctly.

**Using 1.4.1**

**Comment by Abhinandan-Kushwaha** [comment]
@christophby Yes, `stepValue` is the right prop. I will fix it in the next release.

Might have messed up while refactoring with `gifted-charts-core`, to avoid such issues I will add thorough tests very soon.

For now, you can try fixing it by passing the props like `maxValue` [See the docs](https://gifted-charts.web.app/barchart/#propsIllustration)

<img width="768" alt="stepVal" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/c0d0bcc3-7f3b-4e4f-b720-d1fe41ee76ec">

**Comment by christophby** [comment]
@Abhinandan-Kushwaha it's the same behavior on older versions (e.g. 1.3.33).
I can't fix it using `maxValue`.

You can also add negative values like this:

```typescript
  const data: () => stackDataItem[] = () => [
    {stacks: [{value: 123}], label: 'Jan'},
    {stacks: [{value: 18}], label: 'Feb'},
    {stacks: [{value: 100}], label: 'Mar'},
    {stacks: [{value: 256}], label: 'Jun'},
    {stacks: [{value: -51}, {value: 5, color: '#776464'}], label: 'Jun'},
  ];
```

which leads to weird behavior. It doesn't show the y-axis below the x-axis anymore.

Thank you for looking into it!

**Comment by Abhinandan-Kushwaha** [comment]
Hi @christophby 

If you want to set `stepValue={100}` and `noOfSection={5}`, then you must set `maxValue` to `500`.
Only then the relation becomes valid-
```js
maxValue = noOfSections * stepValue;
```
Setting `maxValue={500}` and `noOfSections={5}` in your above code, produces the below chart-

<img width="303" alt="Screenshot 2024-01-24 at 12 33 33 AM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/f7ca9b0e-39bd-4e28-a79b-ca2d7dd76a38">

And with below configuration-
```js
stepValue={100}
noOfSections={3}
maxValue={300}
```
the output is-
<img width="302" alt="Screenshot 2024-01-24 at 12 34 56 AM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/f9320956-c6ef-4eeb-bd96-8d0a01ffca13">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @christophby 

I have tried to refactor the code such that the user does not need to care about the relation-
```js
maxValue = noOfSections * stepValue;
```

Starting from version `1.4.2` it is now handled internally by the library.

**Comment by MSaeedNajafi** [comment]
<img width="291" alt="image" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/19430099/65cd1a9e-1980-4f57-9ca7-ab1e8af96521">
<img width="282" alt="image" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/19430099/d6afbd27-3de8-4c34-941e-0c1d09f0ca6e">


please take a look at these images, I am using the bra chart and I am encountering weird issue, as you can see sometimes the graph looks normal but as soon as there negative values it breaks and looking at the image from 26 of may you can see that it moves the secondaryYAxis, and also secondaryYAxis is not being represented correctly and also the line should be at 1 which means 100% since secondaryYAxis and the line are percentage. is there anyway to fix this issue?
