### ISSUE TITLE
onPressOut prop [Feature Request]

### ISSUE THREAD

**Issue by mister-10k** [Abhinandan-Kushwaha/react-native-gifted-charts#523]
Hi,

I couldn't find the onPressOut prop for the BarChart component. 

I saw you just added onLongPress [here](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/506).

Would it be possible to also add onPressOut?

Thanks,
Kwabena

**Comment by Abhinandan-Kushwaha** [comment]
Hi @mister-10k 👋
Thanks for requesting this feature. It is now available from version `1.4.4` onwards. It can be passed as a prop, or as a property to individual data items (similar to `onPress`). It takes 2 parameters- `item` and `index`.

**Comment by mister-10k** [comment]
Thank you!
