### ISSUE TITLE
YLabels are cut

### ISSUE THREAD

**Issue by steq28** [Abhinandan-Kushwaha/react-native-gifted-charts#524]
I'm trying to replicate this design, but when I reach high values on Y axis, they are cut (I don't want to decrease the font of the text but reduce the right part of the graph to give more space to the Y labels):
![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/77461343/ccf65d77-f2e7-495d-9852-4717c793bbd9)
This is how it looks in app:
![Screenshot_20240130-120757](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/77461343/cabfd647-9cb9-46b2-9fd8-918a466de52d)
I'm also trying to create the blue box only on X label that is selected, any suggestions?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @steq28 
To increase the Y-axis label width, you can use the `yAxisLabelWidth` prop.

To create a blue box for the selected X-axis label, you can use the `labelComponent` property inside the data array objects.

Here's a sample code for your use case-
```js
export const HighlightXaxis = () => {
  const [selectedIndex, setSelectedIndex] = useState(-1);

  const MyComponent = (labelText, index) => {
    const isSelected = selectedIndex === index;
    return (
      <View
        style={{
          backgroundColor: isSelected ? '#344F6C' : 'transparent',
          width: 20,
          height: 24,
          paddingTop: 2,
          alignSelf: 'center',
          borderRadius: 4,
        }}>
        <Text
          style={{textAlign: 'center', color: isSelected ? 'white' : 'gray'}}>
          {labelText}
        </Text>
      </View>
    );
  };

  const data: barDataItem[] = [
    {value: 49.5, labelComponent: () => MyComponent('M', 0)},
    {value: 64.2, labelComponent: () => MyComponent('T', 1)},
    {value: 52.2, labelComponent: () => MyComponent('W', 2)},
    {value: 76.5, labelComponent: () => MyComponent('T', 3)},
  ];
  return (
    <BarChart
      data={data}
      roundedTop
      frontColor="lightgray"
      barWidth={20}
      spacing={40}
      showReferenceLine1
      referenceLine1Position={60}
      referenceLine1Config={{
        color:'#6DBDBD',
        thickness: 5
      }}
      referenceLinesOverChartContent={false}
      rulesType={ruleTypes.SOLID}
      showFractionalValues
      roundToDigits={3}
      noOfSections={5}
      yAxisLabelWidth={60}
      yAxisTextStyle={{color: 'gray'}}
      yAxisColor={'lightgray'}
      xAxisColor={'lightgray'}
      focusBarOnPress
      focusedBarConfig={{color: '#344F6C'}}
      onPress={(item, index) => {
        setSelectedIndex(index);
      }}
    />
  );
};
```

https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/e36710df-9ad7-4c14-8223-a8aa75e8ec7f

**Comment by steq28** [comment]
Thanks!

**Comment by leolo784** [comment]
is it possible to display Y-axis label with metric prefix?

**Comment by Abhinandan-Kushwaha** [comment]
Yes @leolo784 
Try the props `yAxisLabelPrefix`, `yAxisLabelSuffix` or `formatYLabel`

You can also use the `yAxisLabelTexts` prop for custom label texts. See https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/22

**Comment by jungjungx** [comment]
> Hi [@steq28](https://github.com/steq28) To increase the Y-axis label width, you can use the `yAxisLabelWidth` prop.
> 
> To create a blue box for the selected X-axis label, you can use the `labelComponent` property inside the data array objects.
> 
> Here's a sample code for your use case-
> 
> export const HighlightXaxis = () => {
>   const [selectedIndex, setSelectedIndex] = useState(-1);
> 
>   const MyComponent = (labelText, index) => {
>     const isSelected = selectedIndex === index;
>     return (
>       <View
>         style={{
>           backgroundColor: isSelected ? '#344F6C' : 'transparent',
>           width: 20,
>           height: 24,
>           paddingTop: 2,
>           alignSelf: 'center',
>           borderRadius: 4,
>         }}>
>         <Text
>           style={{textAlign: 'center', color: isSelected ? 'white' : 'gray'}}>
>           {labelText}
>         </Text>
>       </View>
>     );
>   };
> 
>   const data: barDataItem[] = [
>     {value: 49.5, labelComponent: () => MyComponent('M', 0)},
>     {value: 64.2, labelComponent: () => MyComponent('T', 1)},
>     {value: 52.2, labelComponent: () => MyComponent('W', 2)},
>     {value: 76.5, labelComponent: () => MyComponent('T', 3)},
>   ];
>   return (
>     <BarChart
>       data={data}
>       roundedTop
>       frontColor="lightgray"
>       barWidth={20}
>       spacing={40}
>       showReferenceLine1
>       referenceLine1Position={60}
>       referenceLine1Config={{
>         color:'#6DBDBD',
>         thickness: 5
>       }}
>       referenceLinesOverChartContent={false}
>       rulesType={ruleTypes.SOLID}
>       showFractionalValues
>       roundToDigits={3}
>       noOfSections={5}
>       yAxisLabelWidth={60}
>       yAxisTextStyle={{color: 'gray'}}
>       yAxisColor={'lightgray'}
>       xAxisColor={'lightgray'}
>       focusBarOnPress
>       focusedBarConfig={{color: '#344F6C'}}
>       onPress={(item, index) => {
>         setSelectedIndex(index);
>       }}
>     />
>   );
> };
>  highlight.mov

Hello, is there a way to apply this to horizontal graphs? I have the same issue but since I am working with the horizontal graph, its the X-axis that needs a larger width. One would assume changing labelwidth prop would fix this, but it changes the 'height' instead (Meaning that instead of widening the label, it makes it taller, basically just adding blank space between values, since thats how it should work on a normal graph).

**Comment by Abhinandan-Kushwaha** [comment]
@jungjungx Horizontal charts are just the rotated versions of normal charts. Try adjusting the widths, heights of the labels by setting `horizontal={false}` and then setting `horizontal={true}`.

Try alternating between horizontal = true and false and keep adjusting the widths/heights repeatedly untill you get the desired result
