### ISSUE TITLE
Hide data lower than... on Y axis

### ISSUE THREAD

**Issue by FrSenpai** [Abhinandan-Kushwaha/react-native-gifted-charts#526]
Hello all ! 

I try to hide some data lower than 50, but my chart keep going down...
Is there any solution ?

<img width="295" alt="Capture d'écran 2024-01-31 085622" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/46403405/49f662ef-fab9-4687-810f-5a9f74124ad4">

<img width="437" alt="Capture d'écran 2024-01-31 085704" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/46403405/7fef6f07-e3c7-4ae7-95c5-c649978f6fc9">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @FrSenpai 👋
There was a bug due to which `noOfSectionsBelowXAxis={0}` was not working. This has been fixed from version `1.4.4` onwards.

Please use the latest version of _react-native-gifted-charts_.
