### ISSUE TITLE
onPress method is not getting called in both Android and iOS

### ISSUE THREAD

**Issue by VibhorKockpit** [Abhinandan-Kushwaha/react-native-gifted-charts#53]
onPress method in Bar Chart is not getting called.

`<BarChart
          barWidth={40}
          noOfSections={3}
          barBorderRadius={4}
          frontColor={"#000000"}
          data={barData}
          yAxisThickness={1}
          xAxisThickness={1}
          onPress={()=>console.log("OK")}
        />
`

**Comment by Abhinandan-Kushwaha** [comment]
Hi @VibhorKockpit As of now, `onPress` should be put in the objects inside the data array.

For example-

```js
const data=[
    {value: 40, onPress: ()=>console.log(40)},
    {value: 80, onPress: ()=>console.log(80)},
    {value: 58, onPress: ()=>console.log(58)}
]
```

**Comment by VibhorKockpit** [comment]
Thanks @Abhinandan-Kushwaha
