### ISSUE TITLE
Pie Chart Issue

### ISSUE THREAD

**Issue by iamabhi9v** [Abhinandan-Kushwaha/react-native-gifted-charts#530]
@Abhinandan-Kushwaha 

**There's an issue regarding Pie Chart :**

**The issue is :** This is **By Default** in the **node_modules**.
<div align="center">
<img src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/66355946/ab5dae1b-b84f-4b12-b764-e272def9e5a2" alt="Screenshot" width="200" height="450">
</div>

**And it should be like this :** I got this using the changes I made myself manually in **main.tsx** file in **Pie Chart** folder in **node_modules**.
<div align="center">
<img src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/66355946/4e095be5-5a76-412c-b3a5-06c320686035" alt="Screenshot" width="200" height="450">
</div>

**_Note: Please, fix this issue and update the react-native-gifted-charts package as soon as possible._**

**Comment by Abhinandan-Kushwaha** [comment]
This is fixed in version `1.4.5`. See https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/discussions/528#discussioncomment-8340327

Please use the latest version of the library.
