### ISSUE TITLE
Unwanted space with hideRules chart is not full width

### ISSUE THREAD

**Issue by tahola** [Abhinandan-Kushwaha/react-native-gifted-charts#533]
Hello, I have an unwanted space on all the LineChart when I am using hideRules and hideYAxisText, it doesn't take full width.

 With Rules and YAxisText (width is ok) :

![Capture d’écran 2024-02-04 à 14 55 38](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/1329725/25b9ec6b-6d45-4ab7-b44e-f6332a261d30)

With hideRules and hideYAxisText (the width seems to not be full) :

![Capture d’écran 2024-02-04 à 14 56 01](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/1329725/65a320fa-5a7d-4a43-8a1b-0fb5e4c2cb09)

Here is my code :
```
<View
        style={{
          backgroundColor: 'red,
        }}>
<LineChart
            data={symbolLastPrices}
            maxValue={Math.max(...symbolLastPrices.map(item => item.value))}
            height={100}
            initialSpacing={0}
            adjustToWidth={true}
            hideDataPoints
            thickness={3}
            hideRules
            hideYAxisText
            yAxisColor={'transparent'}
            showVerticalLines={false}
            verticalLinesColor={theme.colors.surfaceContainerHigh}
            xAxisColor={'transparent'}
            color={theme.colors.primaryFixedDim}
            scrollToEnd={true}
            scrollAnimation={false}
            endSpacing={0}
            hideOrigin
            areaChart
            startFillColor={theme.colors.surfaceContainer}
            endFillColor={theme.colors.surfaceContainerLow}
            isAnimated={false}
            disableScroll
          />
</View>
```

I understand that its not a style issue but is there an option to really remove that extra space ?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @tahola 
You can use the prop `yAxisLabelWidth` and pass `0` or a negative value to remove the extra space from the left side of the chart.
