### ISSUE TITLE
LineChart: `animateOnDataChange` causing chart to not be rendered

### ISSUE THREAD

**Issue by danielgelling** [Abhinandan-Kushwaha/react-native-gifted-charts#537]
When adding the `animateOnDataChange` to a `LineChart` the chart is not rendered at all. Even when simply copy-pasting the example from https://gifted-charts.web.app/linechart#animateOnChange

Version: 1.4.6

![Screenshot 2024-02-06 at 18 50 34 jpeg](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/6146135/c826460b-d80a-42c4-86ad-f490f8e73ec8)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @danielgelling 
Thanks for reporting this issue. It has been fixed in version `1.4.7`🎉

Please use the latest version of the library.
