### ISSUE TITLE
Format yAxisLabelText  large value like lets say 1000 as $ 1K in yAxis

### ISSUE THREAD

**Issue by jagajastic** [Abhinandan-Kushwaha/react-native-gifted-charts#54]
@Abhinandan-Kushwaha I still can't grasp how you format the <code> yAxisLabelText </code> 1000 as $ 1K in yAxis

**Comment by Abhinandan-Kushwaha** [comment]
Hi @jagajastic You can use the `yAxisLabelTexts` prop like this-

```js
const barData = [{value: 250}, {value: 500}, {value: 745}, {value: 320}]
<BarChart
  yAxisLabelTexts={['$0', '$250', '$500', '$750']}
  data={barData}
/>
```

This issue is already reported and resolved here- https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/22#issuecomment-939575744
