### ISSUE TITLE
Tooltip is gettnig cutoff for lfirst and last bar 

### ISSUE THREAD

**Issue by prasannakulal16** [Abhinandan-Kushwaha/react-native-gifted-charts#540]
Hii @Abhinandan-Kushwaha  
Currently Tooltip is gettnig cutoff for lfirst and last bar  as well as the  graph is getting cutoff in smaller devices. Any solution for this?

This is my code:
```
 <View
            style={{
                borderWidth: GetDeviceSize(1),
                borderRadius: GetDeviceSize(24),
                borderColor: COLORS.DarkDividerGrey,
                paddingVertical: GetDeviceSize(20),
            }}>
            <BarChart
                data={chartData}
                height={100}
                // width={Dimensions.get('window').width}
                barBorderTopLeftRadius={4}
                barBorderTopRightRadius={4}
                yAxisTextStyle={{color: 'red'}}
                showYAxisIndices={false}
                hideYAxisText
                xAxisLabelTextStyle={{
                    color: COLORS.ThinGrey,
                    fontSize: GetDeviceSize(10),
                    fontFamily: Fonts.PoppinsSemiBold.fontFamily,
                }}
                xAxisLabelTexts={['4AM', '8PM', '12AM', '4PM', '8PM', '9AM']}
                renderTooltip={topLabelComponent}
                barStyle={{color: 'red'}}
                barWidth={GetDeviceSize(26)}
                yAxisColor={COLORS.Transparent}
                xAxisColor={COLORS.DividerGrey}
                barBorderColor={'green'}
                frontColor={COLORS.WarmBlue}
                yAxisExtraHeight={60}
                focusBarOnPress
                focusedBarConfig={{color: selectedItem}}
                // rulesType={'solid'}
                hideRules
            />
        </View>

```And this is the tooltip component 


  ```
const topLabelComponent = item => {
        const {toolTipColor, toolTipIcon, barColor} = GetToolTipColor(item);
        setSelectedItem(barColor);
        return (
            <View
                style={{
                    // width: GetDeviceSize(70),
                    // height: GetDeviceSize(60),
                    paddingHorizontal: GetDeviceSize(10),
                    paddingVertical: GetDeviceSize(8),
                    borderRadius: GetDeviceSize(8),
                    backgroundColor: COLORS.PrimaryBlack,
                    marginBottom: 4,
                    marginLeft: -20,
                }}>
                <Text
                    style={{
                        fontFamily: Fonts.PoppinsRegular.fontFamily,
                        color: COLORS.PrimaryWhite,
                        textAlign: 'center',
                    }}>
                    {item.xValue}
                </Text>
                <View
                    style={{
                        flexDirection: 'row',
                        alignItems: 'center',
                    }}>
                    <View>{toolTipIcon}</View>

                    <Text
                        style={{
                            fontFamily: Fonts.PoppinsSemiBold.fontFamily,
                            color: toolTipColor,
                            // textAlign: 'center',
                            paddingLeft: GetDeviceSize(3),
                        }}>
                        {item.value} mins
                    </Text>
                </View>
            </View>
        );
    };
```

Current output screenshot:
![Group 19991](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/32484352/f63b435e-2557-4332-9bba-1c23f89f6b69)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @prasannakulal16 
The screenshots you shared are not visible
Can you please share the screenshots again

**Comment by Abhinandan-Kushwaha** [comment]
Hi @prasannakulal16 
1. To stop the tooltip from getting cut off, you can use the `leftShiftForLastIndexTooltip` and `leftShiftForTooltip` props.
2. To stop the chart from getting cut off, you can decrease the width of the bars using the `barWidth` prop. You can also use `spacing` prop to adjust the gap between adjacent bars.

However, the chart is scrollable, so cutting off should not be much of a problem.

**Comment by prasannakulal16** [comment]
Thanks @Abhinandan-Kushwaha its worked
