### ISSUE TITLE
Not Showing lines properly in BarChart 

### ISSUE THREAD

**Issue by sandeep-synclovis** [Abhinandan-Kushwaha/react-native-gifted-charts#543]
I'm encountering an issue when integrating a line view within a BarChart that utilizes a SecondaryYAxis. The challenge arises from the discrepancy between the maximum value I specify (e.g., 500) and the actual maximum value in the dataset (e.g., 400). Despite setting the maxValue to 500, the BarChart displays based on the second highest value, resulting in a displayed maximum of 500 while the max value for the lines remains at 400. Consequently, if any data point exceeds this adjusted maximum (e.g., 300), it won't be visible in the chart rendering.

<img width="278" alt="Screenshot 2024-02-15 at 11 35 19 AM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/60770689/613f6bba-5586-4a32-80a4-254a6e413c7a">

**Comment by hkellou-vitalcare** [comment]
Hi @sandeep-synclovis ,
I would suggest you dynamically change the max value of the lines based on your maximum value (plus an added value if you don't want the top of your chart to be on the very top of your chart)
Something like "Math.max(array)"

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sandeep-synclovis 
Were you able to solve this issue?

**Comment by sandeep-synclovis** [comment]
Hi Abhinandan,
  Thanks for your reply, there was an issue in the library(
gifted-charts-core), which I figured out and fixed and sent a PR for the
same, please review and merge in your library.

https://github.com/Abhinandan-Kushwaha/gifted-charts-core/pull/9

*With Best Regards,*
*Sandeep Mishra*
Lead Software Engineer
Synclovis Systems Pvt. Ltd. <https://www.synclovis.com/> | Bluewings
<http://www.bluewings.in/>
Phone: +91 9620971846, +91 7892633810
Locations: Bangalore | New Jersey

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sandeep-synclovis 
The PR you mentioned above ([Abhinandan-Kushwaha/gifted-charts-core#9](https://github.com/Abhinandan-Kushwaha/gifted-charts-core/pull/9)) deals with Line charts, not with combined Bar-Line charts.
I gues you meant this issue- https://github.com/Abhinandan-Kushwaha/gifted-charts-core/issues/4

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sandeep-synclovis 
I have made the fix that you suggested [here](https://github.com/Abhinandan-Kushwaha/gifted-charts-core/issues/4) through patch-package.
The fix is available from version `1.4.16` onwards.

Please use the latest version of the library.
