### ISSUE TITLE
i can't add multiple X axis label data for BarChart 

### ISSUE THREAD

**Issue by sahildb** [Abhinandan-Kushwaha/react-native-gifted-charts#545]
import {Dimensions, SafeAreaView, StyleSheet, Text, View} from 'react-native';
import React from 'react';
import {BarChart} from 'react-native-gifted-charts';

const Graph = () => {
  const width = Dimensions.get('screen').width;
  const stackData = [
    {
      stacks: [
        {value: 10, color: '#0080FF'},
        {value: 10, color: '#00DCF0'},
      ],
      label: 'Mon\nNov',
    },
    {
      stacks: [
        {value: 10, color: '#0080FF'},
        {value: 20, color: '#00DCF0'},
      ],
      label: 'Tue\nNov',
    },
    {
      stacks: [
        {value: 10, color: '#0080FF'},
        {value: 12, color: '#00DCF0'},
      ],
      label: 'Wed\nNov',
    },
    {
      stacks: [
        {value: 15, color: '#0080FF'},
        {value: 10, color: '#00DCF0'},
      ],
      label: 'Thu\nNov',
    },
    {
      stacks: [
        {value: 5, color: '#0080FF'},
        {value: 5, color: '#00DCF0'},
      ],
      label: 'Fri\nNov',
    },
    {
      stacks: [
        {value: 0, color: '#0080FF'},
        {value: 0, color: '#00DCF0'},
      ],
      label: 'Sat\nNov',
    },
    {
      stacks: [
        {value: 0, color: '#0080FF'},
        {value: 0, color: '#00DCF0'},
      ],
      label: 'Sun\nNov',
    },
  ];
  return (
    <SafeAreaView
      style={{
        flex: 1,
      }}>
      <View style={{margin: 0}}>
        <BarChart
          width={width}
          showYAxisIndices
          // noOfSections={3}
          stackData={stackData}
          rulesColor="red"
          hideRules="false"
          initialSpacing={10}
          spacing={20}
          xAxisLabelTextStyle={{
            textAlign: 'center',
            marginRight: 6,
          }}
        />
      </View>
    </SafeAreaView>
  );
};

export default Graph;

const styles = StyleSheet.create({
  monthContainer: {
    flexDirection: 'row',
    paddingHorizontal: 50,
  },
});

this is my code

![Screenshot 2024-02-19 at 5 46 08 PM](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/94191373/85bfaaa7-0208-4501-aa40-45ae60d0e730)

**Comment by Abhinandan-Kushwaha** [comment]
@sahildb can you please send a screenshot of desired output?

**Comment by sahildb** [comment]
![Screenshot 2024-02-20 at 9 26 14 AM](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/94191373/a9d4933d-6221-4bcf-8fde-cd12a30b946f)
@Abhinandan-Kushwaha

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sahildb 
Try adding the following to the `<BarChart>` component-
```js
xAxisTextNumberOfLines={3}
xAxisLabelTextStyle={{
  width: 40,
  textAlign: 'center',
}}
```

**Comment by sahildb** [comment]
@Abhinandan-Kushwaha thank you.

**Comment by sahildb** [comment]
![Screenshot_20240221_094920_MyNewReduxProject](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/94191373/0e068c8d-6432-46e1-9922-0482779d1214)
when i run in android device that time i am getting some marginBottom at barBottom 
@Abhinandan-Kushwaha

**Comment by sahildb** [comment]
@Abhinandan-Kushwaha  can i start X axis at 0.5 or 1 value of y axis. you can see my desired output ss
