### ISSUE TITLE
Type checks failing

### ISSUE THREAD

**Issue by abpbackup** [Abhinandan-Kushwaha/react-native-gifted-charts#546]
Problem when having Typescript with strict mode and noImplicitAny: false
<img width="1005" alt="image" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/17506339/3967870d-9104-4f4b-83c4-242de48fe32d">

Solution: add missing types
<img width="916" alt="image" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/17506339/685faa94-ac15-417f-8da0-59eaa8c35347">

This goes for all the components:
<img width="1193" alt="image" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/17506339/922a6272-1377-4ce1-a727-7ec2217ff270">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @abpbackup, I am working on adding types. Should be ready within a week.

**Comment by Darkhorse-Fraternity** [comment]
Any update on this issue?

**Comment by cliveportman** [comment]
Hi @abpbackup. If you have a local branch and don't have time to finish, I'd be happy to pick it up if you want?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @abpbackup @Darkhorse-Fraternity @lakardion @cliveportman 
`react-native-gifted-charts` is now shipping compiled js files instead of ts files from version `1.4.22` onwards. This should fix all type related issues. 🎉
