### ISSUE TITLE
Add support to control the backgroundColor of each section of the yAxis individually

### ISSUE THREAD

**Issue by Golannnnn** [Abhinandan-Kushwaha/react-native-gifted-charts#547]
Like so:

![SCR-20240219-pwvf](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/95919462/bf588f23-ec33-4290-82b5-3006a0157c07)

Would be great to have this option.

**Comment by Abhinandan-Kushwaha** [comment]
Thanks, @Golannnnn for requesting this feature. I will release it in the next version.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Golannnnn 👋
Sorry for the late response. This feature is now available from version `1.4.15` onwards. 🎉

We can now use the prop `sectionColors` to set the background color of the horizontal sections of the chart. It is an array of ColorValues (or strings denoting colors). So, each section can have a different background color now.

Please use the latest version of the library.
