### ISSUE TITLE
Could not find the example mentioned in the documentation.

### ISSUE THREAD

**Issue by VibhorKockpit** [Abhinandan-Kushwaha/react-native-gifted-charts#55]
HI @Abhinandan-Kushwaha I was trying to find the following example of Bar Charts in the documentation but could not find it.
![Screenshot 2021-12-28 at 10 08 40 AM](https://user-images.githubusercontent.com/70505950/147529087-c5ef8f01-1bdd-4054-bfa7-d9c4908ef67f.png)
Can you please tell if it is added in the documentation or yet to be added? Actually, I wanted to show the values of yAxis above the Bars on xAxis.

**Comment by Abhinandan-Kushwaha** [comment]
Yes @VibhorKockpit the above chart is documented here - https://gifted-charts.web.app/horizbar
