### ISSUE TITLE
secondary line data not aligning with secondary y axis

### ISSUE THREAD

**Issue by MicahDavid** [Abhinandan-Kushwaha/react-native-gifted-charts#552]
I was able to use the secondaryData prop to add my second line graph, and subsequently styled the secondary line and secondary y axis with the appropriate props. The problem is that the secondary data is not in the appropriate y position. 

The screenshot below shows the 2 lines. Dark blue is wave height, light blue is wave period.  The wave period values range from 11 to 13 seconds, but as you can see on the graph they align withe the right y-axis in the 9 - 11 value range. 
![Simulator Screenshot - iPhone 15 Pro - 2024-02-20 at 11 50 12](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/51126961/cfc8e3c4-47fe-4284-8d9b-296d1cbb9136)

Code: 
```
<LineChart
    width={Dimensions.get('window').width - 70}
    adjustToWidth={true}
    height={200}
    areaChart
    //curved
    //animateOnDataChange
    initialSpacing={0}
    endSpacing={0}
    //showVerticalLines={true}
    data={chartData.lineChart1}
    secondaryData={chartData.lineChart2}
    color={globalStyles.colors.blue700}
    startFillColor={globalStyles.colors.blue700}
    startOpacity={0.1}
    endFillColor={globalStyles.colors.blue700}
    endOpacity={0.1}
    secondaryLineConfig={{
        color:globalStyles.colors.blue100,
        dataPointsColor:globalStyles.colors.blue100,
        startFillColor:"rgb(46, 217, 255)",
        startOpacity:0.0,
        endFillColor:"rgb(203, 241, 250)",
        endOpacity:0.0,
    }}
    dataPointsColor={globalStyles.colors.blue700}
    thickness={1}
    verticalLinesColor={'#efefef'}
    yAxisColor={globalStyles.colors.blue700}
    xAxisColor={globalStyles.colors.blue700}
    curveType={CurveType.QUADRATIC}
    noOfSections={6}
    showFractionalValues={false}
    roundToDigits={true}
    yAxisLabelSuffix={' ft'}
    yAxisTextStyle={{
        fontFamily:'Roboto',
        fontSize:11,
        color:globalStyles.colors.gray500
    }}
    secondaryYAxis={{
        yAxisOffset: minChartPeriod,
        noOfSections:6,
        //showFractionalValues: true,
        yAxisLabelSuffix:' s'
    }}
    pointerConfig={{
        //activatePointersOnLongPress:true
    }}
    trimYAxisAtTop={true}
/>
```

Any suggestions?

**Comment by MicahDavid** [comment]
This secondary values were not lining up properly, because of the roundToDigits={true} prop. When I removed this, the got rid of the data alignment problem.

**Comment by Abhinandan-Kushwaha** [comment]
@MicahDavid Cool you figured out the issue and its solution yourself.
I will make changes if required. Suggestions are welcome.

Closing it for now.
