### ISSUE TITLE
How do we add border radius to semi circle pie charts?

### ISSUE THREAD

**Issue by AyoCodess** [Abhinandan-Kushwaha/react-native-gifted-charts#554]
[
![IMG_2933](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/72066389/f50fac54-161b-49db-85b7-8cf799a8759b)
](url)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @AyoCodess 
 You can add it to the style of your component (or View) inside which you put the `<PieChart>` component.

**Comment by AyoCodess** [comment]
> Hi @AyoCodess 
> 
>  You can add it to the style of your component (or View) inside which you put the `<PieChart>` component.

So both bottom corners of the speed omometer looking pie chart ok either side can simply be rounded with a border radius: 10 for example?

**Comment by Abhinandan-Kushwaha** [comment]
@AyoCodess I misunderstood your requirement. Seems like you want the donut edges to be rounded. This is currently not supported by the library.

I will add this feature in the next version of the library by tomorrow.

**Comment by AyoCodess** [comment]
> @AyoCodess I misunderstood your requirement. Seems like you want the donut edges to be rounded. This is currently not supported by the library.
> 
> 
> 
> I will add this feature in the next version of the library by tomorrow.

Awesome! Please let me know. 

This is a great library by the way.

By chance could you add the ability to add depth/shadow to the donuts too?

**Comment by AyoCodess** [comment]
any updates @Abhinandan-Kushwaha

**Comment by Abhinandan-Kushwaha** [comment]
Hi @AyoCodess
Try out the newly launched `<PieChartPro>` component in version 1.4.8
It supports curved edges using the the following properties inside the objects in the data array-

1. isStartEdgeCurved
2. isEndEdgeCurved
3. startEdgeRadius
4. endEdgeRadius

**Comment by AyoCodess** [comment]
Great! Is there a dashed pie chart available?

Kind Regards,
Ayo Adesanya
https://www.ayoadesanya.com/
