### ISSUE TITLE
Animate piechart/semi circle

### ISSUE THREAD

**Issue by AyoCodess** [Abhinandan-Kushwaha/react-native-gifted-charts#555]
Is there away to animate this chart when the app mounts?

**Comment by Abhinandan-Kushwaha** [comment]
Not yet @AyoCodess 
Will see if there's an easy way to implement animations in Pie charts.

**Comment by AyoCodess** [comment]
any updates @Abhinandan-Kushwaha

**Comment by Abhinandan-Kushwaha** [comment]
Hi @AyoCodess 
Try out the newly launched `<PieChartPro>` component in version `1.4.8`
It supports animation using the `isAnimated` prop.

**Comment by christophby** [comment]
@Abhinandan-Kushwaha is the animation expected to look like this (also multiple times)?




https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/12933672/f2ca859f-586e-4784-9c62-8a9ebdca14e2

**Comment by L2Develop96** [comment]
> @Abhinandan-Kushwaha is the animation expected to look like this (also multiple times)?
> 
>  chart-animation.mov

I have the same issue as this, Animation is not fluid and doesn't look nice :/

**Comment by AyoCodess** [comment]
The animation is pretty bad, i unfortunately had to use another library for this usecase
