### ISSUE TITLE
BarChart floating away element

### ISSUE THREAD

**Issue by taciocabral** [Abhinandan-Kushwaha/react-native-gifted-charts#56]
I'm trying to add the bars inside a card, but it has a fixed size and is floating outside the element.

When I set the maxValue or height it cuts the bar.

**in short: it is not possible to change the size of bars, pie, donut etc.**

**Comment by Abhinandan-Kushwaha** [comment]
Please the screenshot of the Card you need, and the card you have made.
Also the code you have written for it.

Usually, we can fix such issues using `width`, `height`, `maxValue` and `stepValue` props.
