### ISSUE TITLE
RulesType at LineChart does not work

### ISSUE THREAD

**Issue by nguyenthanhdat4326** [Abhinandan-Kushwaha/react-native-gifted-charts#560]
Im using version 1.4.7
This is my code:
` <LineChart
        data={totalRevenue}
        // isAnimated
        focusEnabled
        // xAxisType="solid"
        rulesType="solid"
        secondaryData={totalOrders}
        curved
        maxValue={maxValueRevenueY}
        noOfSections={5}
        width={290}
        color="orange"
        yAxisColor={'#fff'}
        dataPointsRadius={2}
        dataPointsColor={'red'}
        xAxisLength={1}
        // rulesColor={'#000'}
        initialSpacing={0}
        secondaryLineConfig={{ color: 'blue' }}
        secondaryYAxis={{
          maxValue: maxValueOrderY,
          noOfSections: 5,
          yAxisColor: '#fff',
          yAxisIndicesColor: 'blue',
          yAxisTextStyle: {
            fontSize: 6,
            color: '#000',
            marginRight: 20,
          },
        }}
        formatYLabel={(label: string) => {
          const symbols = ['', 'K', 'M', 'B'];
          let num = parseInt(label);
          let suffixIndex = 0;
          while (num >= 1000 && suffixIndex < symbols.length - 1) {
            num /= 1000;
            suffixIndex++;
          }
          num = Math.round(num * 10) / 10;
          return num.toString() + symbols[suffixIndex];
        }}
        thickness1={2}
        xAxisLabelTextStyle={{ width: 150, marginLeft: -45, fontSize: 10 }}
        yAxisTextStyle={{ fontSize: 6, color: '#000', marginLeft: 5 }}
        xAxisIndicesHeight={0}
        xAxisIndicesWidth={2}
        // showDataPointOnFocus
        showTextOnFocus
        // showStripOnFocus
      />`
Im using both xAxisType and rulesType but none of it work, could u support me on this

**Comment by Abhinandan-Kushwaha** [comment]
Hi @nguyenthanhdat4326 
For me, it's working. I think you just need to refresh (reload the app)
