### ISSUE TITLE
How to achieve Multiple Circular Progressbar using this library? 

### ISSUE THREAD

**Issue by novamaster-git** [Abhinandan-Kushwaha/react-native-gifted-charts#563]
> Example
![Screenshot 2024-03-01 145959](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/83171626/a35f3328-05e5-46b4-9eef-fa730495995d)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @novamaster-git 
You can make 3 donut charts and use `position: 'absolute` to put them above one another.

Here's an example-
```js
onst d1 = [
  {value: 4, color: '#E33716'},
  {value: 9, color: '#381C16'},
];
const d2 = [
  {value: 4.5, color: '#B0D44C'},
  {value: 9, color: '#303621'},
];
const d3 = [
  {value: 4, color: '#43D5FC'},
  {value: 9, color: '#16353C'},
];

return (
  <View style={{flex: 1, backgroundColor: 'black'}}>
    <PieChart data={d1} donut innerCircleColor="black" innerRadius={92} />
    <View style={{position: 'absolute', top: 38, left: 38}}>
      <PieChart
        data={d2}
        donut
        radius={82}
        innerCircleColor="black"
        innerRadius={62}
      />
    </View>
    <View style={{position: 'absolute', top: 68, left: 68}}>
      <PieChart
        data={d3}
        donut
        radius={52}
        innerCircleColor="black"
        innerRadius={32}
      />
    </View>
  </View>
);
```
The output is-

<img width="230" alt="Screenshot 2024-03-01 at 7 23 13 PM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/14d4f6e5-e40a-4a5d-86f4-ab47be4842fc">

Note: Curved sections are not supported yet. I will add this feature soon.

**Comment by novamaster-git** [comment]
Thank you for replying, but I need it to be dynamic, meaning the number of progress bars will depend on the number of datasets.

**Comment by Abhinandan-Kushwaha** [comment]
@novamaster-git Thanks for requesting this feature. I will release it in the next version.
