### ISSUE TITLE
first and last xAxisLabel are cut-off

### ISSUE THREAD

**Issue by frangejt123** [Abhinandan-Kushwaha/react-native-gifted-charts#568]
I have an issue with the xAxislabels are being cut-off

![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/63201708/5c07709b-a921-4b6e-a84b-272231e7eac8)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @frangejt123 👋
You can move the first label towards the right using `labelTextStyle: {marginLeft: <value>}` and the last label towards the left using `labelTextStyle: {marginRight: <value>}` in the respective data items in the data array.

Alternatively, you can use the `labelComponent` prop to render your own label.

**Comment by trocoli96** [comment]
Hello, I would like to just point up that this is not the best walkaround. The best would be the labels having a increased zindex so they can be outside the graph limits. Moving the margins makes the labels on bigger number of data points to be potentially overlapped. 
<img width="477" alt="image" src="https://github.com/user-attachments/assets/8a963c32-7cc2-4765-9f39-33fe7546e86d" />

Is there any solution to increase z-index on this element?

**Comment by Abhinandan-Kushwaha** [comment]
@trocoli96 unfortunately, labels along with the chart-content are inside ScrollView. And you cannot let the contents of a ScrollView overflow out of its bounds using `zIndex`.

See [LineChart architecture](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/dev/LineChart/index.md)
