### ISSUE TITLE
onPress usage with LineChart

### ISSUE THREAD

**Issue by izniburak** [Abhinandan-Kushwaha/react-native-gifted-charts#570]
Hi, 
I use v1.4.3 of the package. I have a question about the `onPress` functionality in `LineChart`.

I think it doesn't have an useful experience, because to press `dot` in the chart is very hard. I tried to use `customDataPoint` prop and prepared a custom component with `Pressable` component in order to use `onPress`. But `onPress` still didn't work.

Apart from that, I also couldn't use `onPress` functionality with the chart texts in the X axis. Normally, when I use `BarChart` and press the any text in X axis, `onPress` is triggered. Why we don't use similar functionality with `LineChart`?

Also, I know that, `LineChart` has some props such as `focusEnabled`,  `onFocus`, `onPress` to handle 'press' actions. But, as I said, I think the experience of the LineChart onPress events not good. I would be good if it has similar behaviour with `BarChart`. 

Do you have any suggestion for that?

**Comment by ahsan-abrar** [comment]
facing a similar issue, when I inspect I noticed that there is Svg that overly the whole graph lines area,


![Screenshot_1710281475](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/58684529/367ec982-67b8-4990-930d-09c215441963)

**Comment by ahsan-abrar** [comment]
> Hi, I use v1.4.3 of the package. I have a question about the `onPress` functionality in `LineChart`.
> 
> I think it doesn't have an useful experience, because to press `dot` in the chart is very hard. I tried to use `customDataPoint` prop and prepared a custom component with `Pressable` component in order to use `onPress`. But `onPress` still didn't work.
> 
> Apart from that, I also couldn't use `onPress` functionality with the chart texts in the X axis. Normally, when I use `BarChart` and press the any text in X axis, `onPress` is triggered. Why we don't use similar functionality with `LineChart`?
> 
> Also, I know that, `LineChart` has some props such as `focusEnabled`, `onFocus`, `onPress` to handle 'press' actions. But, as I said, I think the experience of the LineChart onPress events not good. I would be good if it has similar behaviour with `BarChart`.
> 
> Do you have any suggestion for that?

Did you figure it out?

**Comment by wkchoong** [comment]
Can try to use this function when use the custom component from <LineChart />.

```
delayBeforeUnFocus={0}
 focusedCustomDataPoint={() => {
              console.log('hi');
            }}
   customDataPoint={(item: any, i: number) => {
              return (
                <Box
                  key={i}
                  ml={2}
                  mb={4}
                  h={12}
                  w={12}
                  borderWidth={3}
                  rounded="$full"
                  borderColor="#FF9F0A"
                />
              );
            }}
```

**Comment by Abhinandan-Kushwaha** [comment]
Hi @izniburak @wkchoong @ahsan-abrar 
I have fixed the `onPress` related issue in multi-line charts. See https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/dev/LineChart/MultiLine.md#onpress-for-data-points-in-multi-line-charts
