### ISSUE TITLE
yaxisoffset issue

### ISSUE THREAD

**Issue by priyadharshinib18** [Abhinandan-Kushwaha/react-native-gifted-charts#572]
if 
![Screenshot_2024-03-15-14-48-52-53_202d9c861f44240e0359383b4dc9f4b4](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/162097947/12e571ca-bff1-4929-bbbb-9aae2291f64b)
my value was between range of 31.4 - 32.5 so i give yaxisoffset as low value maxvalue as high value but it returns wrong value when i give offset value

**Comment by Abhinandan-Kushwaha** [comment]
Hi @priyadharshinib18 
You need to manually adjust the value displayed in the `pointerLabelComponent`.

Here's an example-
```js
pointerConfig={{
  pointerLabelComponent: (items)=>{
    return(
      <Text>{items[0].value + 31.4}</Text>  // Added the offset, 31.4 
    )
  }
}}
```
