### ISSUE TITLE
Long Press does not immediately trigger pointer if activatePointersOnLongPress=true

### ISSUE THREAD

**Issue by tfkennedy777** [Abhinandan-Kushwaha/react-native-gifted-charts#573]
I'm developing a page with a line chart that dynamically renders data for various timeframes, which occasionally means that the chart needs to be scrollable. In these cases, I have the `pointerConfig` prop `activatePointersOnLongPress` set to `true` in order to allow scrolling. However, when this prop is set to true, simply long pressing does not activate the pointer. Instead, a long press PLUS some degree of movement / drag is required to trigger the pointer. Additionally, if the user begins scrolling (panning gesture) but holds down for too long while scrolling, the pointer is triggered.

It would be great if this logic could be fixed so that:
1. a simple long press, absent of panning gesture, triggers the pointer when this prop is set to true.  
2. a panning gesture prior to reaching the longPress threshold disables pointer for duration of panning gesture.

I've attached two screen recordings below to demonstrate the issues noted. The first screen recording shows how, when activatePointersOnLongPress=true, some degree of movement is necessary in addition to a long press in order to trigger the pointer. The second recording shows how the pointer can be triggered even in the middle of a scrolling gesture.

https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/97812981/1ac00958-ec59-4ee6-a9a1-44a0f5239558

https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/97812981/5fcfcffc-5ba8-48d8-8457-40a95c26797b

**Comment by Abhinandan-Kushwaha** [comment]
Hi @tfkennedy777 👋

If the pointers are getting activated too soon (while the user's intention is to scroll), you can use the property ` activatePointersDelay` inside the `pointerConfig` object.

For the first issue, we cannot enable the pointers on simple long press. We need to drag after a long press. This is because of the way we have implemented the pointers.
