### ISSUE TITLE
Data points are vertically off-center by x-axis thickness

### ISSUE THREAD

**Issue by tfkennedy777** [Abhinandan-Kushwaha/react-native-gifted-charts#574]
Pretty self-explanatory. All data gets pushed up by an equal number of pixels as the x-axis thickness, causing the data points to become uncentered with the y-axis rule lines. This occurs even with the default 1px thickness

Thickness = 1
![Screenshot 2024-03-15 at 9 43 55 AM](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/97812981/1e234b44-f03e-4ed7-ae55-cd0db80e05e7)

Thickness = 5 
![Screenshot 2024-03-15 at 9 44 24 AM](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/97812981/ec171f3a-d8bd-473f-b90b-31b6ece742b6)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @tfkennedy777 👋
Thanks for reporting this issue. It has been fixed from version `1.4.8` onwards.
Please use the latest version of the library.
