### ISSUE TITLE
Y-axis indices are not properly aligned with rule lines

### ISSUE THREAD

**Issue by tfkennedy777** [Abhinandan-Kushwaha/react-native-gifted-charts#577]
Rather than aligning vertically, the rule lines appear to sit on top of the indices
![Screenshot 2024-03-20 at 12 47 30 PM](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/97812981/3efca088-1824-4eb8-a0ff-1aa27c1f2e59)

**Comment by g-sharat** [comment]
+1 facing same issue here

**Comment by Abhinandan-Kushwaha** [comment]
Hi @g-sharat @tfkennedy777 👋
Thanks for reporting this bug. It has been fixed in versions `1.4.19` onwards. 🎉
please use the latest version of the library.
