### ISSUE TITLE
Y-axis is always from 0,

### ISSUE THREAD

**Issue by AndrianarivoAlpha** [Abhinandan-Kushwaha/react-native-gifted-charts#579]
Hello, I want to know how can I set a minimum value in LineChart props please?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @AndrianarivoAlpha 
You can use the `yAxisOffset` prop to set a minimum value on the y Axis.

**Comment by AndrianarivoAlpha** [comment]
> Hi @AndrianarivoAlpha 
> 
> You can use the `yAxisOffset` prop to set a minimum value on the y Axis.

Hi, oh thank you so much. You have made a good job 🙏🙏🙏
