### ISSUE TITLE
Add Border color for each bar chart

### ISSUE THREAD

**Issue by ChauVV** [Abhinandan-Kushwaha/react-native-gifted-charts#580]
How can i add border color for each bar chart like below:
![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/16476877/3b2ece30-6adf-422a-b6f9-837fadec8166)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ChauVV 👋
Thanks for requesting this feature. We already had support for `barBorderColor` and `barBorderWidth` props, but they applied to all the bars through props.
Now we can set the properties `barBorderWidth` and `barBorderColor` to data items through the data array, so each bar can have its own border color and width.

This feature is available from version `1.4.19` onwards.
please use the latest version of the library.
