### ISSUE TITLE
LineChart: set dash line for whole

### ISSUE THREAD

**Issue by ChauVV** [Abhinandan-Kushwaha/react-native-gifted-charts#591]
i try add dash line for whole, then i set lineSegment like this:

![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/16476877/83291352-dae0-4d8f-9e10-a41c7209924a)

Let's set `endIndex` as an option, because i dont know the endIndex.

my chart without endIndex:
![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/16476877/a0fcb3a0-9a48-4f4e-9e65-1df326a04a49)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ChauVV 
Thanks for your suggestion to make the `endIndex` optional.

But if you want the whole line to be dashed, then you don't need to use the `lineSegments2` prop. Instead, you can directly use the `strokeDashArray2` prop. It will make the entire line dashed.
