### ISSUE TITLE
Lock strip line on chart

### ISSUE THREAD

**Issue by ChauVV** [Abhinandan-Kushwaha/react-native-gifted-charts#592]
How i can lock a strip on chart, event scrolling.

<img width="365" alt="strip" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/16476877/364ce852-63fd-4865-9e01-fc29407ea382">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ChauVV 
There are many ways to achieve it.

1. Use `showStrip: true` in your desired item in the data array, and set `stripWidth`,`stripColor` and `stripOpacity` properties.
2. Use `focusEnabled` and `showStripOnFocus` props along with `stripWidth`,`stripColor` and `stripOpacity`.
3. Use the `showVerticalLine` prop and set the thickness color etc.

See the [props table here](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/LineChart/LineChartProps.md)
