### ISSUE TITLE
Incomplete Vertical Grid Lines in Bar Chart

### ISSUE THREAD

**Issue by skfaisal93** [Abhinandan-Kushwaha/react-native-gifted-charts#595]
### Description
The vertical grid lines in the Bar Chart component do not extend to the bottom of the chart area, resulting in an incomplete grid visualization.

### Steps to Reproduce
1. Render a `BarChart` component with a set of data points.
2. Observe the vertical grid lines.

### Expected Behavior
The vertical grid lines should extend across the entire height of the chart area, reaching the bottom edge.

### Actual Behavior
The vertical grid lines stop short and do not reach the bottom of the chart area.

### Code
```
<BarChart
    yAxisThickness={0}
    xAxisThickness={0}
    data={DATA1}
    frontColor={'#e19b9980'}
    barWidth={45}
    rulesType={"solid"}
    stepHeight={50}
    barBorderWidth={2}
    barBorderColor={"#e19b99"}
    showVerticalLines={true}
    verticalLinesSpacing={75}
    rotateLabel={true}
/>
```

### Screenshots
![Screenshot 2024-04-07 074717](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/16177407/4c9fc3de-5947-45b8-b6f4-126ccad2b6e7)

### Environment
- Library Version: ^1.4.9
- Expo Version: ~50.0.6
- React Native Version: 0.73.4
- Platform: Web
- React Native Web Version: ~0.19.6

### Additional Context
Also it looks like that if I rotate label then it is getting cropped, I did not set any height of the bar or container.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @skfaisal93 👋
I am unable to reproduce this bug. Can you please check once again in the latest version of the library?
The current latest version is `1.4.19`.

**Comment by bhavesh-trentium** [comment]
@Abhinandan-Kushwaha Same Issue with me.

-   "gifted-charts-core": "^0.1.30",
-    "react-native-gifted-charts": "^1.4.29",
-    "react": "18.2.0",
-    "react-dom": "18.2.0",
-    "expo": "^49.0.21",

code: 
```
                 const  data={[
                        {
                          value: 15,
                          label: 'Jan',
                          frontColor: '#d51717',
                          barBorderColor: '#808080',
                          barWidth: 20,
                          barBorderRadius: 4,
                          barBorderWidth: 1,
                          spacing: 20,
                        },
                        {
                          value: 40,
                          label: 'Feb',
                          frontColor: '#79d517',
                          barBorderColor: '#ff0000',
                          barWidth: 20,
                          barBorderRadius: 4,
                          barBorderWidth: 1,
                          spacing: 20,
                        },
                        {
                          value: 10,
                          label: 'Mar',
                          frontColor: '#d55617',
                          barBorderColor: '#5800e6',
                          barWidth: 20,
                          barBorderRadius: 4,
                          barBorderWidth: 1,
                          spacing: 20,
                        },
                      ]}
              <BarChart
                  data={data}
                 width={Dimensions.get('window').width - 120}
                height={300}
                dashGap={0}
                 showVerticalLines={true}/>
```

![image](https://github.com/user-attachments/assets/224b1c0c-37f5-43d6-8db0-2f209037d76e)

**Comment by Abhinandan-Kushwaha** [comment]
@bhavesh-trentium 
For me your code produces the below output, the grid lines are rendered properly-

<img width="325" alt="Screenshot 2024-08-23 at 9 50 35 PM" src="https://github.com/user-attachments/assets/ea08803b-39f2-4020-b916-15b1a3b61251">

**Comment by bhavesh-trentium** [comment]
@Abhinandan-Kushwaha Can you check above i have package version and you have version is same?

**Comment by Abhinandan-Kushwaha** [comment]
Yes @bhavesh-trentium I tested on the same versions which you have. Did you run it on Android or iOS or web?

**Comment by Abhinandan-Kushwaha** [comment]
For web, use the [react-gifted-charts](https://www.npmjs.com/package/react-gifted-charts) library.

**Comment by bhavesh-trentium** [comment]
@Abhinandan-Kushwaha I used this: `react-gifted-charts` library. But Fetching Some Issues Check this one: [https://github.com/Abhinandan-Kushwaha/react-gifted-charts/issues/4#issuecomment-2312029465](url)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @bhavesh-trentium 
react-gifted-charts does not work in React-Native projects. It works in ReactJS projects only.

I will make the fix for issues you are facing on web using `react-native-gifted-charts`.

**Comment by bhavesh-trentium** [comment]
@Abhinandan-Kushwaha Okay, thanks. You fix that and let me know.
