### ISSUE TITLE
Add axis name

### ISSUE THREAD

**Issue by ChauVV** [Abhinandan-Kushwaha/react-native-gifted-charts#598]
How can i add Axis name like this

![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/16476877/eb2a63a3-4f3b-4c78-b576-23515963a07a)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ChauVV 
Thanks for requesting this feature. I will add it in the next release.

For now, I can suggest you a workaround. Try adding Text with position absolute. Here's an example-

```js
const data= [
  {value:10, label:'2'},
  {value:15, label:'3'},
  {value:18, label:'4'},
  {value:15, label:'5'},
  {value:12, label:'6'},
  {value:8, label:'7'},
]
return(
  <View style={{marginTop:20}}>

    <LineChart
      data={data}
    />

    <View style={{position:'absolute',top:-20,left:16}}>
      <Text>Wh</Text>
    </View>

    <View style={{position:'absolute',bottom:12,right:32}}>
      <Text>Days</Text>
    </View>
    
  </View>
)
```
Output-

<img width="365" alt="Screenshot 2024-04-09 at 11 44 50 AM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/48578b6a-8192-4c6b-b536-8f072c3d913f">
