### ISSUE TITLE
How to give a pound symbol(£) in bar chart along y-axis label values?also hideOrigin not hiding origin in Bar chart

### ISSUE THREAD

**Issue by VijinR** [Abhinandan-Kushwaha/react-native-gifted-charts#60]
£10
£20
hideOrigin={true}

**Comment by Abhinandan-Kushwaha** [comment]
Hi @VijinR 👋

You can display custom text on y-axis using the `yAxisLabelTexts` prop. For example-

```js
<BarChart
 data={barData}
  yAxisLabelTexts={['0', '£10', '£20']} />
```
By default, there are 10 sections in the chart. You can control the number of sections using the `noOfSections` prop.

The issue with hideOrigin is now fixed in version `0.2.6` 🎉
Cheers! 🍻

**Comment by VijinR** [comment]
@Abhinandan-Kushwaha by using yAxisLabelTexts we must specify the value also right?how we will get the y-axis value been generated by default by library?I need the default yaxis value generated by library with '£' appended at beginning

**Comment by Abhinandan-Kushwaha** [comment]
Use `yAxisLabelPrefix='£'`
