### ISSUE TITLE
endSpacing increase my chart width

### ISSUE THREAD

**Issue by ChauVV** [Abhinandan-Kushwaha/react-native-gifted-charts#604]
This is my chart with 2 Y axis, 
- 1st case: 
chart 
width = 280
endSpacing = 10

![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/16476877/2201b475-644c-4c00-aaea-023fce47a11f)

- 2nd case: 
chart 
width = 280
endSpacing = 30

![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/16476877/8b8bc8ad-884b-454f-b8fb-e6706d54b192)

- 3th case:
chart 
width = 280
endSpacing = 100

![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/16476877/2d8da021-fb8c-40dc-abc9-6da1faac6ca2)

Increase endSpacing , chart width increase too, my 2nd Y axis is go out of screen.
I want to set endSpacing = chartWidth/2, how i keep my chart width, keep my 2nd y asix.

my code:
```
const color1 = '#4A48CA';
const color2 = '#FF76EC';
const AXIS_COLOR = '#A9C3FA';
const Y_LABEL_WIDTH = 35;
const CHART_HEIGHT = 300;
const CHART_WIDGHT = 280;
const SPACING = CHART_WIDGHT / 10;
const END_SPACING = 100;

<View style={styles.vChart}>
        <LineChart
          interpolateMissingValues={false}
          onlyPositive
          spacing={SPACING}
          initialSpacing={SPACING}
          color1={color1}
          textShiftX={0}
          textShiftY={-10}
          textColor1={'#595E63'}
          textColor2={'#595E63'}
          dataPointsHeight={9}
          dataPointsWidth={9)}
          dataPointsColor1={color1}
          xAxisLabelTextStyle={styles.xAxislabel}
          yAxisTextStyle={styles.yAxislabel}
          xAxisTextNumberOfLines={2}
          xAxisColor={AXIS_COLOR}
          xAxisThickness={2}
          yAxisColor={color1}
          yAxisThickness={2}
          thickness={3}
          focusEnabled
          showDataPointOnFocus={true}
          showTextOnFocus
          width={CHART_WIDGHT}
          height={CHART_HEIGHT}
          textFontSize={12}
          data={data1}
          hideYAxisText={isLoading}
          yAxisLabelWidth={Y_LABEL_WIDTH}
          scrollToEnd
          //
          secondaryData={data2}
          secondaryLineConfig={{ color: color2 }}
          secondaryYAxis={{
            showFractionalValues: true,
            yAxisColor: color2,
            yAxisIndicesColor: color2,
          }}
          endSpacing={END_SPACING}
        />
      </View>
      
      
const styles = StyleSheet.create({
  vChart: {
    maxWidth: CHART_WIDGHT
  },
});
```

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ChauVV 
You said you want `endSpacing = chartWidth/2`

Let's say you want the total chart width to be 280, and endSpacing to be 140.
For this, you can do this-

```js
width={140}
endSpacing={140}
```

So, the total chart width will become `140+140 = 280`

**Comment by ChauVV** [comment]
i mean that, 
i want to set shift end of chart from right border,
it's should have a padding for first time.
After that, when i scroll the chart to right, it's should not cut line at middle.

i just want to set first init padding like bar chart in my video.

https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/16476877/970cab44-56a3-4865-8994-5934b816d15a

**Comment by ChauVV** [comment]
hi @Abhinandan-Kushwaha , i try to add paddingRight but it's not effect.

In react-native-gift-charts
src/Components/BarAndLineChartsWrapper
ScrollView>contentContainerStyle

i try to add `paddingRight: 150`
but it's not effect.
![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/16476877/b275ed80-dda0-42cd-9d7a-481544d25720)
