### ISSUE TITLE
LineChart(AreaChart) : Strip Type Change (Solid, Dotted, Dashed)

### ISSUE THREAD

**Issue by dasjideepak** [Abhinandan-Kushwaha/react-native-gifted-charts#611]
```
const data = [ {
      showStrip: true,
      stripColor: colors.primaryBlue,
      stripHeight: 152,
      value: 66,
  }]
```

How I can update the strip type (from solid to dashbed) in LineChart (Area Chart)?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @dasjideepak 👋
Thanks for requesting this feature.
Added the prop `stripStrokeDashArray` to support dotted and dashed vertical strips in Line and Area charts.

This feature is available from version `1.4.19` onwards.🎉
Please use the latest version of the library.
