### ISSUE TITLE
How to use custom String value on Y axis

### ISSUE THREAD

**Issue by ErMapsh** [Abhinandan-Kushwaha/react-native-gifted-charts#613]
i want to do like this, how I can do
![temp](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/72149385/d6af6a53-1cf8-4a1c-a940-8ed24e7cda24)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ErMapsh 👋
You can use the `yAxisLabelTexts` prop. It takes an array of label texts to be displayed along y-axis.
See [Axes and rules related props](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/BarChart/BarChartProps.md#axes-and-rules-related-props)
