### ISSUE TITLE
Labels on xAxis are not visible | BarChart

### ISSUE THREAD

**Issue by sanford-fernandes** [Abhinandan-Kushwaha/react-native-gifted-charts#614]
I am testing BarChart on my ongoing project and most of the things work as expected. Only issue that is bothering right now is the labels on the xAxis are not displayed at all the way they should. Kindly help!

**Comment by rrameshbtech** [comment]
+1 For me, Seems based on screen size it is behaving differently. For example, it shows labels in pixel simulator, but in Redme note 11 it is cropping the x axis label. Also `xAxisLabelTextStyle` does not impact the style. Any help?

**Comment by rrameshbtech** [comment]
-Update-
I am able to workaround using labelComponent. Thanks

**Comment by sanford-fernandes** [comment]
> -Update- I am able to workaround using labelComponent. Thanks

This actually worked! Thank you so much!! @rrameshbtech

**Comment by Abhinandan-Kushwaha** [comment]
Hi @rrameshbtech Thanks for the solution.

Also, if you don't want to use the `labelComponent` you can still fix the issue with the help of the following props-

1. `xAxisLabelsHeight`
2. `xAxisLabelsVerticalShift`
3. `labelsExtraHeight`

See the [Axes and rules related props](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/BarChart/BarChartProps.md#axes-and-rules-related-props)
