### ISSUE TITLE
Need to add Title for X Axis and Y Axis

### ISSUE THREAD

**Issue by maheshkannank** [Abhinandan-Kushwaha/react-native-gifted-charts#619]
I need to give the Title for Y Axis for example I have Indices for Temperature I need to Give Title as Temperature and for same as X Axis for example if it have Date as Indices I need give Title as Date

**Comment by Abhinandan-Kushwaha** [comment]
Hi @maheshkannank 
You can easily render titles with Text components before/under/around the chart component.
The library doesn't support Axis titles becauese-

1. It is very easily to implement by yourself
2. Axis titles are usually outside the chart- (before/under/around)
3. You can customise the title components and their positions to greater extent if youimplement it by yourself
