### ISSUE TITLE
Type Error: Have any of these errors been reported?

### ISSUE THREAD

**Issue by ygnoh** [Abhinandan-Kushwaha/react-native-gifted-charts#625]
https://stackoverflow.com/questions/78427587/tsc-keeps-tracking-node-modules-can-anyone-help-me-resolve-this-issue

I'm using Expo, and I'm reaching out because I'm getting `react-native-gifted-charts` caught in the `tsc` error.

I understand that this is a TS  configuration error, but I'm reaching out to see if you've seen any reports of it.

Thank you.

**Comment by leineveber** [comment]
Same here, nothing helps..

**Comment by ygnoh** [comment]
@leineveber Did you solve it? I can't find any solutions.

**Comment by ygnoh** [comment]
I think it's not a TS configuration error but this library.
@Abhinandan-Kushwaha Could you help?

**Comment by mhfortuna** [comment]
hey there, I was also having this issue but I used the solution from this other issue: https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/473
I think it is the same 🙂

**Comment by leineveber** [comment]
@mhfortuna it works, great job!

**Comment by ygnoh** [comment]
@mhfortuna It does not work. It looks like outdated:

```
Applying patches...

**ERROR** Failed to apply patch for package gifted-charts-core at path
  
    node_modules/gifted-charts-core

  This error was caused because gifted-charts-core has changed since you
  made the patch file for it. This introduced conflicts with your patch,
  just like a merge conflict in Git when separate incompatible changes are
  made to the same piece of code.

  Maybe this means your patch file is no longer necessary, in which case
  hooray! Just delete it!

  Otherwise, you need to generate a new patch file.

  To generate a new one, just repeat the steps you made to generate the first
  one.

  i.e. manually make the appropriate file changes, then run 

    patch-package gifted-charts-core

  Info:
    Patch file: patches/gifted-charts-core+0.0.21.patch
    Patch was made for version: 0.0.21
    Installed version: 0.1.4

---
patch-package finished with 1 error(s).
```

**Comment by leineveber** [comment]
@ygnoh as far as I understand, you're trying to use patch from the "instructions", please try to do your own patch using steps from the "alternative instructions"

**Comment by ygnoh** [comment]
@leineveber Thanks! It works well

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ygnoh @leineveber @mhfortuna 
`react-native-gifted-charts` is now shipping compiled js files instead of ts files from version `1.4.22` onwards. This should fix all type related issues. 🎉

**Comment by mhfortuna** [comment]
thanks @Abhinandan-Kushwaha and great work 🙌🏻
