### ISSUE TITLE
Bar chart with onFocus/pointerConfig (touch and drag) support?

### ISSUE THREAD

**Issue by jamesmcn1** [Abhinandan-Kushwaha/react-native-gifted-charts#633]
Hi there!

We have a bar chart like the below:

![Screenshot 2024-05-14 at 16 03 45](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/31623929/28b481be-5bb8-4569-85e4-6882c443cbe7)
 
I'm looking for functionality that will allow us to drag/swipe our fingers across the bar chart and select the render the tooltip for the bar closest to our finger. I noticed there is a similar functionality via the `onFocus` prop on LineChart's but not BarChart.

Has someone done this before or is there any plans to add this functionality?

Cheers

**Comment by Abhinandan-Kushwaha** [comment]
Hi @jamesmcn1 👋
You can use the `pointerConfig` prop to achieve this.
