### ISSUE TITLE
onBlur or make out of focus area chart props

### ISSUE THREAD

**Issue by Yogeshwar267** [Abhinandan-Kushwaha/react-native-gifted-charts#634]
i cant find any event if i click outside region for area chart and alo no option for text label of pointer position prop to make it in bottom at x axis or top

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Yogeshwar267 👋
Thanks for requesting this feature.

I have added 2 new props named `onChartAreaPress` and `onBackgroundPress` which you can use to click inside and outside region for area chart. It is available from version `1.4.17` onwards.  🎉

Please use the latest version of the library.

**Comment by shubham-cpp** [comment]
Hello @Abhinandan-Kushwaha , can we add similar events to `BarChart`?

**Comment by shubham-cpp** [comment]
Hello @Abhinandan-Kushwaha, an updates on this?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @shubham-cpp Thanks for requesting this feature. It is now available from versions `1.4.59` onwards. 🎉

Please use the latest version of the library.
