### ISSUE TITLE
[web] Partial data loss when getting over `250px` of height

### ISSUE THREAD

**Issue by FacuM** [Abhinandan-Kushwaha/react-native-gifted-charts#636]
On the web, changing the height of the graph breaks the amount of displayed information from the `data` array.

This behaviour isn't observed within **Expo Go** on an **Android device**.

Here's the code for the broken component:

```TSX
import { View } from "react-native";
import { useTheme } from "react-native-paper";

import { LineChart } from "react-native-gifted-charts";
import { useSafeAreaFrame } from "react-native-safe-area-context";
import { useState } from "react";

export default function Index() {
  const [ graphHeight, setGraphHeight ] = useState(0);

  console.log('graphHeight:', graphHeight);

  const { colors } = useTheme();

  const data = [
    {
      value: 50, 
      date: '20 Apr 2022',
      label: '20 Apr'
    },
    {
      value: 80,
      date: '20 Apr 2022',
      label: '20 Apr'
    },
    { value: 90 },
    { value: 70 }
  ];

  return (
    <>
      <View style={{ display: 'flex', flexGrow: 1 }} onLayout={event => setGraphHeight(event.nativeEvent.layout.height)}></View>
      <View style={{ position: 'absolute', height: graphHeight }}>
        <LineChart
          data={data}
          height={graphHeight - 52}
          initialSpacing={0}
          showXAxisIndices={true}
          adjustToWidth={true}
          textColor={colors.onBackground}
          rulesColor={colors.onBackground}
          dataPointsColor={colors.onBackground}
          stripColor={colors.onBackground}
          yAxisColor={colors.onBackground}
          xAxisColor={colors.onBackground}
          verticalLinesColor={colors.onBackground}
          showValuesAsDataPointsText={true}
          textShiftY={-12}
          textFontSize={16}
          yAxisTextStyle={{ color: colors.onBackground }}
          xAxisLabelTextStyle={{ color: colors.onBackground }}
          isAnimated={true}
          animateOnDataChange={true}
          color={colors.onBackground}
        />
      </View>
    </>
  );
}
```

Here's a screenshot from the web with a height of `250px`:

![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/3741108/b223592e-07c7-4c0a-9409-3f28a46a1e6e)

And here's one when going with the full height of the container:

![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/3741108/bb206b05-e438-4013-93be-85da6fa8c713)

However, here's how it looks totally fine on a *native* device:

![IMG_20240519_212815_487](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/3741108/f4af09e5-2a8f-42fb-b2f9-8831d0638601)

Please let me know if I missed any information to help when debugging the issue.

**Comment by FacuM** [comment]
> Same issue, did you find a way to fix it? @FacuM

Nothing so far, I've paused this project for now though, I'm not in the mood to keep it up.

Hope the owner can get it sorted out so that I can keep using this library.

**Comment by dhinesh-foodhub** [comment]
The chart gets cropped in web for some reasons
<img width="361" alt="Screenshot 2024-07-15 at 3 56 52 PM" src="https://github.com/user-attachments/assets/3bb778d4-7071-47d4-99ec-0250ae808703">


The below is the screenshot of same component used in mobile 
<img width="308" alt="Screenshot 2024-07-15 at 3 54 27 PM" src="https://github.com/user-attachments/assets/c07a6504-96f0-4089-bae8-99c6f61ca3ec">

**Comment by tafty** [comment]
@dhinesh-foodhub I'm not sure why you've tagged me: I'm not a maintainer or expert on this library; my only contribution has been a one line update to the Typescript declarations; I have also not used this library on the web. Sorry, but I cannot help.

**Comment by Rouret** [comment]
@FacuM @dhinesh-foodhub I created a patch package to fix the library. The fix involves using onLayout on the graph view to get the width and height and applying this to the content of the graph.

I will try to create a PR this week to fix it.

**Comment by FacuM** [comment]
> @FacuM @dhinesh-foodhub I created a patch package to fix the library. The fix involves using onLayout on the graph view to get the width and height and applying this to the content of the graph.
> 
> I will try to create a PR this week to fix it.

Oh, I'm really sorry. I was going through my open issues and figured I didn't reply here.

Any chances you can make a branch specificallly with those changes? I guess I could get this going on my end with `patch-package`, did you try to do so on your project?

**Comment by Abhinandan-Kushwaha** [comment]
@FacuM I guess it was fixed at some point. Not sure though, can you test with the latest version of react-native-gifted-charts once?

**Comment by FacuM** [comment]
> @FacuM I guess it was fixed at some point. Not sure though, can you test with the latest version of react-native-gifted-charts once?

It does absolutely work!

**Web:**

![image](https://github.com/user-attachments/assets/77a80a51-3e56-4efd-9ddf-74d45ebe53ea)

**Android:** (via Expo Go)

![image](https://github.com/user-attachments/assets/67bbde02-6c33-46d1-a82a-3f4cf1faa9bc)

Thanks for the hint! 😄 Looks like this one is good to go!
