### ISSUE TITLE
The `mostNegativeValue` setting does not appear to be working as expected.

### ISSUE THREAD

**Issue by god-zhang** [Abhinandan-Kushwaha/react-native-gifted-charts#638]
Hello, thank you very much for this library, it's fantastic! However, I have a question:
I've set both mostNegativeValue and maxValue, but mostNegativeValue isn't displaying as the value I provided. Instead, it's showing a symmetric negative value relative to the maximum value. Why is this happening? Here's my code snippet:
`<BarChart
                                                            width={adapterSize(282)}
                                                            frontColor={colors.color_3d8}
                                                            barWidth={report.bar_data.data.length < 5 ? adapterSize(28) : adaptFontSize(175/report.bar_data.data.length)}
                                                            height={adapterSize(222)}
                                                            data={report.bar_data.data}
                                                            showYAxisIndices
                                                            showXAxisIndices
                                                            noOfSections={5}
                                                            noOfSectionsBelowXAxis={calcMaxMin(values).min < 0 ? 5 : 0}
                                                            initialSpacing={9}
                                                            maxValue={calcMaxMin(values).max}
                                                            mostNegativeValue={calcMaxMin(values).min}
                                                            spacing={16}
                                                            autoShiftLabels
                                                            yAxisLabelWidth={adapterSize(40)}
                                                            yAxisTextStyle={{ color: colors.color_505, fontSize: adaptFontSize(8) }}
                                                            xAxisLabelTextStyle={{ color: colors.color_505, fontSize: adaptFontSize(8) }}
                                                            xAxisIndicesWidth={0}
                                                            xAxisTextNumberOfLines={3}
                                                            xAxisThickness={0}
                                                            barBorderRadius={4}
                                                            dashGap={adapterSize(0)}
                                                            yAxisThickness={0}
                                                            yAxisIndicesWidth={0}
                                                            disablePress
                                                            hideRules
                                                            yAxisLabelContainerStyle={{ width: adapterSize(40), marginLeft: adapterSize(-3) }}
                                                        />`
My dataset (values) consists of the following numbers:
[1550000.0, 720000.0, 28761.0599999998, 7522.12, 2035.4, -6194.690002]

Within this dataset, I've correctly set the maximum value to 1550000.0, and it displays as expected. But when I set the minimum value (mostNegativeValue) to -6194.690002, it doesn't display properly; instead, it appears as -1550000.0.

Additionally, manually assigning a value of -10000 to mostNegativeValue results in the application crashing.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @god-zhang 
This has been fixed from version `1.4.15` onwards.
