### ISSUE TITLE
Set NegativeHeight

### ISSUE THREAD

**Issue by freudarian** [Abhinandan-Kushwaha/react-native-gifted-charts#639]
I am facing an issue with data visualization where the use of negativeSections and mostNegativeValue results in data points disappearing if they exceed the predefined negative values. The problem arises because these sections and values are symmetric to the positive values.

To improve the visualization, I need the following:

Custom Negative Height: Implement a negative height setting that allows for a different proportion compared to the positive values. This will enhance the visual appeal and provide more design flexibility.
Boundary Handling: Ensure that all data points remain within their border limits, without disappearing when they exceed the predefined sections or values.
Percentage-wise Representation: Ideally, maintain a percentage-wise representation of data points so they do not go out of bounds.
This approach will ensure that the visualization is more flexible and aesthetically pleasing, without data points being cut off.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @freudarian 
This has been fixed from version `1.4.15` onwards. Added the props `negativeStepValue` and `negativeStepHeight` that can be used to control the negative heights independent of the positive ones.
