### ISSUE TITLE
Support for secondaryXAxis

### ISSUE THREAD

**Issue by devevecare** [Abhinandan-Kushwaha/react-native-gifted-charts#642]
Hi,

I can see there is secondaryYAxis props in bar chart, can we have similar for x axis as well.

As you can see in the video, which is from an app which I am referring to make my current app, we have x axis labels and as well as labels at the top of the axis for each month. 

Can we support this?

https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/151470851/5f17ee8d-99da-486b-b19b-1e97f9eb214a

**Comment by Abhinandan-Kushwaha** [comment]
Hi @devevecare 👋
Thanks for requesting this feature. It is now available from version `1.4.18` onwards.🎉

Added the prop `secondaryXAxis` to render an additional X axis at the top of the chart.

The labels to be displayed along the secondary X-axis can be passed in these 2 ways-
   1. Through the property named `secondaryLabel` in the data array
   2. Through the property named `labelTexts` in the `secondaryXAxis` prop.

The `secondaryXAxis` props accepts an object of the following type-
```ts
XAxisConfig {
  thickness?: number
  color?: ColorValue
  labelsDistanceFromXaxis?: number
  labelsHeight?: number
  labelsTextStyle?: any
  labelTexts?: string[]
}
```
