### ISSUE TITLE
Different values are being shown in PointerLabelComponent using LineChart

### ISSUE THREAD

**Issue by AbdulHadi1010** [Abhinandan-Kushwaha/react-native-gifted-charts#645]
Hi! 👋 

I am using this package with these versions.

- "react-native-gifted-charts": "^1.4.10"
- "react": "18.2.0"
- "react-native": "0.74.0",

I was trying to pass a data to LineChart and show it using PointerConfig. The graph was rendered with the correct values but the PointerConfig had different values. This is my code for rendering LineChart:

```
           <LineChart
              areaChart
              data={chartData}
              rotateLabel
              yAxisOffset={chartData[0]?.value - 20}
              width={widthToDp(100)}
              hideDataPoints
              color="#00ff83"
              thickness={2}
              startFillColor="rgba(20,105,81,0.3)"
              endFillColor="rgba(20,85,81,0.01)"
              startOpacity={0.9}
              endOpacity={0.2}
              initialSpacing={0}
              noOfSections={5}
              yAxisThickness={0}
              rulesColor="transparent"
              yAxisTextStyle={{color: Colors.white}}
              xAxisColor="lightgray"
              pointerConfig={{
                pointerStripHeight: widthToDp(15),
                pointerStripColor: 'lightgray',
                pointerStripWidth: 2,
                pointerStripHeight: widthToDp(40),
                pointerColor: 'lightgray',
                radius: 6,
                pointerLabelWidth: widthToDp(20),
                pointerLabelHeight: widthToDp(20),
                activatePointersOnLongPress: true,
                autoAdjustPointerLabelPosition: false,
                pointerLabelComponent: items => {
                  // console.log(items);
                 // The values inside the items were different to the data provided
                  return (
                    <View
                      style={{
                        height: 90,
                        width: 100,
                        justifyContent: 'center',
                        marginTop: -30,
                        marginLeft: -40,
                      }}>
                      <Text
                        style={{
                          color: 'white',
                          fontSize: 14,
                          marginBottom: 6,
                          textAlign: 'center',
                        }}>
                        {items[0].date}
                      </Text>

                      <View
                        style={{
                          paddingHorizontal: 14,
                          paddingVertical: 6,
                          borderRadius: 16,
                          backgroundColor: 'white',
                        }}>
                        <Text
                          style={{
                            fontWeight: 'bold',
                            textAlign: 'center',
                            color: 'black',
                          }}>
                          {'$' + items[0].value}
                        </Text>
                      </View>
                    </View>
                  );
                },
              }}
            />
```
Here is the diff that solved my problem:

```diff
// var data = useMemo(function () { return getSanitisedData(props.data, dataSanitisationProps); }, [yAxisOffset, props.data]);
    var data = useMemo(function () { return props.data; }, [yAxisOffset, props.data]);
    var data2 = useMemo(function () { return getSanitisedData(props.data2, dataSanitisationProps); }, [yAxisOffset, props.data2]);
    var data3 = useMemo(function () { return getSanitisedData(props.data3, dataSanitisationProps); }, [yAxisOffset, props.data3]);
    var data4 = useMemo(function () { return getSanitisedData(props.data4, dataSanitisationProps); }, [yAxisOffset, props.data4]);
    var data5 = useMemo(function () { return getSanitisedData(props.data5, dataSanitisationProps); }, [yAxisOffset, props.data5]);
    var secondaryData = (_e = getSecondaryDataWithOffsetIncluded(props.secondaryData, props.secondaryYAxis, showDataPointsForMissingValues, interpolateMissingValues, onlyPositive)) !== null && _e !== void 0 ? _e : [];
```
Original Data
`
[{"date": "2023-05-23", "time": "16:00:00", "value": 306.88}, {"date": "2023-06-09", "time": "16:00:00", "value": 387.7}, {"date": "2023-06-28", "time": "16:00:00", "value": 411.17}, {"date": "2023-07-17", "time": "16:00:00", "value": 464.61}, {"date": "2023-08-02", "time": "16:00:00", "value": 442.69}, {"date": "2023-08-18", "time": "16:00:00", "value": 432.99}, {"date": "2023-09-06", "time": "16:00:00", "value": 470.61}, {"date": "2023-09-22", "time": "16:00:00", "value": 416.1}, {"date": "2023-10-10", "time": "16:00:00", "value": 457.98}, {"date": "2023-10-26", "time": "16:00:00", "value": 403.26}, {"date": "2023-11-13", "time": "16:00:00", "value": 486.2}, {"date": "2023-11-30", "time": "16:00:00", "value": 467.7}, {"date": "2023-12-18", "time": "16:00:00", "value": 500.77}, {"date": "2024-01-05", "time": "16:00:00", "value": 490.97}, {"date": "2024-01-24", "time": "16:00:00", "value": 613.62}, {"date": "2024-02-09", "time": "16:00:00", "value": 721.33}, {"date": "2024-02-28", "time": "16:00:00", "value": 776.63}, {"date": "2024-03-15", "time": "16:00:00", "value": 878.37}, {"date": "2024-04-03", "time": "16:00:00", "value": 889.64}, {"date": "2024-04-19", "time": "16:00:00", "value": 762}, {"date": "2024-05-07", "time": "16:00:00", "value": 905.54}, {"date": "2024-05-23", "time": "16:00:00", "value": 1037.99}],
`

Data from Items Array before patching
`
 LOG  [{"date": "2023-08-02", "time": "16:00:00", "value": 155.81}]
 LOG  [{"date": "2023-08-02", "time": "16:00:00", "value": 155.81}]
 LOG  [{"date": "2023-06-28", "time": "16:00:00", "value": 124.29000000000002}]
 LOG  [{"date": "2023-06-09", "time": "16:00:00", "value": 100.82}]
 LOG  [{"date": "2023-06-28", "time": "16:00:00", "value": 124.29000000000002}]
 LOG  [{"date": "2023-07-17", "time": "16:00:00", "value": 177.73000000000002}]
 LOG  [{"date": "2023-07-17", "time": "16:00:00", "value": 177.73000000000002}]
`

### To Reproduce this issue:
Pass the above original data with the given LineChart props

**Comment by Abhinandan-Kushwaha** [comment]
Hi @AbdulHadi1010 👋
Thanks for reporting this issue. It has been fixed in versions `1.4.17` onwards. 🎉

Please use the latest version of the library.
