### ISSUE TITLE
Pointer Label component is cutting on the edges in LineChart

### ISSUE THREAD

**Issue by Ashishpal438** [Abhinandan-Kushwaha/react-native-gifted-charts#648]
When I go to the extreme right or left, pointer label component box is cutting from the screen. How to make it responsive and auto adjust when we slide left or right.

Attaching the screenshot of the middle and extreme left pointer label component.

@Abhinandan-Kushwaha 

I tried to fix this by setting **autoAdjustPointerLabelPosition: true** but that also doesn't fix this.

<img width="354" alt="Screenshot 2024-05-28 at 10 30 11 AM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/72219646/6bdc20b5-84d6-4ba8-89dc-9059e96cdc7a">

<img width="344" alt="Screenshot 2024-05-28 at 10 29 51 AM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/72219646/7546e300-c0e2-4f91-8ab6-aaa3b39edfd5">

**Comment by Harshrath0re** [comment]
were able to find any solution for this??

**Comment by Ashishpal438** [comment]
Yes, I have fixed the above issue temporarily. 

<img src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/72219646/1b7138fd-ca97-4f3c-9d8f-1ded971f094c" width="250">
<img src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/72219646/8872a815-62f2-43de-ae96-555f92579f5b" width="250">
<img src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/72219646/69227722-19bd-4d16-b24d-95865692b350" width="250">
 

.

You can use the below code to render the pointer Label accordingly on the edges : 

```
import { Dimensions, PanResponder } from "react-native";
```

```
 const position = useRef({ x: 0, y: 0 }).current;
 const [touchPosition, setTouchPosition] = useState({ x: 0, y: 0 });

 const deviceWidth = Dimensions.get("window").width;

 const panResponder = useRef(
    PanResponder.create({
      onStartShouldSetPanResponder: () => true,
      onMoveShouldSetPanResponder: () => true,
      onPanResponderGrant: (evt, gestureState) => {
        // The touch has started
        position.x = gestureState.x0;
        position.y = gestureState.y0;
        setTouchPosition({ x: gestureState.x0, y: gestureState.y0 });
      },
      onPanResponderMove: (evt, gestureState) => {
        // The touch is moving
        position.x = gestureState.moveX;
        position.y = gestureState.moveY;
        setTouchPosition({ x: gestureState.moveX, y: gestureState.moveY });
      },
      onPanResponderRelease: (evt, gestureState) => {
        // The touch has ended
        position.x = gestureState.moveX;
        position.y = gestureState.moveY;
        setTouchPosition({ x: gestureState.moveX, y: gestureState.moveY });
      },
    }),
  ).current;
  ```

Wrap your <LineChart/> component inside a <View>  and add the following prop in the view: 
```
 <View
     {...panResponder.panHandlers}
     style={{}}
 >
  <LineChart 
      data={}
      pointerConfig={{
      shiftPointerLabelX: touchPosition.x < deviceWidth / 5 ? 40 : touchPosition.x > deviceWidth * 0.8 ? -60  : 0  
      pointerLabelComponent: : items => {}
      }}
   />
</View>
 ```         

In your Line Chart PointerConfig prop, use the ```shiftPointerLabelX```  prop like below : 

```
shiftPointerLabelX : touchPosition.x < deviceWidth / 5 ? 40 : touchPosition.x > deviceWidth * 0.8 ? -60  : 0  
```

You can use the division and multiplication value (here i have used 5 and 0.8), and the shifting values (here i have used 40 and 60) according to your usecase


Note : This is a temporary solution, we need to fix the ```autoAdjustPointerLabelPosition``` in the library. I will do when i will 
           get time.

**Comment by Harshrath0re** [comment]
Thanks alot ashish for the support

**Comment by frec-hansen** [comment]
Very interesting solution, but unfortunately the panResponder seems to block my chart from receiving the gesture event and the strip stops showing up

**Comment by Ashishpal438** [comment]
we can connect and fix this : https://www.linkedin.com/in/ashish-kumar-pal-2a6954188

**Comment by 1guzzy** [comment]
> Very interesting solution, but unfortunately the panResponder seems to block my chart from receiving the gesture event and the strip stops showing up

Same for me

**Comment by Abhinandan-Kushwaha** [comment]
@Ashishpal438 @Harshrath0re @frec-hansen @1guzzy 
You can wrap the `pointerLabelComponent` in a `View` and provide negative margins inside the style of the View conditionally for the leftmost element. For example-
```js
pointerConfig = {{
  pointerLabelComponent: (items, secondaryItems, index) => {
    return(
      <View style = {{marginLeft: index===0 ? -50 : 0}}>
        <> Your label component </>
      </View>
    )
  }
}}
```
