### ISSUE TITLE
bar chart animation not working in android,working fine in iOS

### ISSUE THREAD

**Issue by VijinR** [Abhinandan-Kushwaha/react-native-gifted-charts#65]
"react-native-gifted-charts": "^0.2.7",

**Comment by Abhinandan-Kushwaha** [comment]
Hi @VijinR 👋

This usually occurs only while development, should work fine when you run it on a real device after generating an apk.

However, to see animations on the simulator while developing, you can try one or more of these-

1. Turning off the remote debugger.
2. Making a change in the code and saving it.
3. Reloading the app.

**Comment by VijinR** [comment]
@Abhinandan-Kushwaha issue still there after generating app

**Comment by Abhinandan-Kushwaha** [comment]
@VijinR I will look into the issue tomorrow, thanks for pointing it out.

**Comment by VijinR** [comment]
Hi @Abhinandan-Kushwaha  any updates on this issue?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @VijinR 👋
Thanks a lot for pointing out this serious issue.

It has now been fixed. 🎉 Please use version `0.2.8`

**Comment by Abhinandan-Kushwaha** [comment]
The issue is now fixed! Please update to the latest version.

**Comment by VijinR** [comment]
@Abhinandan-Kushwaha it worked  on 0.2.8🎉
