### ISSUE TITLE
BarChart with negative values and pointerConfig rendering incorrectly

### ISSUE THREAD

**Issue by mhfortuna** [Abhinandan-Kushwaha/react-native-gifted-charts#654]
Hi there!

First of all, great work with this package, I'm using it to create some charts and so far it's been great 🙂 

I ran into an issue today when the dataset has negative values and we set some stuff to the pointerConfig, looks like this:
<img width="354" alt="image" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/66578026/9dbcf505-8dcc-4d01-b9fd-fa8197790d86">
While leaving everything the same but deleting the pointerConfig looks like this:

<img width="355" alt="image" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/66578026/d184e10f-28ec-499a-a6e5-c50fd4afd752">

Here is a sample snack for you to see the issue itself:
https://snack.expo.dev/@ecoplanet/barchart-issue-react-native-gifted-charts

Am I doing something wrong? Thanks!

**Comment by Haywardchan** [comment]
I encountered the same issue, you can fix it by adding autoShiftLabels for the negative values. 
https://gifted-charts.web.app/barchart

**Comment by Abhinandan-Kushwaha** [comment]
Hi @mhfortuna 👋
Thanks for pointing it out. It has been fixed in version `1.4.11` 🎉

Please use the latest version of the library.
cc: @Haywardchan

**Comment by mhfortuna** [comment]
Thanks!!!!
