### ISSUE TITLE
Line Chart - Multiple secondary y axis data points possible?

### ISSUE THREAD

**Issue by jantznick** [Abhinandan-Kushwaha/react-native-gifted-charts#659]
Hello, loving this library so far. One question I have. 

Is it possible to have multiple data lines on the secondary y axis? Currently trying to graph some weather stats, on the primary y axis I have temperature in f and humidity, this is fine as these values will usually be fairly close together, or at least for my needs close enough. On the second y axis I have wind speed. Which is usually quite a bit lower. For this I'm able to use a secondary y axis. However, what if I wanted to add more data points to the secondary y axis, is this possible?

Thanks!

**Comment by Abhinandan-Kushwaha** [comment]
Hi @jantznick 👋

Thanks for asking this question. We can have multiple secondary lines using the `dataSet` prop.
The lines rendered using the `dataSet` prop are primary by default. To make some or all of them secondary, we need to add the property `isSecondary: true` inside the items of the dataSet array. 

In the example below, the orange line is primary while the blue and green lines are secondary.
This was done by adding the property `isSecondary: true` inside the respective items of the dataSet array.

<img width="378" alt="Screenshot 2024-06-18 at 1 58 18 AM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/12948550-123b-455c-8eeb-b01556cc651a">
