### ISSUE TITLE
Using DataSet Line Chart, sometimes  the color of the line  is not drawn or unseen

### ISSUE THREAD

**Issue by vorn-dev-ni** [Abhinandan-Kushwaha/react-native-gifted-charts#665]
![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/161212067/febec92b-5e2e-47b4-a237-e8eebe0d6bd0)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @vorn-dev-ni 
You need to reload once.
Can you confirm if the issue persists even after reloading?

**Comment by vorn-dev-ni** [comment]
Yes i did reload and stuff, sometimes its appear, other time didnt

**Comment by vorn-dev-ni** [comment]
problem only occur for dataSet, already setState and debug the log  the data lines were added but sometimes these lines color wont appear

**Comment by Abhinandan-Kushwaha** [comment]
Hi @vorn-dev-ni 
Did you find a fix?

**Comment by vorn-dev-ni** [comment]
@Abhinandan-Kushwaha

**Comment by Abhinandan-Kushwaha** [comment]
Strange!!
It's a very hacky solution. I will try to find a straightforward fix.
Thanks for bringing it out.

**Comment by Puguix** [comment]
Hey! I have a similar a issue: I have attendances to display for different groups during a certain period so I want a LineChart with multiple lines (one for each group). I am using dataSet as I may have more than 5 groups. The thing is, the Y axis is fitted for the values of the **first** dataset. So let's say group 2 has more attendances than group 1, its line may not show up as the Y axis may stop lower than the attendances values of group 2...
Also, is there a way to display some kind of legend in either LineChart or BarChart?
Thanks

**Comment by Abhinandan-Kushwaha** [comment]
@Puguix You can use the prop `maxValue` to set the max value to a higher value on the Y-axis.

**Comment by aik117** [comment]
@Abhinandan-Kushwaha still facing this issue. Had to use both data and dataSet props to show lines properly. If only dataSet props is used the lines are disappearing.
