### ISSUE TITLE
When using LineChart with specifying both dataSet and pointerConfig, "Cannot read property 'value' of undefined" error occurs

### ISSUE THREAD

**Issue by wotsushi** [Abhinandan-Kushwaha/react-native-gifted-charts#673]
### Package Versions

- react-native-gifted-charts: "1.4.11"
- react-native: "0.73.6"
- react: "18.2.0"

### Target OS

- iOS
- Android

## Steps to Reproduce

Tap the 3rd item on the following `Example` component.

```tsx
function Example() {
	const data = (ys: number[]) => ys.map((y) => ({ value: y }));
	const dataSet = [
		{
			data: data([1, 1, 1]),
		},
		{
			data: data([2, 2, 2]),
		},
		{
			data: data([3, 3, 3]),
		},
		{
			data: data([4, 4, 4]),
		},
		{
			data: data([5, 5, 5]),
		},
		{
			// Only 2 data points
			data: data([6, 6]),
		},
	];
	return <LineChart dataSet={dataSet} pointerConfig={{}} />;
}
```

## Expected Result

5 pointers(y = 1, 2, 3, 4, 5) are shown.

## Actual Result

`Cannot read property 'value' of undefined` error occurs at the following code.

https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/src/LineChart/index.tsx#L1524

**Comment by Abhinandan-Kushwaha** [comment]
Hi @wotsushi 👋
Thanks for reporting this issue and also suggesting its fix. It has been fixed from version `1.4.16` onwards.
