### ISSUE TITLE
Programmatically trigger the `onPress` event on BarChart

### ISSUE THREAD

**Issue by VitorValandro** [Abhinandan-Kushwaha/react-native-gifted-charts#675]
Hi there!

I am trying to achieve a similar behavior to the one described in [this issue](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/633). I have a `BarChart` and I want the user to be able move the finger on top of the bars and change the current selected bar with the gestures.

I managed to get it work partly by wrapping the chart in a `<Pressable />` container and having an external state to keep track of the current selected bar index, then I can do a calculation to highlight the bar index that is closer to the point the user touched. It works fine, but since it's an external state the bar is not actually selected from the gifted-charts point of view, meaning that the tooltip is not rendered.

I searched the docs and could not find an API I can use to programmatically select a bar by passing its index without the user having to actually press the bar and therefore trigger the `onPress` function. Also, if there is a way for the `renderTooltip` to be applied to all bars I would be able to conditionally render the tooltip using my external state, however it seems that this function is only applied to the current selected bar, which leads us to the start of the issue.

Has anyone done something related to selecting a bar without having to actually press on it? Is there any way this could work?

Here is a code that gives the idea of the current state I have:

```
const MyStyledBarChart = () => {
  const [pressedBar, setPressedBar] = useState < number | null > (null);

  const handleTouchOnChartArea = (event: GestureResponderEvent) => {
    if (!data) return;
    const x = event.nativeEvent.locationX;
    const barIndex = Math.floor(x / (chartWidth / data.length));
    setPressedBar(barIndex);
  };

  return (
    <Pressable
      onPress={handlePressOnChartArea}
      onTouchMove={handleTouchOnChartArea}
      onLayout={(event) => {
        setViewWidth(event.nativeEvent.layout.width);
      }}
      ref={wrapperRef}
    >
      <BarChart
        {...chartProps}
        barInnerComponent={barInnerComponentRenderer}
        barWidth={barWidth}
        data={ChartsHelpers.getData(data, disable)}
        onPress={(_, index: number) => {
          handlePressBar(index);
        }}
        renderTooltip={(_, index: number) => {
          return (
              <ChartTooltip
                item={data[index]}
              />
          );
        }}
        width={chartWidth}
      />
    </Pressable>
  );
};
```

**Comment by Abhinandan-Kushwaha** [comment]
Hi @VitorValandro 👋
Thanks for requesting this feature.

It is now available from version `1.4.14` onwards! 🎉
Added the prop `focusedBarIndex` to Bar charts.

So, you can focus any bar from outside using the `focusedBarIndex` as a state variable and passing it as a prop to the `<BarChart>` component. Later you can update the value of `focusedBarIndex` by updating the state value.

See https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/680
Please use the latest version of the library.
