### ISSUE TITLE
 yaxisLabel problem with negative values

### ISSUE THREAD

**Issue by dogankablan** [Abhinandan-Kushwaha/react-native-gifted-charts#676]
Hello, when the range between positive and negative values increases, distortions occur on the y-axis label. I have tried a lot but couldn't find any solution. I think a solution needs to be found for this problem.
Although the value is -90, the chart ends at -84.

My Code : 

<BarChart
        height={160}
        activeOpacity={0.9}
        focusBarOnPress={true}
        data={[
          { value: 50, label: 'AAA' },
          { value: -34, label: 'AAA' },
          { value: 200, label: 'AAA' },
          { value: -90, label: 'AAA' },
        ]}
        adjustToWidth={true}
        yAxisThickness={0}
        yAxisLabelPrefix="%"
        yAxisTextStyle={styles.yAxisText}
        xAxisLabelTextStyle={styles.xAxisText}
        dashGap={0}
        rulesThickness={1}
        barBorderTopLeftRadius={4}
        barBorderTopRightRadius={4}
        disableScroll
        autoShiftLabels
      />
      

<img width="363" alt="Screenshot 2024-06-26 at 10 52 39" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/91274638/86bb5ceb-df25-464d-9a79-5313a713f8f4">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @dogankablan 👋
Thanks for reporting this issue. It has been fixed in versions `1.4.14` and later.
Please use the latest version of the library.
