### ISSUE TITLE
Customization of the Y label text in LineChart

### ISSUE THREAD

**Issue by sareyMediaLabIng** [Abhinandan-Kushwaha/react-native-gifted-charts#679]
The yAxisLabelText prop in lineDataItem seems not to do anything.

Also the yAxisLabelTexts array does not work properly, it only shows Nan.

Is there another way to customize the y axis labels?

Could it be possible to have the same approach of the x label using a customLabelComponent for the y label texts?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sareyMediaLabIng 👋
This has been fixed from version `1.4.13` onwards 🎉

Please use the latest version of the library.
