### ISSUE TITLE
A way to set focused point via props

### ISSUE THREAD

**Issue by vilnytskyi** [Abhinandan-Kushwaha/react-native-gifted-charts#680]
Is there any way to control focused point via props? If not, could you please add `focusedDataPointIndex` prop for that? And then `onFocus` callback could be adjusted to get changed value out of chart, like:
```jsx
const [focusedPointIndex, setFocusedPointIndex] = useState(2)
...
<LineChart data={...} focusedDataPointIndex={focusedPointIndex} onFocus={setFocusedPointIndex} />
```

**Comment by Abhinandan-Kushwaha** [comment]
Hi @vilnytskyi 
Thanks for requesting this feature.

It is now available from version `1.4.13` onwards! 🎉
Added the prop `focusedDataPointIndex` to Line/Area charts.
