### ISSUE TITLE
Make endSpacing behave like initialSpacing

### ISSUE THREAD

**Issue by vilnytskyi** [Abhinandan-Kushwaha/react-native-gifted-charts#681]
The first screenshot is what I've managed to achieve so far after migrating from `victory-native@34` and the second one is what I actually need in order to be able to clearly see the last focused point and X axis label without cropping. The `initialSpacing` does the job perfectly for the left Y axis, but `endSpacing` seems to behave different: although it adds extra space between axis and chart content, but that space is just blank, so chart can't be rendered over it. Also, it seems like configuring padding for rules is not possible unfortunately (I can achieve similar rules by specifying `ruleLength` but that only does the job for right side, I'd need something like `ruleOffset` to shift it by 20 and shorten it by 40, to achieve required result e.g.)

<img width="396" alt="Screenshot 2024-06-30 at 01 57 15" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/12172171/62bc0d8e-b462-4d61-a56c-aee4c8a9cbf0">

<img width="441" alt="Screenshot 2024-06-30 at 01 50 36" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/12172171/68f4f0d6-4984-4213-8687-68569494e7a4">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @vilnytskyi 👋
Thanks for reporting this issue. It is fixed in versions 1.4.13 onwards. 🎉

Now we are also adding the `dataPointsRadius` to the width of the chart, so the data point will not be cropped.
Please use the latest version of the library.
