### ISSUE TITLE
yaxisLabel spacing with negative values

### ISSUE THREAD

**Issue by dogankablan** [Abhinandan-Kushwaha/react-native-gifted-charts#685]
Hello, at point Y, as the values increase, degradation occurs after a certain threshold.

MyData=[
          { label: 'AAA', value: 30 },
          { label: 'BBB', value: 20 },
          { label: 'CCC', value: 10 },
          { label: 'DDD', value: -90 },
        ];
        
Screenshot 
<img width="274" alt="Screenshot 2024-07-01 at 14 59 13" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/91274638/0e1c68b9-8b94-47ff-8345-04618ed24777">
        
        
 As seen in the screenshot, the values start to degrade at a certain point.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @dogankablan 👋
Thanks for pointing out this issue. It has now been fixed from version `1.4.15` onwards. 🎉

Additionally, We can now use the props-

1. `negativeStepValue`
2. `negativeStepHeight`
to independently control the value and height steps/sections in the Y axis for negative values.

Please use the latest version of the library.
