### ISSUE TITLE
Independent Value Ranges for Positive and Negative Regions to Prevent Distortions

### ISSUE THREAD

**Issue by dogankablan** [Abhinandan-Kushwaha/react-native-gifted-charts#686]
Hello, I believe the value ranges in the positive and negative regions of the chart should be independent of each other; otherwise, distortions occur. To explain this with a few examples:

For example, in this data, the values increase by 8, 8 and decrease by 8, 8. However, I want the values in the negative part of the chart to decrease by a different amount.

So, I want the chart to have 5 sections in the positive area and 2 sections in the negative area. I set the noOfSections prop to 5 and the noOfSectionsBelowXAxis prop to 2, but this causes my chart to look distorted.

For this reason, I believe the interval values in the positive and negative areas should be independent of each other.

My example : 

 <BarChart
        height={160}
        activeOpacity={0.9}
        focusBarOnPress={true}
        data={[
          { label: 'AAA', value: 30 },
          { label: 'BBB', value: 20 },
          { label: 'CCC', value: 10 },
          { label: 'DDD', value: -90 },
        ]}
        adjustToWidth={true}
        noOfSections={5}
        noOfSectionsBelowXAxis={2}
        autoShiftLabels
      />
      
      
      Screenshot 
<img width="296" alt="Screenshot 2024-07-01 at 15 31 26" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/91274638/1c5bdb36-fdad-4275-bd53-eae2707ba49a">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @dogankablan 👋
Thanks for requesting this feature. This is now supported from version `1.4.15` onwards 🎉

We can now use the props-
1. `negativeStepValue`
2. `negativeStepHeight`
to independently control the value and height steps/sections in the Y axis for negative values.

Please use the latest version of the library.
