### ISSUE TITLE
Can bar chart combined with stacked chart?

### ISSUE THREAD

**Issue by GabiApc** [Abhinandan-Kushwaha/react-native-gifted-charts#690]
Hello, I want to make a more complex graph in which to display for each element a bar, or a stack , and next to another bar with a value in coins. I managed to make the chart below with BarChart. But how to add stack data?
![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/68150383/b4ccd7b9-8ddf-45a7-b9e6-b12adb0da779)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @GabiApc 
Can you please share the code you have written for the chart so far?

**Comment by GabiApc** [comment]
import React from 'react'
import { View, StyleSheet, Text } from 'react-native'
import { BarChart } from 'react-native-gifted-charts'
import { Path, Pattern, Svg } from 'react-native-svg'

interface ChartData {
  value: number
  color?: string
  barBackgroundPattern?: () => JSX.Element
  topLabelComponent?: () => JSX.Element
}

interface CustomBarChartProps {
  data: ChartData[]
}

export const Coins = () => {
  return (
    <Pattern id="coins" patternUnits="userSpaceOnUse" x="0" y="0" width={19} height={5} viewBox="0 0 9 2">
      <Path
        d="M7.99036 0.165527H1.00982C0.836736 0.165527 0.696289 0.352343 0.696289 0.582946V1.1226C3.31982 1.33426 5.86081 1.34694 8.30377 1.1226V0.582946C8.30389 0.352343 8.16357 0.165527 7.99036 0.165527Z"
        fill="#D38700"
      />
      <Path
        d="M8.30377 1.1226C8.30377 1.36098 8.15875 1.55553 7.97957 1.55553H1.02061C0.841561 1.55553 0.696289 1.36115 0.696289 1.1226H8.30377Z"
        fill="#E8B436"
      />
    </Pattern>
  )
}

export const BigCoin = () => {
  return (
    <View style={{ justifyContent: 'center', bottom: -2 }}>
      <Svg id="bigCoin" x="0" y="0" width={16} height={16} viewBox="0 0 5 5">
        <Path
          d="M2.50006 4.56555C3.7608 4.56555 4.78283 3.54351 4.78283 2.28277C4.78283 1.02203 3.7608 0 2.50006 0C1.23932 0 0.217285 1.02203 0.217285 2.28277C0.217285 3.54351 1.23932 4.56555 2.50006 4.56555Z"
          fill="#FFC843"
        />
        <Path
          d="M2.49956 4.0577C3.4801 4.0577 4.27499 3.26282 4.27499 2.28227C4.27499 1.30173 3.4801 0.506836 2.49956 0.506836C1.51901 0.506836 0.724121 1.30173 0.724121 2.28227C0.724121 3.26282 1.51901 4.0577 2.49956 4.0577Z"
          fill="#D38700"
        />
        <Path
          d="M2.73994 2.09128H2.25993C2.22528 2.09128 2.19596 2.06196 2.19596 2.0273V1.65489C2.19596 1.62024 2.22528 1.59092 2.25993 1.59092H2.73994C2.7746 1.59092 2.80392 1.62024 2.80392 1.65489C2.80392 1.7531 2.88356 1.83281 2.98184 1.83281C3.08011 1.83281 3.15975 1.75317 3.15975 1.65489C3.15975 1.42339 2.97145 1.23509 2.73994 1.23509H2.67789V1.1134C2.67789 1.01512 2.59825 0.935483 2.49997 0.935483C2.40169 0.935483 2.32206 1.01512 2.32206 1.1134V1.23509H2.25993C2.02843 1.23509 1.84013 1.42339 1.84013 1.65489V2.0273C1.84013 2.2588 2.02843 2.44711 2.25993 2.44711H2.73994C2.7746 2.44711 2.80392 2.47643 2.80392 2.51109V2.88342C2.80392 2.91808 2.7746 2.9474 2.73994 2.9474H2.25993C2.22528 2.9474 2.19596 2.91808 2.19596 2.88342C2.19596 2.78514 2.11632 2.70551 2.01804 2.70551C1.91976 2.70551 1.84013 2.78514 1.84013 2.88342C1.84013 3.11492 2.02843 3.30323 2.25993 3.30323H2.32206V3.45139C2.32206 3.54967 2.40169 3.62931 2.49997 3.62931C2.59825 3.62931 2.67789 3.54967 2.67789 3.45139V3.30323H2.73994C2.97145 3.30323 3.15975 3.11492 3.15975 2.88342V2.51109C3.15975 2.27966 2.97145 2.09128 2.73994 2.09128Z"
          fill="#FFC843"
        />
      </Svg>
    </View>
  )
}
const CustomBarChart: React.FC<CustomBarChartProps> = ({ data }) => {
  return (
    <BarChart
      data={data}
      barWidth={18}
      spacing={20}
      patternId="coins"
      height={100}
      width={310}
      labelWidth={39}
      xAxisThickness={0}
      xAxisLabelsHeight={18}
      yAxisThickness={0}
      yAxisTextStyle={{ color: 'gray' }}
      xAxisTextNumberOfLines={1}
      noOfSections={3}
      maxValue={100}
      initialSpacing={18}
    />
  )
}

const styles = StyleSheet.create({})

export default CustomBarChart


Aici este componenta utilizată în alt fișier, împreună cu data. 

  <CustomBarChart data={SurfAndCons} />

 const SurfAndCons = [
    {
      value: 40,
      spacing: 5,
      labelComponent: () => (
        <Text
          style={{
            color: 'gray',
            fontSize: 13,
            fontFamily: 'PoppinsMedium',
            transform: [{ rotate: '-45deg' }],
            top: 7,
            left: 7,
          }}
        >
          T193
        </Text>
      ),
      frontColor: colors.yellow,
    },
    {
      value: 20,
      barBackgroundPattern: () => <Coins />,
      frontColor: 'rgba(23, 122, 213, 0)',
      topLabelComponent: () => <BigCoin />,
    },
    {
      value: 50,
      spacing: 5,
      frontColor: colors.bogdanRed,
      labelComponent: () => (
        <Text
          style={{
            color: 'gray',
            fontSize: 13,
            fontFamily: 'PoppinsMedium',
            transform: [{ rotate: '-45deg' }],
            top: 7,
            left: 7,
          }}
        >
          828
        </Text>
      ),
    },
    {
      value: 40,
      barBackgroundPattern: () => <Coins />,
      frontColor: 'rgba(23, 122, 213, 0)',
      topLabelComponent: () => <BigCoin />,
    },
    {
      value: 75,
      labelComponent: () => (
        <Text
          style={{
            color: 'gray',
            fontSize: 13,
            fontFamily: 'PoppinsMedium',
            transform: [{ rotate: '-45deg' }],
            top: 7,
            left: 7,
          }}
        >
          939
        </Text>
      ),
      spacing: 5,
      frontColor: '#177AD5',
    },
    {
      value: 25,
      barBackgroundPattern: () => <Coins />,
      frontColor: 'rgba(23, 122, 213, 0)',
      topLabelComponent: () => <BigCoin />,
    },
    {
      value: 30,
      labelComponent: () => (
        <Text
          style={{
            color: 'gray',
            fontSize: 13,
            fontFamily: 'PoppinsMedium',
            transform: [{ rotate: '-45deg' }],
            top: 7,
            left: 7,
          }}
        >
          NH950
        </Text>
      ),
      spacing: 5,
      frontColor: '#177AD5',
    },
    {
      value: 20,
      barBackgroundPattern: () => <Coins />,
      frontColor: 'rgba(23, 122, 213, 0)',
      topLabelComponent: () => <BigCoin />,
    },
    {
      value: 60,
      labelComponent: () => (
        <Text
          style={{
            color: 'gray',
            fontSize: 13,
            fontFamily: 'PoppinsMedium',
            transform: [{ rotate: '-45deg' }],
            top: 7,
            left: 7,
          }}
        >
          N123
        </Text>
      ),
      spacing: 5,
      frontColor: '#177AD5',
    },
    {
      value: 40,
      barBackgroundPattern: () => <Coins />,
      frontColor: 'rgba(23, 122, 213, 0)',
      topLabelComponent: () => <BigCoin />,
    },
    {
      value: 65,
      labelComponent: () => (
        <Text
          style={{
            color: 'gray',
            fontSize: 13,
            fontFamily: 'PoppinsMedium',
            transform: [{ rotate: '-45deg' }],
            top: 7,
            left: 7,
          }}
        >
          T250
        </Text>
      ),
      spacing: 2,
      frontColor: '#177AD5',
    },
    {
      value: 30,
      barBackgroundPattern: () => <Coins />,
      frontColor: 'rgba(23, 122, 213, 0)',
      topLabelComponent: () => <BigCoin />,
    },
  ]

**Comment by Abhinandan-Kushwaha** [comment]
Hi @GabiApc 👋

You can use the prop `stackData` instead of data if you want some of the bars to have stacks. For example, in your screenshot, the 6th Bar is a stack of 2 bars.

If you add the below code to your existing code-
```js
const MyPattern = () => {
  return (
    <Pattern id="myPattern" patternUnits="userSpaceOnUse" width="30" height="6">
      <Rect x={0} y={0} height={4} width={30} rx={2} ry={2} fill={'#D38600'} />
    </Pattern>
  );
};

const stackData: stackDataItem[] = SurfAndCons.map((item, index) => {
  const bar: stackDataItem = {
    stacks: [
      {
        value: item.value,
      },
    ],
    labelComponent: item.labelComponent,
  };
  if (index % 2 === 0) { // even index bars are normal bars
    bar.spacing = 5;
    bar.color = item.frontColor;
  } else { // odd index bars are coins (so we will use barBackgroundPattern)
    bar.barBackgroundPattern = MyPattern;
    bar.patternId = 'myPattern';
    bar.color = 'transparent';
    bar.topLabelComponent = () => (
      <Image
        style={{height: 20, width: 20}}
        source={{
          uri: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkky2PgMWu-BxNQsQHeaVqG0iiqmcSs57VyA&s',
        }}
      />
    );
  }

  if (index === 2) {
    // Adding an extra bar on this stack
    bar.stacks.push({value: 30, color: 'green'});
  }

  return bar;
});
```
And then replace `data` prop with `stackData`, then the output becomes-

<img width="365" alt="Screenshot 2024-07-02 at 6 54 17 PM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/5d2b90b4-1cb9-4897-ba9c-9ed10416fd07">

I hope it helps!🙂
