### ISSUE TITLE
Bar Chart, Sometimes the bar is invisible

### ISSUE THREAD

**Issue by imdadulhaque1** [Abhinandan-Kushwaha/react-native-gifted-charts#694]
I have faced an issue that sometimes the bar is invisible as mentioned in the attached screenshots,

![BarChart_YAxisBarNotVisible](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/45633928/d20d4c9a-94fb-433a-a651-eff2054fcf5a)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @imdadulhaque1 
Can you share the code

**Comment by imdadulhaque1** [comment]
Hello @Abhinandan-Kushwaha , please check below code,

` <BarChart
              maxValue={maxCalculations}
              height={width > 650 ? width / 1.9 : width / 1.5}
              cappedBars
              capColor={'#7660d8'}
              spacing={width > 650 ? 8 : 5}
              isAnimated
              barWidth={width > 650 ? width / 24 : width / 18}
              noOfSections={getNoOfSections}
              barBorderRadius={2}
              data={transformedData}
              yAxisThickness={1}
              xAxisThickness={1}
              yAxisTextStyle={styles.yAxisTextStyle}
              xAxisTextStyle={styles.xAxisTextStyle}
              showReferenceLine1
              referenceLine1Position={finalTGTPerHourValue}
              referenceLine1Config={{
                text: `${finalTGTPerHourValue}`,
                color: COLORS.darkPrimary,
                thickness: 2,
                width: width > 650 ? height - 300 : height - 200,
                type: 'dashed', // Can be 'dotted' or 'dashed'
              }}
              renderTooltip={(item, index) => {
                return (
                  <View style={styles.barTooltipStyle}>
                    <Text
                      style={[
                        styles.linetextStyle,
                        {color: COLORS.white, fontSize: width / 30},
                      ]}>
                      {item.value}
                    </Text>
                  </View>
                );
              }}
            />`

**Comment by Abhinandan-Kushwaha** [comment]
Hi @imdadulhaque1 
This is possible only if the `frontColor` is transparent in some objects of the data array. 
Please check the `frontColor` in the data.
