### ISSUE TITLE
Label positioning

### ISSUE THREAD

**Issue by verofy-simon-denny** [Abhinandan-Kushwaha/react-native-gifted-charts#70]
Hi,

Is it possible to add a bit more customisation for labels on the x axis? it's difficult to get them lined up.

You can currently add labelWidth. Are you able to add labelX so that you can adjust the left position of the View?

So something like this (from line 107 in RenderBars.tsx):

```
<View
        style={[
          {
            width:
              (item.labelWidth ||
                props.labelWidth ||
                item.barWidth ||
                props.barWidth ||
                30) ,
            left: props.labelX,
            position: 'absolute',
            backgroundColor:'orange',
            bottom: rotateLabel ? -40 : -25,
          },
          rotateLabel
            ? props.horizontal
              ? {transform: [{rotate: '330deg'}]}
              : {transform: [{rotate: '60deg'}]}
            : props.horizontal
            ? {transform: [{rotate: '-90deg'}]}
            : {},
        ]}>
        {item.labelComponent ? (
          item.labelComponent()
        ) : (
          <Text
            style={[labelTextStyle, {textAlign: 'center'}]}
            numberOfLines={1}>
            {label || ''}
          </Text>
        )}
      </View>
```

Thanks!

**Comment by verofy-simon-denny** [comment]
Hmmm, I'm not sure this works actually but if you come up with another solution, do let me know :)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @verofy-simon-denny 👋
We can give our own custom label component to the entries of the data array using the `labelComponent` property.

Since it is a custom component, you can give it any styling of your choice and adjust its position.

Here's an example-

```js
const barData = [
    {
      value: 15,
      labelComponent: () => {
        return (
          <View style={{backgroundColor: 'yellow', marginLeft: -20}}>
            <Text>Mon</Text>
          </View>
        );
      },
    },
    {value: 30, label: 'Tue'},
    {value: 26, label: 'Wed'},
    {value: 40, label: 'Thu'},
  ];

<BarChart data={barData} />
```

**Comment by ravis-farooq** [comment]
@Abhinandan-Kushwaha 
![Screenshot_1686721664](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/88315219/77f6eb60-dfe7-45a0-b92f-47db3cc9bcc6)

How can we shift the Bar chart to the right to accommodate the labels perfectly?

**Comment by hassamarifdev** [comment]
> @Abhinandan-Kushwaha ![Screenshot_1686721664](https://private-user-images.githubusercontent.com/88315219/245687857-77f6eb60-dfe7-45a0-b92f-47db3cc9bcc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTEyNTQsIm5iZiI6MTcyMTI5MDk1NCwicGF0aCI6Ii84ODMxNTIxOS8yNDU2ODc4NTctNzdmNmViNjAtZGZlNy00NWEwLWI5MmYtNDdkYjNjYzliY2M2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA4MjIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmNGRhZGJhZDUyMDhkOTIyMDM4OGM3ZmYzNTY5YjhlYzU3NjgxYWQxNzUxMjYxZmQ2YjZkNTM3ZjliZGE0NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iODSzBDAOOf5GkbJIQG0mTROHXEioLoeKA1Cg90zFgM)
> 
> How can we shift the Bar chart to the right to accommodate the labels perfectly?

Horizontal charts can be rendered from right to left using the rtl prop. By default its ltr while using horizontal prop

**Comment by Abhinandan-Kushwaha** [comment]
Hi @hassamarifdev 
You can add the `rtl` prop along with the horizontal` prop
