### ISSUE TITLE
Line chart with pointer 

### ISSUE THREAD

**Issue by ap9101** [Abhinandan-Kushwaha/react-native-gifted-charts#700]
Hello, great work awesome.
I need to know how can I achieve the same thing as your example 

https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/demos/scrollLine.gif

I need an example code for the same. didn't exist anywhere in your example code. kindly guide how to achieve the above thing.

Thank you!

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ap9101 
You can use the `pointerConfig` to achieve this. [See the docs](https://gifted-charts.web.app/areachart/#pointerConfig)

If you scroll down [in the docs here](https://gifted-charts.web.app/areachart/#pointerConfig), you will find the example shon below along with the code for the same.

<img width="936" alt="Screenshot 2024-07-08 at 4 07 37 PM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/1b82c486-b6cd-48f6-b6b1-89fe7be98f89">

**Comment by ap9101** [comment]
hey thanks for very quick response i will look into this.
