### ISSUE TITLE
Positioning Pie Chart Labels Outside the Border

### ISSUE THREAD

**Issue by kmauric** [Abhinandan-Kushwaha/react-native-gifted-charts#701]
I am currently using a Pie Chart and would like to position the labels outside the border of the chart. However, I am unsure how to achieve this. Could you please provide guidance or an example on how to position the labels outside the border of the Pie Chart?

I'm trying to achieve this layout:

<img width="327" alt="Screenshot 2024-07-08 at 9 31 54 AM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/12818657/8f218eee-43f8-461a-a1ec-92fbd7144e0b">

Thank you for your assistance!

**Comment by Abhinandan-Kushwaha** [comment]
@kmauric You can now add external labels in Pie and donut charts using the below props-
   1. `showExternalLabels` (boolean)
   2. `labelLineConfig` (object of LabelLineConfig type)
   3. `externalLabelComponent` (svg component for label, a callback function with 2 parameters- item and index)

See https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/763

**Comment by kmauric** [comment]
@Abhinandan-Kushwaha - awesome! Thank you!
