### ISSUE TITLE
Horizontal Bar Chart Top Label cut off

### ISSUE THREAD

**Issue by realPrimoh** [Abhinandan-Kushwaha/react-native-gifted-charts#706]
![Screenshot 2024-07-11 at 12 17 22 AM](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/24800437/22f4b964-7009-46a8-b569-d74161b943cf)

For my horizontal bar chart the top label is cut off. How do I fix this?

```
<BarChart
                    horizontal
                    disableScroll
                    barWidth={22}
                    hideAxesAndRules
                    roundedTop
                    showValuesAsTopLabel
                    frontColor="#177AD5"
                    data={[{"label": "M", "value": 0}, {"label": "T", "value": 2596,}, {"label": "W", "value": 10857}, {"label": "T", "value": 0}, {"label": "F", "value": 0}, {"label": "S", "value": 0}, {"label": "S", "value": 0}]}
                    showYAxisIndices={false}
                    showXAxisIndices={false}
                    yAxisLabelContainerStyle={{ opacity: 0 }}
                    yAxisThickness={0}
                    xAxisThickness={0}
                    color={'black'}
                />
```

**Comment by Abhinandan-Kushwaha** [comment]
Hi @realPrimoh 👋
You can use the `overflowTop` prop.
For example-
```js
overflowTop={10}
```

**Comment by realPrimoh** [comment]
Hi @Abhinandan-Kushwaha, unfortunately this is not working. `overflowTop` just seems to shift the entire graph instead of affecting the top labels. Example below.

With no `overflowTop` prop:
![Screenshot 2024-07-11 at 1 01 28 AM](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/24800437/986d0fd8-aba7-4d8b-8411-f07ef6604b9b)


With `overflowTop={35}`:

![Screenshot 2024-07-11 at 1 02 18 AM](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/24800437/bc8c167e-d865-45d5-af7a-d11d919d3636)
