### ISSUE TITLE
Invariant Violation: [3327,"RCTScrollContentView",1,{"onLayout":true,"flexDirection":"row","height":"<<NaN>>","width":321.3793103448276,"paddingLeft":20,"paddingBottom":"<<NaN>>","alignItems":"flex-end","collapsable":false}] is not usable as a native method argument

### ISSUE THREAD

**Issue by Kadir-flipcause** [Abhinandan-Kushwaha/react-native-gifted-charts#707]
Array for graph
[{"label": "11/07", "value": "0.00"}, {"label": "10/07", "value": "0.00"}, {"label": "09/07", "value": "0.00"}, {"label": "08/07", "value": "0.00"}, {"label": "07/07", "value": "0.00"}, {"label": "06/07", "value": "0.00"}, {"label": "05/07", "value": "0.00"}]

code
<BarChart
                horizontal
                barWidth={22}
                width={widthDP("66%")}
                height={Dimensions.get("window").height / 2.9}
                barBorderRadius={4}
                dashGap={0}
                frontColor="lightgray"
                data={[
                  { label: "11/07", value: 0.00 },
                  { label: "10/07", value:0.00 },
                  { label: "09/07", value: 0.00 },
                  { label: "08/07", value: 0.00 },
                  { label: "07/07", value: 0.00 },
                  { label: "06/07", value: 0.00 },
                  { label: "05/07", value: 0.00 },
                ]}
                disablePress
                verticalLinesColor={isDarkMode ? "#f2f2f2" : textPrimary}
                noOfSections={5}
                yAxisLabelPrefix="$"
                yAxisAtTop
                yAxisColor={"#CCC"}
                xAxisLength={0}
                yAxisTextNumberOfLines={2}
                maxValue={Number(Math.max(...datas))}
                yAxisTextStyle={{
                  color: isDarkMode ? whitePrimary : blackPrimary,
                  fontFamily: "NunitoSans-Regular",
                  fontSize: 12,
                  textAlign: "center",
                }}
                xAxisLabelTextStyle={{
                  color: isDarkMode ? whitePrimary : blackPrimary,
                  fontFamily: "NunitoSans-Regular",
                  fontSize: 12,
                  textAlign: "center",
                }}
                xAxisThickness={0}
                isAnimated
                xAxisLabelsVerticalShift={20}
              />

getting this error for others its working fine @Abhinandan-Kushwaha can you please help me on this
thanks

 this issue is on IOS on android its working fine

**Comment by khunshan85** [comment]
Facing the same problem

**Comment by yasindemircan** [comment]
check to maxValue={Number(Math.max(...datas))}  probably its 0 because of that  its doesnt work you need to give higher number like 10

**Comment by TimRoadley** [comment]
Same issue happening to me for cases where I have no data in the chart data array yet. 

For example this works

`<LineChart areaChart data={[{value:1}]} />`

However this 

`<LineChart areaChart data={[]} />`

throws error:

 [[4,4,4,4,4,4],[19,8,19,19,19,2],[[32697,[],[],[],[],[1]],[32703,"RCTView",{"width":59}],[32795,"RCTRawText",11,{"text":"Something went wrong"}]],76413]
This error is located at:
    in RCTText (created by Text)
    in Text (created by ErrorBoundary)
    in RCTView (created by View)
    ... etc etc etc
    
    
I work around this by checking my chart data has SOME value higher than 0 in the array and it seems to work

**Comment by jvallar** [comment]
Default maxValue = 1
`maxValue={Math.max(data1[24].value || 1, data2[24].value || 1, data3[24].value || 1)}
              `

**Comment by marsakt** [comment]
Same issue, pls any idea how to fix it instead of modifying the data?
- I also need to use data with a "zero" value, unfortunately changing the value is not a usable workaround in my case

**Comment by marsakt** [comment]
sorry i didn't read the comments carefully, workaround is for chart property maxValue, it's possible to change it when all data values ​​are 0

**Comment by Abhinandan-Kushwaha** [comment]
Hi @jvallar @Kadir-flipcause @khunshan85 @yasindemircan @marsakt 👋
This has been fixed from versions `1.4.39` onwards. Now the library itself handles empty data arrays without having to pass `maxValue`.

Please use the latest version of the library.

**Comment by Kadir-flipcause** [comment]
> Hi @jvallar @Kadir-flipcause @khunshan85 @yasindemircan @marsakt 👋 This has been fixed from versions `1.4.39` onwards. Now the library itself handles empty data arrays without having to pass `maxValue`.
> 
> Please use the latest version of the library.

thanks @Abhinandan-Kushwaha
