### ISSUE TITLE
 ERROR  Invariant Violation: [4603,"RCTView",11,{"position":"absolute","left":236.65289256198346,"top":"<<NaN>>"}] is not usable as a native method argument 

### ISSUE THREAD

**Issue by Niteshgithub174** [Abhinandan-Kushwaha/react-native-gifted-charts#708]
ERROR  Invariant Violation: [4603,"RCTView",11,{"position":"absolute","left":236.65289256198346,"top":"<<NaN>>"}] is not usable as a native method argument  This error is located at:     in RCTView (created by View)     in View (created by BarAndLineChartsWrapper)     in RCTView (created by View)     in View (created by BarAndLineChartsWrapper)     in AndroidHorizontalScrollContentView (created by ScrollView)     in AndroidHorizontalScrollView (created by ScrollView)     in ScrollView (created by ScrollView)     in ScrollView (created by BarAndLineChartsWrapper)     in RCTView (created by View)     in View (created by BarAndLineChartsWrapper)     in BarAndLineChartsWrapper (created by LineChart)     in LineChart (created by MachineAvailability)     in RCTView (created by View)     in View (created by MachineAvailability)     in MachineAvailability (created by SiteOverview)     in RCTView (created by View)     in View (created by SiteOverview)     in RCTView (created by View)     in View (created by ScrollView)     in RCTScrollView (created by ScrollView)     in ScrollView (created by ScrollView)     in ScrollView (created by SiteOverview)     in SiteOverview (created by SceneView)     in StaticContainer     in EnsureSingleNavigator (created by SceneView)     in SceneView (created by SceneView)     in RCTView (created by View)     in View (created by DebugContainer)     in DebugContainer (created by MaybeNestedStack)     in MaybeNestedStack (created by SceneView)     in RCTView (created by View)     in View (created by SceneView)     in RNSScreen     in Unknown (created by InnerScreen)     in Suspender (created by Freeze)     in Suspense (created by Freeze)     in Freeze (created by DelayedFreeze)     in DelayedFreeze (created by InnerScreen)     in InnerScreen (created by Screen)     in Screen (created by SceneView)     in SceneView (created by NativeStackViewInner)     in Suspender (created by Freeze)     in Suspense (created by Freeze)     in Freeze (created by DelayedFreeze)     in DelayedFreeze (created by ScreenStack)     in RNSScreenStack (created by ScreenStack)     in ScreenStack (created by NativeStackViewInner)     in NativeStackViewInner (created by NativeStackView)     in RCTView (created by View)     in View (created by SafeAreaInsetsContext)     in SafeAreaProviderCompat (created by NativeStackView)     in NativeStackView (created by NativeStackNavigator)     in PreventRemoveProvider (created by NavigationContent)     in NavigationContent     in Unknown (created by NativeStackNavigator)     in NativeStackNavigator (created by HomeStack)     in HomeStack (created by SceneView)     in StaticContainer     in EnsureSingleNavigator (created by SceneView)     in SceneView (created by Drawer)     in RCTView (created by View)     in View (created by Screen)     in RCTView (created by View)     in View (created by Background)     in Background (created by Screen)     in Screen (created by Drawer)     in RNSScreen     in Unknown (created by InnerScreen)     in Suspender (created by Freeze)     in Suspense (created by Freeze)     in Freeze (created by DelayedFreeze)     in DelayedFreeze (created by InnerScreen)     in InnerScreen (created by Screen)     in Screen (created by MaybeScreen)     in MaybeScreen (created by Drawer)     in RNSScreenContainer (created by ScreenContainer)     in ScreenContainer (created by MaybeScreenContainer)     in MaybeScreenContainer (created by Drawer)     in RCTView (created by View)     in View (created by Drawer)     in RCTView (created by View)     in View (created by AnimatedComponent(View))     in AnimatedComponent(View)     in Unknown (created by Drawer)     in RCTView (created by View)     in View (created by AnimatedComponent(View))     in AnimatedComponent(View)     in Unknown (created by PanGestureHandler)     in PanGestureHandler (created by Drawer)     in Drawer (created by DrawerViewBase)     in DrawerViewBase (created by DrawerView)     in RNGestureHandlerRootView (created by GestureHandlerRootView)     in GestureHandlerRootView (created by DrawerView)     in RCTView (created by View)     in View (created by SafeAreaInsetsContext)     in SafeAreaProviderCompat (created by DrawerView)     in DrawerView (created by DrawerNavigator)     in PreventRemoveProvider (created by NavigationContent)     in NavigationContent     in Unknown (created by DrawerNavigator)     in DrawerNavigator (created by DrawerStack)     in DrawerStack (created by SceneView)     in StaticContainer     in EnsureSingleNavigator (created by SceneView)     in SceneView (created by SceneView)     in RCTView (created by View)     in View (created by DebugContainer)     in DebugContainer (created by MaybeNestedStack)     in MaybeNestedStack (created by SceneView)     in RCTView (created by View)     in View (created by SceneView)     in RNSScreen     in Unknown (created by InnerScreen)     in Suspender (created by Freeze)     in Suspense (created by Freeze)     in Freeze (created by DelayedFreeze)     in DelayedFreeze (created by InnerScreen)     in InnerScreen (created by Screen)     in Screen (created by SceneView)     in SceneView (created by NativeStackViewInner)     in Suspender (created by Freeze)     in Suspense (created by Freeze)     in Freeze (created by DelayedFreeze)     in DelayedFreeze (created by ScreenStack)     in RNSScreenStack (created by ScreenStack)     in ScreenStack (created by NativeStackViewInner)     in NativeStackViewInner (created by NativeStackView)     in RNCSafeAreaProvider (created by SafeAreaProvider)     in SafeAreaProvider (created by SafeAreaInsetsContext)     in SafeAreaProviderCompat (created by NativeStackView)     in NativeStackView (created by NativeStackNavigator)     in PreventRemoveProvider (created by NavigationContent)     in NavigationContent     in Unknown (created by NativeStackNavigator)     in NativeStackNavigator (created by AppNavigator)     in EnsureSingleNavigator     in BaseNavigationContainer     in ThemeProvider     in NavigationContainerInner (created by AppNavigator)     in AppNavigator (created by App)     in RCTView (created by View)     in View (created by LayoutProvider)     in LayoutProvider (created by Providers)     in CommonMastersProvider (created by Providers)     in TaskManagementProvider (created by Providers)     in LogBookProvider (created by Providers)     in PodProvider (created by Providers)     in AuthProvider (created by Providers)     in Providers (created by App)     in RCTView (created by View)     in View (created by App)     in App     in RCTView (created by View)     in View (created by AppContainer)     in RCTView (created by View)     in View (created by AppContainer)     in AppContainer     in FleetManager(RootComponent), js engine: hermes

<LineChart
            dataSet={chartData}
            height={250}
            width={screenWidth / 1.32}
            adjustToWidth
            endSpacing={10}
            yAxisTextStyle={{ color: colors.black }}
            xAxisIndicesHeight={5}
            xAxisIndicesWidth={1}
            color="#00ff83"
            thickness={2}
            startFillColor="rgba(20,105,81,0.3)"
            endFillColor="rgba(20,85,81,0.01)"
            startOpacity={0.9}
            endOpacity={0.2}
            scrollToEnd
            focusEnabled
            showStripOnFocus
            pointerConfig={{
              pointerStripUptoDataPoint: true,
              pointerStripColor: 'lightgray',
              pointerStripWidth: 2,
              strokeDashArray: [2, 5],
              pointerColor: 'lightgray',
              radius: 4,
              pointerLabelWidth: 100,
              pointerLabelHeight: 120,
              pointerLabelComponent: pointerLabelComponent
            }}
          />
          
          Getting this error when using pointer config 
          Please resolve @Abhinandan-Kushwaha

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Niteshgithub174 
Can you share the value of `chartData` that you have passed as dataSet.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Niteshgithub174 👋
Thanks for reporting this issue. It has been fixed in versions `1.4.17` onwards. 🎉

Please use the latest version of the library.
