### ISSUE TITLE
Negative section is showing below x axis

### ISSUE THREAD

**Issue by cuongnv-dev** [Abhinandan-Kushwaha/react-native-gifted-charts#710]
Could someone please advise on which properties (props) should be added to address this issue?
- Actual result:
![Simulator Screenshot - iPhone 15 Pro - 2024-07-12 at 19 53 28](https://github.com/user-attachments/assets/f2b71b37-0b63-4fb0-a2ed-97b957c7a1a0)
- Expected result:
<img width="1204" alt="Screenshot 2024-07-12 at 19 57 04" src="https://github.com/user-attachments/assets/4e68d767-b52a-47f1-99d8-88135b2b0abf">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @cuongnv-dev 
The library displays negative values below the X-axis.

But you can make the negative values appear above the X-axis by carefully adding some constant to each data item and then using the `yAxisLabelTexts` prop.

Here's an example-

Let's say the data values are 5,8,6,0,4,-1 
I directly render the chart using the simple code below-
```js
const data = [
  {value:5},
  {value:8},
  {value:6},
  {value:0},
  {value:4},
  {value:-1},
]

return (
  <LineChart
    data={data}
    noOfSections={4}
  />
)
```

The output of the above code is-

<img width="336" alt="Screenshot 2024-07-13 at 12 32 12 AM" src="https://github.com/user-attachments/assets/896a0cc5-cad1-4246-aed8-751f5ba86587">

Now, I want the 0 on the Y-axis to become -10. So I add 10 to each data item. Now the code becomes-
```js
const data = [
  {value: 5},
  {value: 8},
  {value: 6},
  {value: 0},
  {value: 4},
  {value: -1},
];

return (
  <LineChart
    data={data.map(item => ({...item, value: item.value + 10}))}
    noOfSections={4}
  />
);
```
And the output will be-
<img width="338" alt="Screenshot 2024-07-13 at 12 35 32 AM" src="https://github.com/user-attachments/assets/00df19a0-6e2c-42b6-a509-8075bf1aac86">

Finally, I change the values on the Y axis, using-
```js
yAxisLabelTexts={['-10','-5','0','5','10']}
```
And the output now becomes-

<img width="330" alt="Screenshot 2024-07-13 at 12 36 49 AM" src="https://github.com/user-attachments/assets/2a42ea52-503f-4f72-9e47-8ed4b1670018">

**Comment by cuongnv-dev** [comment]
I am very grateful for your help. I was really surprised that my question seemed to be answered immediately. My problem has been solved. Thank you for helping me understand the library props better @Abhinandan-Kushwaha

**Comment by dumihi313** [comment]
Thank you for your solution @Abhinandan-Kushwaha, but I am very looking for the ability of lib could do that for us. It gonna be great
