### ISSUE TITLE
Line chart now showing correct data

### ISSUE THREAD

**Issue by cuongnv-dev** [Abhinandan-Kushwaha/react-native-gifted-charts#711]
Here is my data:
`[{"label": "SEP'24", "value": 2.5}, {"label": "OCT'24", "value": 5.5}, {"label": "NOV'24", "value": 7.5}, {"label": "DEC'24", "value": 10.5}]`

yAxisLabelTexts =` ["0", "2.5", "5", "7.5", "10", "12.5"]`

But the result showing not correct data
<img width="526" alt="Screenshot 2024-07-15 at 12 41 17" src="https://github.com/user-attachments/assets/da19230f-11e5-4824-809a-3e43e6f33eca">

Hope to get someone help. Thanks guys

**Comment by Abhinandan-Kushwaha** [comment]
Hi @cuongnv-dev 
You need to remove the `yAxisLabelTexts` prop and use the following props instead -

1. showFractionalValues
2. maxValue
3. noOfSections
4. roundToDigits
