### ISSUE TITLE
LineChart does not recognize sectionColors parameter

### ISSUE THREAD

**Issue by ilyaserenyilmaz** [Abhinandan-Kushwaha/react-native-gifted-charts#715]
Is there any example of where sectionColors prop is used with LineChart? It seems that in documents with release of 1.4.15, the sectionColors parameter both added to the BarChart and LineChart however while coding LineChart component does not recognize this parameter. When I look through the code, I saw that sectionColors was not added to the LineChartPropsType. Is there any other way to use sectionColors with LineCharts?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ilyaserenyilmaz 👋
Thanks for reporting this issue. It has been fixed in versions `1.4.17` onwards. 🎉

Please use the latest version of the library.
