### ISSUE TITLE
CurveType cannot be used as a value because it was exported using export type

### ISSUE THREAD

**Issue by 1mike12** [Abhinandan-Kushwaha/react-native-gifted-charts#719]
It seems like we can't import the actual enum CurveType since it is being erronesouly exported as a type, which causes a typescript error.

**Comment by 1mike12** [comment]
in fact, it seems like however gifted-charts-core index.ts is generated is wrongly putting type in front of all enums

```ts
export {
  type RuleType,
  type RuleTypes,
  type RulesConfig,
  CurveType, <---
  EdgePosition, <---
  ```

**Comment by 1mike12** [comment]
ah i didn't realize this is a totally different project. 

https://github.com/Abhinandan-Kushwaha/gifted-charts-core/blob/fb8daa761a8428b1b01a3b18566f63ff9150b012/src/index.ts#L131

**Comment by 1mike12** [comment]
https://github.com/Abhinandan-Kushwaha/gifted-charts-core/pull/24

**Comment by Abhinandan-Kushwaha** [comment]
Thanks for the PR @1mike12 
I've merged it. Will release a new version with this change soon.
