### ISSUE TITLE
How to see your release changes by version ?

### ISSUE THREAD

**Issue by dumihi313** [Abhinandan-Kushwaha/react-native-gifted-charts#724]

**Comment by Abhinandan-Kushwaha** [comment]
Hi @dumihi313 👋
The Github and npm readme has the [Release notes 🎉](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/release-notes/release-notes.md) where you can see the release changes by version.

<img width="931" alt="Screenshot 2024-07-22 at 8 05 32 PM" src="https://github.com/user-attachments/assets/64bf3e96-d8e7-4c45-a1b0-02db2c908ebb">
