### ISSUE TITLE
Bar Chart Focus

### ISSUE THREAD

**Issue by Osamasomy** [Abhinandan-Kushwaha/react-native-gifted-charts#729]
Hello,

### First, thank you for creating such an amazing library! I am currently facing a couple of issues:

**1: Bar Focus Issue:**

- When I click on a bar chart, the focus is removed, or if I click on the focused bar, the same behavior occurs.
- The focusBarOnPress={true} property only shows the focus bar when set to true, otherwise, it does not show.
- I would like to be able to press on a bar to set the active bar index and apply the respective style to the focused bar.

**2: Missing Configuration Options for Bar Chart:**

I noticed that the line chart has several parameters, such as focus point, but I am unable to set these options inside the bar chart configuration. Specifically, the lineConfig is missing options like:

### Inside the barChart
```
lineConfig: {
  focusedDataPointColor: "black", // missing
  focusedDataPointIndex: 2,       // missing
  dataPointsColor: "transparent"  // missing
}

```
Could you please assist with these issues? Thank you!

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Osamasomy 👋

For the **Bar Focus Issue**-
You can focus a bar by clicking on it, if you set `focusBarOnPress` to true.

Then you can configure the properties of the focused bar using the `focusedBarConfig` prop.

Here's an example-

```js
focusBarOnPress
focusedBarConfig={{
  color:'orange',
  width:40,
  borderRadius:10
}}
```
The output of the above code is-

https://github.com/user-attachments/assets/50e7ebc5-e425-4487-95b2-285e971f42dd

Besides the `focusBarOnPress`, you can also use the `onPress` prop to call your own function on pressing a bar.

For your second issue regarding **Missing Configuration Options**, I will add them in the next release.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Osamasomy 
I have added the following properties in the `lineConfig` prop for Bar charts -

```ts
focusEnabled?: boolean;
focusedDataPointColor?: ColorValue;
focusedDataPointRadius?: number;
focusedDataPointIndex?: number;
```
This is available from version `1.4.20` onwards.🎉

**Comment by Osamasomy** [comment]
Thank you for your quick response! One last question: if we click outside the bars, does the focus remain or is it removed?

On my end, when I press outside, the focus is removed. However, I would like the focus to remain until I click on another bar.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Osamasomy 
Can you share your code?
