### ISSUE TITLE
How to create 4 line graph 2 with primary and 2 with secondary data

### ISSUE THREAD

**Issue by sandeep-synclovis** [Abhinandan-Kushwaha/react-native-gifted-charts#740]
I want to display four lines on a line chart using react-native-gifted-chart. Specifically, I need to show two lines using primary data (data, data1) and two lines using secondary data(secondary data) because the y-axis value differs for the primary and secondary datasets. However, when I attempted this, I couldn't get the values from data2 to appear on the graph if I used secondary data. Please help Thanks

<img width="391" alt="Screenshot 2024-07-29 at 3 35 10 PM" src="https://github.com/user-attachments/assets/a33b9af1-91e4-4ca7-baf4-786fc9ddb632">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sandeep-synclovis 👋
You can use the `dataSet` prop instead of `data`.

In the dataSet array, add the property `isSecondary: true` to the two sets which you want to make secondary.
