### ISSUE TITLE
Tooltip Does Not Show on react-native-web

### ISSUE THREAD

**Issue by jeffpearsall** [Abhinandan-Kushwaha/react-native-gifted-charts#741]
Using version 1.4.22 I am able to see my tooltip on ios and android but when testing the react-gifted-charts in a react-native-web project the tooltips do not show when hovering over datapoints. I have tried a variety of config changes but have never successfully seen a tooltip on hover. Is there a specific prop to enable this?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @jeffpearsall 
For web I would suggest you use [react-gifted-charts](https://www.npmjs.com/package/react-gifted-charts)

Hover options are not available in this library but will be added soon.
