### ISSUE TITLE
Gradient package was not found

### ISSUE THREAD

**Issue by tahmidmozaffar** [Abhinandan-Kushwaha/react-native-gifted-charts#744]
Hi, I am trying to install the library in react-native cli app

I have these in my package.json
"react-native-gifted-charts": "1.4.23",
"gifted-charts-core": "^0.1.25",
"react-native-linear-gradient": "2.5.6",
"react-native-svg": "13.9.0",

But I see this error. 

![Screenshot_1722454634](https://github.com/user-attachments/assets/a42675ba-589b-4401-af0f-aecf94549913)

What may be the reason for this issue?

**Comment by Abhinandan-Kushwaha** [comment]
@tahmidmozaffar Try using the latest versions of `react-native-linear-gradient` and `react-native-svg`
