### ISSUE TITLE
Show dataPointLabelComponent in left/right side if trip, but it should be in visible zone of chart (cropped)

### ISSUE THREAD

**Issue by dumihi313** [Abhinandan-Kushwaha/react-native-gifted-charts#745]
Thank you for your wonderful library, it helps me a lot
I see the datappointLabel is in the middle of trip now, I want it to be on the left or right of the trip. 

![Simulator Screenshot - iPhone 14 Pro Max - 2024-08-01 at 09 19 54](https://github.com/user-attachments/assets/91b54e07-575d-46e7-823b-895384164f68)

I can use dataPointLabelShiftX to do that, but it cropped over the chart, and it does not fit in the visible chart

![Simulator Screenshot - iPhone 14 Pro Max - 2024-08-01 at 09 20 37](https://github.com/user-attachments/assets/f7eaaa56-a1d4-4b96-914f-0d5965575f30)
![Simulator Screenshot - iPhone 14 Pro Max - 2024-08-01 at 09 20 09](https://github.com/user-attachments/assets/6af470cd-f75c-42d1-a31a-2492e5c35c1e)

Do you have any way to make datapointLabel dynamically positioned way, it should not be cropped in the chart and in the left/right of trip?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @dumihi313 
You can dynamically position the datappointLabelComponent with the help of the third parameter in the callback function. The third parameter is the index of the current pointer or `pointerIndex`.

See https://stackoverflow.com/a/78814198/7533126

**Comment by ish107** [comment]
will this be applicable to focusedDataPointLabelComponent too?
