### ISSUE TITLE
Control the range (stepValue) of each section of the yAxis individually

### ISSUE THREAD

**Issue by ilyaserenyilmaz** [Abhinandan-Kushwaha/react-native-gifted-charts#746]
Is there a way to control the range of each section on the yAxis of a LineChart such that when separate values are given as range to each section individually they will expand or shrink according to given ranges? It seems that each section has the same range which is controlled by stepValue prop. Is it possible to give separate stepValues for each section in LineChart?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ilyaserenyilmaz 👋

This can be achieved by hiding some sections and the corresponding y-axis labels.

We will show, not all but just a few rules and the corresponding y-axis labels. For this, we will use the props-
1. `yAxisLabelTexts`
2. `rulesConfigArray`

Here's an example-

```js
import React from 'react';
import {LineChart} from 'react-native-gifted-charts';

const App = () => {
  const data = [
    {value: 10},
    {value: 12},
    {value: 28},
    {value: 16},
    {value: 20},
    {value: 32},
  ];
  const visible = {rulesColor: 'gray'};
  const invisible = {rulesColor: 'transparent'};
  return (
    <LineChart
      data={data}
      yAxisLabelTexts={[
        '0',
        '4',
        '8',
        ' ',
        ' ',
        ' ',
        '20',
        ' ',
        '32',
        ' ',
        '40',
      ]}
      rulesConfigArray={[
        visible,
        visible,
        visible,
        invisible,
        invisible,
        invisible,
        visible,
        invisible,
        visible,
        invisible,
        visible,
      ]}
    />
  );
};

export default App;
```

The output of the above code is-

<img width="337" alt="Screenshot 2024-08-01 at 9 50 43 PM" src="https://github.com/user-attachments/assets/4da5c718-8b89-4365-8bc3-6025f336fda3">

Notice that we have sections of varying length now, but each section is a multiple of `stepValue`, in this case multiple of `4`.

We may want to have some sections which are not multiples of `stepValue`. For this, we can use referenceLines.
Let's say, in the above chart we want to show one more section at `15`.
To achieve this, I can show a reference line at 15 using the below code-
```js
showReferenceLine1
referenceLine1Position={15}
```
 Now the output is-
<img width="356" alt="Screenshot 2024-08-01 at 9 55 22 PM" src="https://github.com/user-attachments/assets/9f8403bc-4fa7-4fd9-891b-cafcedde7efa">

This has 2 problems-
1. Reference line is longer than other rules
2. It does not have the label at y-axis

To fix these 2 issues, we can use the `referenceLine1Config` prop as follows-
```js
referenceLine1Config={{width: 310, labelText: '15'}}
```
Now the output is-

<img width="331" alt="Screenshot 2024-08-01 at 9 57 21 PM" src="https://github.com/user-attachments/assets/a62ab3ac-cb22-4ab3-bb9f-dfb88b5bab8d">

The label 15 is not at the right place, so we move it to the right place using the `labelTextStyle` property inside the `referenceLine1Config`.
So, the final code will be-
```js
import React from 'react';
import {LineChart} from 'react-native-gifted-charts';

const App = () => {
  const data = [
    {value: 10},
    {value: 12},
    {value: 28},
    {value: 16},
    {value: 20},
    {value: 32},
  ];
  const visible = {rulesColor: 'gray'};
  const invisible = {rulesColor: 'transparent'};
  return (
    <LineChart
      data={data}
      yAxisLabelTexts={[
        '0',
        '4',
        '8',
        ' ',
        ' ',
        ' ',
        '20',
        ' ',
        '32',
        ' ',
        '40',
      ]}
      rulesConfigArray={[
        visible,
        visible,
        visible,
        invisible,
        invisible,
        invisible,
        visible,
        invisible,
        visible,
        invisible,
        visible,
      ]}
      showReferenceLine1
      referenceLine1Position={15}
      referenceLine1Config={{
        width: 310,
        labelText: '15',
        labelTextStyle: {marginLeft: -26, marginTop: -10},
      }}
    />
  );
};

export default App;
```
And the output is-
<img width="327" alt="Screenshot 2024-08-01 at 10 00 07 PM" src="https://github.com/user-attachments/assets/35229abb-c085-4c2b-8ac7-cfb42d82d16f">

**Comment by ilyaserenyilmaz** [comment]
Thanks a lot for a quick answer and brief explanation, I will try it 🙌.
