### ISSUE TITLE
[Crash]  TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by dumihi313** [Abhinandan-Kushwaha/react-native-gifted-charts#747]
![Simulator Screenshot - iPhone 14 Pro Max - 2024-08-02 at 12 13 37](https://github.com/user-attachments/assets/d19fb5b0-3e67-4bdd-9f36-cdeb52117b66)

    gifted-charts-core: ^0.1.25
    react-native-gifted-charts: "^1.4.23"

I faced with this crash, my dataset below
[{"data":[{"value":70.88,"label":"0","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 1)","dataPointLabelShiftX":75},{"value":70.88,"label":"1","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 1)","dataPointLabelShiftX":75},{"value":70.88,"label":"2","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 1)","dataPointLabelShiftX":75},{"value":70.88,"label":"3","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 1)","dataPointLabelShiftX":75},{"value":70.88,"label":"4","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 1)","dataPointLabelShiftX":75},{"value":null,"label":"5"},{"value":70.88,"label":"6","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 1)","dataPointLabelShiftX":75},{"value":70.88,"label":"7","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 1)","dataPointLabelShiftX":75},{"value":70.88,"label":"8","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 1)","dataPointLabelShiftX":75},{"value":70.88,"label":"9","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 1)","dataPointLabelShiftX":75},{"value":70.88,"label":"10","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 1)","dataPointLabelShiftX":75},{"value":70.88,"label":"11","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 1)","dataPointLabelShiftX":75},{"value":70.88,"label":"12","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 1)","dataPointLabelShiftX":75},{"value":32,"label":"13","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 1)","dataPointLabelShiftX":75},{"value":null,"label":"14"},{"value":null,"label":"15","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 1)"},{"value":null,"label":"16","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 1)"},{"value":70.88,"label":"17","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 1)","dataPointLabelShiftX":75},{"value":70.88,"label":"18","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 1)","dataPointLabelShiftX":75},{"value":70.88,"label":"19","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 1)","dataPointLabelShiftX":75},{"value":70.88,"label":"20","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 1)","dataPointLabelShiftX":75},{"value":70.88,"label":"21","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 1)","dataPointLabelShiftX":75},{"value":70.88,"label":"22","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 1)","dataPointLabelShiftX":75},{"value":70.88,"label":"23","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 1)","dataPointLabelShiftX":75},{"value":0,"label":"24"}],"color":"rgba(60, 121, 245, 1)","dataPointsColor":"rgba(60, 121, 245, 1)","startIndex":0,"endIndex":23},{"data":[{"value":69.25999999999999,"label":"0","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.6)"},{"value":69.25999999999999,"label":"1","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.6)"},{"value":69.25999999999999,"label":"2","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.6)"},{"value":65.8987988,"label":"3","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.6)"},{"value":69.25999999999999,"label":"4","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.6)"},{"value":null,"label":"5"},{"value":50.629999999999995,"label":"6","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.6)"},{"value":null,"label":"7","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.6)"},{"value":69.25999999999999,"label":"8","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.6)"},{"value":66.6491,"label":"9","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.6)"},{"value":69.25999999999999,"label":"10","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.6)"},{"value":69.25999999999999,"label":"11","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.6)"},{"value":69.25999999999999,"label":"12","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.6)"},{"value":69.25999999999999,"label":"13","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.6)"},{"value":null,"label":"14"},{"value":69.25999999999999,"label":"15","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.6)"},{"value":null,"label":"16","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.6)"},{"value":69.25999999999999,"label":"17","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.6)"},{"value":69.25999999999999,"label":"18","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.6)"},{"value":69.25999999999999,"label":"19","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.6)"},{"value":69.25999999999999,"label":"20","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.6)"},{"value":69.25999999999999,"label":"21","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.6)"},{"value":69.25999999999999,"label":"22","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.6)"},{"value":69.25999999999999,"label":"23","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.6)"},{"value":null,"label":"24"}],"color":"rgba(60, 121, 245, 0.6)","dataPointsColor":"rgba(60, 121, 245, 0.6)","startIndex":0,"endIndex":23},{"data":[{"value":null,"label":"0","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.3)"},{"value":67.8182,"label":"1","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.3)"},{"value":67.8182,"label":"2","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.3)"},{"value":61.88,"label":"3","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.3)"},{"value":67.8182,"label":"4","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.3)"},{"value":null,"label":"5"},{"value":32,"label":"6","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.3)"},{"value":67.8182,"label":"7","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.3)"},{"value":67.8182,"label":"8","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.3)"},{"value":61.88,"label":"9","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.3)"},{"value":67.8182,"label":"10","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.3)"},{"value":null,"label":"11","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.3)"},{"value":67.8182,"label":"12","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.3)"},{"value":67.8182,"label":"13","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.3)"},{"value":null,"label":"14"},{"value":67.8182,"label":"15","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.3)"},{"value":null,"label":"16","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.3)"},{"value":67.8182,"label":"17","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.3)"},{"value":67.8182,"label":"18","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.3)"},{"value":67.8182,"label":"19","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.3)"},{"value":67.8182,"label":"20","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.3)"},{"value":67.8182,"label":"21","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.3)"},{"value":67.8182,"label":"22","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.3)"},{"value":67.8182,"label":"23","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(60, 121, 245, 0.3)"},{"value":null,"label":"24"}],"color":"rgba(60, 121, 245, 0.3)","dataPointsColor":"rgba(60, 121, 245, 0.3)","startIndex":1,"endIndex":23},{"data":[{"value":1,"label":"0","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 1)"},{"value":1,"label":"1","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 1)"},{"value":1,"label":"2","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 1)"},{"value":2.713,"label":"3","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 1)"},{"value":1,"label":"4","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 1)"},{"value":null,"label":"5"},{"value":1,"label":"6","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 1)"},{"value":1,"label":"7","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 1)"},{"value":1,"label":"8","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 1)"},{"value":2.713,"label":"9","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 1)"},{"value":1,"label":"10","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 1)"},{"value":1,"label":"11","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 1)"},{"value":1,"label":"12","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 1)"},{"value":null,"label":"13","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 1)"},{"value":null,"label":"14"},{"value":0,"label":"15","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 1)","dataPointLabelShiftX":75},{"value":0,"label":"16","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 1)","dataPointLabelShiftX":75},{"value":1,"label":"17","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 1)"},{"value":1,"label":"18","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 1)"},{"value":1,"label":"19","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 1)"},{"value":1,"label":"20","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 1)"},{"value":1,"label":"21","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 1)"},{"value":1,"label":"22","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 1)"},{"value":1,"label":"23","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 1)"},{"value":null,"label":"24"}],"isSecondary":true,"color":"rgba(3, 201, 136, 1)","dataPointsColor":"rgba(3, 201, 136, 1)","startIndex":0,"endIndex":23},{"data":[{"value":3.334,"label":"0","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.6)"},{"value":3.334,"label":"1","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.6)"},{"value":3.334,"label":"2","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.6)"},{"value":2.918,"label":"3","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.6)"},{"value":null,"label":"4","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.6)"},{"value":null,"label":"5"},{"value":3.334,"label":"6","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.6)"},{"value":3.334,"label":"7","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.6)"},{"value":3.334,"label":"8","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.6)"},{"value":3.022,"label":"9","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.6)"},{"value":3.334,"label":"10","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.6)"},{"value":3.334,"label":"11","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.6)"},{"value":null,"label":"12","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.6)"},{"value":3.334,"label":"13","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.6)"},{"value":null,"label":"14"},{"value":0,"label":"15","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.6)"},{"value":0,"label":"16","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.6)"},{"value":3.334,"label":"17","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.6)"},{"value":3.334,"label":"18","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.6)"},{"value":3.334,"label":"19","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.6)"},{"value":3.334,"label":"20","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.6)"},{"value":3.334,"label":"21","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.6)"},{"value":3.334,"label":"22","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.6)"},{"value":3.334,"label":"23","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.6)"},{"value":null,"label":"24"}],"isSecondary":true,"color":"rgba(3, 201, 136, 0.6)","dataPointsColor":"rgba(3, 201, 136, 0.6)","startIndex":0,"endIndex":23},{"data":[{"value":0.5,"label":"0","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.3)"},{"value":0.5,"label":"1","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.3)"},{"value":0.5,"label":"2","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.3)"},{"value":0.5,"label":"3","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.3)"},{"value":0.5,"label":"4","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.3)"},{"value":null,"label":"5"},{"value":0.5,"label":"6","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.3)"},{"value":0.5,"label":"7","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.3)"},{"value":0.5,"label":"8","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.3)"},{"value":0.5,"label":"9","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.3)"},{"value":0.5,"label":"10","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.3)"},{"value":0.5,"label":"11","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.3)"},{"value":0.5,"label":"12","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.3)"},{"value":0.5,"label":"13","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.3)"},{"value":null,"label":"14"},{"value":0,"label":"15","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.3)"},{"value":0,"label":"16","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.3)"},{"value":null,"label":"17","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.3)"},{"value":0.5,"label":"18","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.3)"},{"value":0.5,"label":"19","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.3)"},{"value":0.5,"label":"20","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.3)"},{"value":0.5,"label":"21","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.3)"},{"value":0.5,"label":"22","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.3)"},{"value":0.5,"label":"23","focusedDataPointRadius":4,"focusedDataPointColor":"rgba(3, 201, 136, 0.3)"},{"value":null,"label":"24"}],"isSecondary":true,"color":"rgba(3, 201, 136, 0.3)","dataPointsColor":"rgba(3, 201, 136, 0.3)","startIndex":0,"endIndex":23}]

**Comment by dumihi313** [comment]
Please help me review this fix PR https://github.com/Abhinandan-Kushwaha/gifted-charts-core/pull/37

**Comment by Abhinandan-Kushwaha** [comment]
I have merged your PR @dumihi313 and your changes are available from version `1.4.24` onwards.
Please use the latest version of the library.

**Comment by dumihi313** [comment]
Thank you so much
