### ISSUE TITLE
Datapoint in secondary lines are incorrect position in pointerConfig -> pointerLabelComponent  (2) 

### ISSUE THREAD

**Issue by dumihi313** [Abhinandan-Kushwaha/react-native-gifted-charts#749]
<img width="324" alt="image" src="https://github.com/user-attachments/assets/d6a060cd-7c9d-440e-a0be-cd074dba15c5">

I am using pointerLabelComponent inside pointerConfig
the position of data pointers of secondary lines are incorrect

**Comment by Abhinandan-Kushwaha** [comment]
Hi @dumihi313 👋
Thanks for reporting this issue. It has been fixed in version `1.4.24` 🎉
Please use the latest version of the library.

**Comment by dumihi313** [comment]
Thank you so much
