### ISSUE TITLE
hideDataPoints = true in dataSet is not applied for datapoint in pointerConfig

### ISSUE THREAD

**Issue by dumihi313** [Abhinandan-Kushwaha/react-native-gifted-charts#755]
It was amazing because you are always active and supportive
Thank you for your update a lot <3

https://github.com/user-attachments/assets/db4c1bf7-c05d-47f0-a3fe-7bb4cd31cf38

<img width="310" alt="image" src="https://github.com/user-attachments/assets/4f39861b-fb53-4246-86f7-4ca3ef54a461">

My issue is when I set some hideDataPoints in dataset follows this [implemetation](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/725#issuecomment-2251283186), it should apply hide datapoint in pointerConfig when I press to see, please see the recording video
`  pointerConfig={{

              pointerStripUptoDataPoint: false,
              pointerStripColor: 'lightgray',
              pointerStripWidth: 2,
              strokeDashArray: [2, 5],
              // pointerColor: 'lightgray',
              radius: 4,
              // pointerLabelWidth: 100,
              // pointerLabelHeight: 90,
              showPointerStrip: true,
              activatePointersOnLongPress: true,
              autoAdjustPointerLabelPosition: false,
              pointerColorsForDataSet: [
                theme.Colors.maxTempColor,
                theme.Colors.avgTempColor,
                theme.Colors.minTempColor,
                theme.Colors.maxVolColor,
                theme.Colors.avgVolColor,
                theme.Colors.minVolColor,
              ],
              //
              // pointerStripHeight: 120,

              // activatePointersOnLongPress: true,
              // autoAdjustPointerLabelPosition: false,
              // stripOverPointer: true,
              pointerVanishDelay: 1500,
              initialPointerAppearDelay: 5,
              activatePointersDelay: 600,
              // pointerEvents: 'auto',
              // pointerEvents: 'auto',
              //
              pointerLabelComponent: (items1, items2, index) => {
                console.log('🚀 ~ items1:', items1)
                console.log('🚀 ~ items2:', items2)
                console.log('🚀 ~ index:', index)
                return renderDataPointLabelComponent(
                  items1[0].value,
                  items1[1].value,
                  items1[2].value,
                  items2[0].value,
                  items2[1].value,
                  items2[2].value,
                )
              },`

**Comment by Abhinandan-Kushwaha** [comment]
Hi @dumihi313 
Thanks for reporting this issue. You need to set `hidePointers: true`  in those objects of the dataSet array for which you want the pointers to be hidden.

Also, we can now add the property `hidePointer` inside individual data items of any dataSet.
This is available from version `1.4.26` onwards. 🎉
Please use the latest version of the library.

**Comment by dumihi313** [comment]
` You need to set hidePointers: true in those objects of the dataSet array for which you want the pointers to be hidden.`
Thank you this is what I want
