### ISSUE TITLE
Unknown value in pointerLabelComponent inside pointerConfig

### ISSUE THREAD

**Issue by dumihi313** [Abhinandan-Kushwaha/react-native-gifted-charts#756]
https://github.com/user-attachments/assets/eb54c2e8-1bba-4a9e-bfe5-7fd8f92ab9f3

<img width="749" alt="Screenshot 2024-08-04 at 9 52 57 AM" src="https://github.com/user-attachments/assets/c69819cb-5ce5-469a-b2af-461af8f5ffbe">

I have only one data at the label 7
Some data value 82 logging in console that I don't know why while I press any datapoints, it shouldn't show or log at this vertical line

**Comment by Abhinandan-Kushwaha** [comment]
Can you please share the code and data @dumihi313

**Comment by dumihi313** [comment]
my dataSet
[
   {
      "data":[
         {
            "value":null,
            "label":"0"
         },
         {
            "value":null,
            "label":"1"
         },
         {
            "value":null,
            "label":"2"
         },
         {
            "value":null,
            "label":"3"
         },
         {
            "value":null,
            "label":"4"
         },
         {
            "value":null,
            "label":"5"
         },
         {
            "value":null,
            "label":"6"
         },
         {
            "value":66.9182,
            "label":"7",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)"
         },
         {
            "value":null,
            "label":"8"
         },
         {
            "value":null,
            "label":"9"
         },
         {
            "value":null,
            "label":"10"
         },
         {
            "value":null,
            "label":"11"
         },
         {
            "value":null,
            "label":"12"
         },
         {
            "value":null,
            "label":"13"
         },
         {
            "value":null,
            "label":"14"
         },
         {
            "value":null,
            "label":"15"
         },
         {
            "value":null,
            "label":"16"
         },
         {
            "value":null,
            "label":"17"
         },
         {
            "value":null,
            "label":"18"
         },
         {
            "value":null,
            "label":"19"
         },
         {
            "value":null,
            "label":"20"
         },
         {
            "value":null,
            "label":"21"
         },
         {
            "value":null,
            "label":"22"
         },
         {
            "value":null,
            "label":"23"
         },
         {
            "value":0,
            "label":"24"
         }
      ],
      "color":"rgba(60, 121, 245, 1)",
      "dataPointsColor":"rgba(60, 121, 245, 1)",
      "startIndex":7,
      "endIndex":7
   },
   {
      "data":[
         {
            "value":null,
            "label":"0"
         },
         {
            "value":null,
            "label":"1"
         },
         {
            "value":null,
            "label":"2"
         },
         {
            "value":null,
            "label":"3"
         },
         {
            "value":null,
            "label":"4"
         },
         {
            "value":null,
            "label":"5"
         },
         {
            "value":null,
            "label":"6"
         },
         {
            "value":48.2,
            "label":"7",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 0.6)"
         },
         {
            "value":null,
            "label":"8"
         },
         {
            "value":null,
            "label":"9"
         },
         {
            "value":null,
            "label":"10"
         },
         {
            "value":null,
            "label":"11"
         },
         {
            "value":null,
            "label":"12"
         },
         {
            "value":null,
            "label":"13"
         },
         {
            "value":null,
            "label":"14"
         },
         {
            "value":null,
            "label":"15"
         },
         {
            "value":null,
            "label":"16"
         },
         {
            "value":null,
            "label":"17"
         },
         {
            "value":null,
            "label":"18"
         },
         {
            "value":null,
            "label":"19"
         },
         {
            "value":null,
            "label":"20"
         },
         {
            "value":null,
            "label":"21"
         },
         {
            "value":null,
            "label":"22"
         },
         {
            "value":null,
            "label":"23"
         },
         {
            "value":null,
            "label":"24"
         }
      ],
      "color":"rgba(60, 121, 245, 0.6)",
      "dataPointsColor":"rgba(60, 121, 245, 0.6)",
      "startIndex":7,
      "endIndex":7
   },
   {
      "data":[
         {
            "value":null,
            "label":"0"
         },
         {
            "value":null,
            "label":"1"
         },
         {
            "value":null,
            "label":"2"
         },
         {
            "value":null,
            "label":"3"
         },
         {
            "value":null,
            "label":"4"
         },
         {
            "value":null,
            "label":"5"
         },
         {
            "value":null,
            "label":"6"
         },
         {
            "value":32,
            "label":"7",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 0.3)"
         },
         {
            "value":null,
            "label":"8"
         },
         {
            "value":null,
            "label":"9"
         },
         {
            "value":null,
            "label":"10"
         },
         {
            "value":null,
            "label":"11"
         },
         {
            "value":null,
            "label":"12"
         },
         {
            "value":null,
            "label":"13"
         },
         {
            "value":null,
            "label":"14"
         },
         {
            "value":null,
            "label":"15"
         },
         {
            "value":null,
            "label":"16"
         },
         {
            "value":null,
            "label":"17"
         },
         {
            "value":null,
            "label":"18"
         },
         {
            "value":null,
            "label":"19"
         },
         {
            "value":null,
            "label":"20"
         },
         {
            "value":null,
            "label":"21"
         },
         {
            "value":null,
            "label":"22"
         },
         {
            "value":null,
            "label":"23"
         },
         {
            "value":null,
            "label":"24"
         }
      ],
      "color":"rgba(60, 121, 245, 0.3)",
      "dataPointsColor":"rgba(60, 121, 245, 0.3)",
      "startIndex":7,
      "endIndex":7
   },
   {
      "data":[
         {
            "value":null,
            "label":"0"
         },
         {
            "value":null,
            "label":"1"
         },
         {
            "value":null,
            "label":"2"
         },
         {
            "value":null,
            "label":"3"
         },
         {
            "value":null,
            "label":"4"
         },
         {
            "value":null,
            "label":"5"
         },
         {
            "value":null,
            "label":"6"
         },
         {
            "value":2.713,
            "label":"7",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(3, 201, 136, 1)"
         },
         {
            "value":null,
            "label":"8"
         },
         {
            "value":null,
            "label":"9"
         },
         {
            "value":null,
            "label":"10"
         },
         {
            "value":null,
            "label":"11"
         },
         {
            "value":null,
            "label":"12"
         },
         {
            "value":null,
            "label":"13"
         },
         {
            "value":null,
            "label":"14"
         },
         {
            "value":null,
            "label":"15"
         },
         {
            "value":null,
            "label":"16"
         },
         {
            "value":null,
            "label":"17"
         },
         {
            "value":null,
            "label":"18"
         },
         {
            "value":null,
            "label":"19"
         },
         {
            "value":null,
            "label":"20"
         },
         {
            "value":null,
            "label":"21"
         },
         {
            "value":null,
            "label":"22"
         },
         {
            "value":null,
            "label":"23"
         },
         {
            "value":null,
            "label":"24"
         }
      ],
      "isSecondary":true,
      "color":"rgba(3, 201, 136, 1)",
      "dataPointsColor":"rgba(3, 201, 136, 1)",
      "startIndex":7,
      "endIndex":7
   },
   {
      "data":[
         {
            "value":null,
            "label":"0"
         },
         {
            "value":null,
            "label":"1"
         },
         {
            "value":null,
            "label":"2"
         },
         {
            "value":null,
            "label":"3"
         },
         {
            "value":null,
            "label":"4"
         },
         {
            "value":null,
            "label":"5"
         },
         {
            "value":null,
            "label":"6"
         },
         {
            "value":1.3545,
            "label":"7",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(3, 201, 136, 0.6)"
         },
         {
            "value":null,
            "label":"8"
         },
         {
            "value":null,
            "label":"9"
         },
         {
            "value":null,
            "label":"10"
         },
         {
            "value":null,
            "label":"11"
         },
         {
            "value":null,
            "label":"12"
         },
         {
            "value":null,
            "label":"13"
         },
         {
            "value":null,
            "label":"14"
         },
         {
            "value":null,
            "label":"15"
         },
         {
            "value":null,
            "label":"16"
         },
         {
            "value":null,
            "label":"17"
         },
         {
            "value":null,
            "label":"18"
         },
         {
            "value":null,
            "label":"19"
         },
         {
            "value":null,
            "label":"20"
         },
         {
            "value":null,
            "label":"21"
         },
         {
            "value":null,
            "label":"22"
         },
         {
            "value":null,
            "label":"23"
         },
         {
            "value":null,
            "label":"24"
         }
      ],
      "isSecondary":true,
      "color":"rgba(3, 201, 136, 0.6)",
      "dataPointsColor":"rgba(3, 201, 136, 0.6)",
      "startIndex":7,
      "endIndex":7
   },
   {
      "data":[
         {
            "value":null,
            "label":"0"
         },
         {
            "value":null,
            "label":"1"
         },
         {
            "value":null,
            "label":"2"
         },
         {
            "value":null,
            "label":"3"
         },
         {
            "value":null,
            "label":"4"
         },
         {
            "value":null,
            "label":"5"
         },
         {
            "value":null,
            "label":"6"
         },
         {
            "value":0,
            "label":"7",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(3, 201, 136, 0.3)"
         },
         {
            "value":null,
            "label":"8"
         },
         {
            "value":null,
            "label":"9"
         },
         {
            "value":null,
            "label":"10"
         },
         {
            "value":null,
            "label":"11"
         },
         {
            "value":null,
            "label":"12"
         },
         {
            "value":null,
            "label":"13"
         },
         {
            "value":null,
            "label":"14"
         },
         {
            "value":null,
            "label":"15"
         },
         {
            "value":null,
            "label":"16"
         },
         {
            "value":null,
            "label":"17"
         },
         {
            "value":null,
            "label":"18"
         },
         {
            "value":null,
            "label":"19"
         },
         {
            "value":null,
            "label":"20"
         },
         {
            "value":null,
            "label":"21"
         },
         {
            "value":null,
            "label":"22"
         },
         {
            "value":null,
            "label":"23"
         },
         {
            "value":null,
            "label":"24"
         }
      ],
      "isSecondary":true,
      "color":"rgba(3, 201, 136, 0.3)",
      "dataPointsColor":"rgba(3, 201, 136, 0.3)",
      "startIndex":7,
      "endIndex":7
   }
]

`
   {dataSet && (
          <LineChart
            key={renderChartWithDateKey}
            maxValue={75}
            dataSet={dataSet}
            isAnimated={true}
            spacing={32}
            endSpacing={10}
            noOfSections={4}
            onlyPositive={true}
            yAxisTextStyle={{ color: 'blue' }}
            width={windowWidth - 100}
            showYAxisIndices
            yAxisIndicesColor={'transparent'}
            yAxisIndicesWidth={10}
            // showTextOnFocus={true}
            // showDataPointLabelOnFocus={true}
            // showStripOnFocus={true}
            // focusEnabled={true}
            stripColor={'gray'}
            stripOpacity={0.5}
            dataPointsWidth={4}
            dataPointsRadius={2}
            dataPointsHeight={4}
            dataPointLabelWidth={100}
            roundToDigits={2}
            yAxisColor={'blue'}
            yAxisThickness={2}
            // showFractionalValues={true}
            trimYAxisAtTop={true}
            secondaryYAxis={{
              maxValue: 6,
              noOfSections: 6,
              roundToDigits: 2,
              yAxisTextStyle: {
                color: 'green',
              },
              yAxisColor: 'green',
              yAxisThickness: 2,
              yAxisIndicesColor: 'transparent',
            }}
            xAxisIndicesHeight={10}
            xAxisIndicesWidth={4}
            pointerConfig={{

              pointerStripUptoDataPoint: false,
              pointerStripColor: 'lightgray',
              pointerStripWidth: 2,
              strokeDashArray: [2, 5],
              // pointerColor: 'lightgray',
              radius: 4,

              // pointerLabelWidth: 100,
              // pointerLabelHeight: 90,
              showPointerStrip: true,
              activatePointersOnLongPress: true,
              autoAdjustPointerLabelPosition: false,
              pointerColorsForDataSet: [
                theme.Colors.maxTempColor,
                theme.Colors.avgTempColor,
                theme.Colors.minTempColor,
                theme.Colors.maxVolColor,
                theme.Colors.avgVolColor,
                theme.Colors.minVolColor,
              ],
              //
              // pointerStripHeight: 120,

              // activatePointersOnLongPress: true,
              // autoAdjustPointerLabelPosition: false,
              // stripOverPointer: true,
              pointerVanishDelay: 1500,
              initialPointerAppearDelay: 5,
              activatePointersDelay: 600,
              // pointerEvents: 'auto',
              //
              pointerLabelComponent: (items1, items2, index) => {
                console.log('🚀 ~ items1:', items1)
                console.log('🚀 ~ items2:', items2)
                console.log('🚀 ~ index:', index)
                return renderDataPointLabelComponent(
                  items1[0].value,
                  items1[1].value,
                  items1[2].value,
                  items2[0].value,
                  items2[1].value,
                  items2[2].value,
                )
              },
            }}
          />
        )}
`

**Comment by Abhinandan-Kushwaha** [comment]
Hi @dumihi313 
This is happening because `value` in the data objects is supposed to be a number, but you are passing `null`.

You will have to solve this issue yourself by passing some numeric value instead of null.
