### ISSUE TITLE
areaChart given in dataSet array of line chart doesn't work

### ISSUE THREAD

**Issue by HASH-0021** [Abhinandan-Kushwaha/react-native-gifted-charts#758]
I created a dataSet array for 2 lines. If areaChart prop of LineChart is set true, then both of the lines become areaChart. I want to make only one of them an areaChart, but giving areaChart key as true in dataSet item doesn't seem to work. Also there is no areaChart1,areaChart2,...... props for LineChart.

Sidenote: Why doesn't endSpacing adjust linechart the way initialSpacing does? endSpacing doesn't seem to effect line chart, then what is the purpose of it?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @HASH-0021 👋
Thanks for reporting this issue.

You can now set `areaChart: true` in the individual objects of the `dataSet` array. This will not make all lines into area charts, but only those for which `areaChart` property is set to true inside the `dataSet` array.

This is available from versions `1.4.26` onwards.
Please use the latest version of the library.

`endSpacing` actually increases the rules length (or background of the chart) in case the line/curve of the chart does not cover the entire width of the screen. It is like a padding at the right side of the line/curve in the chart.
