### ISSUE TITLE
DataPoints, datapointlabel and strip aren't not show when press to datapoint marker in new versions

### ISSUE THREAD

**Issue by dumihi313** [Abhinandan-Kushwaha/react-native-gifted-charts#762]
1. In my old version, It works well when I press label **17** (lib interpolate some value null before), please view video
  gifted-charts-core: ^0.1.18
  react-native-gifted-charts: ^1.4.19

https://github.com/user-attachments/assets/53d5fbe0-ec1d-49de-be57-81c273934265

2. Now with some new versions, it does not show anything when I press label 17

https://github.com/user-attachments/assets/600034fc-7fd5-481f-8001-2d56a546b936

I set dataPointLabelComponent into the first blue line
3. My dataset:
[
   {
      "data":[
         {
            "value":70.88,
            "label":"0",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)",
            "dataPointLabelShiftX":75
         },
         {
            "value":70.88,
            "label":"1",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)",
            "dataPointLabelShiftX":75
         },
         {
            "value":70.88,
            "label":"2",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)",
            "dataPointLabelShiftX":75
         },
         {
            "value":70.88,
            "label":"3",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)",
            "dataPointLabelShiftX":75
         },
         {
            "value":70.88,
            "label":"4",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)",
            "dataPointLabelShiftX":75
         },
         {
            "value":null,
            "label":"5"
         },
         {
            "value":70.88,
            "label":"6",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)",
            "dataPointLabelShiftX":75
         },
         {
            "value":70.88,
            "label":"7",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)",
            "dataPointLabelShiftX":75
         },
         {
            "value":70.88,
            "label":"8",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)",
            "dataPointLabelShiftX":75
         },
         {
            "value":70.88,
            "label":"9",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)",
            "dataPointLabelShiftX":75
         },
         {
            "value":70.88,
            "label":"10",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)",
            "dataPointLabelShiftX":75
         },
         {
            "value":70.88,
            "label":"11",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)",
            "dataPointLabelShiftX":75
         },
         {
            "value":70.88,
            "label":"12",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)",
            "dataPointLabelShiftX":75
         },
         {
            "value":32,
            "label":"13",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)",
            "dataPointLabelShiftX":75
         },
         {
            "value":null,
            "label":"14"
         },
         {
            "value":null,
            "label":"15",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)"
         },
         {
            "value":null,
            "label":"16",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)"
         },
         {
            "value":70.88,
            "label":"17",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)",
            "dataPointLabelShiftX":75
         },
         {
            "value":70.88,
            "label":"18",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)",
            "dataPointLabelShiftX":75
         },
         {
            "value":70.88,
            "label":"19",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)",
            "dataPointLabelShiftX":75
         },
         {
            "value":70.88,
            "label":"20",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)",
            "dataPointLabelShiftX":75
         },
         {
            "value":70.88,
            "label":"21",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)",
            "dataPointLabelShiftX":75
         },
         {
            "value":70.88,
            "label":"22",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)",
            "dataPointLabelShiftX":75
         },
         {
            "value":70.88,
            "label":"23",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(60, 121, 245, 1)",
            "dataPointLabelShiftX":75
         },
         {
            "value":0,
            "label":"24"
         }
      ],
      "color":"rgba(60, 121, 245, 1)",
      "dataPointsColor":"rgba(60, 121, 245, 1)",
      "startIndex":0,
      "endIndex":23
   }
]

**Comment by Abhinandan-Kushwaha** [comment]
Hi @dumihi313 
Can you share the entire code and data?

Make sure that I can run your code in my empty react-native project with minimum changes.

**Comment by dumihi313** [comment]
I tested this bug maybe happens when version gifted-charts-core > 0.1.18
I already set datapointlabelComponent in my Dataset
<img width="601" alt="image" src="https://github.com/user-attachments/assets/4f2a67f9-a0aa-464b-a8a1-ad572ffcaa72">

My code:
 const [dataSet, setDataSet] = useState<DataSet[] | undefined>()
 const initialDataSet = useRef<DataSet[]>()

 useEffect(() => {
      if (batteryChart && batteryChart.length > 0) {
        const result = parseDTOtoChartModel(
          batteryChart,
          renderDataPointLabelComponent,
        ).dataSet
        setDataSet(result) // mydataset example below
        initialDataSet.current = result.map(a => Object.assign({}, a))
      }
    }, [batteryChart])


 <LineChart
            key={renderChartWithDateKey}
            maxValue={75}
            dataSet={dataSet}
            isAnimated={true}
            spacing={32}
            endSpacing={10}
            noOfSections={4}
            onlyPositive={true}
            yAxisTextStyle={{ color: 'blue' }}
            width={windowWidth - 100}
            showYAxisIndices
            yAxisIndicesColor={'transparent'}
            yAxisIndicesWidth={10}
            showTextOnFocus={true}
            showDataPointLabelOnFocus={true}
            showStripOnFocus={true}
            focusEnabled={true}
            stripColor={'gray'}
            stripOpacity={0.5}
            dataPointsWidth={4}
            dataPointsRadius={2}
            dataPointsHeight={4}
            dataPointLabelWidth={100}
            roundToDigits={2}
            yAxisColor={'blue'}
            yAxisThickness={2}
            // showFractionalValues={true}
            trimYAxisAtTop={true}
            secondaryYAxis={{
              maxValue: 6,
              noOfSections: 6,
              roundToDigits: 2,
              yAxisTextStyle: {
                color: 'green',
              },
              yAxisColor: 'green',
              yAxisThickness: 2,
              yAxisIndicesColor: 'transparent',
            }}
            xAxisIndicesHeight={10}
            xAxisIndicesWidth={4}
          />
        )}

My dataset:

[
{
"data":[
{
"value":70.88,
"label":"0",
"focusedDataPointRadius":4,
"focusedDataPointColor":"rgba(60, 121, 245, 1)",
"dataPointLabelShiftX":75
},
{
"value":70.88,
"label":"1",
"focusedDataPointRadius":4,
"focusedDataPointColor":"rgba(60, 121, 245, 1)",
"dataPointLabelShiftX":75
},
{
"value":70.88,
"label":"2",
"focusedDataPointRadius":4,
"focusedDataPointColor":"rgba(60, 121, 245, 1)",
"dataPointLabelShiftX":75
},
{
"value":70.88,
"label":"3",
"focusedDataPointRadius":4,
"focusedDataPointColor":"rgba(60, 121, 245, 1)",
"dataPointLabelShiftX":75
},
{
"value":70.88,
"label":"4",
"focusedDataPointRadius":4,
"focusedDataPointColor":"rgba(60, 121, 245, 1)",
"dataPointLabelShiftX":75
},
{
"value":null,
"label":"5"
},
{
"value":70.88,
"label":"6",
"focusedDataPointRadius":4,
"focusedDataPointColor":"rgba(60, 121, 245, 1)",
"dataPointLabelShiftX":75
},
{
"value":70.88,
"label":"7",
"focusedDataPointRadius":4,
"focusedDataPointColor":"rgba(60, 121, 245, 1)",
"dataPointLabelShiftX":75
},
{
"value":70.88,
"label":"8",
"focusedDataPointRadius":4,
"focusedDataPointColor":"rgba(60, 121, 245, 1)",
"dataPointLabelShiftX":75
},
{
"value":70.88,
"label":"9",
"focusedDataPointRadius":4,
"focusedDataPointColor":"rgba(60, 121, 245, 1)",
"dataPointLabelShiftX":75
},
{
"value":70.88,
"label":"10",
"focusedDataPointRadius":4,
"focusedDataPointColor":"rgba(60, 121, 245, 1)",
"dataPointLabelShiftX":75
},
{
"value":70.88,
"label":"11",
"focusedDataPointRadius":4,
"focusedDataPointColor":"rgba(60, 121, 245, 1)",
"dataPointLabelShiftX":75
},
{
"value":70.88,
"label":"12",
"focusedDataPointRadius":4,
"focusedDataPointColor":"rgba(60, 121, 245, 1)",
"dataPointLabelShiftX":75
},
{
"value":32,
"label":"13",
"focusedDataPointRadius":4,
"focusedDataPointColor":"rgba(60, 121, 245, 1)",
"dataPointLabelShiftX":75
},
{
"value":null,
"label":"14"
},
{
"value":null,
"label":"15",
"focusedDataPointRadius":4,
"focusedDataPointColor":"rgba(60, 121, 245, 1)"
},
{
"value":null,
"label":"16",
"focusedDataPointRadius":4,
"focusedDataPointColor":"rgba(60, 121, 245, 1)"
},
{
"value":70.88,
"label":"17",
"focusedDataPointRadius":4,
"focusedDataPointColor":"rgba(60, 121, 245, 1)",
"dataPointLabelShiftX":75
},
{
"value":70.88,
"label":"18",
"focusedDataPointRadius":4,
"focusedDataPointColor":"rgba(60, 121, 245, 1)",
"dataPointLabelShiftX":75
},
{
"value":70.88,
"label":"19",
"focusedDataPointRadius":4,
"focusedDataPointColor":"rgba(60, 121, 245, 1)",
"dataPointLabelShiftX":75
},
{
"value":70.88,
"label":"20",
"focusedDataPointRadius":4,
"focusedDataPointColor":"rgba(60, 121, 245, 1)",
"dataPointLabelShiftX":75
},
{
"value":70.88,
"label":"21",
"focusedDataPointRadius":4,
"focusedDataPointColor":"rgba(60, 121, 245, 1)",
"dataPointLabelShiftX":75
},
{
"value":70.88,
"label":"22",
"focusedDataPointRadius":4,
"focusedDataPointColor":"rgba(60, 121, 245, 1)",
"dataPointLabelShiftX":75
},
{
"value":70.88,
"label":"23",
"focusedDataPointRadius":4,
"focusedDataPointColor":"rgba(60, 121, 245, 1)",
"dataPointLabelShiftX":75
},
{
"value":0,
"label":"24"
}
],
"color":"rgba(60, 121, 245, 1)",
"dataPointsColor":"rgba(60, 121, 245, 1)",
"startIndex":0,
"endIndex":23
}
]

**Comment by Abhinandan-Kushwaha** [comment]
Hi @dumihi313 
PointerLabelComponent is not appearing for those indices at which you have set `null` or `undefined` values in the first set of dataSet (the first blue line).

You should set pointerLabelComponent in that set which does not have null values.

**Comment by Abhinandan-Kushwaha** [comment]
@dumihi313 I will try to fix this for null values.

Meanwhile there's a workaround you can try-

The issue is fixed if you use the prop `showDataPointsForMissingValues`.
And if you don't want the data points for null values to appear, set the dataPointRadius to zero for those data items which have null value.

**Comment by dumihi313** [comment]
Thank u for your support
Just summary my issue again:
In my case label 17 has data value but it does not show pointer or strip while press. 15 and 16 are null so it should not show pointer/ strip when press. Maybe some thing is mis calculation between 16 and 17
i also want lib do interpolate for null values because it render lines correctly now
Thank you, I go to bed now. Have a good day

**Comment by Abhinandan-Kushwaha** [comment]
@dumihi313 
On my system, it shows for label 17-

https://github.com/user-attachments/assets/9b91c1c7-8b93-4a31-8235-9405153d9339

I have used your dataSet.

**Comment by dumihi313** [comment]
Thank u, i will double check to morrow
I will let u know about it

**Comment by dumihi313** [comment]
Thank you for your effort. After double check, I found the issue
My dataset has 6 lines, and the last line (dataset[5].data - green color) has lineDataItem with null value
 {
            "value":null,
            "label":"17",
            "focusedDataPointRadius":4,
            "focusedDataPointColor":"rgba(3, 201, 136, 0.3)"
         },

So, the chart can not show pointerLabelComponent while pressing label 17 even though each other lines at label 17 in dataset has a value **NOT** null

https://github.com/user-attachments/assets/42edd1d1-d6bc-49b5-9890-e5428bd78f61
