### ISSUE TITLE
[Feature Request] Make custom stepHeight for specific range of y-Axis

### ISSUE THREAD

**Issue by dumihi313** [Abhinandan-Kushwaha/react-native-gifted-charts#767]
I know we can use stepHeight to make space between each section of y-axis. I expect to modify stepHeight for only a range of y-Axis from 60 - 70 and keep existed stepHeight ratio for the rest range y-Axis. Because I want it is more clear to see, Its values of these blue lines are so close together.
<img width="278" alt="image" src="https://github.com/user-attachments/assets/6067daa4-366a-4772-9f7c-392fb5e53b8a">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @dumihi313 
This might help you- https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/746

**Comment by dumihi313** [comment]
Thank you a lot, i will try it
