### ISSUE TITLE
[Question] Andoird performance on bar chart when create 1000 data

### ISSUE THREAD

**Issue by ducpt-bili** [Abhinandan-Kushwaha/react-native-gifted-charts#768]
I am using basic barchart of gifted chart, when i am using 1000 data to render bar chart, it freezed.
I check the code in gifted chart, bar chart using scrollview to implement.
So my question is, do you have any way to make it more performance when data is huge? 
Can we using flatlist/flashlist to replace scrollview so we will have better perf?

Thank you for your lib.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ducpt-bili 
Pagination is currently supported using the below props-

1. onEndReached
2. onStartReached
3. endReachedOffset

See [The pagination related props here](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/BarChart/BarChartProps.md#pagination-related-props)
