### ISSUE TITLE
Can't find a way to add legend to stacked bar chart

### ISSUE THREAD

**Issue by osymo** [Abhinandan-Kushwaha/react-native-gifted-charts#77]
Hello.

First of all thank you for your great plugin. It is totally helpful.

I'm using the stacked bar chart. 

I'm  looking for a way to add a legend next to each part of a stacked bar chart so that the users are able to visually identify what each (colored) part of the stacked bar chart represents.

Thanks again.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @osymo 👋
Thanks for pointing out the issue.
Currently, we don't have in-built legend components for any chart in the library. However, it's quite easy to make your own custom legend component.

I have shared an example of custom legend [here](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/64)

If you wanted something different, please do let me know. I will work on it.
Hope it helps🤗
