### ISSUE TITLE
Support for dynamic timestamp values on X-Axis for LineChart

### ISSUE THREAD

**Issue by quememo** [Abhinandan-Kushwaha/react-native-gifted-charts#770]
I would like to create a daily LineChart that evolves throughout the day, where the X-axis is fixed between 00:00 and the following 00:00 (a total of 24 hours) with labels every 4 hours. The Y-axis would indicate the number of steps walked up to that moment. Something like this:
![image](https://github.com/user-attachments/assets/ca318b2c-ffcc-4768-84b6-a8f7f4041d14)

Specifically, an example of my data looks like this:
```json
[
    {
        "steps": 28,
        "timestamp": "2024-08-06T02:10:48.000000-04:00"
    },
    {
        "steps": 62,
        "timestamp": "2024-08-06T04:21:19.000000-04:00"
    },
    {
        "steps": 98,
        "timestamp": "2024-08-06T09:16:49.000000-04:00"
    },
    {
        "steps": 116,
        "timestamp": "2024-08-06T09:25:43.000000-04:00"
    },
    {
        "steps": 261,
        "timestamp": "2024-08-06T14:06:51.000000-04:00"
    }
]

```

The timestamps can be at any moment; there is no regular interval. Considering this, by midday, only half of the chart should be drawn, and the points should be positioned according to the timestamp value.

Is it possible to do this without normalizing my data using this library? According to what I saw in this [issue](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/589), it's not supported, but I would like to know if there is any alternative or if it is planned to be supported in the future.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @quememo 
Thanks for requesting this feature. For Bar charts, we can add `spacing` property to individual data items. I will try to add this feature to Line charts as well.

Expect a new release with this feature in 2-3 days.

**Comment by hbd9417** [comment]
Hello! Any news on this? Really looking forward for this feature also. Thanks!

**Comment by Yaseen-Ejaz** [comment]
I used the ```useEffect()``` property in React for a fixed array size. All the values are initialized as 0 in an array. Then if the data changes check if the value is above 0 and set the spacing dynamically with the screen size using
```Dimensions.get('window').width``` divided by the number of entries above 0.

**Comment by Abhinandan-Kushwaha** [comment]
@hbd9417 @Yaseen-Ejaz individual spacing is now allowed for Line charts as well
