### ISSUE TITLE
Reducing Initial Spacing Affects X-Axis Label Position; Dot/Strip and Label Not Vertically Aligned

### ISSUE THREAD

**Issue by Rashid-Rcp** [Abhinandan-Kushwaha/react-native-gifted-charts#772]
I'm facing an issue with the positioning of the X-axis labels and the vertical alignment of the dot/strip with the labels when using the LineChart.

I have set initialSpacing to 0 and adjustToWidth to true. The X-axis labels are automatically adjusted, but the alignment is not accurate. Specifically, the position of the dot/strip and the corresponding X-axis labels are not vertically aligned.

Here's the code snippet:

<LineChart
                  data={chartData[0]}
                  data2={chartData[1] ?? null}
                  data3={chartData[2] ?? null}
                  data4={chartData[3] ?? null}
                  areaChart
                  initialSpacing={0}
                  adjustToWidth={true}
                  xAxisLabelTextStyle={{
                    fontSize: 11,
                    fontFamily: fonts.fontRegular,
                  }}
                  xAxisLength={screenWidth - 30}
                  yAxisTextStyle={{
                    fontSize: 11,
                    fontFamily: fonts.fontRegular,
                  }}
                  color1={colors.MED_BLUE}
                  color2={"#FF7F7F"}
                  startFillColor1={colors.MED_GREEN}
                  startFillColor2={colors.MED_BLUE}
                  dataPointsColor1={colors.MED_BLUE}
                  dataPointsColor2={"#FF7F7F"}
                  dataPointsRadius={3}
                  curved={true}
                  focusEnabled={true}
                  showStripOnFocus={true}
                  stripWidth={1}
                  stripColor={'red'}
                  focusedDataPointColor={'red'}
                  delayBeforeUnFocus={30000}
                  onFocus={(item, index) => {
                    hanldeOnFocus(index);
                  }}
                  height={250}
                />

![image](https://github.com/user-attachments/assets/fad7729c-494c-4a63-8aac-c90308af9860)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Rashid-Rcp 
Try adding margins and/or alignments inside `xAxisLabelTextStyle`. 
**Note-** You might need to add negative margins.

**Comment by Rashid-Rcp** [comment]
Thanks for the response. I was able to solve the issue with margins and width on labelTextStyle
