### ISSUE TITLE
label overflow in barchart

### ISSUE THREAD

**Issue by sd535682** [Abhinandan-Kushwaha/react-native-gifted-charts#774]
![Screenshot_2024-08-11-16-41-28-59_f73b71075b1de7323614b647fe394240~2.jpg](https://github.com/user-attachments/assets/5f625b89-d578-4f47-86c4-d7ba5deb6bed)

Why are the labels overflowing here?

https://snack.expo.dev/kAIinbKfvt1viem9v9JFF

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sd535682 
This can be fixed using the `labelWidth` and `xAxisLabelTextStyle` props.

Here's my snack with the above props- https://snack.expo.dev/@ak_97/hot-indigo-cookie

**Comment by hokagedemehin** [comment]
instead of alignSelf: "flex-end", you can use textAlign: "right"
