### ISSUE TITLE
Bug: Negative steps and values in in second y axis are incorrect position

### ISSUE THREAD

**Issue by dumihi313** [Abhinandan-Kushwaha/react-native-gifted-charts#775]
![image](https://github.com/user-attachments/assets/dcc327da-cb57-45ff-be00-9ef98c5c2f40)

Please check this bug, the first y-axis is correct, but the second right steps and values in y-axis are incorrect

**Comment by Abhinandan-Kushwaha** [comment]
Hi @dumihi313 
Thanks for reporting this issue. It has been fixed from versions `1.4.29` onwards. 🎉

Please use the latest version of the library.

**Comment by dumihi313** [comment]
Yes it has been fixed at versions 1.4.29
Thank u
