### ISSUE TITLE
Why the y axis of line chart is shifted up and some data cannot be displayed

### ISSUE THREAD

**Issue by Haywardchan** [Abhinandan-Kushwaha/react-native-gifted-charts#778]
![image](https://github.com/user-attachments/assets/a7643c66-6a5f-4656-9c8a-ef1bd77ff23c)
![image](https://github.com/user-attachments/assets/5afefcf5-81b2-4751-9233-178f37083390)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Haywardchan Thanks for reporting this issue. It has been fixed from versions `1.4.31` onwards.
Please use the latest version of the library.
