### ISSUE TITLE
Negative Values

### ISSUE THREAD

**Issue by ensargunesdogdu** [Abhinandan-Kushwaha/react-native-gifted-charts#78]
Hey there,

We could not render negative values with any charts. Could not find any documentation about it. Do you have any plan supporting negative values? If so, I can help you with that.

**Code:**
`
const data=[ {value:-25}, {value:-45}, {value:-35}, {value:-95}]
<BarChart data = {data} />
`

**Result:**
![Screen Shot 2022-02-01 at 10 21 51](https://user-images.githubusercontent.com/5063517/151927795-2264a8fb-3207-4d10-9ec4-033726f79bb7.png)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ensargunesdogdu 👋
Thanks for posting out the issue. The support for negative values is added in version `1.0.1`.🎉

But, in case there are only negative values in your data set, and no positive values, you can set the data values as positive (their absolute values), and add the prefix `-` with the help of the `yAxisLabelPrefix` prop.

Or, you can pass negative values too, then the Bars corresponding to the negative values will be drawn under the X-Axis (in the 4th Quadrant).

But, while using negative values, you may need to pass these props-
1. maxValue
2. minValue
3. stepValue
4. stepHeight
5. height
6. noOfSections
7. noOfSectionsBelowXAxis

`minValue` here represents the most negative value to be seen on the Y-Axis.
`noOfSections` means the number of horizontal sections (strips) **above** the X-Axis in the chart.
`noOfSectionsBelowXAxis` means the number of horizontal sections (strips) **below** the X-Axis in the chart.
`height` represents the height of the chart above the X-Axis (excluding the part below the X-Axis).

Hope it helps. Cheers!🤗

**Comment by dogancancelik12** [comment]
Hi @Abhinandan-Kushwaha ,

Are negative values also provided in stack bar chart? 
Could not see any negative value in chart with trying what you said above. 

Thank you.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @dogancancelik12 
The support for negative values in stack bar chart is now added in version `1.0.2`🎉

Make sure that the values in a single stack should be all positive or all negative.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ensargunesdogdu 
This feature is now supported for stacks having a mix of +ve and -ve values from version `1.3.27` onwards.

Thanks @christophby for your PR.

**Comment by ensargunesdogdu** [comment]
Thanks, @Abhinandan-Kushwaha and @christophby, that will help us :)
