### ISSUE TITLE
Having x label without values

### ISSUE THREAD

**Issue by nrcaz** [Abhinandan-Kushwaha/react-native-gifted-charts#781]
<img width="530" alt="image" src="https://github.com/user-attachments/assets/7641d0b0-3ec8-491e-b844-373fcec27bcd">

Is it possible to display every month on the bottom even if we have no value for the specific month ?

Using `hideDataPoint` does not work, and value must be defined.

Is there a way to accomplish this ?

**Comment by Abhinandan-Kushwaha** [comment]
@nrcaz We can now have `undefined` data values, as I have made it optional now. See https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/releases/tag/v1.4.49

Please use the latest version of the library.

**Comment by nrcaz** [comment]
@Abhinandan-Kushwaha nice !
Thank you for this.
