### ISSUE TITLE
LineChart doesn't display lines of chart on Safari (iPhone)

### ISSUE THREAD

**Issue by rodnoycry** [Abhinandan-Kushwaha/react-native-gifted-charts#782]
### Description
Apparently Safari has some differences in displaying of SVG elements relative to other browsers, and on of them seems to be displaying `<svg>` tag with no specified `viewport` as element with 0 width and 0 height. Other browsers seems to adjust size of `svg` container but this is not the case with Safari. So this behavior leads to issues with displaying `LineChart` component from this library on Safari. Instead of this beautiful default chart:

<image src="https://github.com/user-attachments/assets/308c57df-e7a6-4eb6-82e5-8e0e2713a525" height="300px" width="auto" />

Safari displays this:
<image src="https://github.com/user-attachments/assets/9afbb6e0-11c7-446c-8873-fc2e32a0c9ec" height="500px" width="auto" />

with no chart lines at all

### Reproduction and example
1. First of all I created repo with minimal reproduction example here: https://github.com/rodnoycry/safari-charts-bug/tree/main
So you can clone repo using this command:
```sh
git clone git@github.com:rodnoycry/safari-charts-bug.git
```
And test locally, using for example [ngrok](https://ngrok.com/), the steps for running the app are pretty usual: run `npm install` and `npm run web`

2. Also I deployed project from this example repo, so you can open it on any device by this link, if you want to quickly test this issue you can use this link:
https://safari-charts-bug.vercel.app/

### Environment
Tested on device with this specs:
- iPhone Model: 11
- iOS Version: 17.5.1
- react-native-gifted-charts: 1.4.29

### Minimal Example Repository
https://github.com/rodnoycry/safari-charts-bug/tree/main

If you need any extra information please let me know

**Comment by Abhinandan-Kushwaha** [comment]
Hi @rodnoycry 
For web projects, please use the [react-gifted-charts](https://www.npmjs.com/package/react-gifted-charts) repo.

**Comment by rodnoycry** [comment]
Yeah, but we are working on Android and iOS also in the same react-native project, or we should use both libraries in this case and display charts with different libraries depending on environment?

Also I want to open a PR with potential fix of this issue, can it be helpful?

**Comment by Abhinandan-Kushwaha** [comment]
Sure @rodnoycry 
A PR for fix would be great!!

**Comment by Abhinandan-Kushwaha** [comment]
Thanks for the PR @rodnoycry 
I will test and merge it by tomorrow.

**Comment by rodnoycry** [comment]
@Abhinandan-Kushwaha Thank you!
