### ISSUE TITLE
show labels without having data point to respective label

### ISSUE THREAD

**Issue by sajjadMohammad679** [Abhinandan-Kushwaha/react-native-gifted-charts#784]
is there any way to show labels without having a data point to respective label or we can define labels and data point values separately i tried but not worked

**Comment by Abhinandan-Kushwaha** [comment]
@sajjadMohammad679 
Do you want a label on the X-axis? Or a label near the data line, something like `dataPointText`)?

**Comment by sajjadMohammad679** [comment]
labels on x-axis

**Comment by Abhinandan-Kushwaha** [comment]
Defining X axis labels and data points separately will cause issues in scrolling. Currently data points and X axis labels are tied together so they scroll together (on horizontal scroll).

You can show/hide labels selectively for some data points. If you want a label in between data points, we can have work arounds like these -

1. Use `labelComponent` and make your custom label appear like 2 separate labels (separated by space or margin).
2. Use`labelTextStyle` and `labelWidth` and with help of spaces and margins, make a single label appear as 2 labels
