### ISSUE TITLE
Bug: Updating state inside pointerLabelComponent

### ISSUE THREAD

**Issue by gustavokenzo1** [Abhinandan-Kushwaha/react-native-gifted-charts#785]
Whenever I try to set a state inside pointerLabelComponent, I get the following warning:

![simulator_screenshot_0C3CBA3B-CC16-4F34-9BBD-72D228D35511](https://github.com/user-attachments/assets/0554493f-995f-4972-b11d-5d891f8a2dfa)

The thing is, I want to render info about the selected item on other parts of my screen, and I always get this warning.

**Comment by gustavokenzo1** [comment]
Sometimes, I even get this:

<img width="1281" alt="Screenshot 2024-08-14 at 06 34 59" src="https://github.com/user-attachments/assets/da118f1b-a2a8-4a08-9253-ccd58657e6ed">

**Comment by ak-spotter** [comment]
Hi @gustavokenzo1 
Don't set state inside pointerLabelComponent, instead do it in `getPointerProps`.
This issue might help- https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/714
