### ISSUE TITLE
Controlling the boundaries of sections painted with sectionColors

### ISSUE THREAD

**Issue by ilyaserenyilmaz** [Abhinandan-Kushwaha/react-native-gifted-charts#790]
Is there any way to manipulate the boundaries of sections that are colored using sectionColors on y axis? For example, is it possible to have seven different sections such that first section is between [0,30] in y-axis filled with green, second section is between [30,100] in y-axis filled with blue and etc.?

**Comment by Abhinandan-Kushwaha** [comment]
Can you share an image @ilyaserenyilmaz

**Comment by ilyaserenyilmaz** [comment]
Of course @Abhinandan-Kushwaha! As you can see, I would like to give different ranges for each colored section on y axis. 
<img width="289" alt="image" src="https://github.com/user-attachments/assets/64d2e253-f4ec-4e6d-9eb6-d933ae8a4859">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ilyaserenyilmaz 
To have Y axis sections of different lengths, [this issue might help](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/746)

**Comment by harishgupta01** [comment]
Hi @ilyaserenyilmaz  - I am looking for the similar use case but i dont have have the section but using reference line and want to make sure the color each reference line is different from the other. so basically based on three reference line I want to show three different color. Could you suggest how can I achieve this  ?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ilyaserenyilmaz @harishgupta01 
Thanks for requesting this feature. 

I have added the prop `customBackground` to Bar, Line, Area charts. `customBackground` is an object with following keys (All of which are optional). 

```ts
type CustomBackground = {
  color?: ColorValue
  component?: Function
  horizontalShift?: number
  verticalShift?: number
  height?: number
  width?: number
  widthAdjustment?: number // the library aut-computes the width, if you want slight less or more than that, use this property
}
```

You can pass any component in the `component`  property of the `customBackground` prop which will be rendered as the background of the chart.
