### ISSUE TITLE
Data Pointer Selection not working

### ISSUE THREAD

**Issue by aabidDevit** [Abhinandan-Kushwaha/react-native-gifted-charts#792]
I want to display Datapointer as selected when user press on dot. Current it is not working like this. It is working on clicking on line.

https://github.com/user-attachments/assets/16c6f2fe-9973-4741-b30f-a37e2f4b4d33

**Comment by Abhinandan-Kushwaha** [comment]
Can you share the code @aabidDevit

**Comment by aabidDevit** [comment]
Here @Abhinandan-Kushwaha 

 <LineChart
           height={130}
          data={mapLineChartDataDynamically(data, [1], 0)}
          data2={data2 ? data2 : undefined}
          data3={data3}
          areaChart={areaChart}
          adjustToWidth={true}
         onPress={(item: any)=>{
           handlePointerUpdate([item])
         }}
          showVerticalLines
          spacing={ chartWidthDataPoints / data.length}
          initialSpacing={15}
          color1={line1Color ? line1Color : 'skyblue'}
          color2="orange"
          color3="red"
          yAxisColor={tgColors.white}
          xAxisColor={tgColors.white}
          dataPointsColor1={line1Color ? line1Color : 'skyblue'}
          dataPointsColor2="yellow"
          dataPointsColor3="red"
          startFillColor1={fill1Color ? fill1Color : 'white'}
          startFillColor2="orange"
          startFillColor3="red"
          isAnimated
          disableScroll
          pointerConfig={{
            pointerColor: line1Color,
            persistPointer: true,
            pointerLabelComponent:(items: any)=>{
               handlePointerUpdate([items])
            },
          startOpacity={0.2}
          endOpacity={0.2}
        />

**Comment by Abhinandan-Kushwaha** [comment]
Hi @aabidDevit 
I can see you have put the following in the `pointerLabelComponent` property of the `pointerConfig` prop-
```js
(items: any) => {
 handlePointerUpdate([items])
}
```
Remove it from there and put it in the `getPointerProps` prop.
See https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/785#issuecomment-2288310649
