### ISSUE TITLE
YAxis values in Multple lines in LineChart not showing correct.

### ISSUE THREAD

**Issue by aabidDevit** [Abhinandan-Kushwaha/react-native-gifted-charts#795]
I passed 3 arrays in line chart. All 3 has different range of yaxis values. It is taking first array yAxis values. As a result chart is displaying wrong data.

You can see skyblue line is starting from top of chart, which means its yAxis value is greater than it is showing on chart.
It is taking 1st array values for yAxis

![Screenshot 2024-08-23 at 5 52 00 PM](https://github.com/user-attachments/assets/3ac0ecfb-b00f-40b0-8738-116b232c33bd)

Here is the code,

 <LineChart
           height={130}
          data={data} => [{label: 'Apr', value: 33506}...{label: 'Mar', value: 33506}]
          data2={data2} => [{label: 'Apr', value: 33506}...{label: 'Mar', value: 66006}]
          data3={data3} => [{label: 'Apr', value: 33506}...{label: 'Mar', value: 77003}]
          areaChart={areaChart}
          adjustToWidth={true}
 />
 
 it should display yAxis till the max number with in 3 arrays

**Comment by Abhinandan-Kushwaha** [comment]
Hi @aabidDevit 
You can use the `maxValue` prop.
See the [props table here](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/BarChart/BarChartProps.md#basic-props)
