### ISSUE TITLE
Misaligned external label in PieChart

### ISSUE THREAD

**Issue by Nickersoft** [Abhinandan-Kushwaha/react-native-gifted-charts#798]
Hey @Abhinandan-Kushwaha,

Great job on this library – though I noticed when using the `externalLabelComponent` that my text isn't aligned to the end of the label line on the left side. Looking at the core library it looks like it should be calculating the position correctly, but for some reason it's not.

![CleanShot 2024-08-23 at 18 06 38](https://github.com/user-attachments/assets/f1be07b8-c6b1-4f1c-9d4c-63bdb719555a)
![CleanShot 2024-08-23 at 18 07 16](https://github.com/user-attachments/assets/ef5cd28b-9a56-42ed-a77e-7e44a8296c8d)

(I would expect "Good" in the screenshot above to be right-aligned and not eclipsing the label line). 

Is there anything I can do on my end to fix this, or is this a confirmed bug?

Also – is adding an extraRadius prop the only way to avoid it clipping my labels?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Nickersoft 
Try adding `labelComponentWidth: <some_value>` in the `labelLineConfig` prop.

See [the note in props list here](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/PieChart/PieChartProps.md#labellineconfig)
You might also need the `labelComponentMargin` property in the `labelLineConfig` prop.

**Comment by Nickersoft** [comment]
Hey @Abhinandan-Kushwaha, thanks for the prompt response –

I plan for this chart to be part of a larger component library in which the data and labels provided to the chart will be dynamic. Is providing this width always going to be the job of the consumer, or is there a way that I as a library author can reliably predict the label width given its string?
