### ISSUE TITLE
In the LineChart, the pointer line is only displayed in the positive area (above 0).

### ISSUE THREAD

**Issue by yeongil4764** [Abhinandan-Kushwaha/react-native-gifted-charts#799]
Thank you for providing such a great library.

In the LineChart, the pointer line is only displayed in the positive area (above 0). 
How can I make the pointer line extend into the negative area as well?

![line_chart_pointer_positive](https://github.com/user-attachments/assets/5f31e12a-ab9f-42d6-ab2d-4457508cade8)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @yeongil4764 Thanks for reporting this issue. It has been fixed from versions `1.4.31` onwards.
Please use the latest version of the library.
