### ISSUE TITLE
Can we give intervals and range on yAxis values?

### ISSUE THREAD

**Issue by aabidDevit** [Abhinandan-Kushwaha/react-native-gifted-charts#803]
Here is my Data,
![Screenshot_1724909503](https://github.com/user-attachments/assets/2f87dc2b-5519-4c06-bb19-146bcb86d99b)

I want yAxis values like below:
![Screenshot 2024-08-29 at 11 05 05 AM](https://github.com/user-attachments/assets/dda58911-bd1a-4834-a3ad-b63ae1691a72)

**Comment by Abhinandan-Kushwaha** [comment]
@aabidDevit try the `stepValue` and `noOfSections` props.

**Comment by Abhinandan-Kushwaha** [comment]
@aabidDevit you can use the `xAxisLabelsVerticalShift` prop.
