### ISSUE TITLE
Can we get total length of yAxis values?

### ISSUE THREAD

**Issue by aabidDevit** [Abhinandan-Kushwaha/react-native-gifted-charts#804]
I want length of yAxis values (i.e how many numbers are populated on yAxis) on the basis of this I want to give stepValue
![Screenshot_1724909503](https://github.com/user-attachments/assets/03631faa-78fa-4053-8523-7849613f0fdd)

**Comment by Abhinandan-Kushwaha** [comment]
@aabidDevit On the positive y-axis, 10 values are populated by default, which can be changed using the `noOfSections` prop.
On the negative y-axis, the library decides the number of labels based on the `mostNegativeValue`. However, we can override it using the `noOfSectionsBelowXAxis` prop.
