### ISSUE TITLE
Line Charts: line segments doesn't work with CurveType = {CurveType.QUADRATIC}

### ISSUE THREAD

**Issue by coderBeat** [Abhinandan-Kushwaha/react-native-gifted-charts#807]
I am using **Line Charts** with the following properties
```
<LineChart
              areaChart
              curved
              isAnimated
              lineSegments={lineSegments}
/>
```
by default **CurveType** is **CUBIC**

<img width="1030" alt="Untitled5" src="https://github.com/user-attachments/assets/e647a49b-b77e-47a0-9d44-f7895c438ac7">

```
    const lineSegments = [
      {
        startIndex: dataLength - 2,
        endIndex: dataLength - 1,
        strokeDashArray: [5, 5],
      },
    ];
```

My intention is to make the last element (line joining last two points) in the array as a dotted line.

When I use `CurveType={CurveType.CUBIC}`, it works. But, when I switch to `CurveType = {CurveType.QUADRATIC}`, **line segments** are never shown.

_What could be work around for this problem ?_

**Comment by Abhinandan-Kushwaha** [comment]
Hi @coderBeat Thanks for reporting this issue. It has been fixed from versions `1.4.31` onwards.
Please use the latest version of the library.
