### ISSUE TITLE
Can we acheive yAxis addtional label?

### ISSUE THREAD

**Issue by aabidDevit** [Abhinandan-Kushwaha/react-native-gifted-charts#808]
I want the below additional label ("Quantity") in rotate state on yAxis. Can we acheive this?
![Screenshot 2024-08-30 at 2 39 21 PM](https://github.com/user-attachments/assets/2c96c7cc-1908-45c1-a230-57a457d6da49)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @aabidDevit The library does not support it yet.
But this can be achieved by creating some space at the left of the Bar chart by giving a `marginLeft` in the parent View. Then adding the Label - 'Quantity' using position absolute and rotating it by -90 deg.

Here's an example-
```js
<View style={{marginLeft: 18}}> // shifting the bar chart towards right, creating room for the label at left
  <BarChart
    data={[
      {value: 2, frontColor: '#10A1D0'},
      {value: 1, frontColor: '#8FDBF9'},
    ]}
    barWidth={100}
    maxValue={2}
    showFractionalValues
    stepHeight={25}
  />
  <Text
    style={{
      position: 'absolute',
      top: 150,
      left: -32,
      transform: [{rotate: '-90deg'}],
    }}>
    Quantity
  </Text>
</View>
```
The output of the above code is-

<img width="356" alt="Screenshot 2024-08-31 at 4 36 34 PM" src="https://github.com/user-attachments/assets/ff876060-bef9-4d6d-9206-88a8204bee03">
