### ISSUE TITLE
Pie Chart label text overflowing 

### ISSUE THREAD

**Issue by irfaanf** [Abhinandan-Kushwaha/react-native-gifted-charts#809]
## Problem

I am using the Pie Chart, specifically the donut version. My data includes text with decimal values. Currently the label text overflows beyond the edge of the circular background area, which is a problem:

![image](https://github.com/user-attachments/assets/7e7a6e4f-3ed1-4f58-bb7f-00dacad40fcb)

My data object looks like this:

```
const chartData = useMemo(
    () =>
      accountMembers?.map((member, index) => ({
        value: member.pointsContributionPercentage,
        color: theme.customColors.donutChartSlices[index % 5],
        text: `${member.pointsContributionPercentage}%`
      })),
    [accountMembers]
  );
```
And the Pie Chart looks like this:

```
<PieChart
    donut
    radius={donutRadius}
    innerRadius={donutInnerRadius}
    data={chartData}
    showText
    showTextBackground
    font="Gustan-Bold"
    textSize={12}
    textBackgroundRadius={18}
    textColor={theme.customColors.donutChartLabelText}
/>
```

➡️ Is there currently a way to control the styling or at least the alignment of the text inside the label so that the text does not overflow?

## Proposed solution

If such a control does not exist, I would suggest adding one of the following features to the `<PieChart />` component:

- A prop called `textStyling` that allows for configuring the style of the label text:
  `<PieChart textStyling={{ textAlign: 'center' }} />`
  
- A prop called `labelTextAlign` that allows for configuring the alignment of the label text:
  `<PieChart labelTextAlign='center' />`

- A field called `textAlign` inside the data object that allows for configuring the alignment of the label text:
```
const pieData = [
        {value: 54, color: '#177AD5', text: '54%', textAlign: 'center'},
        {value: 40, color: '#79D2DE', text: '30%', textAlign: 'center'},
        {value: 20, color: '#ED6665', text: '26%', textAlign: 'center'},
    ];
```

Note that I am aware of the existing `shiftTextX` prop. However, that moves the entire label area instead of just the text. Also, due to business rules I am unable to omit the decimal value from the text.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @irfaanf Thanks for the suggestion. The text we are rendering as labels is Svg Text, so it's hard to add the align property to them.

But your problem can be solved by shifting the text background by adding the `shiftTextBackgroundX` in the data items.
