### ISSUE TITLE
Automatically scroll to right or start from right side of the chart

### ISSUE THREAD

**Issue by dogancancelik12** [Abhinandan-Kushwaha/react-native-gifted-charts#81]
Hi, 

For example I'm using monthly data to show, and origin at x axis my data starts from 30 days ago and continues to today through right side. User need to scroll right to see his/her most recent data. 

So, can you please provide a prop like automatically start from right or automatically scroll to right to user sees his most recent data at first. 

Thank you!

**Comment by Abhinandan-Kushwaha** [comment]
Hey @dogancancelik12 👋
Thanks for pointing out the issue. Now the feature to automatically scroll to the last bar (rightmost side) is added in version `1.0.2` 🎉

Just pass the prop `scrollToEnd` to achieve this.

The automatic scroll is visible when the chart loads. To scroll to the last element without showing the scroll animation, pass the prop `scrollAnimation={false}`.

Hope it helps.🤗

**Comment by dogancancelik12** [comment]
Thank you so much, this is very important improvement for us. Really amazing library!🤩

**Comment by SparkleFaerieCoder** [comment]
Hi, I was looking to implement something similar with the Line Chart. As of right now, I can only see the `scrollToEnd` prop working for Bar Chart.
