### ISSUE TITLE
Issue - OnPress is not working in pie chart

### ISSUE THREAD

**Issue by PrajotDexTech** [Abhinandan-Kushwaha/react-native-gifted-charts#812]
<PieChart
            data={pieData}
            donut={true}
            radius={110}
            innerRadius={80}
            innerCircleColor="#312E42"
            innerCircleBorderWidth={1}
            innerCircleBorderColor={"#000"}
            onPress={(index) => handlePress(index)}/>

in above for me onPress is not working

**Comment by Abhinandan-Kushwaha** [comment]
Hi @PrajotDexTech 
This has been fixed from versions `1.4.39` onwards. 🎉

Please use the latest version of the library.
