### ISSUE TITLE
Image Capture for charts

### ISSUE THREAD

**Issue by vijaydiyyala842** [Abhinandan-Kushwaha/react-native-gifted-charts#816]
Hi @Abhinandan-Kushwaha , I am curios to know can we capture full view Image of the bar chart. Because taking screenshot doesn't help as it take a part of the chart not full view.

**Comment by ak-spotter** [comment]
@vijaydiyyala842 [react-native-view-shot](https://github.com/gre/react-native-view-shot) might be helpful.

**Comment by vijaydiyyala842** [comment]
But it is not taking the entire bar chart image when bar chart exceed the screen view.

**Comment by Abhinandan-Kushwaha** [comment]
Can you please share your code @vijaydiyyala842

**Comment by vijaydiyyala842** [comment]
Even if use scrollref In bar chart, then the Y- axis labels are missing.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @vijaydiyyala842 You need to give width to your `<View>` using -
```js
<View style={{width: <enough_width_for_entire_chart>}}>
```
 and then wrap your above code in `<ScrollView style={{flex: 1}}>`.

See https://github.com/gre/react-native-view-shot/issues/274#issuecomment-593094893
