### ISSUE TITLE
Stop interpolating after the last not null datapoint

### ISSUE THREAD

**Issue by dannybit** [Abhinandan-Kushwaha/react-native-gifted-charts#821]
### Description

I am working on a graph to display user weights for each month. In my current implementation, I set the values for each month to null initially and then populate them with the user’s logged weights. However, I’m encountering an issue where the graph continues to interpolate values beyond the last non-null data point.

Here is a screenshot of the issue:
<img width="400" alt="Screenshot 2024-09-07 at 3 13 23 PM" src="https://github.com/user-attachments/assets/21d68fc2-8405-4a95-b6f2-5e810541cc26">

Is there a way to prevent the graph from interpolating values after the last not-null datapoint?

I don't want the graph to stop at the last datapoint and I would like to display the labels for the entire month, even if we are still at the beginning of the month.

Thank you.

### Steps to reproduce

1. Create a list of datapoints with null values appended at the end.
2. Create LineChart with interpolateMissingValues set to true
3. Line will keep interpolating after the last datapoint

### version of react-native-gifted-charts

1.4.10

### React Native version

0.74.3

### Platforms

iOS

### Workflow

Expo Go

**Comment by Abhinandan-Kushwaha** [comment]
Hi @dannybit Did you try `interpolateMissingValues = {false}` ?

**Comment by dannybit** [comment]
Yes, it works but I still want the other values before the last value to interpolate. 

I think this is what causing the issue
"2. If we don't have any numeric values ahead, but we have numeric values in the previous section, we find the slope between the last two numeric values in the previous section and compute the remaining values."

Is there a way to disable this behavior while still interpolating the other values?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @dannybit Thanks for requesting this feature. It is now available from versions `1.4.34` onwards.

I have added a new prop named `extrapolateMissingValues` to enable/disable the extrapolation of nullish values at the start and end of the chart. The default value of `extrapolateMissingValues` is true.  You can set it to false to stop extrapolation.

Please use the latest version of the library.

**Comment by dannybit** [comment]
Amazing!! Thank you for implementing so quickly. I just tested it and it works perfectly.

**Comment by dannybit** [comment]
Hi Abhinandan, thank you again for adding the new field. However, I'm still encountering an issue with the yAxis labels. Even though the extrapolated line is no longer visible, it seems to still be affecting the yAxis.

As you can see from this screenshot, the line after the last data point is no longer being rendered (I believe it's now set to transparent), but it's still causing the yAxis labels to extend below the yAxisOffset, which I've set to 150.8 in this case

<img width="379" alt="Screenshot 2024-09-14 at 12 23 13 PM" src="https://github.com/user-attachments/assets/78b5486c-6062-4962-8ae4-9370094852d1">

Ideally, the graph shouldn't display the labels 147 and 147, as both are being rendered below the xAxis.

Anything that I can do to prevent this issue?

**Comment by Abhinandan-Kushwaha** [comment]
@dannybit to avoid negative y-axis you can set `noOfSectionsBelowXAxis={0}`

**Comment by dannybit** [comment]
great thanks, it fixed the issue.

**Comment by Rajichansek** [comment]
<img width="272" height="608" alt="Image" src="https://github.com/user-attachments/assets/27ea063b-aaea-484b-9f9c-a0b6d27bc4a6" />

Api response returns null values for all based on filter in that case i just need to simply show x-axis along with its label .I can easily achive this in bar chart but in area and line chart i am only able to hide data points but the line is still showing

**Comment by Rajichansek** [comment]
@Abhinandan-Kushwaha Can you please help to fix this issue

**Comment by Abhinandan-Kushwaha** [comment]
@Rajichansek Try using `overflowBottom={-2}`
