### ISSUE TITLE
Support for Y-Axis labels on right side?

### ISSUE THREAD

**Issue by SparkleFaerieCoder** [Abhinandan-Kushwaha/react-native-gifted-charts#83]
Hi, 

I'm interested in using this package but have a specific requirement for something I'm trying to implement. Is it possible to set up the layout so the Y-Axis labels are on the right side of the chart, similar to this:

![5993a5c3-a185-414c-ab38-56d37c2b38f0](https://user-images.githubusercontent.com/19397130/152859495-e1ec7b36-2891-4622-b4fd-97b6fa6e8eb0.png)

Thanks!

**Comment by Abhinandan-Kushwaha** [comment]
Hi @SparkleFaerieCoder 👋
Thanks for requesting this feature. The feature is now available in version `1.0.3`🎉

You can now add the prop `yAxisSide = 'right'` to render the y axis labels on the right side.

If you are setting yAxisSide to 'right', make sure to specify the width of the chart, using the `width` prop.
Hope it helps🤗

**Comment by rexin1995** [comment]
transform:
              i18n.language == 'ar'
                ? [{rotateY: '-180deg'}]
                : [{rotateY: '0deg'}],

yAxisTextStyle={{
                color: 'black',
                textAlign: 'center',  
                fontSize: 14,
                transform:
                  i18n.language == 'ar'
                    ? [{rotateY: '-180deg'}]
                    : [{rotateY: '0deg'}],
              }}
