### ISSUE TITLE
(PieChart) onPress event is not returning data properly

### ISSUE THREAD

**Issue by aabidDevit** [Abhinandan-Kushwaha/react-native-gifted-charts#832]
### Description

When I tap on small area than its data is coming wrong (Expected value is 'Andhra Pradesh' , Getting values is 'Delhi'. (refer video duration 0 - 10 secs)

Also it changes its value when click on same area multiple times.(refer video duration 0.14 secs)
Please refer to video

My Json I am using in PieChart
[PieChartData.json](https://github.com/user-attachments/files/16993097/PieChartData.json)

https://github.com/user-attachments/assets/3111ea4a-2aa4-483a-ae90-b35810727a6d

### Steps to reproduce

- Render pie chart with multiple values.
- Click on same area multiple times (we will get different values on different taps)
- Click on small area (we will not get actual value of that area)

### version of react-native-gifted-charts

^1.4.29

### React Native version

0.74.3

### Platforms

Android

### Workflow

React Native

**Comment by Abhinandan-Kushwaha** [comment]
Hi @aabidDevit 👋
This has been fixed from versions `1.4.39` onwards. 🎉

Please use the latest version of the library.
