### ISSUE TITLE
Animation is not working anymore

### ISSUE THREAD

**Issue by CristianSereaVSP** [Abhinandan-Kushwaha/react-native-gifted-charts#833]
### Description

Hi, I am started using this awesome library in the beginning of the August using the 1.4.29 version. Yesterday I've updated the library to the latest version that was 1.4.34 and the animation stoped working. I am not when this bug has been introduced, in which version, but the chart line is not animating anymore.

### Steps to reproduce

1. v1.4.29 - animation is working
2. v1.4.34 - animation is not working

### version of react-native-gifted-charts

1.4.34

### React Native version

0.73.3

### Platforms

Android, iOS

### Workflow

React Native

**Comment by Abhinandan-Kushwaha** [comment]
Thanks for reporting this issue @CristianSereaVSP 
I will release a new version with the fix today

**Comment by Abhinandan-Kushwaha** [comment]
Hi @CristianSereaVSP This has been fixed from versions `1.4.37` onwards. Please use the latest version of the library.
