### ISSUE TITLE
X-Axis alignmetn when isAnimated={true} & extra space at the bottom of the graph when using xAxisLabelsVerticalShift

### ISSUE THREAD

**Issue by sandeep-synclovis** [Abhinandan-Kushwaha/react-native-gifted-charts#842]
### Description

Hi,

After updating my react-native-gifted-charts library to 1.4.40 x-axis alignment issue was fixed which I reported earlier but now I am facing 2 different issues.

1. Now when I set isAnimated={true} x-axis again started behaving how it was in the previous version, please refer to the images.

When isAnimtated={false} or not set
<img width="266" alt="Screenshot 2024-09-17 at 11 16 52 AM" src="https://github.com/user-attachments/assets/f4d7ce95-7ead-462e-bc78-6e6fb5c2ca55">

When isAnimated={true}
<img width="265" alt="Screenshot 2024-09-17 at 11 17 43 AM" src="https://github.com/user-attachments/assets/953f8f78-6545-4cce-bd27-28330c6a6a1b">

In the above image, you can see the alignment of **Dec 24**

2. After adding xAxisLabelsVerticalShift it creates extra space at the bottom of the graph like the below-shared image, Please let me know how we can get rid of that space.

<img width="266" alt="Screenshot 2024-09-17 at 11 20 29 AM" src="https://github.com/user-attachments/assets/5c69db57-ef8b-4d2d-8ea4-b5800060684e">

### Steps to reproduce

**For Issue 1**

Step 1. Create a graph with a negative value.
Step 2. Set sutoShiftLevels to false.
Step 3. Add xAxisLabelsVerticalShift
Step 4. Set isAnimated={true}

**For Issue 2**

Step 1. Create a graph with a negative value.
Step 2. Set sutoShiftLevels to false.
Step 3. Add xAxisLabelsVerticalShift
Step 4. Now you can see extra space at the bottom of the graph

### version of react-native-gifted-charts

1.4.40

### React Native version

0.75.3

### Platforms

iOS

### Workflow

React Native

**Comment by sandeep-synclovis** [comment]
Hi,

To remove extra space at the bottom of the graph when using xAxisLabelsVerticalShift. I made one change in the library.

In: /react-native-gifted-charts/dist/Components/BarAndLineChartsWrapper/index.js line number: 40

I made the change in marginBottom

  `  marginBottom: xAxisLabelsVerticalShift ? (xAxisLabelsHeight !== null && xAxisLabelsHeight !== void 0 ? xAxisLabelsHeight : xAxisTextNumberOfLines * 18) - 160 : 
            (xAxisLabelsHeight !== null && xAxisLabelsHeight !== void 0 ? xAxisLabelsHeight : xAxisTextNumberOfLines * 18) - 55
       `
       
       I made the above changes as per my requirement, but it should be dynamic based on the value of xAxisLabelsVerticalShift or the user should get the option to set marginBottom of the graph.

**Comment by Abhinandan-Kushwaha** [comment]
Fixed in version `1.4.41`
Thanks for reprting @sandeep-synclovis

**Comment by sandeep-synclovis** [comment]
Hi, still if I use isAnimated={true} x-axis is showing on top of the bar instead of the bottom of the bar for negative values. Please fix this. This happens only if I use  isAnimated={true}.
