### ISSUE TITLE
How to move xAxisLabel upwards in Horizontal bar chart?

### ISSUE THREAD

**Issue by aabidDevit** [Abhinandan-Kushwaha/react-native-gifted-charts#843]
### Description

In Horizontal bar chart,
How can we give xAxisLabelContainerStyle values? as we don't have such property like yAxisLabels. Also Chart is starting after some space on top. Please refer SS.
![Screenshot_1726552553](https://github.com/user-attachments/assets/e177c441-375a-4175-a3aa-2345e503d8e6)

### Steps to reproduce

Add values in Bar chart
Enable horizontal property

### version of react-native-gifted-charts

1.4.40

### React Native version

0.74.3

### Platforms

Android, iOS

### Workflow

React Native

**Comment by Abhinandan-Kushwaha** [comment]
Hi @aabidDevit 👋
To remove the space on top, you can set `initialSpacing = {0}`

To adjust the labels' positions, please take a look at https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/194
