### ISSUE TITLE
Dont see line in the chart on android device if I use hideDataPoints

### ISSUE THREAD

**Issue by SpiritMan77** [Abhinandan-Kushwaha/react-native-gifted-charts#844]
### Description

With hideDataPoints on in android line i nchart is not visible.

### Steps to reproduce

1. Implement line chart
2. Add hideDataPoints

### version of react-native-gifted-charts

1.4.10

### React Native version

0.74.0

### Platforms

Android

### Workflow

None

**Comment by Abhinandan-Kushwaha** [comment]
@SpiritMan77 please use the latest version of the library
