### ISSUE TITLE
BarChart erros when empty array passed in for data

### ISSUE THREAD

**Issue by aminosman** [Abhinandan-Kushwaha/react-native-gifted-charts#851]
### Description

Code
`<BarChart data={[]}/>`

Error
```
 ERROR  Invariant Violation: [1165,"RCTView",711,{"position":"absolute","height":"<<NaN>>","bottom":60,"paddingLeft":20,"width":40,"flexDirection":"row"}] is not usable as a native method argument
```

### Steps to reproduce

`<BarChart data={[]}/>`

### version of react-native-gifted-charts

1.4.41

### React Native version

0.74.5

### Platforms

iOS

### Workflow

None

**Comment by Abhinandan-Kushwaha** [comment]
Hi @aminosman 
Thanks for reporting this issue. It has been fixed from versions `1.4.42` onwards. 🎉

Please use the latest version of the library.
