### ISSUE TITLE
animateOnDataChange does not work when yAxisOffset is set

### ISSUE THREAD

**Issue by csmartinsfct** [Abhinandan-Kushwaha/react-native-gifted-charts#853]
### Description

`animateOnDataChange` does not work when `yAxisOffset` is set.

It works fine when `yAxisOffset` is not set but otherwise it does not work.

### Steps to reproduce

You can reproduce using this code:

```
 <LineChart
    width={320}
    height={90}
    data={data}
    isAnimated
    thickness={3}
    adjustToWidth
    yAxisOffset={min}
    hideYAxisText
    animateOnDataChange
    hideDataPoints
    backgroundColor="transparent"
    rulesColor="transparent"
    rulesType="transparent"
    yAxisColor="transparent"
    xAxisColor="transparent"
    color="blue"
    trimYAxisAtTop
/>
```

This only animates on enter, if you update the `data` it does not animate between old and new data set. However, it does animate between old and new data set if you remove `yAxisOffset`. This happens when `yAxisOffset` > 0.

I would expect it to still be able to animate between the data sets, even with `yAxisOffset` defined. For now, I'm passing in a key so that it animates from scratch for every new data set, which isn't too bad but it would be preferred if it could animate the line like it does when we set `animateOnDataChange`.

### version of react-native-gifted-charts

1.4.41

### React Native version

0.73.4

### Platforms

iOS

### Workflow

React Native

**Comment by Abhinandan-Kushwaha** [comment]
Hi @csmartinsfct 
Thanks for reporting this issue. It has been fixed from versions `1.4.42` onwards. 🎉

Please use the latest version of the library.
