### ISSUE TITLE
scrollAnimation does not affect scrollToIndex

### ISSUE THREAD

**Issue by dannybit** [Abhinandan-Kushwaha/react-native-gifted-charts#859]
### Description

Setting `scrollAnimation` to false in a LineChart does not disable the initial animation for `scrollToIndex`. Reviewing the code, it looks like scrollAnimation is only applied for `scrollToEnd` but not for `scrollToIndex`.
https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/8f7d6065e54653b5f1c671567c97e2748ba7a366/src/Components/BarAndLineChartsWrapper/index.tsx#L192

### Steps to reproduce

1. Set `scrollAnimation` to false and pass an index to `scrollToIndex`
2. Load the chart
3. Chart navigates to the index with the animation enabled. Expected behavior is the for the chart to be disabled.

### version of react-native-gifted-charts

1.4.34

### React Native version

0.74.3

### Platforms

Android, iOS

### Workflow

None

**Comment by Abhinandan-Kushwaha** [comment]
Thanks for your PR @dannybit 
Your changes are available from versions `1.4.44` onwards.
