### ISSUE TITLE
span horizontal rule lines to the end of the container

### ISSUE THREAD

**Issue by jagajastic** [Abhinandan-Kushwaha/react-native-gifted-charts#86]
Make rule lines and the horizontal x-axis line span to the end of the container irrespective of less amount of data.

The below Image show the current problems where the horizontal rule line stop just after August. I want it to continue to the end of the container
<img width="344" alt="Screenshot 2022-02-17 at 10 48 39 PM" src="https://user-images.githubusercontent.com/28712864/154614065-8bb0415e-df94-4a59-85c3-036121bb3a30.png">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @jagajastic 👋
Can you try using the `width` prop to adjust the width of the chart?

For example, if you want the horizontal rules to continue to the end of the container (and say the container width is 200), then the code should look like this-
```js
  <BarChart
    data={data}
    width={200}/>
 ```

**Comment by jagajastic** [comment]
Thank you so much. you are doing a great job
