### ISSUE TITLE
[BarChart]: Numbers bigger than 4 zeros are truncated

### ISSUE THREAD

**Issue by PedroW21** [Abhinandan-Kushwaha/react-native-gifted-charts#864]
### Description

I’m having a problem using `<BarChart />`, I noticed that when trying to use numbers that have more than 3 zeros, they are truncated and remain at 3 zeros (on the y axis of the chart, where the labels are placed).

The photo exemplifying follows below.

# Chart
![image](https://github.com/user-attachments/assets/fef36a49-e59c-434e-968d-115b3f02de93)

# Data
```js
export const mockedSmallNumbersData = [
    { label: "Janeiro", value: 1239 },
    { label: "Fevereiro", value: 1046 },
    { label: "Março", value: 2041 },
    { label: "Abril", value: 2068 },
    { label: "Maio", value: 1830 },
    { label: "Junho", value: 0 },
];


export const mockedRealWorldNumbersData = [
    { label: "Janeiro", value: 1238964 },
    { label: "Fevereiro", value: 1043650.8 },
    { label: "Março", value: 2042172.91 },
    { label: "Abril", value: 2068089.3 },
    { label: "Maio", value: 1830461.7 },
    { label: "Junho", value: 1 },
];
```

### Steps to reproduce

- Access the provided Expo Snack;

### Snack or a link to a repository

https://snack.expo.dev/@pedrow21/rngc?platform=android

### version of react-native-gifted-charts

1.4.29

### React Native version

0.74.5

### Platforms

Android

### Workflow

Expo Dev Client

**Comment by Abhinandan-Kushwaha** [comment]
Hi @PedroW21 You can use the `yAxisLabelWidth` prop to make the Y-axis labels container wider.

**Comment by PedroW21** [comment]
Thank you!

Sorry to bother.
