### ISSUE TITLE
Line Chart Animation is not working

### ISSUE THREAD

**Issue by wacci6** [Abhinandan-Kushwaha/react-native-gifted-charts#875]
### Description

here is my code.

```tsx

const apidata = [
  { text: 'jan', value: 13000 },
  { text: 'feb', value: 16500 },
  { text: 'mar', value: 14200 },
  { text: 'apr', value: 20000 },
  { text: 'may', value: 14000 },
  { text: 'jun', value: 12000 },
  { text: 'jul', value: 30000 },
  { text: 'aug', value: 21000 },
  { text: 'sep', value: 19000 },
  { text: 'oct', value: 9000 },
  { text: 'nov', value: 12000 },
  { text: 'dec', value: 14000 },
];


const App = () => {
  const {width} = useWindowDimensions()

  return (
    <LineChart
      isAnimated
      curved
      curvature={0.12}
      height={150}
      width={width - 75}
      noOfSections={3}
      animationDuration={500}
      data={apidata}
      initialSpacing={15}
      endSpacing={5}
      thickness={2.5}
      startOpacity={1}
      endOpacity={0}
      xAxisLabelTexts={apidata.map(d => d.text)}
      yAxisLabelWidth={40}
      formatYLabel={(value) => ((Math.round(+value / 100) * 100)).toLocaleString()}
      areaChart
      hideDataPoints
    />
  )
}
```

I tried the sample code provided on the following page, but the animation didn't work:
https://gifted-charts.web.app/areachart/#animated

The animation for the BarChart worked well.

### Steps to reproduce

1. Write the code.
2. Load the page.
3. The chart renders without the animation functioning.

### version of react-native-gifted-charts

1.4.44

### React Native version

0.73.8

### Platforms

iOS

### Workflow

React Native

**Comment by Abhinandan-Kushwaha** [comment]
Hi @wacci6 👋
I tested your code and found that the animation for Line charts is working perfectly fine on both Android and iOS.
Maybe the `animationDuration` you have set to `500` is making the animation too fast. Try setting it to `1000` or `1200`
