### ISSUE TITLE
Do I need to call useEffect?

### ISSUE THREAD

**Issue by OshedheMunasinghe** [Abhinandan-Kushwaha/react-native-gifted-charts#88]
Hi,
Thank you so much for this API. I really love to read your documents and examples! First-time me having stressless!! Bravo!! 

I have **two** questions!

1. Is it in Typescript? I see from index**.tsx** , it would be awesome if you update npm site that it can "speak" in typescript :) You know that small icon TS.

2. 
I took an example from a graph with days
When I want to change the value from 250 to 500 like this
`   const barData = [
        {value: 250, label: 'M'}, // I WANT TO CHANGE E.G. 500
     ...
`
when I press save the phone react-native doesn't show up, instead, I need to refresh the app. I wonder if I need to call **useEffect**? 
But I can see in index.tsx that you have already called useEffect? 
I am a bit confused , plz help :)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @OshedheMunasinghe 👋
Glad to know that you loved the package.
Thanks for the suggestion to add the **ts** badge on the npm page. I will try adding it in the next release.

The change in the value is not getting reflected in the chart. Thanks for pointing out the issue.
However, it works fine with **animated** charts.

While I fix it, you can make your chart animated by adding `isAnimated={true}` to the `<BarChart/>` component. 
Hope it helps.🤗

**Comment by OshedheMunasinghe** [comment]
**Whoa!!!** 🤯
`isAnimated={true}` really did a thing! Thank you so much! :) 

When I run react-native I saw cool animation on the graph!
and when I changed the value to 1200 .. really impressive!
Nice job @Abhinandan-Kushwaha 

_Phew_! I don't need to call useEffect!

**Comment by Abhinandan-Kushwaha** [comment]
This issue is now fixed even for un-animated charts in version `1.0.5`🎉
