### ISSUE TITLE
verticalLinesHeight props missing

### ISSUE THREAD

**Issue by McFly78** [Abhinandan-Kushwaha/react-native-gifted-charts#883]
### Description

Hello,

For LineChart graph the prop verticalLinesHeight does not seem to exist in the code of the component.
Has this props been removed ?
Many thanks

### Steps to reproduce

None

### version of react-native-gifted-charts

1.4.46

### React Native version

0.74.4

### Platforms

iOS

### Workflow

None

**Comment by Abhinandan-Kushwaha** [comment]
@McFly78 `verticalLinesHeight` prop exists. Please check again.
