### ISSUE TITLE
overflowTop parameter behaviour & verticalLinesHeight

### ISSUE THREAD

**Issue by McFly78** [Abhinandan-Kushwaha/react-native-gifted-charts#884]
### Description

I'm working on a LineChart graph and I'm seeing some strange behaviour when I use the overflowTop parameter.
As you can see, if the value of this parameter is other than 0, the height of the vertical lines displayed using the parameter verticalLinesHeight is much higher than the area of the graph.

There is no issue for vertical lines displayed using the global parameter showVerticalLine**s**.
However, as I would like to only display some verticals lines I can not use the global parameter showVerticalLines.

So I've tried using the verticalLinesHeight parameter to limit the height of the vertical lines, but this parameter doesn't seem to work for the vertical lines displayed using the showVerticalLine parameter. 
The verticalLinesHeight parameter only seems to have an effect for vertical lines displayed with the global parameter showVerticalLines.

Is there something I am missing ?

With an overflowTop parameter other than 0 and whatever the value
<img width="305" alt="image" src="https://github.com/user-attachments/assets/3053299b-0607-446e-9f71-883dcd920c11">

Without overflowTop parameter
<img width="307" alt="image" src="https://github.com/user-attachments/assets/74c8ab10-a0b2-4582-914e-e6b19f013d53">

As a temporary workaround, in the renderSpecificVerticalLines function I added 30 to the y2 value of the SVG Line component -> y2= -xAxisThickness +30

Many thanks for your help

### Steps to reproduce

```
<View style={{backgroundColor: '#1A3461', paddingTop:60}}>
    <LineChart
        data={
          [10, 10, 10, 10, 10, 10, 10, 50].map((v, index) => {
          
            const showVerticalLine= index%2 !=0 // To show only half of verticals lines
            
            return {
              value: v,
              showVerticalLine: showVerticalLine ? true : false,
              verticalLineColor: "red",
              verticalLineThickness:2
            }
        })
        }
        
        overflowTop={1}
  
        // Vertical lines configuration
        verticalLinesColor= "white"
        //verticalLinesHeight={180}
        showVerticalLines={true}
        
        // graph configuration
        height={180}
        spacing={40}
        hideRules
        hideYAxisText
        yAxisColor="white"
        xAxisColor="white"
        color="#0BA5A4"
        initialSpacing={0}
        backgroundColor='#1A3461'
    />
</View>
```

### version of react-native-gifted-charts

1.4.46

### React Native version

0.74.4

### Platforms

iOS

### Workflow

None

**Comment by Abhinandan-Kushwaha** [comment]
Hi @McFly78 Thanks for pointing out this issue.
It has been fixed from versions `1.4.48` onwards. Please use the latest version of the library.
