### ISSUE TITLE
Feature request: Pie chart animation

### ISSUE THREAD

**Issue by jensonjohn001** [Abhinandan-Kushwaha/react-native-gifted-charts#89]
Is it possible to animate Pie chart?
Also, can we align the value text labels to the center?

```
 <PieChart
  strokeColor="white"
  strokeWidth={2}
  donut
  data={pieData}
  showText
  extSize={16}
  />
```
  
![IMG_0B513A6FAFAC-1](https://user-images.githubusercontent.com/35399770/154969167-89379546-3685-4e32-a1bb-7010ece2c119.jpeg)

https://user-images.githubusercontent.com/35399770/154970663-dcdeac51-971c-43ee-b75c-d9ba91f9f186.mov

**Comment by Abhinandan-Kushwaha** [comment]
Hi @jensonjohn001 👋
Animations in Pie Chart are not yet available. Will work on it sometime later.

For aligning the text labels, you can use the `shiftTextX` and `shiftTextY` props with the data items.
For example-
```js
let data = [
  {value: 10, color: 'pink', shiftTextX: -10, shiftTextY: -6},
  {value: 39, color: 'blue', shiftTextX: -10, shiftTextY: -18},
  ...
  ];
```
Hope it helps.🤗
