### ISSUE TITLE
x Axis label color 

### ISSUE THREAD

**Issue by OshedheMunasinghe** [Abhinandan-Kushwaha/react-native-gifted-charts#90]
Hi
I have found out that my x-axis where it says days is colour white and I want it to change to another colour. 
I tried to call label color - didn't work
I tried from BarChart all colour props and it didn't work.

I read almost the whole document.. maybe I have missed it?

**Comment by OshedheMunasinghe** [comment]
I have found out ` yAxisTextStyle` but not xAxisTextStyle

**Comment by Abhinandan-Kushwaha** [comment]
Hi @OshedheMunasinghe 
You can use the `labelTextStyle` property with the data objects.

For example-
```js
const barData = [
  {value: 15, labelTextStyle:{color:'red'}},
  {value: 30, labelTextStyle:{color:'yellow'}},
  {value: 26, labelTextStyle:{color:'blue'}},
  {value: 40, labelTextStyle:{color:'green'}}
];
```

You can even give your own custom X-axis label component using the `labelComponent` property with the data objects.

In addition to the [documentation](https://gifted-charts.web.app/),  we have a complete list of props [here](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/docs.md).
Hope it helps. 🤗
