### ISSUE TITLE
renderTooltip not Working

### ISSUE THREAD

**Issue by atlas-itrc** [Abhinandan-Kushwaha/react-native-gifted-charts#908]
### Description

renderTooltip is not working as expected even though i have added the required prop:

`
<BarChart
              data={barData}
              barWidth={20}
              yAxisTextStyle={{ color: 'gray' }}
              noOfSections={4}
              maxValue={400}
              width={500} // Adjust width for landscape view
              labelWidth={80}
              isAnimated
              renderTooltip={(item, index) => {
                console.log(item);
                return (
                  <View
                    style={
                      {
                        // marginBottom: 20,
                        // // marginLeft: -6,
                        // backgroundColor: '#ffcefe',
                        // // paddingHorizontal: 6,
                        // paddingVertical: 4,
                        // // borderRadius: 4,
                      }
                    }>
                    <Text>{item.value}</Text>
                  </View>
                );
              }}
            />
            
            the console is showing the log for the item, but i am expecting the item value to show on the top of the bar.
`

### Steps to reproduce

I have tried using the same exact example from the documentation. but it is still not working.

### Snack or a link to a repository

https://snack.expo.dev/3ouoGiXPdTpeRR7GAjx_R

### version of react-native-gifted-charts

1.4.47

### React Native version

0.74.5

### Platforms

Android

### Workflow

Expo Dev Client

**Comment by onyx-flame** [comment]
The problem is caused by default tooltip offset configured [here](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/v1.4.47/src/Components/BarSpecificComponents/tooltip.tsx#L40)

You can compensate it by setting `top: 60` or `bottom: -60` to render your tooltip right above the bar. Here is a link to snack with a fix: [click!](https://snack.expo.dev/G56hijucX4bFIcwk2auXY)

**Comment by atlas-itrc** [comment]
this solved it, thank you
