### ISSUE TITLE
Is it possible to add customized tooltip for multi-line charts?

### ISSUE THREAD

**Issue by vijaydiyyala842** [Abhinandan-Kushwaha/react-native-gifted-charts#910]
### Description

I am using multi line charts for my project, Below is the UX reference for customised tooltip
![Screenshot 2024-11-18 at 10 58 02 AM](https://github.com/user-attachments/assets/8197e590-b00b-41a3-af94-7c91b0213453)

### Steps to reproduce

I have also include my code as well.
 <LineChart
                height={300}
                width={300}
                dashGap={0}
                yAxisLabelWidth={40}
                yAxisLabelContainerStyle={{ paddingRight: 5 }}
                yAxisTextStyle={styles.yaxisText}
                xAxisLabelTextStyle={styles.yaxisText}
                xAxisLength={Dimensions.get("screen").width - 80}
                rulesLength={Dimensions.get("screen").width - 80}
                rulesColor={"#E7E7E7"}
                isAnimated
                hideDataPoints
                focusEnabled
                showDataPointLabelOnFocus
                onFocus={(item: any) => console.log(item, "pressed item")}
                spacing={36}
                noOfSections={6}
                dataSet={dataset}
                yAxisThickness={0}
                xAxisColor="#E7E7E7"
              />

### version of react-native-gifted-charts

1.4.46

### React Native version

0.74.5

### Platforms

Android, iOS

### Workflow

None

**Comment by Abhinandan-Kushwaha** [comment]
Yes @vijaydiyyala842 Earlier, `focusEnabled` on multi-line charts focused all the data points at that index together. Now, I have added a prop named `focusTogether` which can be set to false if you want to `focus` one single data point at a time. The default value is true.

Also added a prop named `focusProximity` to set the distance from a data point upto which a press event should result in focusing that data point.

It is available from versions `1.4.48` onwards. Please use the latest version of the library.

**Comment by shubham-cpp** [comment]
@Abhinandan-Kushwaha, can we add the `focusProximity` to `BarChart` as well please

**Comment by shubham-cpp** [comment]
If you check the android's screen time bar chart or IOS's health - steps bar chart, all are doing the same thing.
When the user clicks on the column(i.e proximity) of the bar, its focused.

**Comment by shubham-cpp** [comment]
Hello @Abhinandan-Kushwaha, any update on this?
