### ISSUE TITLE
LineChart - Strip and Points not showing beyond x index 0 for DataSet

### ISSUE THREAD

**Issue by sondreluc** [Abhinandan-Kushwaha/react-native-gifted-charts#911]
### Description

When trying to show a strip and datapoint when pressing a LineChart that uses the `dataSet` property, the points and strip disappears when pressing anything other than the beginning of the graph (x = 0).

I've found what I believe is the cause of the issue, which lies here: https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/20a98cf084b787f6d1beb3a990f51ba4363ec932/src/LineChart/index.tsx#L1362-L1373
Where the active X point is set. The calculation for finding the x value uses the `cumulativeSpacing1` list, which is empty when the component uses `dataSet` instead of `data`, `data2` etc.
I suppose this should be using `cumulativeSpacingForSet` instead? 

### Steps to reproduce

1. Add a LineChart with data passed to `dataSet`
2. Add a `pointerConfig` to enable pointers and strip to appear.
3. See how the  pointers and strip only appear when pressing right in the beginning (left side) of the chart area. 

### version of react-native-gifted-charts

1.4.47

### React Native version

0.75

### Platforms

Android, iOS

### Workflow

React Native

**Comment by adityaranjan006** [comment]
Vertical Strip is not visible after some index point on the data, used using data prop. Circular pointer is visible but the strip is hidden. Do you have any Idea how this could be fixed? 

`pointerConfig={{
                    pointerStripHeight: 200,
                    pointerStripColor: '#454545',
                    pointerStripWidth: 1,
                    pointerColor: '#FFFFFF',
                    radius: 8,
                    pointerLabelWidth: 120,
                    pointerLabelHeight:0,
                    pointerVanishDelay:20000,
                    strokeDashArray:[5,5],
                    pointerStripUptoDataPoint: true,
                    activatePointersOnLongPress: true,
                    autoAdjustPointerLabelPosition: true,
                    persistPointer:true,`
                    
                    
                    
this is the pointerConfig.

**Comment by adityaranjan006** [comment]
@Abhinandan-Kushwaha , poniterConfig is not showing the pointerStrip after certain X data points. I used data prop of the LineGraph using one of the examples shown.
Data object: {
        value: 8,  // PM2.5 level in µg/m³
        date: '07:00 AM',
        label: '07:00 AM',
        labelTextStyle: { color: '#FEFEFE', width: 60, fontSize: 8, fontWeight: "bold" },
    },
    { value: 5, date: '07:05 AM' },
![IMG_20241211_162944](https://github.com/user-attachments/assets/40ff5f5c-68ac-4972-89c3-75bad3a079e4)
![IMG_20241211_162959](https://github.com/user-attachments/assets/fadeb4ea-4235-473c-a105-c1e9f4f78f9c)

**Comment by lucasBruma** [comment]
any updates on this? I'm experiencing the same issue 😅

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sondreluc @lucasBruma @adityaranjan006 @MartinCura 👋
Thanks for pointing out this issue. I have fixed it and now the pointers work fine with dataSet.
It is available from versions `1.4.48` onwards. Please use the latest version of the library.

Thanks @sondreluc for suggesting the fix.
