### ISSUE TITLE
extrapolateMissingValues not working with dataSet

### ISSUE THREAD

**Issue by Xaeryan** [Abhinandan-Kushwaha/react-native-gifted-charts#916]
### Description

When setting extrapolateMissingValues to false and using a dataset, the first and/or last values are extrapolated anyway when null.  Using data/data2/data3/etc instead and extrapolateMissingValues = false works as expected (null first/last values are not extrapolated).

### Steps to reproduce

1a. const dataSet = [{ data: [{},{value: 12},{},{value: 22},{value: 36}] }]; 
1b. const data =             [{},{value: 12},{},{value: 22},{value: 36}];
2. <LineChart 
       dataSet={dataSet} // 1a
       //data2={data}      // 1b
       extrapolateMissingValues={false}
        />
3. Switch between using 1a and 1b to see the difference in how the first line segment is treated.

### version of react-native-gifted-charts

1.4.41

### React Native version

0.73.6

### Platforms

Android, iOS

### Workflow

Expo Dev Client

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Xaeryan Thanks for pointing out this issue.
It has been fixed from versions `1.4.48` onwards. Please use the latest version of the library.
