### ISSUE TITLE
Curved Linechart displays values below the x-axis when there's no negative value 

### ISSUE THREAD

**Issue by jothamc** [Abhinandan-Kushwaha/react-native-gifted-charts#922]
### Description

When I pass in relatively small values, everything seems okay, but when the values are bigger and far apart, the curved version adds a dip before moving up

Also, datapoints are far out of the screen and I don't know how to make sure there's some top padding.

**Without the curved prop**
![IMG_8102](https://github.com/user-attachments/assets/6c6cc053-4422-49d0-98ff-1ef94bc8fe0b)

**With the curved prop**
![IMG_8103](https://github.com/user-attachments/assets/8c885d83-7df4-4961-9aac-94bbc51fcc1f)

![IMG_8102](https://github.com/user-attachments/assets/6c6cc053-4422-49d0-98ff-1ef94bc8fe0b)

PS: I intentionally added a noOfSectionsBelowwXAxis so this can be observed properly. Without it, you can still see that the line drops below the visible view.

Looking forward to any help. Thank you.

### Steps to reproduce

1. Use this line chart: 
```
              <LineChart
                curved
                isAnimated
                data={incomingPaymentTrends}
                data2={outgoingPaymentTrends}
                maxValue={Math.max(
    ...[...outgoingPaymentTrends, ...incomingPaymentTrends].map((i) => i.value)
  )}
                // mostNegativeValue={0}
                noOfSectionsBelowXAxis={1}
                xAxisLabelTexts={ ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]}}
                formatYLabel={formatToAbbreviation} // this can be removed but I'm leaving it so you can see how i use it
                height={400}
                thickness={5}
                spacing={60}
                initialSpacing={20}
                endSpacing={0}
                color1="#4880FF"
                color2="#FF9000"
                textColor1={"white"}
                textColor2={ "white"}
                dataPointsWidth={6}
                focusEnabled
                showTextOnFocus
                showDataPointOnFocus
                dataPointsColor="#fff"
                textShiftY={-2}
                textShiftX={-10}
                textFontSize={13}
                xAxisColor={"white"}
                yAxisColor={"white"}
                xAxisLabelTextStyle={{color: "white"}}
                yAxisTextStyle={{color: "white"}}
              />
```

2. Plug in these values:
```
{"incomingPaymentTrends": [{"dataPointText": "", "value": 0}, {"dataPointText": "", "value": 0}, {"dataPointText": "", "value": 0}, {"dataPointText": "", "value": 0}, {"dataPointText": "", "value": 0}, {"dataPointText": "", "value": 0}, {"dataPointText": "", "value": 0}, {"dataPointText": "", "value": 0}, {"dataPointText": "7.1K", "value": 7058}, {"dataPointText": "38.9K", "value": 38891}, {"dataPointText": "140", "value": 140}, {"dataPointText": "94.3K", "value": 94287}]}
{"outgoingPaymentTrends": [{"dataPointText": "5K", "value": 5020}, {"dataPointText": "48K", "value": 48000}, {"dataPointText": "12M", "value": 12008500}, {"dataPointText": "", "value": 0}, {"dataPointText": "6.8K", "value": 6800}, {"dataPointText": "", "value": 0}, {"dataPointText": "", "value": 0}, {"dataPointText": "", "value": 0}, {"dataPointText": "", "value": 0}, {"dataPointText": "5K", "value": 5000}, {"dataPointText": "44K", "value": 44000}, {"dataPointText": "14.1K", "value": 14100}]}
```

### version of react-native-gifted-charts

1.4.7

### React Native version

0.76.3

### Platforms

Android, iOS

### Workflow

Expo Go

**Comment by jothamc** [comment]
I see that my scenario is the same as [this issue](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/315) and it fixed there by adding 
```curveType={1}```
i.e. (`CurveType.QUADRATIC` which I can't seem to import). Thank you for the great library @Abhinandan-Kushwaha

**Comment by Abhinandan-Kushwaha** [comment]
Hi @shrynshjn `curveType={1}` does not remove the curve, it's just a different algorithm to build the curved path.
See https://www.nan.fyi/svg-paths/bezier-curves and https://www.nan.fyi/svg-paths/cubic-curves
