### ISSUE TITLE
Custom Data Point in wrong position with non-uniform `spacing` on data in LineChart

### ISSUE THREAD

**Issue by thyming** [Abhinandan-Kushwaha/react-native-gifted-charts#923]
### Description

Hi, thanks for the library 🙏 
I believe there's a bug in the placement of customDataPoint components if data is irregularly spaced. The code in question: 
https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/src/LineChart/index.tsx#L733-L734
I believe it ought to use the cumulativeSpacing props that come out of useLineChart to set left/right positioning.

### Steps to reproduce

Create a series where the spacing attributes are different per data point.
Set the customDataPoint component prop.
Observe that the data points are not located correctly. 

### version of react-native-gifted-charts

1.4.47

### React Native version

0.74.2

### Platforms

Android, iOS

### Workflow

Expo Dev Client

**Comment by Abhinandan-Kushwaha** [comment]
Hi @thyming Thanks for pointing out this issue.
It has been fixed from versions `1.4.48` onwards. Please use the latest version of the library.
