### ISSUE TITLE
LineChart 1st data point does not show pointer label if initialSpacing={0}

### ISSUE THREAD

**Issue by pakerwreah** [Abhinandan-Kushwaha/react-native-gifted-charts#925]
### Description

When I set `initialSpacing={0}` to LineChart, every other data point shows my `pointerLabelComponent` just fine, but not the first one.

I'm working around it by adding a `width` to `yAxisLabelContainerStyle` bigger than `yAxisLabelWidth` (to hide the initial spacing), shifting vertical lines, subtracting this offset from the chart width and rules length. It's a nightmare.

I wonder why I can't "hover" the first data point.

My code is now completely poisoned with my workaround, but I can try to clean it up and post it here if necessary.

### Steps to reproduce

1. Create a LineChart with `initialSpacing={0}`
2. Set a custom `pointerLabelComponent`
3. Verify that you are unable to show the component on the 1st data point
4. Remove `initialSpacing` or set a high enough value and see that now everything works fine

### version of react-native-gifted-charts

1.4.47

### React Native version

0.76.5

### Platforms

iOS

### Workflow

Expo Go

**Comment by Abhinandan-Kushwaha** [comment]
Hi @pakerwreah Thanks for reporting this issue. This has been fixed from versions `1.4.49` onwards. 

Please use the latest version of the library.
