### ISSUE TITLE
BarChart lineConfig with strokeDashArray support

### ISSUE THREAD

**Issue by agmo-chichun** [Abhinandan-Kushwaha/react-native-gifted-charts#927]
### Description

I want to have a BarChart combined with a dashed line chart by using showLine prop.
But the lineConfig doesn't have strokeDashArray prop to becomes dash line.
Only supporting solid line.

### Steps to reproduce

1. Create BarChart with showLine = true
2. 

### version of react-native-gifted-charts

1.4.47

### React Native version

0.75.3

### Platforms

Android, iOS

### Workflow

None

**Comment by Abhinandan-Kushwaha** [comment]
Hi @agmo-chichun Thanks for requesting this feature.
I have added the property `strokeDashArray` inside the `lineConfig` object.
It is available from versions `1.4.48` onwards. Please use the latest version of the library.
