### ISSUE TITLE
Rotate label for Bar Chart

### ISSUE THREAD

**Issue by likern** [Abhinandan-Kushwaha/react-native-gifted-charts#93]
Hello 👋🏻 
It would be awesome to have the option to have **rotated labels** (not by `60`, but by `90` / `-90` grad).
I've tried to use `labelTextStyle` / `labelComponent`, but without success.

There is an article on how to do this without shrinking text https://medium.com/@therealmaarten/how-to-layout-rotated-text-in-react-native-6d55b7d71ca5. It works well.

But there is still something that shrinks width of the label itself.
![Screenshot_2022-02-23-22-49-23-037_com breeffy feeve](https://user-images.githubusercontent.com/842306/155396827-0fe7d472-6ea6-415d-8f28-af82d3674604.jpg)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @likern 👋
Thanks for pointing out the issue.
We can achieve such chart labels in the new version- `1.0.5` using the props `labelsExtraHeight`, `labelTextStyle` and `labelWidth`

Here is an example-
```js
const styleObject = {
    marginLeft: -95,
    paddingLeft: 120,
    transform: [{rotate: '90deg'}],
  };
  const data = [
    {
      value: 10,
      label: 'January month',
      labelTextStyle: styleObject,
      labelWidth: 130,
    },
    {
      value: 20,
      label: 'February month',
      labelTextStyle: styleObject,
      labelWidth: 130,
    },
    {
      value: 30,
      label: 'March month',
      labelTextStyle: styleObject,
      labelWidth: 130,
    },
    {
      value: 20,
      label: 'April month',
      labelTextStyle: styleObject,
      labelWidth: 130,
    },
  ]; 
  
return (
  <BarChart
    data={data}
    labelsExtraHeight={60}/>
)
```
The output produced is-

<img width="243" alt="Screenshot 2022-02-24 at 5 29 14 AM" src="https://user-images.githubusercontent.com/20596944/155431126-eacd37d4-0e19-42b2-81e0-fa7b1931787e.png">

Hope it helps🤗

**Comment by ansh029** [comment]
![BarChart](https://user-images.githubusercontent.com/26456500/161480243-c3126eda-38d9-4922-a4a3-28b2154309fe.jpeg)

Hi how to rotate labels like this with small bar width.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ansh029 👋
There is a workaround to achieve labels like this. We can apply custom style to the labels by passing the `labelTextStyle` property in the data array.

Here's the style object-
```js
const styleObject = {
    textAlign: 'left',
    transform: [{rotate: '-90deg'}],
    marginLeft: -120,
    paddingLeft: 100,
  };
```
Let's say you want a chart like this-

<img width="366" alt="Screenshot 2023-07-23 at 3 00 07 PM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/a33eb87f-110c-4eaf-a61f-0c4986fa50c4">

The complete code for the above chart will be-
```js
const App = () => {
  const styleObject = {
    textAlign: 'left',
    transform: [{rotate: '-90deg'}],
    marginLeft: -120,
    paddingLeft: 100,
  };
  const data = [
    {
      value: 1050,
      label: 'Feb-22',
      labelTextStyle: styleObject,
      labelWidth: 130,
    },
    {
      value: 750,
      label: 'Jan-22',
      labelTextStyle: styleObject,
      labelWidth: 130,
    },
    {
      value: 1050,
      label: 'Dec-21',
      labelTextStyle: styleObject,
      labelWidth: 130,
    },
    {
      value: 500,
      label: 'Nov-21',
      labelTextStyle: styleObject,
      labelWidth: 130,
    },
    {
      value: 950,
      label: 'Oct-21',
      labelTextStyle: styleObject,
      labelWidth: 130,
    },
    {
      value: 800,
      label: 'Sep-21',
      labelTextStyle: styleObject,
      labelWidth: 130,
    },
    {
      value: 900,
      label: 'Aug-21',
      labelTextStyle: styleObject,
      labelWidth: 130,
    },
    {
      value: 200,
      label: 'Jul-21',
      labelTextStyle: styleObject,
      labelWidth: 130,
    },
    {
      value: 1050,
      label: 'Jun-21',
      labelTextStyle: styleObject,
      labelWidth: 130,
    },
  ];

  return (
    <BarChart
      data={data}
      height={400}
      barWidth={10}
      spacing={25}
      frontColor={'red'}
      maxValue={1200}
      stepValue={200}
      noOfSections={6}
      labelsExtraHeight={70}
    />
  );
}
```
