### ISSUE TITLE
hidePointer doesn't work

### ISSUE THREAD

**Issue by benbenwsh** [Abhinandan-Kushwaha/react-native-gifted-charts#932]
### Description

When I set hidePointer: true in a lineDataItem, and then I press on that data point, the pointer (the hover over that point with some description) still appears

### Steps to reproduce

1. Set hidePointer: true in one of the data points
2. Write a pointerConfig on a LineChart element
3. Try pressing that point, you will see the pointer still appearing

### version of react-native-gifted-charts

1.4.47

### React Native version

0.76.5

### Platforms

iOS

### Workflow

None

**Comment by Abhinandan-Kushwaha** [comment]
Hi @benbenwsh Thanks for pointing out this issue.
It has been fixed from versions `1.4.48` onwards. Please use the latest version of the library.
