### ISSUE TITLE
Multiple data point issue

### ISSUE THREAD

**Issue by Hariprakash010501** [Abhinandan-Kushwaha/react-native-gifted-charts#941]
### Description

Is it possible to create multiple data points in between x-axis like the way it been handled for y axis?

### Steps to reproduce

Not able to add multiple data points in one axis

### version of react-native-gifted-charts

1.3.26

### React Native version

0.72.10

### Platforms

Android, iOS

### Workflow

React Native

**Comment by Abhinandan-Kushwaha** [comment]
@Hariprakash010501 Can you share a screenshot of your requirement and describe in more detail?

**Comment by Hariprakash010501** [comment]
<img width="287" alt="Screenshot 2024-12-27 at 3 46 27 PM" src="https://github.com/user-attachments/assets/0a6997d0-d0df-431c-9eec-d79997ed6a78" />

Based on the screenshot, there are multiple data points in between x axis (For example between sep and oct)

**Comment by Abhinandan-Kushwaha** [comment]
@Hariprakash010501 This can be achieved by using a data array with only a few items in the array having the label property.
For example, if you have 5 values for each month, the data can be like-
```
const data = [
  {value: 2},
  {value: 4},
  {value: 3, label: 'Sep'},
  {value: 5},
  {value: 3},

  {value: 4},
  {value: 6},
  {value: 5, label: 'Oct'},
  {value: 7},
  {value: 4},

  {value: 5},
  {value: 4},
  {value: 7, label: 'Nov'},
  {value: 6},
  {value: 5},
]
```
Here's another example with `labelComponent` property- https://gifted-charts.web.app/areachart/#customDataPoints
