### ISSUE TITLE
Bug: Donut chart doesn't load on mount

### ISSUE THREAD

**Issue by jorgegvallejo** [Abhinandan-Kushwaha/react-native-gifted-charts#97]
I'm having an issue where the donut chart only shows the center components on load, then in the console it outputs `Did not receive response to shouldStartLoad in time, defaulting to YES` and then it loads the rest of the chart. It does it in dev and in production.

Any ideas how to fix it?

Excellent library btw. You're doing great work.

RN 0.66.3
Gifted Charts 1.0.5
RN Webview 11.0.3

**Comment by Abhinandan-Kushwaha** [comment]
Hey @jorgegvallejo 👋
Glad to know that you liked the library.
I have these versions -
```js "react-native": "0.67.2",
"react-native-webview": "^11.17.2"

**Comment by Abhinandan-Kushwaha** [comment]
Hey @jorgegvallejo 👋
Glad to know that you liked the library.
Please use these versions and let me know if the issue persists.

```js
"react-native": "0.67.2",
"react-native-gifted-charts": "^1.0.5",
"react-native-webview": "^11.17.2"
```

**Comment by jorgegvallejo** [comment]
I updated RN and RN-Webview and I'm still having the same issue. 

All graphs load fine, only the donut graph takes about a 1-2sec to load. It loads immediately after the console logs `Did not receive response to shouldStartLoad in time, defaulting to YES`

**Comment by jorgegvallejo** [comment]
Hey, just wanted you to know that this issue was alleviated by the latest update. Im guessing it's because RN-Webview is not being used anymore.

**Comment by Abhinandan-Kushwaha** [comment]
That's correct @jorgegvallejo 
Since we have removed RN-Webview and canvas, the issue is automatically fixed.
