### ISSUE TITLE
How to OnPress BarChart

### ISSUE THREAD

**Issue by duc562000** [Abhinandan-Kushwaha/react-native-gifted-charts#98]
How to OnPress BarChart

**Comment by Abhinandan-Kushwaha** [comment]
The bars are by default touchable, that means the user can press a bar. If you pass a function to the onPress key in a particular bar object in the data array, it will be called when the user presses that bar.

For example-

```js
const data = [
    {value: 20, onPress: ()=>Alert.alert(20) },
    {value: 18, onPress: ()=>Alert.alert(18) }, 
    {value: 40, onPress: ()=>Alert.alert(40) }
   ]
return <BarChart data={data} />
```
